### ISSUE TITLE
[Feature Request] Make "status" entity-key also available for entities 

### ISSUE THREAD

**Issue by EddyK69** [joBr99/nspanel-lovelace-ui#1002]
### FEATURE DESCRIPTION
Now, the "Status" entity-key is only available for navigate and service items. Please make this also available for all other entities.

### ADDITIONAL CONTEXT
I want this to work:
```
  - entity: input_button.auto_airco
    name: Start airco
    icon: mdi:air-conditioner
    status: sensor.auto_airco
    color:
      "on": [255, 255,0]
      "off": [255, 255, 255]
```
so that my button colors the state of a sensor for example.

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
Please try using this:

```
    - entity: service.input_button.press
      data:
        entity_id: input_button.auto_airco
      status: sensor.auto_airco
      color:
        "on": [255, 255,0]
        "off": [255, 255, 255]
```
