### ISSUE TITLE
[Feature Request] Consider using HomeAssistant API instead of MQTT 

### ISSUE THREAD

**Issue by afarago** [joBr99/nspanel-lovelace-ui#1005]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
I would like to use ability to use Home Assistant API instead of MQTT for esphome nodes.
Fairly easy, would like to start discussion whether such a direction is acceptable for a PR/joint work.

Key advantages: simple and more reliable and faster communication setup.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

Example code:
https://github.com/afarago/nspanel-lovelace-ui
https://github.com/afarago/esphome-nspanel-lovelace-ui

Example yaml - to be integrated better:
```yaml
api:
  id: api_server
  reboot_timeout: 0s

  services:
    - service: app_customsend
      variables:
        data: string
      then:
        - lambda: |-
            id(nspanel).app_custom_send(data);
    - service: app_getdriverversion
      then:
        - lambda: |-
            id(nspanel).app_get_driver_version();
    - service: app_flashnextion
      variables:
        url: string
      then:
        - lambda: |-
            id(nspanel).app_flash_nextion(url);
```

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
53.EU
