### ISSUE TITLE
[Feature Request] optional self-moving line in screensaver to prevent burn-in

### ISSUE THREAD

**Issue by rossi75** [joBr99/nspanel-lovelace-ui#1008]
### FEATURE DESCRIPTION
optional self-moving line in screensaver

### ADDITIONAL CONTEXT
the line below the screensavers date ("Donnerstag, 1. November 2023") can be seen if nothing or another content than the screensaver is being displayed. The line seems to be burning slowly into the display

The idea is to move this line one pixel up or down sporadically, maybe depending on the modulo value given by the minutes or hours or any other random value

### PANEL / FIRMWARE VERION
4.3.3

**Comment by madebywitteveen** [comment]
Hi, that is a good idea ! On my screen the line is starting to burn-in also !

**Comment by joBr99** [comment]
That's interesting, how are your panels running? 

I'm have 4 of them running from day one and I do not notice any burn-in.

Mine are running on 0-10 brightness on screensaver, depending on the ambient light.
So they are turned off in the night and they are also turned off if nobody is at home.

**Comment by madebywitteveen** [comment]
![20231104_200126 (Small)](https://github.com/joBr99/nspanel-lovelace-ui/assets/63544034/8c6f74ac-06e4-4015-8e8a-f0a4fb034429)

Here is my screen; I had the brightness set to '5' 
How do you measure the ambient light ?

thanks, H

**Comment by joBr99** [comment]
I'm using a lux sensor near a window and I'm calculating the brightness for the nspanel from it with a home assistant template.

```
      nspanel_brightness:
        friendly_name: "Nspanel Brigtness"
        value_template: "{{min(((10 / 120) * (states('sensor.tasmota_bh1750_illuminance') | int)) | int, 10)}}"
        unit_of_measurement: u
```
