### ISSUE TITLE
[BUG] lui-us-l-release.tft fails data check

### ISSUE THREAD

**Issue by Gamerayers** [joBr99/nspanel-lovelace-ui#1011]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Latest version of lui-us-l-release.tft with ESPhome firmware fails data check and won't boot.  lui-us-p-release.tft works fine.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/NSPanel1/RESULT"
    panelSendTopic: "cmnd/NSPanel1/CustomSend"
    model: us-l
    sleepTimeout: 20
    defaultBackgroundColor: black
    screenBrightness:
      - time: "00:00:00"
        value: 90
    sleepBrightness:
      - time: "00:00:00"
        value: 10
    timeFormat: "%I:%M   ?%p"
    screensaver:
      entity: weather.home_3
      theme:
        autoWeather: true
      weatherUnit: fahrenheit
    cards:
      - type: cardGrid
        title: Main
        entities:
          - entity: navigate.cardThermo_thermo
            icon: mdi:thermostat
          - entity: navigate.cardThermo_hottub
            icon: mdi:hot-tub
          - entity: navigate.cardQR_wifi
            icon: mdi:wifi
          - entity: navigate.cardAlarm_alarm
            icon: mdi:shield-home
          - entity: navigate.cardGrid_vacuum
            name: Vacuums
            icon: mdi:vacuum
      - type: cardGrid
        title: 1st Floor
        entities:
          - entity: navigate.cardGrid_family
            icon: mdi:sofa
          - entity: navigate.cardGrid_kitchen
            icon: mdi:stove
          - entity: navigate.cardGrid_office
            icon: mdi:laptop
          - entity: navigate.cardGrid_master
            icon: mdi:bed-king
          - entity: navigate.cardGrid_outlight
            icon: mdi:outdoor-lamp
          - entity: navigate.cardGrid_halllight
            icon: mdi:lightbulb-multiple
      - type: cardGrid
        title: 2nd Floor
        entities:
          - entity: navigate.cardGrid_Cody
            icon: mdi:bed
          - entity: navigate.cardGrid_Lucas
            icon: mdi:bed
          - entity: navigate.cardGrid_Guest
            icon: mdi:bed-queen
          - entity: navigate.cardGrid_Bonus
            icon: mdi:toy-brick
          - entity: navigate.cardGrid_Blinds
            icon: mdi:blinds
      - type: cardGrid
        title: Basement
        entities:
          - entity: navigate.cardGrid_Entertainment
            icon: mdi:theater
          - entity: navigate.cardGrid_Bar
            icon: mdi:beer
          - entity: navigate.cardGrid_Brians
            icon: mdi:laptop
          - entity: light.unfinished_basement_light
            name: Unfinished
    hiddenCards:
      - type: cardGrid
        title: Family Room
        entities:
          - entity: switch.family_switch
            name: Lights
            icon: mdi:lightbulb-group
          - entity: fan.great_room
            name: Fan
          - entity: cover.bottom_left
          - entity: cover.bottom_right
          - entity: cover.upper_left
          - entity: cover.upper_right
        key: family
      - type: cardGrid
        title: Kitchen
        entities:
          - entity: light.kitchen_recessed_light
            name: Recessed
          - entity: light.kitchen_table_light
            name: Table
          - entity: light.kitchen_island_switch
            name: Island
          - entity: light.butler_pantry_switch
            name: Butler
          - entity: light.pantry_switch
            name: Pantry
          - entity: light.dining_room_light
            name: Dining
        key: kitchen
      - type: cardGrid
        title: Kendal's Office
        entities:
          - entity: light.kendals_office_fan_light
            name: light
          - entity: fan.kendals_office_fan_speed
            name: Fan
          - entity: cover.kendals_office
            name: blinds
        key: office
      - type: cardGrid
        title: Master Bedroom
        entities:
          - entity: light.master_fan_light
            name: Ceiling Light
          - entity: fan.master_fan_speed
            name: Ceiling Fan
          - entity: light.briansnightstand_bulb
            name: Brian's Bedside
            icon: mdi:lamp
          - entity: light.kendalsnightstand_bulb
            name: Kendal's Bedside
            icon: mdi:lamp
          - entity: switch.masterbedsmartplug_relay
            name: Side Fan
            icon: mdi:fan
          - entity: navigate.cardGrid_mastersit
            icon: mdi:bed-king
        key: master
      - type: cardGrid
        title: Master Cont
        entities:
          - entity: switch.heat_on
            name: Brian's Heat
            icon: mdi:bed-king
          - entity: switch.heat_on_2
            name: Kendal's Heat
            icon: mdi:bed-king
          - entity: light.lowerpolelamp_lowerpolelamp_light
            name: Lower Pole
          - entity: light.upperpolelamp_upperpolelamp_light
            name: Upper Pole
          - entity: light.brians_closet_switch
            name: Brian's Closet
          - entity: light.kendals_closet_switch
            name: Kendal's Closet
        key: mastersit
      - type: cardGrid
        title: Outside Lights
        entities:
          - entity: light.porch_switch
            name: Front Porch
          - entity: light.garage_front_switch
            name: Garage
          - entity: light.patio_switch
            name: Patio
          - entity: light.outdoor_steps_outdoor_steps
            name: Steps
          - entity: light.outdoor_bar_outdoor_bar
            name: Bar
          - entity: light.garage_rear_switch
            name: Garage Rear
        key: outlight
      - type: cardGrid
        title: Hallway
        entities:
          - entity: switch.foyer
            name: Foyer
          - entity: switch.upstairs_hall
            name: Upstairs
          - entity: light.stairled_stairled
            name: Staircase
          - entity: switch.mudroom
            name: Mudroom
          - entity: cover.main_door
            name: Main Garage
          - entity: cover.small_door
            name: Small Garage
        key: halllight
      - type: cardThermo
        title: Thermostat
        entity: climate.home
        key: thermo
      - type: cardThermo
        title: Hot Tub
        entity: climate.hot_tub_thermostat
        key: hottub
      - type: cardQR
        title: Guest Wifi
        qrCode: secret
        entities:
          - entity: iText.Secret
            name: Name
            icon: mdi:wifi
          - entity: iText.Secret
            name: Password
            icon: mdi:key
        key: wifi
      - type: cardAlarm
        title: Alarm
        entity: alarm_control_panel.alarmo
        key: alarm
      - type: cardGrid
        title: Cody's
        entities:
          - entity: light.cody_fan_light
            name: Ceiling Light
          - entity: light.codys_night_stand_light
            name: Nightstand
          - entity: light.cody_s_bookcase_light
            name: Bookcase
          - entity: fan.cody_fan_speed
            name: Fan
          - entity: light.codys_sound_maker_on_off
            name: Noisemaker
            icon: mdi:speaker
        key: Cody
      - type: cardGrid
        title: Lucas's
        entities:
          - entity: light.lucas_fan_light
            name: Ceiling Light
          - entity: light.lucas_s_nightstand_light
            name: Nightstand
          - entity: light.lucas_s_bookcase_light
            name: Bookcase
          - entity: fan.lucas_fan_speed
            name: Fan
          - entity: light.lucass_sound_maker_on_off
            name: Noisemaker
            icon: mdi:speaker
        key: Lucas
      - type: cardGrid
        title: Guest Room
        entities:
          - entity: light.guest_fan_light
            name: Ceiling Light
          - entity: light.guestpole_guestpolelamp
            name: Pole Lamp
          - entity: light.guestnightstand_bulb
            name: Nightstand
          - entity: fan.guest_fan_speed
            name: Fan
        key: Guest
      - type: cardGrid
        title: Bonus Room
        entities:
          - entity: light.bonus_fan_light
            name: Ceiling Light
          - entity: fan.bonus_fan_speed
            name: Fan
          - entity: cover.bonus
            name: Blinds
            icon: mdi:roller-shade-closed
        key: Bonus
      - type: cardGrid
        title: Blinds
        entities:
          - entity: cover.cody
            name: Cody
          - entity: cover.lucas_left
            name: Lucas Left
          - entity: cover.lucas_right
            name: Lucas Right
        key: Blinds
      - type: cardGrid
        title: Entertainment
        entities:
          - entity: light.theater_seating_light
            name: Seating
          - entity: light.theater_projector_light
            name: Projector
          - entity: light.basement_pool_area_light
            name: Billiard
          - entity: switch.pool_table
            name: Table Light
          - entity: switch.basement_stairs
            name: Stairs
        key: Entertainment
      - type: cardGrid
        title: Bar
        entities:
          - entity: light.basement_bar_light
            name: Bar
          - entity: light.basement_kitchenette_light
            name: Kitchenette
          - entity: light.basement_table_light
            name: Table
          - entity: light.basement_arcde_light
            name: Arcade
          - entity: switch.unfinished_basement
            name: Unfinished
        key: Bar
      - type: cardGrid
        title: Brian's Office
        entities:
          - entity: light.brians_office_fan_light
            name: Overhead
          - entity: light.brians_office_dimmer
            name: Desk Lamp
          - entity: fan.brians_office_fan_speed
            name: Fan
          - entity: cover.brians_office
            name: Blinds
        key: Brians
      - type: cardGrid
        title: Vacuum
        entities:
          - entity: navigate.cardGrid_vacuumB
            icon: mdi:robot-vacuum
          - entity: navigate.cardGrid_vacuum1_1
            icon: mdi:robot-vacuum
          - entity: navigate.cardGrid_vacuum2_1
            icon: mdi:robot-vacuum
        key: vacuum
      - type: cardGrid
        title: Basement
        entities:
          - entity: script.vacuum_base_clean_segments
            name: Start
            icon: mdi:play
          - entity: input_boolean.vacuum_basementbath
            name: Bath
            icon: mdi:toilet
          - entity: input_boolean.vacuum_theater
            name: Theater
            icon: mdi:projector
          - entity: input_boolean.vacuum_briansoffice
            name: Brian's Office
            icon: mdi:laptop
          - entity: input_boolean.vacuum_billiard
            name: Billiards
            icon: mdi:billiards-rack
          - entity: input_boolean.vacuum_bar
            name: Bar
            icon: mdi:beer
        key: vacuumB
      - type: cardGrid
        title: 1st Floor
        entities:
          - entity: script.vacuum_clean_segments
            name: Start
            icon: mdi:play
          - entity: input_boolean.vacuum_family
            name: Family
            icon: mdi:sofa
          - entity: input_boolean.vacuum_foyer
            name: Foyer
            icon: mdi:foot-print
          - entity: input_boolean.vacuum_table
            name: Table
            icon: mdi:silverware
          - entity: input_boolean.vacuum_kitchen
            name: Kitchen
            icon: mdi:stove
          - entity: navigate.cardGrid_vacuum1_2
            name: Cont
        key: vacuum1_1
      - type: cardGrid
        title: 1st Floor cont
        entities:
          - entity: input_boolean.vacuum_bath
            name: Bath
            icon: mdi:toilet
          - entity: input_boolean.vacuum_master
            name: Master
            icon: mdi:bed-king
          - entity: input_boolean.vacuum_masterbath
            name: Master Bath
            icon: mdi:bathtub
          - entity: input_boolean.vacuum_mudroom
            name: Mudroom
            icon: mdi:washing-machine
          - entity: input_boolean.vacuum_office
            name: Office
            icon: mdi:laptop
          - entity: script.vacuum_clean_segments
            name: Start
            icon: mdi:play
        key: vacuum1_2
      - type: cardGrid
        title: 2nd Floor
        entities:
          - entity: script.vacuum_second_clean_segments
            name: Start
            icon: mdi:play
          - entity: input_boolean.vacuum_guestbath
            name: Guest Bath
            icon: mdi:shower
          - entity: input_boolean.vacuum_guest
            name: Guest Room
            icon: mdi:bed-queen
          - entity: input_boolean.vacuum_cody
            name: Cody's Room
            icon: mdi:sail-boat
          - entity: input_boolean.vacuum_lucas
            name: Lucas's Room
            icon: mdi:train
          - entity: navigate.cardGrid_vacuum2_2
            name: Cont
        key: vacuum2_1
      - type: cardGrid
        title: 2nd Floor
        entities:
          - entity: input_boolean.vacuum_boysbath
            name: Boy's Bath
            icon: mdi:bathtub
          - entity: input_boolean.vacuum_bonus
            name: Bonus Room
            icon: mdi:toy-brick
          - entity: input_boolean.vacuum_hall
            name: Hallway
            icon: mdi:foot-print
          - entity: script.vacuum_second_clean_segments
            name: Start
            icon: mdi:play
        key: vacuum2_2

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
4.3.3 US-L
