### ISSUE TITLE
[Feature Request] trigger the buzzer from home assistant

### ISSUE THREAD

**Issue by moustic999** [joBr99/nspanel-lovelace-ui#1012]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

add the possibility to trigger the buzzer from home-assistant for a defined time preset

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

while using the nespanel with alarm panel, it would be great that the entry / exit delay from alarmo trigger the buzzer, a bit like a real alarm keypad would do;

That could also be used when something important occurs, the buzzer is triggered.

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

I have the EU version

**Comment by joBr99** [comment]
You can do that by calling the Buzzer Command on Tasmota though the mqtt publish service.

This is an example for a script that you can call in alarmo:
```
alias: Alarm Notification
sequence:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmota_nspkueche/Backlog
      payload: >-
        CustomSend pageType~popupNotify; CustomSend entityUpdateDetail~id~{{
        title }}~65535~~~~~{{ message }}~65535~0; Buzzer 500,2,2
mode: single
icon: mdi:message-badge

```

https://docs.nspanel.pky.eu/notifications/?h=buzzer#notification-on-screensaver
