### ISSUE TITLE
[Help] Blank screen after touching the screensaver

### ISSUE THREAD

**Issue by webncut** [joBr99/nspanel-lovelace-ui#1032]
### PROBLEM DESCRIPTION
Screensaver is fine. After touching the screen, I get a blank screen. After timeout -> screensaver.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

  apps.yaml here:
```
---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel1/RESULT"
    panelSendTopic: "cmnd/nspanel1/CustomSend"
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "20:00:00"
        value: 1
    locale: "de_DE"
    screensaver:
        entity: weather.zuhause
    cards:
      - type: cardGrid
        title: Wohnzimmer
        entities:
          - entity: script.gemutlicht
            icon: mdi:hand-heart-outline
          - entity: light.wled
            icon: mdi:led-strip-variant
            name: LED Wand
          - entity: light.stehlampe_1
            icon: mdi:floor-lamp
          - entity: light.shellycolorbulb_3c6105e50d6f
            icon: mdi:floor-lamp
          - entity: switch.tasmota_84f3eb3e6c77_switch_relay_0
            name: kleines Feuer
            icon: mdi:fire
          - entity: script.alles_aus
            name: Alles aus
            icon: mdi:lightbulb-off-outline
      - type: cardEntities
        title: Außenbereich
        entities:
          - entity: switch.tasmota_d8f15b8bf759_switch_relay_0
            name: Terrasse Licht
            icon: mdi:outdoor-lamp
``` 

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  `2023-11-16 11:47:00.542936 INFO nspanel-1: Sending MQTT Message: time~11:47~
2023-11-16 11:47:40.463221 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel1/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,screensaver,bExit,1"}'}
2023-11-16 11:47:40.466889 INFO nspanel-1: Received Message from Screen: event,buttonPress2,screensaver,bExit,1
2023-11-16 11:47:40.470281 INFO nspanel-1: Button Press Event; entity_id: screensaver; button_type: bExit; value: 1 
2023-11-16 11:47:40.521347 INFO nspanel-1: Sending MQTT Message: pageType~cardGrid
2023-11-16 11:47:40.529515 INFO nspanel-1: Sending MQTT Message: timeout~20
2023-11-16 11:47:40.563180 WARNING nspanel-1: ------------------------------------------------------------
2023-11-16 11:47:40.564264 WARNING nspanel-1: Unexpected error in worker for App nspanel-1:
2023-11-16 11:47:40.565788 WARNING nspanel-1: Worker Ags: {'id': '57294c09e48b424dbf66997f16e4a873', 'name': 'nspanel-1', 'objectid': 'd5fdb2f77ffe435e851d0aaf85bfbe84', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method LuiMqttListener.mqtt_event_callback of <luibackend.mqtt.LuiMqttListener object at 0x7f99227a10>>, 'data': {'topic': 'tele/nspanel1/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,screensaver,bExit,1"}'}, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'topic': 'tele/nspanel1/RESULT', '__thread_id': 'thread-0'}}
2023-11-16 11:47:40.566935 WARNING nspanel-1: ------------------------------------------------------------
2023-11-16 11:47:40.572765 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1095, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/apps/nspanel-lovelace-ui/luibackend/mqtt.py", line 57, in mqtt_event_callback
    self._controller.button_press(entity_id, btype, value)
  File "/config/apps/nspanel-lovelace-ui/luibackend/controller.py", line 234, in button_press
    self._pages_gen.render_card(self._current_card)
  File "/config/apps/nspanel-lovelace-ui/luibackend/pages.py", line 739, in render_card
    self.generate_entities_page(navigation, card.title, card.entities, card.cardType, temp_unit)
  File "/config/apps/nspanel-lovelace-ui/luibackend/pages.py", line 428, in generate_entities_page
    command += self.generate_entities_item(item, cardType, tempUnit)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/nspanel-lovelace-ui/luibackend/pages.py", line 253, in generate_entities_item
    color = self.get_entity_color(entity, ha_type=entityType, overwrite=colorOverride)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/nspanel-lovelace-ui/luibackend/pages.py", line 102, in get_entity_color
    color = rgb_brightness(color, attr.brightness)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/nspanel-lovelace-ui/luibackend/helper.py", line 34, in rgb_brightness
    brightness = int(scale(brightness,(0,255),(70,255)))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/nspanel-lovelace-ui/luibackend/helper.py", line 9, in scale
    return ((val - src[0]) / (src[1]-src[0])) * (dst[1]-dst[0]) + dst[0]
             ~~~~^~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

2023-11-16 11:47:40.573696 WARNING nspanel-1: ------------------------------------------------------------
2023-11-16 11:48:00.511821 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel1/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,sleepReached,cardGrid"}'}
2023-11-16 11:48:00.514066 INFO nspanel-1: Received Message from Screen: event,sleepReached,cardGrid
2023-11-16 11:48:00.519561 INFO nspanel-1: Button Press Event; entity_id: cardGrid; button_type: sleepReached; value: None 
2023-11-16 11:48:00.523852 INFO nspanel-1: Sending MQTT Message: pageType~screensaver
2023-11-16 11:48:00.531111 INFO nspanel-1: Sending MQTT Message: timeout~20`


### TO REPRODUCE
Update all devices to latest releases -
Reboot everything (HA - AppDemon - HACS - NSPanel)
Flash with latest Autoexec


### EXPECTED BEHAVIOUR
Show my apps.yaml configured grid. But I see a blank screen.


### SCREENSHOTS
Nothing to show, just a blank screen.


### ADDITIONAL CONTEXT


### PANEL / FIRMWARE VERION
NSPanel v4.3.3
HACS 1.33.0
AppDaemon 0.15.2
Home Assistant
Core 2023.11.2
Supervisor 2023.11.3
Operating System 11.1
Frontend 20231030.2
