### ISSUE TITLE
Xiaomi/Roidmi/Roborock vacum 

### ISSUE THREAD

**Issue by cr4shydlo** [joBr99/nspanel-lovelace-ui#1047]
### FEATURE DESCRIPTION
Add label for Vacum cleaner

### ADDITIONAL CONTEXT
Add map/ or only Button for cleaning whole or a set configs to start celaning / info about battery etc.

### PANEL / FIRMWARE VERION
Newest PL language

**Comment by joBr99** [comment]
A map is not possible.

For start/stop simply add the robot to  your config.

```
          - entity: vacuum.valetudo_dustin
```

You can call the service directly if you want to clean a specific room and add the required data for the room.
```
          - entity: service.vacuum.start
            data:
              entity_id: vacuum.valetudo_dustin
            name: Schlafzimmer
            icon: "mdi:play"
```
