### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by hrarish** [joBr99/nspanel-lovelace-ui#1085]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel all the time. and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:

![tasmota mqtt](https://github.com/joBr99/nspanel-lovelace-ui/assets/149952893/2fa67733-04f6-4d71-9f8d-955eb2feeff1)

- [ ] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:
---
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Amsterdam
  app_dir: /homeassistant/appdaemon/apps
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: 192.168.0.101  # This should work if you are using supervised HomeAssistant; if not use the IP Address instead.
      #client_host: core-mosquitto
      client_port: 1883
      client_user: **********
      client_password: Htarish61
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
secrets: /homeassistant/secrets.yaml/

```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:
---
nspanel-1:
module: nspanel-lovelace-ui
class: NsPanelLovelaceUIManager
config:
  panelRecvTopic: "tele/t*********/RESULT"
  panelSendTopic: "cmnd/t*******/CustomSend"
  model: eu
sleepTimeout: 20
sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
locale: "de_DE"
screensaver:
      entity: weather.k3ll3r
cards:
      - type: cardEntities
        entities:
          - entity: switch.example_item
          - entity: light.example_item
        title: Example 1
      - type: cardGrid
        entities:
          - entity: switch.example_item
          - entity: light.example_item
        title: Example 2


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:
AppDaemon
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: AppDaemon
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.15.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.12.0
 Home Assistant Supervisor: 2023.11.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Collecting babel
  Downloading https://wheels.home-assistant.io/musllinux-index/Babel-2.13.1-py3-none-any.whl (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 11.6 MB/s eta 0:00:00
Installing collected packages: babel
Successfully installed babel-2.13.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[16:15:01] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
ERROR Error loading secrets file: /homeassistant/secrets.yaml/
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 417, in main
    admain.main()
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 276, in main
    if "appdaemon" not in config:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
[16:15:07] INFO: Service AppDaemon exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service appdaemon: stopping
s6-rc: info: service appdaemon successfully stopped
s6-rc: info: service init-appdaemon: stopping
s6-rc: info: service init-appdaemon successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_
I have flashed the nspanel several times and nothing has shown on the screen of the panel except Waiting for content ...  , when open- device and services, integration, Tasmota: showing connecting of the device with 12 entities, and the device info is about the nspanel, but nothing is shown on the panel screen

**Comment by joBr99** [comment]
ERROR Error loading secrets file: /homeassistant/secrets.yaml/

The path to your secret file is wrong. Remove the tailing slash.

**Comment by hrarish** [comment]
I have removed the tailing slash, and nothing changed.

**Comment by joBr99** [comment]
Please restart appdaemon and post the log from appdaemon again.

**Comment by hrarish** [comment]
Restart is done.
AppDaemon
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: AppDaemon
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.15.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.12.1
 Home Assistant Supervisor: 2023.11.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Collecting babel
  Downloading https://wheels.home-assistant.io/musllinux-index/Babel-2.13.1-py3-none-any.whl (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 10.2 MB/s eta 0:00:00
Installing collected packages: babel
Successfully installed babel-2.13.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[11:38:46] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
2023-12-09 09:38:52.956821 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2023-12-09 09:38:52.957275 INFO AppDaemon: Python version is 3.11.6
2023-12-09 09:38:52.957666 INFO AppDaemon: Configuration read from: /config/appdaemon.yaml
2023-12-09 09:38:52.958101 INFO AppDaemon: Added log: AppDaemon
2023-12-09 09:38:52.958569 INFO AppDaemon: Added log: Error
2023-12-09 09:38:52.958992 INFO AppDaemon: Added log: Access
2023-12-09 09:38:52.959389 INFO AppDaemon: Added log: Diag
2023-12-09 09:38:53.331966 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2023-12-09 09:38:53.695567 INFO HASS: HASS Plugin Initializing
2023-12-09 09:38:53.695852 WARNING HASS: ha_url not found in HASS configuration - module not initialized
2023-12-09 09:38:53.696125 INFO HASS: HASS Plugin initialization complete
2023-12-09 09:38:53.696617 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
2023-12-09 09:38:53.831592 INFO MQTT: MQTT Plugin Initializing
2023-12-09 09:38:53.831995 INFO MQTT: Using 'appdaemon/status' as Will Topic
2023-12-09 09:38:53.832309 INFO MQTT: Using 'appdaemon/status' as Birth Topic
2023-12-09 09:38:53.833371 INFO AppDaemon: Initializing HTTP
2023-12-09 09:38:53.834120 INFO AppDaemon: Using 'ws' for event stream
2023-12-09 09:38:53.841952 INFO AppDaemon: Starting API
2023-12-09 09:38:53.848095 INFO AppDaemon: Starting Admin Interface
2023-12-09 09:38:53.848940 INFO AppDaemon: Starting Dashboards
2023-12-09 09:38:53.880951 INFO HASS: Connected to Home Assistant 2023.12.1
2023-12-09 09:38:53.932786 WARNING AppDaemon: App 'module' missing 'class' or 'module' entry - ignoring
2023-12-09 09:38:53.934681 WARNING AppDaemon: App 'class' missing 'class' or 'module' entry - ignoring
2023-12-09 09:38:53.935963 WARNING AppDaemon: App 'config' missing 'class' or 'module' entry - ignoring
2023-12-09 09:38:53.937483 WARNING AppDaemon: App 'sleepTimeout' missing 'class' or 'module' entry - ignoring
2023-12-09 09:38:53.938805 WARNING AppDaemon: App 'sleepBrightness' missing 'class' or 'module' entry - ignoring
2023-12-09 09:38:53.940327 WARNING AppDaemon: App 'locale' missing 'class' or 'module' entry - ignoring
2023-12-09 09:38:53.941519 WARNING AppDaemon: App 'screensaver' missing 'class' or 'module' entry - ignoring
2023-12-09 09:38:53.943173 WARNING AppDaemon: App 'cards' missing 'class' or 'module' entry - ignoring
2023-12-09 09:38:53.946601 INFO AppDaemon: Found 0 active apps
2023-12-09 09:38:53.948285 INFO AppDaemon: Found 0 inactive apps
2023-12-09 09:38:53.949317 INFO AppDaemon: Found 0 global libraries
2023-12-09 09:38:53.950842 INFO AppDaemon: Starting Apps with 0 workers and 0 pins
2023-12-09 09:38:53.952410 INFO AppDaemon: Running on port 5050
2023-12-09 09:38:54.015177 INFO HASS: Evaluating startup conditions
2023-12-09 09:38:54.031976 INFO HASS: Startup condition met: hass state=RUNNING
2023-12-09 09:38:54.032932 INFO HASS: All startup conditions met
2023-12-09 09:38:54.091926 INFO AppDaemon: Got initial state from namespace default
2023-12-09 09:38:54.331150 INFO MQTT: Connected to Broker at URL 192.168.0.101:1883
2023-12-09 09:38:54.882900 INFO AppDaemon: Got initial state from namespace mqtt
2023-12-09 09:38:54.884682 INFO MQTT: MQTT Plugin initialization complete
2023-12-09 09:38:55.967072 INFO AppDaemon: Scheduler running in realtime
2023-12-09 09:38:55.976613 INFO AppDaemon: Adding /homeassistant/appdaemon/apps to module import path
2023-12-09 09:38:55.977334 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/nspanel-lovelace-ui to module import path
2023-12-09 09:38:55.978269 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend to module import path
2023-12-09 09:38:55.979431 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations to module import path
2023-12-09 09:38:55.980558 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/frontend to module import path
2023-12-09 09:38:55.981519 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/backend to module import path
2023-12-09 09:38:55.992712 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py - ignoring
2023-12-09 09:38:55.994307 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/icon_mapping.py - ignoring
2023-12-09 09:38:55.995639 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/icons.py - ignoring
2023-12-09 09:38:55.996907 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/config.py - ignoring
2023-12-09 09:38:55.998229 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py - ignoring
2023-12-09 09:38:55.999638 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/apis.py - ignoring
2023-12-09 09:38:56.001102 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py - ignoring
2023-12-09 09:38:56.002499 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py - ignoring
2023-12-09 09:38:56.004085 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/helper.py - ignoring
2023-12-09 09:38:56.005606 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/localization.py - ignoring
2023-12-09 09:38:56.007084 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/updater.py - ignoring
2023-12-09 09:38:56.008972 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/theme.py - ignoring
2023-12-09 09:38:56.010700 INFO AppDaemon: App initialization complete

**Comment by joBr99** [comment]
Where is your apps.yaml located?

It needs to be in /config/appdaemon/apps/apps.yaml

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/ad1a49d0-bdd7-44ec-b212-61555f452d88)

**Comment by hrarish** [comment]
apps.yaml is in :       /config/appdaemon/apps/apps.yaml

apps.yaml:
---
nspanel-1:
module: nspanel-lovelace-ui
class: NsPanelLovelaceUIManager
config:
  panelRecvTopic: "tele/tasmota_nspanel/RESULT"
  panelSendTopic: "cmnd/tasmota_nspanel/CustomSend"
  model: eu
sleepTimeout: 20
sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
locale: "de_DE"
screensaver:
      entity: weather.k3ll3r
cards:
      - type: cardEntities
        entities:
          - entity: switch.example_item
          - entity: light.example_item
        title: Example 1
      - type: cardGrid
        entities:
          - entity: switch.example_item
          - entity: light.example_item
        title: Example 2

**Comment by joBr99** [comment]
The indentation in your apps.yaml is completely messed up, please try to use this one:

```
---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_nspanel/RESULT"
    panelSendTopic: "cmnd/tasmota_nspanel/CustomSend"
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "de_DE"
    screensaver:
      entity: weather.k3ll3r
    cards:
      - type: cardEntities
        entities:
          - entity: switch.example_item
          - entity: light.example_item
        title: Example 1
      - type: cardGrid
        entities:
          - entity: switch.example_item
          - entity: light.example_item
        title: Example 2
```
