### ISSUE TITLE
[BUG] us-p is showing analog temperature in Celcius with Farenheight unit

### ISSUE THREAD

**Issue by mkaatman** [joBr99/nspanel-lovelace-ui#1109]
### PROBLEM DESCRIPTION
In homeassistant, Under Sensors, I'm noticing `ANALOG Temperature1 23.5 °F`
In reality, it should be converting 23.5 C to F and showing 74.84 °F.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:

nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel_AABBCC/RESULT"
    panelSendTopic: "cmnd/nspanel_AABBCC/CustomSend"
    model: us-p
    locale: "en_US"
    timeFormat: "%I:%M   ?%p"
    defaultBackgroundColor: "ha-dark"
    cards:
      - type: cardThermo
        title: Downstairs
        entity: climate.downstairs_thermostat
        temperatureUnit: fahrenheit
      - type: cardThermo
        title: Upstairs
        entity: climate.upstairs_thermostat
        temperatureUnit: fahrenheit
      - type: cardMedia
        entity: media_player.living_room
      - type: cardQR
        title: Guest Wifi
        qrCode: "WIFI:S:secret;T:WPA;P:secret;;"
        entities:
          - entity: iText.secret
            name: Name
            icon: mdi:wifi
          - entity: iText.secret
            name: Password
            icon: mdi:key
    screensaver:
      entities:
        - entity: weather.home
        - entity: weather.home
          type: 0
        - entity: weather.home
          type: 1
        - entity: weather.home
          type: 2
        - entity: weather.home
          type: 3


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
n/a

```

### TO REPRODUCE
Setup device, import into HA

### EXPECTED BEHAVIOUR
Expected internal analog sensor to be converted from C to F. I am wondering if there is a tasmota console command I need to execute to tell it the sensor is in C.

Oddly, from the tasmota interface, it seems even more wrong.
`Analog1 Temperature | -4.9 °C`

### SCREENSHOTS
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/275547/fb81f291-6a8c-4d5b-94e8-ebc19e8131d1)

### PANEL / FIRMWARE VERION
- US-P
- Tasmota 13.3.0
