### ISSUE TITLE
Wetter ( weatherOverrideForecast) funktioniert nicht mehr?

### ISSUE THREAD

**Issue by salopette** [joBr99/nspanel-lovelace-ui#115]
screensaver:
      entity: weather.home
      weatherOverrideForecast3: 
         sensor.bwm_eingang_temperature

Hi, das habe ich jetzt so wie früher, aber es kommt nichts?

**Comment by joBr99** [comment]
hey, sieht im neuen config fromat so aus
```yaml
      weatherOverrideForecast4:
        entity: sensor.example_item
        name: name
        icon: lightbulb
 ```
