### ISSUE TITLE
Timer card displays no start

### ISSUE THREAD

**Issue by justinw78** [joBr99/nspanel-lovelace-ui#1155]
### PROBLEM DESCRIPTION
When i want to change or set the timer  i can change the minutes and seconds but i cant find then the start button. 
To only way to get out off the screen then is to press  X  above right or to wait for the screensaver. But it hasn't saved the time then.
What is it what im doing wrong?

### REQUESTED INFORMATION

```
  appdaemon.yaml here


```

- [ ] Provide your apps.yaml:
```
      - type: cardGrid
        title: Timers
        entities: 
          - entity: timer.overloop
          - entity: timer.keuken
        key: timers


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:


```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_
