### ISSUE TITLE
alternativeLayout

### ISSUE THREAD

**Issue by salopette** [joBr99/nspanel-lovelace-ui#117]
ist das so richtig? ich sehe immer nur noch Temperetur

>  screensaver:
      entity: weather.home
      weatherOverrideForecast3:
        entity: sensor.bwm_eingang_temperature
        name: Eingang
        icon:
      weatherOverrideForecast4:
        entity: sensor.bwm_terrasse_temperature
        name: Garten
        icon:
    alternativeLayout: true

![sshot-1](https://user-images.githubusercontent.com/32480002/161415904-1825140c-c900-4175-aba3-ea670fe1ee98.jpg)

**Comment by joBr99** [comment]
probiers mal so

```yaml
    screensaver:
      entity: weather.k3ll3r
      weatherOverrideForecast4:
        entity: sensor.example_item
        name: name
        icon: lightbulb
      alternativeLayout: True
```
