### ISSUE TITLE
[BUG] Grid Card showing 6 visible entities in 4x2 layout instead of 3x2 in case some entities are hidden by state (EU version)

### ISSUE THREAD

**Issue by peca89** [joBr99/nspanel-lovelace-ui#1190]
### PROBLEM DESCRIPTION
If you have 6 entities defined in the Grid Card, everything is fine. As soon as you define 7th entity in YAML, layout switches to 4x2 despite that 7th entity is hidden by state.

I'm trying to make the first position on the Grid Card switch between two entities based on the opposite state. These two can never be shown at the same time. Yet, the software still seems like trying to accommodate for possible 7th entity shown.

Take a look at the first two entities. They are service calls to vacuum cleaner to start cleaning or stop cleaning which obviously cannot exist at the same time.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:

      - type: cardGrid
        entities:
          - entity: service.vacuum.start
            data:
              entity_id: vacuum.ijai_v3_robot_cleaner
            icon: mdi:robot-vacuum
            name: Clean now
            state_template: '{{ states("vacuum.ijai_v3_robot_cleaner") != "docked" }}'
          - entity: service.vacuum.return_to_base
            data:
              entity_id: vacuum.ijai_v3_robot_cleaner
            icon: mdi:robot-vacuum
            name: Go back
            state_template: '{{ states("vacuum.ijai_v3_robot_cleaner") == "docked" }}'
          - entity: light.kitchen
            name: Kitchen
          - entity: sensor.midea_indoor_temperature
            name: Temperature
          - entity: scene.curtains_closed
            icon: mdi:bed
          - entity: scene.curtains_open
            icon: mdi:weather-sunny
          - entity: sensor.pm2_5
            name: PM2.5
        title: Switches 

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Create Grid Card with 7 entities, set `state: "off"` to one of them which is currently off to hide it, remaining 6 entities show in 4x2 layout with the last two spots empty

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
If 6 entities are visible, show them in 3x2 layout. Switch to 4x2 layout only when 7th or 8th entity becomes visible

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU
