### ISSUE TITLE
[BUG] climate protection card with pin

### ISSUE THREAD

**Issue by meautomatron** [joBr99/nspanel-lovelace-ui#1199]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
I'm trying to hide the climate card with a password to prevent it from being accessed by children, after entering the password climate card appears but with the value 0

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
#0 livingroom
1nspanel:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_1nspanel/RESULT"
    panelSendTopic: "cmnd/tasmota_1nspanel/CustomSend"
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "sunrise"
        value: 10
      - time: "sunset + 1:00:00"
        value: 0
    locale: "ro_RO"
    screensaver:
      type: screensaver
      entities:
        - entity: sensor.1nspanel_t
          icon: mdi:home-account
        - entity: weather.forecast_home
          type: 0
        - entity: weather.forecast_home
          type: 1
        - entity: weather.forecast_home
          type: 2
        - entity: sensor.1nspanel_t
          icon: mdi:home-thermometer
        - entity: sensor.2stemp_t
          icon: mdi:home-thermometer-outline
    cards:
      - type: cardThermo
        title: Living
        entity: climate.livingroom
        tMainText: red

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
I chanched:
```
    cards:
      - type: cardThermo
        title: Living
        entity: climate.livingroom
        tMainText: red
```
to
```
    cards:
      - type: cardUnlock
        pin: 1234
        title: Admin Page
        destination: navigate.adminpage
    hiddenCards:
      - type: cardThermo
        title: Admin Page
        key: adminpage
        entities:
          - entity: climate.livingroom
```
### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._
![IMG_4476](https://github.com/joBr99/nspanel-lovelace-ui/assets/145709692/596066c0-fdb7-480a-8f53-fb0046391027)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
Hey change your config to this:

```
    cards:
      - type: cardUnlock
        pin: 1234
        title: Admin Page
        destination: navigate.adminpage
    hiddenCards:
      - type: cardThermo
        title: Living
        key: adminpage
        entity: climate.livingroom
        tMainText: red
```
