### ISSUE TITLE
[Feature Request] override names of navigate items

### ISSUE THREAD

**Issue by qnpns** [joBr99/nspanel-lovelace-ui#120]
Hello,

Firstable, thank you for your amazing work on this project, every update adds judicious functionalities, it is really a pleasure to see what you are accomplishing.

After I updated to 2.5.3 and adapted my apps.yaml, I noticed that the overrided names I used for the navigate.xxx entities are no more working, the name of the buttons are the title of the pages they point to.

Everything else seams to work flowlessly.

--------------------
And I have another question : would it be possible to add more icons by ourselves ? 
I tried to understand how you do that but it seems to be magic :p

Best regards,

Chris

**Comment by joBr99** [comment]
the navigate items changed with the release of this feature, it's no longer the title, you have to add a key to the page and use the key instead

```yaml
          - entity: navigate.cardGrid_testKey
        title: Exmaple Gird
    hiddenCards:
      - type: cardGrid
        title: Exmaple Grid
        entities:
          - entity: light.kueche_lights
          - entity: light.kueche_lights
          - entity: light.kueche_lights
        key: testKey
 ```
 
 which icons do you need?
 they need to be from this list
 https://htmlpreview.github.io/?https://github.com/aderusha/Generate-HASP-Fonts/blob/master/cheatsheet.html
 
 the firmware has an global text field which is shared over all pages where it substrings the icons from (because it's not possible to tranfer unicode over nextion serial, note that this is limited by the memory of the stm32 on the display, so that's the reason why not all icons in the font have an id)
