### ISSUE TITLE
[BUG] Weather card (used as screensaver) no longer works in HA 2024.4

### ISSUE THREAD

**Issue by tetele** [joBr99/nspanel-lovelace-ui#1204]
### PROBLEM DESCRIPTION
The weather card used as a screensaver cannot display anything when connected to HA 2024.4.0b0 due to the removal of the `forecast` attribute for `weather` entities. It worked well in 2024.3.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
# irrelevant

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
# irrelevant

```

### TO REPRODUCE
Install HA 2024.4 beta and look at the NSPanel

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU panel, Tasmota 13.4.0, HA 2024.4 beta

**Comment by joBr99** [comment]
Thanks for the heads-up, will try to fix this over the weekend.

Unfortunately this is still blocked by upstream, but it looks like there is now a workaround.

https://github.com/AppDaemon/appdaemon/issues/1837

**Comment by joBr99** [comment]
@Odianosen25 Hey, can you help me out with this, not entirely sure how to implement that workaround as it's using async stuff.

**Comment by joBr99** [comment]
came up with a different workaround to keep home assistant providing the forecast as an entity

https://docs.nspanel.pky.eu/stable/prepare_ha/#workaround-for-homeassistant-202404

This also requires two slight changes in the backed to force the entity type of this newly created sensor to weather. So it also requires an update of the backend to current dev version.

(or you just do those two changes manually)
https://github.com/joBr99/nspanel-lovelace-ui/commit/d94d937d776c9ca9dd5cf083c54fc4c51d02af5f
https://github.com/joBr99/nspanel-lovelace-ui/commit/e5c1f0588a3dfc226f129c822bfa83571fd2d240

**Comment by tetele** [comment]
Thank you!

**Comment by tetele** [comment]
Something's a bit off. I'll debug when i have the time, but just letting you know @joBr99 

![20240401_173504](https://github.com/joBr99/nspanel-lovelace-ui/assets/920098/eaa1b854-357c-410b-94cd-cb6cbebe40db)

**Comment by joBr99** [comment]
looks like the entity you specified in your config doesn't exist

**Comment by tetele** [comment]
Right. I forgot to change the domain from `weather` to `sensor`, but even after changing it it has some issues

![20240401_181157](https://github.com/joBr99/nspanel-lovelace-ui/assets/920098/8f88d1f7-c5e9-43fc-89b0-5a196e9168cc)

**Comment by joBr99** [comment]
don't change the first entity - also there's something wrong with your update to the latest version of the appdaemon app - either you forgot to restart appdaemon or you didn't follow all steps during the appdaemon 15 update and you are still accessing an old copy of the app
https://github.com/joBr99/nspanel-lovelace-ui/issues/1029

**Comment by tetele** [comment]
What I did was name the `sensor` differently and NOT add that name in the overrides you mentioned. Sorry, I was super tired yesterday and not able to pay attention to what I was doing.

I still have an issue with the current weather condition (it's not showing), but I'll debug that one myself. Thanks a lot for your help and swiftness!

**Comment by tetele** [comment]
I was not.aware you can have one entity for current condition and another for forecast.

**Comment by joBr99** [comment]
You can configure each item individually:

```
    screensaver:
      entities:
        - entity: weather.demo_weather_north
        - entity: weather.demo_weather_north
          type: 0
        - entity: weather.demo_weather_north
          type: 1
        - entity: weather.demo_weather_north
          type: 2
        - entity: sensor.energy_usage
```

I guess you are using the only config way with one weather entity for the screensaver? Didn't really think about that one.

**Comment by tetele** [comment]
That is what i was using, yes.

**Comment by TheGroundZero** [comment]
Just a small remark.

If the state (and attributes) of `weather.home` is stored in the `daily` variable, you can pull all template data from said variable? Or skip the variable all together and use the source entity for the template?

```yaml
# ...
sensor:
  - name: Weather Forecast Daily
    unique_id: weather_forecast_daily
    state: "{{ daily['weather.home'] }}"
    attributes:
      temperature: "{{ daily['weather.home'].temperature }}"
      temperature_unit: "{{ daily['weather.home'].temperature_unit }}"
      forecast: "{{ daily['weather.home'].forecast }}"
```

or 

```yaml
# ...
sensor:
  - name: Weather Forecast Daily
    unique_id: weather_forecast_daily
    state: "{{ states('weather.home') }}"
    attributes:
      temperature: "{{ state_attr('weather.home', 'temperature') }}"
      temperature_unit: "{{ state_attr('weather.home', 'temperature_unit') }}}"
      forecast: "{{ state_attr('weather.home', 'forecast') }}"
```

Semtantically it's also weird to use a variable named `daily` even though the trigger is hourly.
There's an example code snipper on the HA docs that closely matches the template used here and it uses `hourly` as variable name: https://www.home-assistant.io/integrations/template/#trigger-based-handling-of-service-response-data

I also don't see a real reason to make this a trigger-based template but I might be overlooking something?

**Comment by joBr99** [comment]
With the upcoming homeassistant version the weather entities are no longer providing the forecast attribute and the forecast has to be pulled though the `weather.get_forecasts` service. As appdaemon currently doesn't support calling services with a response, we still need an entity containing this data - this entity is generated with the trigger template.

For the current temperature it doesn't really matter if you are using the variable or the current state.

In homeassistant's example they are using the data type `hourly` for the forecast. In my example the data type `daily` is used. (would be possible to rename the variable to forecast or something like that to make it a bit more universal)
However the daily forecast entity is updated hourly, as it's possible that the forecast is changing during the day ;)

**Comment by denislooby** [comment]
Working good for me using this now.
Took a while, I missed the bit about the upgrade to AppDaemon 15 https://github.com/joBr99/nspanel-lovelace-ui/issues/1029
So my update in HACS was having no effect.
If you are seeing ! instead of weather symbols follow that upgrade to appdaemon 15 how to.

**Comment by ppaciekq** [comment]
I used the workaround described here:
https://docs.nspanel.pky.eu/stable/prepare_ha/#installing-lovelace-appdaemon-backend-application

but I still have a problem.

The screen looks like this:
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/148376806/ba8e1d38-cd1b-4a67-9249-87143be0956f)

and this is what the configuration.yaml and apps.yaml files look like:

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/148376806/b7026317-b8cf-4d88-b96e-fae92ed64fbf)
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/148376806/30d451a9-745c-4603-a77f-245332d5b6e2)


![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/148376806/971c1df6-e900-4eac-981a-34bb93798adc)

what am I doing wrong? Any ideas?

**Comment by ppaciekq** [comment]
yes, I noticed it and after changing it it actually works - thanks! However, only today's weather is visible.
Is it possible to somehow add a view of the next few days?

**Comment by joBr99** [comment]
![319624684-b7026317-b8cf-4d88-b96e-fae92ed64fbf~2](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/b18bafb2-30ab-40e0-aefb-6d636e05e2a9)

**Comment by ppaciekq** [comment]
I changed it here. So I understand that after 1 hour the trigger should change it?

**Comment by joBr99** [comment]
Check the data of the sensor.weather forecast daily entity - forecast data must be populated there

Maybe you can trigger the template by restarting HA, not sure.

**Comment by ppaciekq** [comment]
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/148376806/ee3dfe5d-56c9-4837-bd8d-f7e5d5270d4c)

data in forecast home are visible correctly (daily and hourly):
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/148376806/600e3798-64e0-4c78-8182-835ed784ebe0)

**Comment by joBr99** [comment]
please check on this page:

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/3cacc49f-70db-4e06-84da-73a5b2c1f9dd)

**Comment by tetele** [comment]
> Maybe you can trigger the template by restarting HA, not sure.

It won't. Only triggers can update trigger-based sensors.

What I did was this

```yaml
template:
  - trigger:
      - platform: time_pattern
        hours: /1
      - platform: event
        event_type: event_template_reloaded
# everything else
```

then go to the [Developer tools](https://my.home-assistant.io/redirect/server_controls/) and reload Template entities.

If that doesn't work, try this

```yaml
template:
  - trigger:
      - platform: time_pattern
        hours: /1
      - platform: event
        event_type: manual_event_template_reloaded
```

and add this automation:

```yaml
alias: Re-emit event_template_reloaded event
description: >-
  In order to update trigger-based `template` entities, to prevent a race
  condition, I need to re-emit the `event_template_reloaded` event.
trigger:
  - platform: event
    event_type: event_template_reloaded
    event_data: {}
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - event: manual_event_template_reloaded
    event_data: {}
mode: single
```

then reload the Template entities

**Comment by ppaciekq** [comment]
> > Maybe you can trigger the template by restarting HA, not sure.
> 
> It won't. Only triggers can update trigger-based sensors.
> 
> What I did was this
> 
> ```yaml
> template:
>   - trigger:
>       - platform: time_pattern
>         hours: /1
>       - platform: event
>         event_type: event_template_reloaded
> # everything else
> ```
> 
> then go to the [Developer tools](https://my.home-assistant.io/redirect/server_controls/) and reload Template entities.
> 
> If that doesn't work, try this
> 
> ```yaml
> template:
>   - trigger:
>       - platform: time_pattern
>         hours: /1
>       - platform: event
>         event_type: manual_event_template_reloaded
> ```
> 
> and add this automation:
> 
> ```yaml
> alias: Re-emit event_template_reloaded event
> description: >-
>   In order to update trigger-based `template` entities, to prevent a race
>   condition, I need to re-emit the `event_template_reloaded` event.
> trigger:
>   - platform: event
>     event_type: event_template_reloaded
>     event_data: {}
> condition: []
> action:
>   - delay:
>       hours: 0
>       minutes: 0
>       seconds: 1
>       milliseconds: 0
>   - event: manual_event_template_reloaded
>     event_data: {}
> mode: single
> ```
> 
> then reload the Template entities



I made the changes you wrote about and now the configuration looks like this:

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/148376806/524cf4f8-d032-4668-8495-15890ca13bd0)

forecast seems to be working properly now:

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/148376806/da269292-1e37-476c-99ef-f1657a1edc03)

but there is still no information about the next few days and the icons are also missing:

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/148376806/9d584210-a2e8-40ad-82f7-b03d70d435d5)

**Comment by tetele** [comment]
Quoting joBr99's [comment](https://github.com/joBr99/nspanel-lovelace-ui/issues/1204#issuecomment-2028018314):

> This also requires two slight changes in the backed to force the entity type of this newly created sensor to weather. So it also requires an update of the backend to current dev version.
> (or you just do those two changes manually)
> https://github.com/joBr99/nspanel-lovelace-ui/commit/d94d937d776c9ca9dd5cf083c54fc4c51d02af5f
> https://github.com/joBr99/nspanel-lovelace-ui/commit/e5c1f0588a3dfc226f129c822bfa83571fd2d240


Have you done that too?

**Comment by ppaciekq** [comment]
> Quoting joBr99's [comment](https://github.com/joBr99/nspanel-lovelace-ui/issues/1204#issuecomment-2028018314):
> 
> > This also requires two slight changes in the backed to force the entity type of this newly created sensor to weather. So it also requires an update of the backend to current dev version.
> > (or you just do those two changes manually)
> > [d94d937](https://github.com/joBr99/nspanel-lovelace-ui/commit/d94d937d776c9ca9dd5cf083c54fc4c51d02af5f)
> > [e5c1f05](https://github.com/joBr99/nspanel-lovelace-ui/commit/e5c1f0588a3dfc226f129c822bfa83571fd2d240)
> 
> Have you done that too?

Actually - I missed it. I have already added it and the icons are visible. Thanks for the help!

**Comment by azsoccerpop** [comment]
Apologies for jumping on but I am stuck on the weather fix. I changed my weather integration to Pirate Weather which correctly response to the service.get_forecasts and populates sensor.weather_forecast_daily with all the correct information as verified in the developer tools States. AppDaemon is at latest version NSPanel Lovelace UI is v4.4.0. AppDaemon Log shows this: 2024-04-05 14:43:59.185926 INFO nspanel-1: Sending MQTT Message: weatherUpdate~~~���~31728~PirateWeather~67��F~~~���~17299~Weather Forecast Daily~clou ~~~���~17299~Weather Forecast Daily~clou ~~~���~17299~Weather Forecast Daily~clou ~~~���~17299~Weather Forecast Daily~clou 
apps.yaml
`screensaver:      
      entities:
        - entity: weather.pirateweather
        - entity: sensor.weather_forecast_daily
          type: 0
        - entity: sensor.weather_forecast_daily
          type: 1
        - entity: sensor.weather_forecast_daily
          type: 2
        - entity: sensor.weather_forecast_daily
          type: 3  `
not sure what my next step is and any help is appreciated.

**Comment by joBr99** [comment]
are you sure that you are on v4.4.0? 
did you restart appdaemon? 
is appdaemon using the stuff downloaded from hacs? (only the case if you have app_dir in your appdaemon.yaml) see #1029

**Comment by azsoccerpop** [comment]
Thank you so much!
I had not configured app_dir: /homeassistant/appdaemon/apps/ in the appdaemon.yaml.
All is well.

**Comment by rockyhopper** [comment]
> Thank you so much!
> I had not configured app_dir: /homeassistant/appdaemon/apps/ in the appdaemon.yaml.
> All is well.
> 
> 
> 

Same issue for me. Solved for me too.
Thanks a lot.

**Comment by filipsworks** [comment]
> came up with a different workaround to keep home assistant providing the forecast as an entity
> 
> https://docs.nspanel.pky.eu/stable/prepare_ha/#workaround-for-homeassistant-202404
> 
> This also requires two slight changes in the backed to force the entity type of this newly created sensor to weather. So it also requires an update of the backend to current dev version.
> 
> (or you just do those two changes manually) [d94d937](https://github.com/joBr99/nspanel-lovelace-ui/commit/d94d937d776c9ca9dd5cf083c54fc4c51d02af5f) [e5c1f05](https://github.com/joBr99/nspanel-lovelace-ui/commit/e5c1f0588a3dfc226f129c822bfa83571fd2d240)

It would be great to add homeassistant start trigger to that template as at least for me restarting the HA does not update the service itself:
```
template:
  - trigger:
      - platform: time_pattern
        hours: /1
      - platform: homeassistant
        event: start
```

**Comment by joBr99** [comment]
thanks, good idea added to the documentation

**Comment by soyxan** [comment]
I have implemented the workaround configuration in my HA but this is the result I get in my nspanel:

![20240515_091326](https://github.com/joBr99/nspanel-lovelace-ui/assets/8955206/6f46a551-dc80-49ef-bf7b-90c424659327)

As you can see the current and forecast temperatures are fine, but the weather conditions icons and the weekdays names are missing. These were working fine before the AppDaemon issue.

This is my configuration.yaml:
```
template:
  - trigger:
      - platform: time_pattern
        hours: /1
      - platform: homeassistant
        event: start
    action:
      - service: weather.get_forecasts
        data:
          type: daily
        target:
          entity_id: weather.aemet # change to your weather entity
        response_variable: daily
    sensor:
      - name: Weather Forecast Daily
        unique_id: weather_forecast_daily
        state: "{{ states('weather.aemet') }}" # # change to your weather entity in this line
        attributes:
          temperature: "{{ state_attr('weather.aemet', 'temperature') }}" # change to your weather entity
          temperature_unit: "{{ state_attr('weather.aemet', 'temperature_unit') }}" # change to your weather entity
          forecast: "{{ daily['weather.aemet'].forecast }}" # change to your weather entity
```

And this is my screensaver configuration in apps.yaml:
```
nspanel_salon:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    screensaver:
      entities:
        - entity: sensor.weather_forecast_daily
          value: '{{states("sensor.ewelink_th01_a6451925_temperature")}} º'
        - entity: sensor.weather_forecast_daily
          type: 0
          value: "{{state_attr('sensor.weather_forecast_daily', 'forecast')[0].temperature|round(0)}}º/{{state_attr('sensor.weather_forecast_daily', 'forecast')[0].templow|round(0)}}º"
        - entity: sensor.weather_forecast_daily
          type: 1
          value: "{{state_attr('sensor.weather_forecast_daily', 'forecast')[1].temperature|round(0)}}º/{{state_attr('sensor.weather_forecast_daily', 'forecast')[1].templow|round(0)}}º"
        - entity: sensor.weather_forecast_daily
          type: 2
          value: "{{state_attr('sensor.weather_forecast_daily', 'forecast')[2].temperature|round(0)}}º/{{state_attr('sensor.weather_forecast_daily', 'forecast')[2].templow|round(0)}}º"
        - entity: delete
        - entity: sensor.nspanel_salon_thermostat_temperature
          value: '{{states("sensor.nspanel_salon_thermostat_temperature")}} º'
          icon: mdi:home-thermometer-outline
```
Am I missing anything? Thanks!
