### ISSUE TITLE
[BUG] HA 2024.4 - cannot display forecast properly

### ISSUE THREAD

**Issue by cezarg1410** [joBr99/nspanel-lovelace-ui#1209]
### PROBLEM DESCRIPTION
After updating to HA 2024.4.0 - the weather forecast on the NsPanel doesn't look as it should. Here it is how it looks like:
![nspanel_problem](https://github.com/joBr99/nspanel-lovelace-ui/assets/9452334/302fd57f-f370-4e30-9cc7-212e65af6b81)

The problem is that it only shows "rainy" instead of hour, icon and temperature.

### REQUESTED INFORMATION

- [ ] I'have created the template for weather forecast in the home assistant configuration.yaml in the following way:
```
template:
  - trigger:
      - platform: time_pattern
        minutes: /5
    action:
      - service: weather.get_forecasts
        data:
          type: daily
        target:
          entity_id: weather.tomorrow_io_dom_daily
        response_variable: daily
    sensor:
      - name: Weather Forecast Daily
        unique_id: weather_forecast_daily
        state: "{{ states('weather.tomorrow_io_dom_daily') }}"
        attributes:
          temperature: "{{ state_attr('weather.tomorrow_io_dom_daily', 'temperature') }}" 
          temperature_unit: "{{ state_attr('weather.tomorrow_io_dom_daily', 'temperature_unit') }}"
          forecast: "{{ daily['weather.tomorrow_io_dom_daily'].forecast }}"
```

- [ ] Also, i have modified the screensaver definition:

```
bedroom-nspanel:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/bedroom-nspanel/RESULT"
    panelSendTopic: "cmnd/bedroom-nspanel/CustomSend"
    updateMode: "auto-notify"
    sleepTimeout: 10
    sleepBrightness:
      - time: "6:00:00"
        value: 10
      - time: "23:40:00"
        value: 0
    locale: "pl_PL"
    screensaver:
      entities:
        - entity: weather.tomorrow_io_dom_daily
        - entity: sensor.weather_forecast_daily
          type: 0
        - entity: sensor.weather_forecast_daily
          type: 1
        - entity: sensor.weather_forecast_daily
          type: 2
        - entity: sensor.weather_forecast_daily
          type: 3
```

- [ ] AppDeamon logs look rather strange (it sends only partial information to panel)
```
2024-04-04 23:35:00.164627 INFO bedroom-nspanel: Sending MQTT Message: weatherUpdate~~~���~25375~OpenWeatherMap~11.7��C~~~���~17299~Weather Forecast Daily~rainy ~~~���~17299~Weather Forecast Daily~rainy ~~~���~17299~Weather Forecast Daily~rainy ~~~���~17299~Weather Forecast Daily~rainy 
``` 

Of course, the configured forecast entity looks good:

![nspanel_encja](https://github.com/joBr99/nspanel-lovelace-ui/assets/9452334/16a3bf0e-82bf-410d-bb2a-d399f6c26115)

I will be very glad if You could help me sort out the issue

### ADDITIONAL CONTEXT
- AppDaemon version: 0.16.4

### PANEL / FIRMWARE VERSION
EU Panel - Program Version	13.4.0(tasmota32)
