### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by ZackZarab** [joBr99/nspanel-lovelace-ui#1211]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[x] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide a screenshot of your tasmota mqtt configuration:
n/a -> ESPHome

- [x] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:
secrets: /homeassistant/secrets.yaml
appdaemon:
  latitude: 52.0
  longitude: 4.0
  elevation: 2
  time_zone: Europe/Berlin
  app_dir: /config/appdaemon/apps/ # !!! This is really important for AppDaemon HA Addon >= 15
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdeamon"
      #client_host: core-mosquitto.local.hass.io # This should work if you are using supervised HomeAssistant; if not use the IP Address instead.
      client_host: 192.168.178.167
      client_port: 1883
      client_user: "xxxxx"
      client_password: "xxxxx"
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:

```

- [x] Provide your apps.yaml:
  apps.yaml here:
---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel/RESULT"
    panelSendTopic: "cmnd/nspanel/CustomSend"
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "de_DE"
    screensaver:
      entity: weather.forecast_xxx
    cards:
      - type: cardGrid
        title: Test Grid Card
        entities:
          - entity: sensor.solar_power_consumption

```
- [x] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: AppDaemon
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.16.4
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.1  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2024.4.2
 Home Assistant Supervisor: 2024.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Collecting babel
  Downloading Babel-2.14.0-py3-none-any.whl.metadata (1.6 kB)
Downloading Babel-2.14.0-py3-none-any.whl (11.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 8.5 MB/s eta 0:00:00
Installing collected packages: babel
Successfully installed babel-2.14.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[13:46:41] INFO: Starting AppDaemon...
2024-04-09 13:46:53.720223 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2024-04-09 13:46:53.720996 INFO AppDaemon: Python version is 3.11.6
2024-04-09 13:46:53.722011 INFO AppDaemon: Configuration read from: /config/appdaemon.yaml
2024-04-09 13:46:53.723129 INFO AppDaemon: Added log: AppDaemon
2024-04-09 13:46:53.724107 INFO AppDaemon: Added log: Error
2024-04-09 13:46:53.724730 INFO AppDaemon: Added log: Access
2024-04-09 13:46:53.725471 INFO AppDaemon: Added log: Diag
2024-04-09 13:46:54.482336 WARNING AppDaemon: appdir: /config/appdaemon does not exist exist
2024-04-09 13:46:54.483066 WARNING AppDaemon: appdir: /config/appdaemon/apps does not exist exist
2024-04-09 13:46:54.487166 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2024-04-09 13:46:55.395591 INFO HASS: HASS Plugin Initializing
2024-04-09 13:46:55.396344 WARNING HASS: ha_url not found in HASS configuration - module not initialized
2024-04-09 13:46:55.397322 INFO HASS: HASS Plugin initialization complete
2024-04-09 13:46:55.398822 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
2024-04-09 13:46:55.725783 INFO MQTT: MQTT Plugin Initializing
2024-04-09 13:46:55.726933 INFO MQTT: Using 'appdeamon/status' as Will Topic
2024-04-09 13:46:55.728183 INFO MQTT: Using 'appdeamon/status' as Birth Topic
2024-04-09 13:46:55.731121 INFO AppDaemon: Initializing HTTP
2024-04-09 13:46:55.732507 INFO AppDaemon: Using 'ws' for event stream
2024-04-09 13:46:55.783013 INFO AppDaemon: Starting API
2024-04-09 13:46:55.799031 INFO AppDaemon: Starting Admin Interface
2024-04-09 13:46:55.801344 INFO AppDaemon: Starting Dashboards
2024-04-09 13:46:55.866632 INFO HASS: Connected to Home Assistant 2024.4.2
2024-04-09 13:46:55.868928 INFO AppDaemon: Starting Apps with 0 workers and 0 pins
2024-04-09 13:46:55.871763 INFO AppDaemon: Running on port 5050
2024-04-09 13:46:56.051978 INFO MQTT: Connected to Broker at URL 192.168.178.167:1883
2024-04-09 13:46:56.076549 INFO HASS: Evaluating startup conditions
2024-04-09 13:46:56.088627 INFO AppDaemon: Got initial state from namespace mqtt
2024-04-09 13:46:56.091324 INFO MQTT: MQTT Plugin initialization complete
2024-04-09 13:46:56.119306 INFO HASS: Startup condition met: hass state=RUNNING
2024-04-09 13:46:56.120630 INFO HASS: All startup conditions met
2024-04-09 13:46:56.216713 INFO AppDaemon: Got initial state from namespace default
2024-04-09 13:46:57.893921 INFO AppDaemon: Scheduler running in realtime
2024-04-09 13:46:57.905541 INFO AppDaemon: App initialization complete

```

### ADDITIONAL INFORMATION
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/166508394/b6ccb417-70d3-413f-9fdf-763721272e00)

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_
