### ISSUE TITLE
no weather icons [BUG] 

### ISSUE THREAD

**Issue by meautomatron** [joBr99/nspanel-lovelace-ui#1213]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
I followed the steps described in "Workaround for Homeassistant 2024.04 'but no weather icons appear

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
#0 livingroom
1nspanel:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_1nspanel/RESULT"
    panelSendTopic: "cmnd/tasmota_1nspanel/CustomSend"
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "sunrise"
        value: 10
      - time: "sunset + 1:00:00"
        value: 0
    locale: "ro_RO"
    screensaver:
      type: screensaver
      doubleTapToUnlock: True
      entities:
        - entity: sensor.1nspanel_t
          icon: mdi:home-account
        - entity: sensor.weather_forecast_daily
          type: 0
        - entity: sensor.weather_forecast_daily
          type: 1
        - entity: sensor.weather_forecast_daily
          type: 2
        - entity: sensor.1nspanel_t
          icon: mdi:home-thermometer
        - entity: sensor.2stemp_t
          icon: mdi:home-thermometer-outline
    cards:
      - type: cardThermo
        title: Living
        entity: climate.livingroom
        tMainText: red

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
2024-04-12 11:17:34.146348 INFO 1nspanel: Sending MQTT Message: weatherUpdate~~~���~17299~Temperatura din living~20.6��C~~~���~17299~Weather Forecast Daily~sunny ~~~���~17299~Weather Forecast Daily~sunny ~~~���~17299~Weather Forecast Daily~sunny ~~~���~17299~Temperatura din living~20.6��C~~~���~17299~Temperatura de afara~25.6��C

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._
![IMG_4527](https://github.com/joBr99/nspanel-lovelace-ui/assets/145709692/69a0640b-137e-4eea-bdf5-57aeb075e20b)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_
this is the code from configuration.yaml
template:
  - trigger:
      - platform: time_pattern
        hours: /1
    action:
      - service: weather.get_forecasts
        data:
          type: daily
        target:
          entity_id: weather.forecast_home # change to your weather entity
        response_variable: daily
    sensor:
      - name: Weather Forecast Daily
        unique_id: weather_forecast_daily
        state: "{{ states('weather.forecast_home') }}" # # change to your weather entity in this line
        attributes:
          temperature: "{{ state_attr('weather.forecast_home', 'temperature') }}" # change to your weather entity
          temperature_unit: "{{ state_attr('weather.forecast_home', 'temperature_unit') }}" # change to your weather entity
          forecast: "{{ daily['weather.forecast_home'].forecast }}" # change to your weather entity
### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
panel EU, HA version 12.1
