### ISSUE TITLE
Problem with installation MQTT APPDEAMON

### ISSUE THREAD

**Issue by Mogobec93** [joBr99/nspanel-lovelace-ui#1237]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:

- [ ] Provide your appdaemon.yaml: 

```
  appdaemon.yaml here:

```
---
secrets: /homeassistant/secrets.yaml
appdaemon:
  latitude: 52.0
  longitude: 4.0
  elevation: 2
  time_zone: Europe/Berlin
  app_dir: /homeassistant/appdaemon/apps/ # !!! This is really important for AppDaemon HA Addon >= 15
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: 192.168.0.123 # This should work if you are using supervised HomeAssistant; if not use the IP Address instead.
      #client_host: 192.168.75.30
      client_port: 1883
      client_user: "xxx"
      client_password: "xxx"
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:

```
---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/NSPanelm/RESULT"
    panelSendTopic: "cmnd/NSPanelm/CustomSend"
    model: eu

cards:
  - type: cardAlarm
    title: Alarm Test 1
    entity: alarm_control_panel.home_alarm
```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:

```
Authorised
2024-07-12 06:31:51.617610 CRITICAL MQTT: MQTT Client Disconnected Abruptly. Will attempt reconnection
2024-07-12 06:31:52.617325 CRITICAL MQTT: Could not complete MQTT Plugin initialization, trying again in 5 seconds
2024-07-12 06:32:02.621726 CRITICAL MQTT: Could not Complete Connection to Broker, please Ensure Broker at URL 192.168.0.123:1883 is correct and broker is not down and restart Appdaemon
2024-07-12 06:32:03.620696 CRITICAL MQTT: Could not complete MQTT Plugin initialization, trying again in 5 seconds
```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_

Hello, I have Problem with installation. I think I am doing something wrong with code Tasmota/MQTT and APPDEAMON. Can anybody help me with Info what i am doing wrong? Thanks a lot.
