### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dvoijen** [joBr99/nspanel-lovelace-ui#1242]
### PROBLEM DESCRIPTION
I use nspanel in combination with Home Assistant and a Tuya LED ceiling light (multicolor)
When i pu the light on the nspanel and try to change the color the color of the led changes instantly when traveling over the colors with my finger.
This results in more than 10 presses witch eventually puts the Tuya ceiling light into pair mode.

### REQUESTED INFORMATION
apps.yaml:
```
nsp-slpk-dames:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nsp-slpk-dames/RESULT"
    panelSendTopic: "cmnd/nsp-slpk-dames/CustomSend"
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 5
      - time: "21:00:00"
        value: 0
    locale: "nl_NL"
    screensaver:
      entities:
        - entity: weather.buienradar
        - entity: sensor.weather_forecast_daily
          type: 0
        - entity: sensor.weather_forecast_daily
          type: 1
        - entity: sensor.weather_forecast_daily
          type: 2
        - entity: sensor.weather_forecast_daily
          type: 3
      statusIcon2:
        entity: sensor.fan_direction_dames
        icon:
            "Koelen": mdi:snowflake
            "Verwarmen": mdi:white-balance-sunny
    cards:
      - type: cardGrid
        title: Slaapkamer Dames
        entities:
          - entity: light.slpk_dames_plafondlamp
            name: Plafond Lamp
            icon: mdi:lightbulb
          - entity: navigate.fan_dames
            name: Ventilator
            icon: mdi:fan
          - entity: input_button.klaar_om_naar_bed_te_gaan
            name: Bedtime
            icon: mdi:bed
    hiddenCards:
      - type: cardGrid
        title: Ventilator Dames
        entities:
          - entity: fan.plafondlamp_dames
            name: Ventilator
            icon: mdi:fan
          - entity: service.fan.set_direction
            name: Verwarmen
            icon: mdi:rotate-right
            data:
              entity_id: fan.plafondlamp_dames
              direction: "forward"
          - entity: service.fan.set_direction
            name: Koelen
            icon: mdi:rotate-left
            data:
              entity_id: fan.plafondlamp_dames
              direction: "reverse"
          - entity: input_select.timer_instelling_ventilator_dames
            name: Timer Ventilator
            icon: mdi:timer-sand
        key: fan_dames
```

### TO REPRODUCE
Tap on the bulb icon and change color, drag your finger over the screen just a little bit, than the ceiling led wil instantly change trough all the colors your finger toutches and wil go into pair mote (blinking while light).

### EXPECTED BEHAVIOUR
Change color as soon as you let go of the screen.

### PANEL / FIRMWARE VERSION
Firmware version: EU 4.4.0
