### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by glxxyxafonso** [joBr99/nspanel-lovelace-ui#1253]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[YES] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide a screenshot of your tasmota mqtt configuration:
![Screenshot_20240904_230657_Chrome.jpg](https://github.com/user-attachments/assets/b3237b35-fe49-4be6-be92-e3e77c4da539)

- [x] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:
---
secrets: /homeassistant/secrets.yaml
appdaemon:
  latitude: 52.0
  longitude: 4.0
  elevation: 2
  time_zone: Europe/Berlin
  app_dir: /config/appdaemon/apps/ # !!! This is really important for AppDaemon HA Addon >= 15
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      #client_host: core-mosquitto.local.hass.io # This should work if you are using supervised HomeAssistant; if not use the IP Address instead.
      client_host: 192.168.1.103
      client_port: 1883
      client_user: "mqttuser"
      client_password: "***"
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:

```

- [x] Provide your apps.yaml:
```
  apps.yaml here:
---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_your_mqtt_topic/RESULT"
    panelSendTopic: "cmnd/tasmota_your_mqtt_topic/CustomSend"
    model: eu

```
- [x] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:
2024-09-04 23:58:44.182704 CRITICAL MQTT: Could not Complete Connection to Broker, please Ensure Broker at URL 192.168.1.103:1883 is correct and broker is not down and restart Appdaemon
2024-09-04 23:58:44.186026 CRITICAL MQTT: Could not complete MQTT Plugin initialization, trying again in 5 seconds
(And it repeats, repeats, repeats)

```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_
I'm running a RasPI 4 with Home Assistant OS.
I only have a ZigBee usb as something extra plugged in.

Thank you in advance.
