### ISSUE TITLE
[BUG] Moving Cover renders Panel unusable

### ISSUE THREAD

**Issue by Roxxor91** [joBr99/nspanel-lovelace-ui#1255]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
I added Cover entities (helpers in this case; one cover entity controlling several venetian blinds). When selecting the entitty, the controlling menu opens as expected. When I press the blinds to be closed the panel gets "unresponsive". It appears to me that the refreshes of the display showing the percentage of opening interferes with me pressing the "X" on the upper right corner. i have to quickly press the x button in order to close.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
`nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/NSPanelErdgeschoss/RESULT"
    panelSendTopic: "cmnd/NSPanelErdgeschoss/CustomSend"
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "de_DE"
    screensaver:
      doubleTapToUnlock: True
      entities:
      - entity: weather.village
      - entity: sensor.weather_forecast_daily
           type: 0
      - entity: sensor.weather_forecast_daily
        type: 1
      - entity: sensor.weather_forecast_daily
        type: 2
      - entity: sensor.weather_forecast_daily
        type: 3
    cards:
      - type: cardGrid
        entities:
          - entity: script.alle_lichter_aus
            name: "Lichter aus"
            icon: mdi:lightbulb
          - entity: vacuum.valetudo_roborocks7
            name: "Start/Stop EG"
            icon: mdi:vacuum
          - entity: vacuum.valetudo_r2d2
            name: "Start/Stop OG"
            icon: mdi:vacuum
          - entity: cover.sonnenschutz
            name: "Alle Rollos"
            icon: mdi:window-open
          - entity: cover.rollos_raffstores_eg
            name: "Rollos EG"
            icon: mdi:window-open
        - entity: cover.rollos_og
            name: "Rollos OG"
            icon: mdi:window-open

        title: Quicktoggles
      - type: cardMedia
        entity: media_player.wohnzimmer_2
        title: "Sonos Wohnzimmer"
        entities:
          - entity: scene.br_klassik
            name: "BR Klassik"
            icon: mdi:violin
          - entity: scene.jazz
            name: "Jazz"
            icon: mdi:saxophone
      - type: cardGrid
        entities:
          - entity: vacuum.valetudo_r2d2
            name: "Start/Zurück"
            icon: mdi:vacuum
          - entity: script.r2d2_zum_mulleimer
            name: Pflege
            icon: mdi:spray-bottle
          - entity: script.1646845553960
            name: Küche
            icon: mdi:stove
        title: Haushalt
     - type: cardQR
        title: Gast Wifi
        qrCode: "WIFI:S:XXXXXXXX Gast;T:WPA;P:XXXXXXXXXXXX;;"
        entities:
          - entity: iText.XXXXXXX Gast
            name: Name
            icon: mdi:wifi
          - entity: iText.XXXXXXXXXXXXXXXXX
            name: Passwort
            icon: mdi:key

      - `

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
See description

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
NSPAnel should stay responsive. If there is a technical limitation regarding screen refresh and usability, maybe reduce the refreshes of the cover state and/or add an option to disable the state on the NSPanel and simply allow pressing buttons (up/down/stop).

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU
