### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by xXMoreWhisperXx** [joBr99/nspanel-lovelace-ui#1261]
### PROBLEM DESCRIPTION

I've been going crazy for days now trying to set up this mqtt connection between my nspanel and homeassistant since after trying everything the screen continues to load with the message "waiting for content..", I also tried to duplicate all the appdaemon files both in /config and in /addon... since I didn't really understand this difference between appdaemon 16 and the versions from 14 onwards
 I'm looking for help, thanks in advance

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:

![config1](https://github.com/user-attachments/assets/e1c0459c-a3cb-4a39-8f69-dea7f9c574fe)

- [ ] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:

![config2](https://github.com/user-attachments/assets/3f7a8ff8-3c7b-40f2-b15c-b80644fea156)
"
---
secrets: /homeassistant/secrets.yaml
appdaemon:
  latitude: 52.0
  longitude: 4.0
  elevation: 2
  time_zone: Europe/Berlin
  app_dir: /homeassistant/appdaemon/apps/ # !!! This is really important for AppDaemon HA Addon >= 15
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      #client_host: core-mosquitto.local.hass.io # This should work if you are using supervised HomeAssistant; if not use the IP Address instead.
      client_host: 192.168.1.117
      client_port: 1883
      client_user: "user"
      client_password: "xxxx"
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:

"
```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:
I also tried to duplicate all the files both in /config and in /addon... since I didn't really understand this difference between appdaemon 16 and the versions from 14 onwards
![confi 4](https://github.com/user-attachments/assets/f2c9d2ab-989d-4897-864b-9dce6f0df70c)

"
---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_naspanel/RESULT"
    panelSendTopic: "cmnd/tasmota_nspanel/CustomSend"
    model: eu

"


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:
![confi 5](https://github.com/user-attachments/assets/dbf6f0cc-c10c-43b1-b77c-5ac8a4cc0d61)

"

CRITICAL MQTT: Could not complete MQTT Plugin initialization, trying again in 5 seconds
--
CRITICAL MQTT: Could not Complete Connection to Broker,  please Ensure Broker at URL 192.168.1.117:1883 is correct and broker is  not down and restart Appdaemon

```

### ADDITIONAL INFORMATION

AppDaemon
Current version: v0.16.7

lovelace ui v4.4.0

**Comment by xXMoreWhisperXx** [comment]
![config2](https://github.com/user-attachments/assets/b44f5565-97f0-4847-a270-98a7fa2d26a8)

**Comment by joBr99** [comment]
First of all you need to fix my connection between appdeamon and your mqtt broker. Are you using the default home assistant OS or anything Special? (Like a docker container)

**Comment by xXMoreWhisperXx** [comment]
Yes I am using the default version of Home Assistant which is hosted on a Raspberry Pi 4

**Comment by joBr99** [comment]
You don't need to enter an IP this case the line with hass.io should work fine, just add your user and password.

Please try with 

```
client_host: core-mosquitto.local.hass.io
```

restart appdeamon and post the logs from appdeamon.

**Comment by xXMoreWhisperXx** [comment]
ok thanks, in the mqtt configuration on tasmota I don't change anything? do I remain 192.168.1.117?

**Comment by xXMoreWhisperXx** [comment]
2024-09-28 19:51:01.869258 CRITICAL MQTT: Could not complete MQTT Plugin initialization, trying again in 5 seconds
--
2024-09-28 19:51:01.665737 CRITICAL MQTT: MQTT Client Disconnected Abruptly. Will attempt reconnection
2024-09-28  19:51:01.663993 CRITICAL MQTT: Could not complete MQTT Plugin  initialization, for Connection was refused due to Not Authorised

**Comment by joBr99** [comment]
ip on tasmota doesn't change

`Could not complete MQTT Plugin initialization, for Connection was refused due to Not Authorised`

Your username or password isn't correct. You can also check the logs of your mqtt broker.

**Comment by xXMoreWhisperXx** [comment]
ok now I try to set a temporary password but it still doesn't work...
#client_host: 192.168.1.117
      client_port: 1883
      client_user: "user"
      client_password: "test123"
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
![test pass](https://github.com/user-attachments/assets/7efad9c0-6a7a-41c4-ac07-8fd1ad7ef601)

**Comment by joBr99** [comment]
Tasmota doesn't matter for now, your are authenticating agaist your mqtt broker - you can use your homeassistant user or password or you configure a seperate user on the mosquitto mqtt broker.

![image](https://github.com/user-attachments/assets/3abaddfb-1f1a-4197-98b0-359f1a87a0d9)

**Comment by xXMoreWhisperXx** [comment]
the guide I was following didn't report this step... is there anything I need to change below?
![dfhf](https://github.com/user-attachments/assets/7993684a-ed13-4a20-b562-6ca3b89027ad)

**Comment by joBr99** [comment]
looks good, restart appdaemon and send the current log

**Comment by xXMoreWhisperXx** [comment]
2024-09-28 20:13:34.937840 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/helper.py - ignoring
2024-09-28 20:13:34.939219 INFO AppDaemon: App initialization complete
2024-09-28 20:13:37.001882 INFO AppDaemon: New client Admin Client connected
2024-09-28 20:13:46.045357 INFO AppDaemon: Client disconnection from Admin Client
2024-09-28 20:13:46.827236 INFO AppDaemon: New client Admin Client connected

**Comment by joBr99** [comment]
Ignore the AppDaemon Webinteface. Restart and check logs here:

![image](https://github.com/user-attachments/assets/5fc543e8-ec18-4ab8-b8d2-f673114dc049)

**Comment by xXMoreWhisperXx** [comment]
![hvv](https://github.com/user-attachments/assets/f73bbf4f-bcf2-40f8-8de8-000077e10094)

**Comment by joBr99** [comment]
Ok, looks like you don't have any apps defined in apps.yaml

Might be related to this:

![image](https://github.com/user-attachments/assets/6860f9e5-a9d6-482e-a00d-2c448837287e)

Your appdaemon folder in /config is there twice, not sure how this is possible.

Should look like this:

![image](https://github.com/user-attachments/assets/6d4e6359-89da-4509-93b1-c23bb8e7c9cb)

**Comment by xXMoreWhisperXx** [comment]
I tried to rename the folder without lovelace ui inside and I copied the app.yaml file in the folder where there is also lovelace ui, now I restart everything and see what happens
![dfxch](https://github.com/user-attachments/assets/316dafbe-3e1f-4ca8-b2ae-b7224e81ad4a)

**Comment by joBr99** [comment]
I guess that looks better, restart appdaemon and send it's log again

**Comment by xXMoreWhisperXx** [comment]
![Uploading 56.JPG…]()

**Comment by joBr99** [comment]
Ok, looks good now - please check your mqtt settings on tasmota now.

You can also check and send the console log after restarting tasmota.

**Comment by xXMoreWhisperXx** [comment]
![58](https://github.com/user-attachments/assets/7efa3904-2080-485d-bf61-81b1c5652615)
![57](https://github.com/user-attachments/assets/c98ff640-5c8b-4329-b20a-0b89fdcf2453)

**Comment by joBr99** [comment]
Is the IP Address correct? Needs to be the IP of your HomeAssistant.

**Comment by xXMoreWhisperXx** [comment]
ah it must be the same as the raspberry pi, to be clear?

**Comment by xXMoreWhisperXx** [comment]
it's gone!!!!, yeey

**Comment by joBr99** [comment]
yes, if you are accessing your homeassistant like this:

![image](https://github.com/user-attachments/assets/e2885829-5fcb-4dff-a2b6-4624761c811f)

It's 192.168.75.30

**Comment by xXMoreWhisperXx** [comment]
only a red writing comes out on the right side "change model conf to us-l p" is this normal?

**Comment by joBr99** [comment]
Which type of the nspanel do you have?

**Comment by xXMoreWhisperXx** [comment]
-USW

**Comment by joBr99** [comment]
usw?

there are two different types:

![image](https://github.com/user-attachments/assets/cb45389d-45cd-47c4-ae66-b9bd680099fd)

**Comment by xXMoreWhisperXx** [comment]
the right

**Comment by joBr99** [comment]
Sound's like you've flashed the EU Firmware to the US Device.

Change your apps.yaml to this:

```
---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_nspanel/RESULT"
    panelSendTopic: "cmnd/tasmota_nspanel/CustomSend"
    model: us-l
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "de_DE"
    screensaver:
      entity: weather.k3ll3r
    cards:
      - type: cardEntities
        entities:
          - entity: switch.example_item
          - entity: light.example_item
        title: Example 1
      - type: cardGrid
        entities:
          - entity: switch.example_item
          - entity: light.example_item
        title: Example 2
```

It should automatically ask you if you want to flash the correct firmware on the screen.

If you want to use it in portrait mode instead of landscape use `us-p` instead of `us-l`
