### ISSUE TITLE
[Feature Request] Full example of advanced screensaver

### ISSUE THREAD

**Issue by DaPeace** [joBr99/nspanel-lovelace-ui#1265]
### FEATURE DESCRIPTION
The advanced screensaver has no full example. Ive used it in iobroker and discovered the possibilites in iobroker-forum but in home assistent there is only a short snippet:
  screensaver:
      type: screensaver2
      entities:
        - entity: weather.demo_weather_north
and thats it. Is it possible to have a example for that image :

[https://docs.nspanel.pky.eu/stable/img/screensaver2.png](url)

**Comment by joBr99** [comment]
It's the same as for the normal screensaver - you are just specifiying a list of entities.

If you want to know which entity is where you can do something like this:

```
screensaver:
  entities:
    - entity: iText.1
      icon: text:1
    - entity: iText.2
      icon: text:2
    - entity: iText.3
      icon: text:3
    - entity: iText.4
      icon: text:4
    - entity: iText.5
      icon: text:5
    - entity: iText.6
      icon: text:6
    - entity: iText.7
      icon: text:7
    - entity: iText.8
      icon: text:8
    - entity: iText.9
      icon: text:9
    - entity: iText.10
      icon: text:10
    - entity: iText.11
      icon: text:11
    - entity: iText.12
      icon: text:12
    - entity: iText.13
      icon: text:13
    - entity: iText.14
      icon: text:14
    - entity: iText.15
      icon: text:15
    - entity: iText.16
      icon: text:16
    - entity: iText.17
      icon: text:17
    - entity: iText.18
      icon: text:18
    - entity: iText.19
      icon: text:19
    - entity: iText.20
      icon: text:20
```

If you want to leave on blank in the middle of the list you should be able to use `    - entity: delete`
