### ISSUE TITLE
[Help] how to trigger the small icons at the screensaver from home assistant.

### ISSUE THREAD

**Issue by DaPeace** [joBr99/nspanel-lovelace-ui#1269]
Hi joBr99, in ioBroker it was really easy to trigger the small 2 icons Top Left and Right of the screensaver for the state of the relay.
In HA + Appdaemon i dont find any information how to set those up. 
Could you help out? Thank you!

**Comment by joBr99** [comment]
Hey you need to configure the statusIcons with the two relay entities from tasmota:


```
    screensaver:
.
.
.
        statusIcon1:
          entity: switch.example_item
        statusIcon2:
           entity: binary_sensor.example_item
```

https://docs.nspanel.pky.eu/stable/config-screensaver

**Comment by DaPeace** [comment]
Maybe im to stupid but i cant get it running and in your wiki there is also only a snipplet without connection to the rest of the syntax or a full example of all functions.

This is not working:
`
    screensaver:
      type: screensaver2
      entities:
      statusIcon1:
        - entity: switch.nspanelwozi
          icon:
            "on": mdi:heat-wave
            "off": delete
      statusIcon2:
        - entity: light.ledwozi_channel_1
`
And this is also not working.
`
    screensaver:
      statusIcon1:
        - entity: switch.nspanelwozi
          icon:
            "on": mdi:heat-wave
            "off": delete
      statusIcon2:
        - entity: light.ledwozi_channel_1
      type: screensaver2
      entities:
`

**Comment by randybb** [comment]
it is not a list, so without `-`.

```yaml
screensaver:
  statusIcon1:
    entity: switch.nspanelwozi
    icon:
      "on": mdi:heat-wave
      "off": delete
  statusIcon2:
    entity: light.ledwozi_channel_1
  type: screensaver2
  entities:
```
