### ISSUE TITLE
[Help] Waiting for Content - after HA and AppDaemon upgrade

### ISSUE THREAD

**Issue by uros76** [joBr99/nspanel-lovelace-ui#1271]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide a screenshot of your tasmota mqtt configuration:
![image](https://github.com/user-attachments/assets/153ef8f2-2f57-4d92-9250-3359cedbea46)

- [x] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:
---
secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Amsterdam
  app_dir: /homeassistant/appdaemon/apps/
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: 192.168.1.99
      client_port: 1883
      client_user: mqttonly
      client_password: Masamoja22
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:

```

- [x] Provide your apps.yaml:
```
  apps.yaml here:
---
nspanel:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel/RESULT"
    panelSendTopic: "cmnd/nspanel/CustomSend"
    homeButton: True
    model: eu
    screenBrightness: 50
    sleepTimeout: 20
    sleepBrightness:
      - time: "07:00:00"
        value: 15
      - time: "22:30:00"
        value: 0
    timeAdditionalTemplate: "Weather forecast - {{ states('weather.starowiejska_home') }}"
    cards:
      - type: cardQR
        title: Guest Wifi
        qrCode: "WIFI:S:PLAY internet 8742;T:WPA;P:secret;;"
        key: wifi
        entities:
          - entity: iText.PLAY internet 8742
            name: 'Wifi name:'
            icon: mdi:wifi
          - entity: iText.secret
            name: 'Password:'
            icon: mdi:key
      - type: cardEntities
        entities:
          - entity: cover.living_room_right_curtain
            nane: Living room right
          - entity: cover.living_room_left_curtain
            name: Living room left
          - entity: automation.open_windows_sunrise
            name: Automatic Opening
            icon: mdi:window-shutter-open
          - entity: automation.close_windows_at_sunset
            name: Automatic Closing
            icon: mdi:window-shutter
        title: Windows
    screensaver:
        entity: weather.starowiejska_home
        doubleTapToUnlock: False
        defaultCard: navigate.wifi
        theme:
            autoWeather: true
        statusIcon1:
          entity: lock.front_door_starowiejska_2
          altFont: True
        statusIcon2:
          entity: binary_sensor.front_door_starowiejska_open_2
          altFont: True
        alternativeLayout: True

```
- [x] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:
-----------------------------------------------------------
 Add-on: AppDaemon
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.16.7
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.2  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.10.4
 Home Assistant Supervisor: 2024.10.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[00:57:30] INFO: Starting AppDaemon...
ERROR Error loading secrets file: /config/secrets.yaml
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 417, in main
    admain.main()
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 276, in main
    if "appdaemon" not in config:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
[00:57:41] INFO: Service AppDaemon exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service appdaemon: stopping
s6-rc: info: service appdaemon successfully stopped
s6-rc: info: service init-appdaemon: stopping
s6-rc: info: service init-appdaemon successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

```

### ADDITIONAL INFORMATION

_I startted to get this problem after upgrading HA and AppDaemon from some late 2023 version. Something must have broken the setup or I dont know what_
