### ISSUE TITLE
[BUG] Date time string does not fit on the US version in portrait (with no option to change size/date format)

### ISSUE THREAD

**Issue by dodancs** [joBr99/nspanel-lovelace-ui#1275]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

The US version of the NSPanel in portrait improperly displays the date/time string on the screensaver, causing it to be clipped:
![image](https://github.com/user-attachments/assets/2d2362e4-6262-45bf-ad91-ca5e51c29084)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
  apps.yaml here:

---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_549F38/RESULT"
    panelSendTopic: "cmnd/tasmota_549F38/CustomSend"
    model: us-p
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 1
    screensaver:
      entity: weather.pirateweather
      entities:
        - entity: sensor.pirateweather_temperature
        - entity: sensor.sensor1_bme680_temperature
          name: Indoor
        - entity: sensor.pirateweather_wind_speed
          name: Wind
        - entity: sensor.pirateweather_precip_probability
          name: Rain
        - entity: sensor.pirateweather_cloud_coverage
          name: Clouds
    cards:
      - type: cardGrid
        title: Switches
        entities:
          - entity: switch.sonoff_pow_3
            name: Yamahas
            icon: mdi:speaker
          - entity: switch.sonoff_switch_1_main
            name: Bedroom light
            icon: mdi:ceiling-light-outline
          - entity: light.table_lights
            name: Table
            icon: mdi:floor-lamp
          - entity: light.workshop_light_light
            name: Workbench
            icon: mdi:hammer-wrench
          - entity: switch.sonoff_1001846780_1
            name: Bed lights
            icon: mdi:string-lights
      - type: cardGrid
        title: Scenes
        entities:
          - entity: scene.lights_low
            icon: mdi:floor-lamp
            color: [134, 79, 31]
          - entity: scene.lights_mid
            icon: mdi:floor-lamp
            color: [202, 152, 111]
          - entity: scene.lights_max
            icon: mdi:floor-lamp
            color: [251, 189, 136]
          - entity: scene.workshop_light_low
            name: Workbench low
            icon: mdi:hammer-wrench
            color: [134, 79, 31]
          - entity: scene.workshop_light_mid
            name: Workbench mid
            icon: mdi:hammer-wrench
            color: [202, 152, 111]
          - entity: scene.workshop_light_max
            name: Workbench max
            icon: mdi:hammer-wrench
            color: [251, 189, 136]
      - type: cardPower
        title: Power
        entities:
          - entity: sensor.sonoff_powct_energy_today
            icon: mdi:home
          - entity: delete
          - entity: sensor.sonoff_pow_1_energy_power
            icon: mdi:nas
            name: NAS + Server
            speed: 30
          - entity: delete
          - entity: sensor.sonoff_pow_2_energy_power
            icon: mdi:desktop-tower
            name: Desktop
            speed: 20
          - entity: sensor.sonoff_powct_energy_power
            icon: mdi:transmission-tower
            name: Home
            speed: 50
          - entity: delete
          - entity: sensor.sonoff_pow_3_energy_power
            icon: mdi:speaker
            name: Yamahas
            speed: -5
          - entity: delete
```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

- Buy the Sonoff NSPanel US version
- Install lovelace-ui
- Power it up

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

The date/time should scale automatically, or there should be a way to change the font size manually, or change the date/time format to include short day names or month names, so the text would fit.

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

![image](https://github.com/user-attachments/assets/2d2362e4-6262-45bf-ad91-ca5e51c29084)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

NSPanel US-P
Tasmota 14.2.0 (release-tasmota32)

**Comment by joBr99** [comment]
Hey, you can configure your own date format with dateFormat or dateFromatBabel (if you've that installed)

https://docs.nspanel.pky.eu/stable/config-overview/?h=date

This allows you to configure weekday and or month with short names. (%a and/or %b in the case without babel)

https://docs.python.org/3/library/datetime.html

**Comment by dodancs** [comment]
> Hey, you can configure your own date format with dateFormat or dateFromatBabel (if you've that installed)
> 
> https://docs.nspanel.pky.eu/stable/config-overview/?h=date
> 
> This allows you to configure weekday and or month with short names. (%a and/or %b in the case without babel)
> 
> https://docs.python.org/3/library/datetime.html

Many thanks! Adding `dateFormat` to the config entry allowed me to make it a custom date format:

```yaml
  config:
    model: us-p
    dateFormat: "%A, %d.%m.%Y"
```
