### ISSUE TITLE
[Help] Question about state update interval

### ISSUE THREAD

**Issue by h3llrais3r** [joBr99/nspanel-lovelace-ui#1280]
Hi, I'm using your ui on my 3 panels and I'm really loving it.
However, I have 1 question about the interval on which the states of home assistant sensors are checked/update.

I have the following part in my config:
```yaml
cards:
      - type: cardGrid
        title: Overzicht
        entities:
          - entity: button.bedroom_3_light_profile_default
            name: Standaard
            icon: mdi:lightbulb-on-50
            color: "{{iif(state_attr('light.smart_leds_bedroom_3', 'brightness') | int(0) == states('input_number.light_profile_default_brightness') | int(0), '[255, 193, 7]', '[85, 115, 158]', '[85, 115, 158]')}}"
```

The color of the button depends of the brightness of the light.
However, when I'm toggling the button (which sets the corresponding brightness), it takes quite a few seconds until the color is updated.
When I'm navigating away from the screen and back, it's there immediately.
Only when staying on the same screen, it really takes almost 20-30s until the color is reflected.
Any idea why this is happening and how this can be improved?

**Comment by joBr99** [comment]
Hey, there is a list of entities for each page that is used to get state updates and re-render the page if they have changed in homeassistant. - However this subscription doesn't work for templates. A quick fix would be this:

cards:
      - type: cardGrid
        title: Overzicht
        entities:
          - entity: button.bedroom_3_light_profile_default
            name: Standaard
            icon: mdi:lightbulb-on-50
            color: "{{iif(state_attr('light.smart_leds_bedroom_3', 'brightness') | int(0) == states('input_number.light_profile_default_brightness') | int(0), '[255, 193, 7]', '[85, 115, 158]', '[85, 115, 158]')}}"
          - entity: delete
          - entity: delete
          - entity: light.smart_leds_bedroom_3
          - entity: input_number.light_profile_default_brightness
          
          
Just put the entities you've used in the template at the end of the cardGird, won't be shown on the panel - but you will get state updates for them ;)

**Comment by h3llrais3r** [comment]
Thanks for the tip, but I've just tried it out but still the updates are very slow.
When I navigate away and back, the status is being reflected immediately.
When I'm staying on the page, it takes a long time until it's reflected, so I don't have the impression the state updates are faster... :(

**Comment by joBr99** [comment]
Please post your config

**Comment by h3llrais3r** [comment]
Here the complete config for the bedroom nspanel:

```yaml
nspanel-bedroom-3:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tasmota/sonoff/nspanel_bedroom_3/tele/RESULT"
    panelSendTopic: "tasmota/sonoff/nspanel_bedroom_3/cmnd/CustomSend"
    model: eu
    locale: "nl_BE"
    #dateFormatBabel: "EE d MMMM"
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "21:00:00"
        value: 0
    screensaver:
      entities:
        - entity: weather.forecast_home
        - entity: sensor.weather_forecast_daily # see https://docs.nspanel.pky.eu/stable/prepare_ha/#workaround-for-homeassistant-202404
          type: 0
        - entity: sensor.weather_forecast_daily # see https://docs.nspanel.pky.eu/stable/prepare_ha/#workaround-for-homeassistant-202404
          type: 1
        - entity: sensor.weather_forecast_daily # see https://docs.nspanel.pky.eu/stable/prepare_ha/#workaround-for-homeassistant-202404
          type: 2
        - entity: sensor.weather_forecast_daily # see https://docs.nspanel.pky.eu/stable/prepare_ha/#workaround-for-homeassistant-202404
          type: 3
      statusIcon1:
        entity: climate.smart_trv_bedroom_3
        # prefix with ha: to render home assistant templates, icons must be put between <I></I>
        icon: "ha:{{iif(state_attr('climate.smart_trv_bedroom_3', 'hvac_action')=='heating', '<I>mdi:fire</I>', '', '')}}"
        #color: [255, 193, 7]
      statusIcon2:
        entity: climate.smart_trv_bedroom_3
        icon: "ha:{{state_attr('climate.smart_trv_bedroom_3', 'current_temperature') | float(0) | round(1)}}°C"
        #entity: sensor.nspanel_bedroom_3_analog_temperature1
        #icon: "ha:{{states('sensor.nspanel_bedroom_3_analog_temperature1') | float(0) | round(1)}}°C"
        #color: [255, 193, 7]
    cards:
      - type: cardGrid
        title: Overzicht
        entities:
          - entity: button.bedroom_3_light_profile_default
            name: Standaard
            icon: mdi:lightbulb-on-50
            color: "{{iif(state_attr('light.smart_leds_bedroom_3', 'brightness') | int(0) == states('input_number.light_profile_default_brightness') | int(0), '[255, 193, 7]', '[85, 115, 158]', '[85, 115, 158]')}}"
          - entity: button.bedroom_3_light_profile_night
            name: Nacht
            icon: mdi:lightbulb-on-10
            color: "{{iif(state_attr('light.smart_leds_bedroom_3', 'brightness') | int(0) == states('input_number.light_profile_night_brightness') | int(0), '[255, 193, 7]', '[85, 115, 158]', '[85, 115, 158]')}}"
          - entity: button.bedroom_3_light_profile_work
            name: Werk
            icon: mdi:lightbulb-on
            color: "{{iif(state_attr('light.smart_leds_bedroom_3', 'brightness') | int(0) == states('input_number.light_profile_work_brightness') | int(0), '[255, 193, 7]', '[85, 115, 158]', '[85, 115, 158]')}}"
          - entity: navigate.light
            name: Aanpassen
            icon: mdi:lightbulb
            color: "{{iif(states('light.smart_leds_bedroom_3')=='on', '[255, 193, 7]', '[85, 115, 158]', '[85, 115, 158]')}}"
          - entity: sensor.smart_sensor_bedroom_3_temperature
            name: Temperatuur
          - entity: navigate.thermostat
            name: Thermostaat
            icon: mdi:thermostat
    hiddenCards:
      - type: cardEntities
        title: Verlichting
        key: light
        entities:
          - entity: light.smart_leds_bedroom_3
            name: Kleuren
          - entity: input_boolean.bedroom_3_light_disco_mode_toggle
            name: Disco modus
          - entity: input_number.bedroom_3_light_disco_mode_interval_nspanel
            name: Disco interval
          - entity: navigate.light_lamps
            name: Lampen individueel
            icon: mdi:lightbulb
      - type: cardEntities
        title: Lampen
        key: light_lamps
        entities:
          - entity: light.smart_led_bedroom_3_lamp_1
            name: Lamp 1
          - entity: light.smart_led_bedroom_3_lamp_2
            name: Lamp 2
          - entity: light.smart_led_bedroom_3_lamp_3
            name: Lamp 3
      - type: cardThermo
        title: Thermostaat
        key: thermostat
        entity: climate.smart_trv_bedroom_3
```

**Comment by joBr99** [comment]
This should work - not sure how you added the addtitional entities:

```
nspanel-bedroom-3:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tasmota/sonoff/nspanel_bedroom_3/tele/RESULT"
    panelSendTopic: "tasmota/sonoff/nspanel_bedroom_3/cmnd/CustomSend"
    model: eu
    locale: "nl_BE"
    #dateFormatBabel: "EE d MMMM"
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "21:00:00"
        value: 0
    screensaver:
      entities:
        - entity: weather.forecast_home
        - entity: sensor.weather_forecast_daily # see https://docs.nspanel.pky.eu/stable/prepare_ha/#workaround-for-homeassistant-202404
          type: 0
        - entity: sensor.weather_forecast_daily # see https://docs.nspanel.pky.eu/stable/prepare_ha/#workaround-for-homeassistant-202404
          type: 1
        - entity: sensor.weather_forecast_daily # see https://docs.nspanel.pky.eu/stable/prepare_ha/#workaround-for-homeassistant-202404
          type: 2
        - entity: sensor.weather_forecast_daily # see https://docs.nspanel.pky.eu/stable/prepare_ha/#workaround-for-homeassistant-202404
          type: 3
      statusIcon1:
        entity: climate.smart_trv_bedroom_3
        # prefix with ha: to render home assistant templates, icons must be put between <I></I>
        icon: "ha:{{iif(state_attr('climate.smart_trv_bedroom_3', 'hvac_action')=='heating', '<I>mdi:fire</I>', '', '')}}"
        #color: [255, 193, 7]
      statusIcon2:
        entity: climate.smart_trv_bedroom_3
        icon: "ha:{{state_attr('climate.smart_trv_bedroom_3', 'current_temperature') | float(0) | round(1)}}°C"
        #entity: sensor.nspanel_bedroom_3_analog_temperature1
        #icon: "ha:{{states('sensor.nspanel_bedroom_3_analog_temperature1') | float(0) | round(1)}}°C"
        #color: [255, 193, 7]
    cards:
      - type: cardGrid
        title: Overzicht
        entities:
          - entity: button.bedroom_3_light_profile_default
            name: Standaard
            icon: mdi:lightbulb-on-50
            color: "{{iif(state_attr('light.smart_leds_bedroom_3', 'brightness') | int(0) == states('input_number.light_profile_default_brightness') | int(0), '[255, 193, 7]', '[85, 115, 158]', '[85, 115, 158]')}}"
          - entity: button.bedroom_3_light_profile_night
            name: Nacht
            icon: mdi:lightbulb-on-10
            color: "{{iif(state_attr('light.smart_leds_bedroom_3', 'brightness') | int(0) == states('input_number.light_profile_night_brightness') | int(0), '[255, 193, 7]', '[85, 115, 158]', '[85, 115, 158]')}}"
          - entity: button.bedroom_3_light_profile_work
            name: Werk
            icon: mdi:lightbulb-on
            color: "{{iif(state_attr('light.smart_leds_bedroom_3', 'brightness') | int(0) == states('input_number.light_profile_work_brightness') | int(0), '[255, 193, 7]', '[85, 115, 158]', '[85, 115, 158]')}}"
          - entity: navigate.light
            name: Aanpassen
            icon: mdi:lightbulb
            color: "{{iif(states('light.smart_leds_bedroom_3')=='on', '[255, 193, 7]', '[85, 115, 158]', '[85, 115, 158]')}}"
          - entity: sensor.smart_sensor_bedroom_3_temperature
            name: Temperatuur
          - entity: navigate.thermostat
            name: Thermostaat
            icon: mdi:thermostat
          - entity: light.smart_leds_bedroom_3
          - entity: input_number.light_profile_work_brightness
    hiddenCards:
      - type: cardEntities
        title: Verlichting
        key: light
        entities:
          - entity: light.smart_leds_bedroom_3
            name: Kleuren
          - entity: input_boolean.bedroom_3_light_disco_mode_toggle
            name: Disco modus
          - entity: input_number.bedroom_3_light_disco_mode_interval_nspanel
            name: Disco interval
          - entity: navigate.light_lamps
            name: Lampen individueel
            icon: mdi:lightbulb
      - type: cardEntities
        title: Lampen
        key: light_lamps
        entities:
          - entity: light.smart_led_bedroom_3_lamp_1
            name: Lamp 1
          - entity: light.smart_led_bedroom_3_lamp_2
            name: Lamp 2
          - entity: light.smart_led_bedroom_3_lamp_3
            name: Lamp 3
      - type: cardThermo
        title: Thermostaat
        key: thermostat
        entity: climate.smart_trv_bedroom_3
```
