### ISSUE TITLE
[BUG] icon template color for service ignored

### ISSUE THREAD

**Issue by BenDavidson90** [joBr99/nspanel-lovelace-ui#1288]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
I tried to configure this entity:
```yaml
- entity: service.rest_command.oklyn_pump_off
  name: "Off"
  icon: mdi:fan
  color: '{{iif(states("binary_sensor.test")=="on", "[0,255,0]", "[255,165,255]")}}'
```
It doesn't work, the color stay the default one.
But if I replace service.rest_command.oklyn_pump_off by light.some_lamp, it works and the color changes.
It's a little like https://github.com/joBr99/nspanel-lovelace-ui/issues/586

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
Code above

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
None

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Code above

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
Icon should change color according to the template

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU
