### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by vmhomelab** [joBr99/nspanel-lovelace-ui#1293]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide a screenshot of your tasmota mqtt configuration:
I used esphome to flahs the nspanle. Here is the nspanel.yaml file I used:
```
substitutions:
  devicename: nspanel
  friendly_devicename: NSPanel Test
  panel_recv_topic: "tele/nspanel/RESULT"
  panel_send_topic: "cmnd/nspanel/CustomSend"

esphome:
  name: $devicename

esp32:
  board: esp32dev

wifi:
  networks:
    - ssid: "IoT"
      password: "XXXXXX"

# Logger. Disable the temperature sensor etc. to focus on the HMI development
logger:
  level: DEBUG
  logs:
    sensor: WARN
    resistance: WARN
    text_sensor: WARN
    ntc: WARN

ota:
  platform: esphome

# API. Add api_pwd to your secrets.yaml.
api:
  services:
    - service: upload_tft
      variables:
        url: string
      then:
        - lambda: |-
            id(nspanel).upload_tft(url);
    # Service to play a rtttl tone
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda "return song_str;"
    # Service to send a command directly to the display. Useful for testing
    - service: send_command
      variables:
        cmd: string
      then:
        - lambda: "id(nspanel).send_custom_command(cmd.c_str());"
    # Service to pusblish to mqtt used for refreshin the panel
    - service: publish_to_recv_topic
      variables:
        cmd: string
      then:
        - mqtt.publish:
            topic: $panel_recv_topic
            payload: !lambda "return cmd;"
    # Service to send a command wake the screen
    - service: wake
      then:
        - lambda: 'id(nspanel).send_custom_command("wake");'
    # Service to send a command to show screensaver (some of the values are hardcoded)
    - service: show_screensaver
      then:
        - mqtt.publish:
            topic: $panel_recv_topic
            payload: '{"CustomRecv":"event,sleepReached,cardGrid"}'
    # Service to navigate to screen
    - service: navigate_to_page
      variables:
        page: string
      then:
        - mqtt.publish_json:
            topic: $panel_recv_topic
            payload: |-
              root["CustomRecv"] = "event,buttonPress2,navigate." + page + ",button";
    # Service to send a command disable screensaver
    - service: disable_screensaver
      then:
        - lambda: 'id(nspanel).send_custom_command("timeout~0");'
    # Service to send a command enabled screensaver
    - service: enable_screensaver
      then:
        - lambda: 'id(nspanel).send_custom_command("timeout~20");'
    # Service to send a command wake the screen
    - service: dim_0_to_100
      variables:
        intensity: string
      then:
        - lambda: 'id(nspanel).send_custom_command("dimmode~"+intensity+"~100");'
    # Service to send a command To show the screen of a specific like
    - service: show_entity
      variables:
        entity: string
        title: string
      then:
        - lambda: 'id(nspanel).send_custom_command("pageType~popupLight~" + title + "~" + entity);'
    # Service to send a command To show the screen of a specific like
    - service: notify_on_screensaver
      variables:
        line1: string
        line2: string
      then:
        - lambda: 'id(nspanel).send_custom_command("notify~" + line1 + "~" + line2);'
        - rtttl.play: "short:d=4,o=5,b=100:16e6"
    # Service to send a command To show the screen of a specific like
    # interaction of the buttons are on implemented yet
    - service: notify_fullscreen
      variables:
        title: string
        description: string
        button1: string
        button2: string
        time_secs: string
      then:
        # show notification screen
        - lambda: 'id(nspanel).send_custom_command("pageType~popupNotify");'
        # set values on notification screen
        # color defined as number created in binary and converted to decimal (rrrrggggbbbbaaaa)
        - lambda: 'id(nspanel).send_custom_command("entityUpdateDetail~id~"+ title + "~65535~" + button1 +"~3840~" + button2 + "~61440~" + description + "~65535~" + time_secs);'
        - rtttl.play: "scale_up:d=32,o=5,b=100:c,c#,d#,e,f#,g#,a#,b"

# Uart for the Nextion display
uart:
  tx_pin: 16
  rx_pin: 17
  baud_rate: 115200

# Functionality for the Nextion display
external_components:
  - source:
      type: git
      url: https://github.com/sairon/esphome-nspanel-lovelace-ui
      ref: dev
    components: [nspanel_lovelace]

mqtt:
  id: mqtt_client
  broker: "10.17.200.5"
  username: "XXXXXX"
  password: "XXXXXX"

nspanel_lovelace:
  id: nspanel
  mqtt_recv_topic: $panel_recv_topic
  mqtt_send_topic: $panel_send_topic

sensor:
  # Internal temperature sensor, adc value
  - platform: adc
    id: ntc_source
    pin: 38
    update_interval: 10s
    attenuation: 11db

  # Internal temperature sensor, adc reading converted to resistance (calculation)
  - platform: resistance
    id: resistance_sensor
    sensor: ntc_source
    configuration: DOWNSTREAM
    resistor: 11.2kOhm

  # Internal temperature sensor, resistance to temperature (calculation)
  - platform: ntc
    id: temperature
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: $friendly_devicename Temperature

output:
  # Buzzer for playing tones
  - platform: ledc
    id: buzzer_out
    pin:
      number: 21

# Rtttl function for buzzer
rtttl:
  id: buzzer
  output: buzzer_out

switch:
  # Physical relay 1
  - platform: gpio
    name: $friendly_devicename Relay 1
    id: relay_1
    pin:
      number: 22
    on_turn_on:
      # show a light on the panel when we swich on the light
      # - lambda: 'id(nspanel).send_custom_command("pageType~popupLight~[TITLE TO SHOW ON SCREEN]~[ENTITY NAME]");'
      - lambda: 'id(nspanel).send_custom_command("pageType~popupLight~Light 1~light.deckenlampe");'
    on_turn_off:
      # send to screensaver when switch off the light
      - mqtt.publish:
          topic: $panel_recv_topic
          payload: '{"CustomRecv":"event,sleepReached,cardGrid"}'

  # Physical relay 2
  - platform: gpio
    name: $friendly_devicename Relay 2
    id: relay_2
    pin:
      number: 19
    on_turn_on:
      # show a light on the panel when we swich on the light
      - lambda: 'id(nspanel).send_custom_command("pageType~popupLight~Light 2~light.fado_5");'
    on_turn_off:
      # send to screensaver when switch off the light
      - mqtt.publish:
          topic: $panel_recv_topic
          payload: '{"CustomRecv":"event,sleepReached,cardGrid"}'

  # Turn screen power on/off. Easy way to configure the screen power control, but this should not be used from HA, as all components must be re-initialized afterwards. For lights, names of lights etc. this practically means that the state must change once to happen.
  - platform: gpio
    name: Screen Power
    id: screen_power
    entity_category: config
    pin:
      number: 4
      inverted: true
    restore_mode: ALWAYS_ON

# Binary sensors
binary_sensor:
  # Left button below the display
  - platform: gpio
    name: $friendly_devicename Left Button
    pin:
      number: GPIO14
      inverted: true
    id: left_button
    on_press:
      then:
        - switch.toggle: relay_1

  # Right button below the display
  - platform: gpio
    name: $friendly_devicename Right Button
    pin:
      number: GPIO27
      inverted: true
    id: right_button
    on_press:
      then:
        - switch.toggle: relay_2`
```

- [x] Provide your appdaemon.yaml: 

  appdaemon.yaml here:

```
secrets: /homeassistant/secrets.yaml
appdaemon:
  latitude: 52.0
  longitude: 4.0
  elevation: 2
  time_zone: Europe/Berlin
  app_dir: /homeassistant/appdaemon/apps/ # !!! This is really important for AppDaemon HA Addon >= 15
  #app_dir: homeassistant/appdaemon/apps/ # !!! This is really important for AppDaemon HA Addon >= 15
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: core-mosquitto.local.hass.io # This should work if you are using supervised HomeAssistant; if not use the IP Address instead.
      #client_host: 10.17.200.5
      client_port: 1883
      client_user: "XXXXXX"
      client_password: "XXXXXX"
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
```

- [x] Provide your apps.yaml:
  apps.yaml here:

```
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_nspanel/RESULT"
    panelSendTopic: "cmnd/tasmota_nspanel/CustomSend"
    model: us-l
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "it_IT"
    screensaver:
      entity: weather.zuhause
    cards:
      - type: cardEntities
        entities:
          - entity: switch.example_item
          - entity: light.example_item
        title: Example 1
      - type: cardGrid
        entities:
          - entity: switch.example_item
          - entity: light.example_item
        title: Example 2`
```

- [x] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container: Log output here:

```
Installing collected packages: babel
Successfully installed babel-2.16.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[17:26:23] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
2025-01-12 17:26:25.980005 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2025-01-12 17:26:25.980181 INFO AppDaemon: Python version is 3.11.10
2025-01-12 17:26:25.980304 INFO AppDaemon: Configuration read from: /config/appdaemon.yaml
2025-01-12 17:26:25.980425 INFO AppDaemon: Added log: AppDaemon
2025-01-12 17:26:25.980533 INFO AppDaemon: Added log: Error
2025-01-12 17:26:25.980650 INFO AppDaemon: Added log: Access
2025-01-12 17:26:25.980786 INFO AppDaemon: Added log: Diag
2025-01-12 17:26:26.109165 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2025-01-12 17:26:26.227382 INFO HASS: HASS Plugin Initializing
2025-01-12 17:26:26.227536 WARNING HASS: ha_url not found in HASS configuration - module not initialized
2025-01-12 17:26:26.227681 INFO HASS: HASS Plugin initialization complete
2025-01-12 17:26:26.228003 INFO AppDaemon: Initializing HTTP
2025-01-12 17:26:26.228232 INFO AppDaemon: Using 'ws' for event stream
2025-01-12 17:26:26.230797 INFO AppDaemon: Starting API
2025-01-12 17:26:26.232369 INFO AppDaemon: Starting Admin Interface
2025-01-12 17:26:26.232607 INFO AppDaemon: Starting Dashboards
2025-01-12 17:26:26.243970 INFO HASS: Connected to Home Assistant 2025.1.2
2025-01-12 17:26:26.251509 INFO AppDaemon: App 'hello_world' added
2025-01-12 17:26:26.252235 INFO AppDaemon: Found 1 active apps
2025-01-12 17:26:26.252432 INFO AppDaemon: Found 0 inactive apps
2025-01-12 17:26:26.252701 INFO AppDaemon: Found 0 global libraries
2025-01-12 17:26:26.252956 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2025-01-12 17:26:26.253447 INFO AppDaemon: Running on port 5050
2025-01-12 17:26:26.281617 INFO HASS: Evaluating startup conditions
2025-01-12 17:26:26.285951 INFO HASS: Startup condition met: hass state=RUNNING
2025-01-12 17:26:26.286127 INFO HASS: All startup conditions met
2025-01-12 17:26:26.320204 INFO AppDaemon: Got initial state from namespace default
2025-01-12 17:26:28.258446 INFO AppDaemon: Scheduler running in realtime
2025-01-12 17:26:28.260216 INFO AppDaemon: Adding /config/apps to module import path
2025-01-12 17:26:28.261295 INFO AppDaemon: Loading App Module: /config/apps/hello.py
2025-01-12 17:26:28.283991 INFO AppDaemon: Loading app hello_world using class HelloWorld from module hello
2025-01-12 17:26:28.285388 INFO AppDaemon: Calling initialize() for hello_world
2025-01-12 17:26:28.328668 INFO hello_world: Hello from AppDaemon
2025-01-12 17:26:28.329581 INFO hello_world: You are now ready to run Apps!
2025-01-12 17:26:28.330568 INFO AppDaemon: App initialization complete
2025-01-12 17:26:30.868078 INFO AppDaemon: New client Admin Client connected

```
### ADDITIONAL INFORMATION
When I first installed the NSPanel Lovelace UI Backend I had to manually create the folder appdaemon and the two files appdaemon.yaml and apps.yaml.

In the mqqt broker I can see the nspanel connecting.
_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_

**Comment by joBr99** [comment]
Where is your appdaemon.yaml located?

apps.yaml needs to be here:

![image](https://github.com/user-attachments/assets/946f4371-394e-47a7-b0b6-286056523b3f)

But appdaemon.yaml here:

![image](https://github.com/user-attachments/assets/7e665c6d-f01a-49ce-add0-f535dee233e2)

**Comment by vmhomelab** [comment]
My appdaemon.yaml is located in /config/appdaemon
![grafik](https://github.com/user-attachments/assets/1fe57328-1a80-4dd2-af05-3786da20a053)

**Comment by joBr99** [comment]
Appdaemon is searching for the file at this location:

![image](https://github.com/user-attachments/assets/cd523f12-d8d1-45c3-af10-95ace6bd0355)


You can change the folder with File>Open Folder in the Editor

**Comment by vmhomelab** [comment]
So do I have to create a folder A0D7B954_APPDAEMON? Because I do not have such a folder

**Comment by vmhomelab** [comment]
![grafik](https://github.com/user-attachments/assets/be2162f4-f52a-43a1-8f9b-eddad0b584de)
This is my appdaemon folder

**Comment by joBr99** [comment]
It's automatically created by appdeamon in /addon_configs/

**Comment by vmhomelab** [comment]
Ohhh I see. Now its getting content but it keeps on telling me that the display firmaware has changed (current: us-l and new: eu; I have the eu version) When I click update/change it starts to load a new firmware but then it just keeps telling me the same thing. I cant use the touchscreen if I dismiss the notification. I will post a picture as soon as the device updated

**Comment by vmhomelab** [comment]
Nevermind, now it is working. Now I have setup a cardEntities but when waking up the display it shows: "Setup successful..."
![grafik](https://github.com/user-attachments/assets/ae6fec34-3fc3-4cae-83cd-3607ffa1e67b)

This is the apps.yaml:

```
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel/RESULT"
    panelSendTopic: "cmnd/nspanel/CustomSend"
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "de_DE"
    screensaver:
      entity: weather.zuhause
      cards:
        - type: cardEntities
          title: Test Entities Card
          entities:
            - entity: light.deckenlampe
            - entity: light.fado_5
            - entity: light.kugel
```
