### ISSUE TITLE
[Feature Request] Screensaver and notification

### ISSUE THREAD

**Issue by wolwin** [joBr99/nspanel-lovelace-ui#1306]
### FEATURE DESCRIPTION
When a notification is sent to the active screensaver, it is displayed with 'Heading' and 'Text'.
`notify~heading~text`
If the screen saver is in 'sleepBrightness' mode, the message cannot be read. If you tap on the screen, the message disappears.

Please add / change the following points
1. When a message is sent, the screen saver should be reactivated so that the message can be read (or is there a workaround?).
2. The message should not be deleted in the screen saver if 'doubleTapToUnlock: True' is set and you press the screen once to see the active screen saver.
3. The notification sent to the active screen saver should be configurable with colors
 `notify~heading~text~headingColor~textColor`

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERSION
Homeassistant 2024.12.5 - Tasmota Firmware: 14.4.1.3 - NSPanel Lovelace UI V4.4.0

**Comment by joBr99** [comment]
Hey, looking at the code this should already be the case:

```
                                    if(tInstruction.txt=="notify")
                                    {
                                        spstr strCommand.txt,tNotifyHead.txt,"~",1
                                        spstr strCommand.txt,tNotifyText.txt,"~",2
                                        if(tNotifyHead.txt!=""||tNotifyText.txt!="")
                                        {
                                            vis tNotifyHead,1
                                            vis tNotifyText,1
                                        }else
                                        {
                                            vis tNotifyHead,0
                                            vis tNotifyText,0
                                        }
                                        tNotifyHead.bco=tTime.bco
                                        tNotifyText.bco=tTime.bco
                                        spstr strCommand.txt,tTmp.txt,"~",3
                                        if(tTmp.txt!="")
                                        {
                                            covx tTmp.txt,tNotifyHead.pco,0,0
                                        }
                                        spstr strCommand.txt,tTmp.txt,"~",4
                                        if(tTmp.txt!="")
                                        {
                                            covx tTmp.txt,tNotifyText.pco,0,0
                                        }
                                    }
```

**Comment by joBr99** [comment]
>When a message is sent, the screen saver should be reactivated so that the message can be read (or is there a workaround?).

A possible workaround would be to send the command for changing the brightness with the notification. (Is also increasing the chance that something is able to see it)

**Comment by wolwin** [comment]
> Hey, looking at the code colors should already be set:
> 
Right, I must have missed it in the documentary - works ...

`notify~heading~text~headingColor~textColor`

**Comment by wolwin** [comment]
> A possible workaround would be to send the command for changing the brightness with the notification. (Is also increasing the chance that something is able to see it)

You mean with

`dimmode~sleepBrightness~screenBrightness`

**Comment by wolwin** [comment]
> double tap is currently a server side feature and the message is deleted on the panel's side

OK - that would have been the main entry point for a change. So the workaraound with 'sleepBrightness' must in any case be reset to the original value ...

**Comment by wolwin** [comment]
My proof of concept for HA - maybe someone can use it ...

**Scripts**

```
alias: NSPanel - screensaver notification send
description: NSPanel - screensaver notification send
sequence:
  - data:
      topic: "{{mqttpath}}/{{target}}/cmnd/CustomSend"
      payload: dimmode~{{ sleepBrightness }}~{{ screenBrightness }}
    action: mqtt.publish
  - data:
      topic: "{{mqttpath}}/{{target}}/cmnd/CustomSend"
      payload: notify~{{ heading }}~{{ message }}~{{ headingColor }}~{{ messageColor }}
    action: mqtt.publish
  - data:
      topic: "{{mqttpath}}/{{target}}/cmnd/Buzzer"
      payload: "{{buzzer}}"
    action: mqtt.publish
mode: queued
icon: mdi:message-badge
``` 
```
alias: NSPanel - screensaver notification clear
description: NSPanel - screensaver notification clear
sequence:
  - data:
      topic: "{{mqttpath}}/{{target}}/cmnd/CustomSend"
      payload: dimmode~{{ sleepBrightness }}~{{ screenBrightness }}
    action: mqtt.publish
  - data:
      topic: "{{mqttpath}}/{{target}}/cmnd/CustomSend"
      payload: notify~~
    action: mqtt.publish
mode: queued
icon: mdi:message-badge-outline
```

**Automations**

```
alias: NSP-999 - screensaver notification send
description: NSP-999 - screensaver notification send
triggers: null
conditions: []
actions:
  - action: script.nspanel_notification_send
    metadata: {}
    data:
      target: nspanel_999
      mqttpath: myXYZ/devices
      heading: Test-Heading
      headingColor: 63488
      message: >-
        Franz jagt im komplett verwahrlosten Taxi quer {{'\r\n'}}durch Bayern.
        Franz jagt quer durch Bayern.
      messageColor: 2047
      sleepBrightness: 60
      screenBrightness: 60
      buzzer: 1,1,1,0xF54
mode: single
```

```
alias: NSP-999 - screensaver notification clear
description: NSP-999 - screensaver notification clear
triggers: null
conditions: []
actions:
  - action: script.nspanel_notification_clear
    metadata: {}
    data:
      target: nspanel_999
      mqttpath: myXYZ/devices
      sleepBrightness: 4
      screenBrightness: 60
mode: single
```
