### ISSUE TITLE
How to install to stand allone AppDaemon

### ISSUE THREAD

**Issue by krzysztofkuczek** [joBr99/nspanel-lovelace-ui#1308]
Hi,
I have installed HA, mosquito and AppDaemon instances on separate dockers, and somehow integrated, but i still can't find info, how to  manually install nspanel-lovelace-ui to AppDaemon (no HA store available for HACK,etc).
What i did is copy apps/nspanel-lovelace-ui folder to the apps folder and it starts working (somehow)

The problem is that nspanel is updated but not any graphics appears, just error not found check

![Image](https://github.com/user-attachments/assets/22530eed-981e-45cb-812b-609890afa580)

So it looks like i forgot about copying some part of this cool stuff :)

Thank you in advance

The conf files
appdaemon.yaml: 
```
appdaemon:
  latitude: 0
  longitude: 0
  elevation: 30
  time_zone: Europe/Berlin
  plugins:
    HASS:
      type: hass
      ha_url: http://192.168.14.2:8123
      token: asddasdsadadasd
      cert_verify: False
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: 192.168.14.2
      client_port: 1883
      client_user: "xxxx"
      client_password: "dasdasdasd"
      client_topics: NONE

http:
  url: http://192.168.14.2:5050
admin:
api:
hadashboard:


```

and the  apps.yaml:
```
hello_world:
  module: hello
  class: HelloWorld

nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel1/RESULT"
    panelSendTopic: "cmnd/nspanel1/CustomSend"
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "de_DE"
    screensaver:
      entities:
        - entity: weather.demo_weather_north
        - entity: weather.demo_weather_north
          type: 0
        - entity: weather.demo_weather_north
          type: 1
        - entity: weather.demo_weather_north
          type: 2
        - entity: sensor.energy_usage
    cards:
      - type: cardEntities
        entities:
          - entity: switch.example_item
          - entity: light.example_item
        title: Example 1
      - type: cardGrid
        entities:
          - entity: switch.example_item
          - entity: light.example_item
        title: Example 2



```
