### ISSUE TITLE
[Help] What is the meaing of "type" field in screensaver config

### ISSUE THREAD

**Issue by krzysztofkuczek** [joBr99/nspanel-lovelace-ui#1309]
Hi,
Can't find info what is the meaning of "type" field with values 0,1,2  
Is it index for forecast day? or what?
```

screensaver config with custom entities/overrides:

    screensaver:
      entities:
        - entity: weather.demo_weather_north
        - entity: weather.demo_weather_north
          type: 0
        - entity: weather.demo_weather_north
          type: 1
        - entity: weather.demo_weather_north
          type: 2
        - entity: sensor.energy_usage

```

Thank you in advance
Kris
