### ISSUE TITLE
Check release link

### ISSUE THREAD

**Issue by dominikfe** [joBr99/nspanel-lovelace-ui#131]
Hi!
For me neither the grid card, nor the entities card show an icon - tried it with different entries, e.g. "lightbulb" or "fingerprint" but only get "0" or "1" on the display instead of an icon.
Thx

**Comment by joBr99** [comment]
Please post an example of your config, in case you are using the current release this is the list of available icons:

https://github.com/joBr99/nspanel-lovelace-ui/blob/v2.5.5/HMI/icons.md

**Comment by dominikfe** [comment]
Here is my config:
```
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/NSpanel/RESULT"
    panelSendTopic: "cmnd/NSpanel/CustomSend"
    updateMode: "auto-notify"
    sleepTimeout: 20
    #sleepBrightness: 10
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "de_DE" # used for translations in translations.py and for localized date if babel python package is installed
    screensaver:
      entity: weather.home
    cards:
      - type: cardEntities
        title: Lichter
        entities:
          - entity: light.wand_kuche
            icon: lightbulb
```
