### ISSUE TITLE
[Help] How to prevent updating number type entity with old value

### ISSUE THREAD

**Issue by krzysztofkuczek** [joBr99/nspanel-lovelace-ui#1310]
Hi,
I have  a problem with a number (slider) entity which is responsible for setting temperature of my viessmann boiler.
The problem is, that when i try to set the value, it's set for the moment and then it returns to the previous state.
Probably because the boiler does not update fast enough desired temperature and it still sends old temperature.

You can take a closer look at short video:
https://youtu.be/i-k-OgKxp0Q

The card definition looks like this
```
      - type: cardEntities
        title: Piec
        navItem1:
          entity: navigate.home
          icon: home
        entities:
          - entity: climate.e3_vitodens_100_bhc_0421_heating
            name: "Ogrzewanie"
          - entity: number.e3_vitodens_100_bhc_0421_normalna_temperatura
            name: "Ogrzewanie - temp."
          - entity: number.e3_vitodens_100_bhc_0421_dhw_temperature
            name: "Ciepła woda - temp."

```

Thank you in advance.
Kris

PS, maybe i should use climate.e3_vitodens_100_bhc_0421_heating entity instead, but i don't have idea how to use it's temperature attribute

PS2, 
Using such a automation, and input number for UI solve the problem partially
```
alias: Ustawianie temperatury ogrzewania dla nspanel
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_number.temperatura_ogrzewania
conditions: []
actions:
  - target:
      entity_id: number.e3_vitodens_100_bhc_0421_normalna_temperatura
    data:
      value: "{{ states('input_number.temperatura_ogrzewania') | float }}"
    action: number.set_value
mode: single
```
