### ISSUE TITLE
[Help] Call a Specific Card

### ISSUE THREAD

**Issue by tv4you2016** [joBr99/nspanel-lovelace-ui#1312]
Hello @joBr99 ,
I would like to know if it is possible with an external input (script/service/input/etc), to tell my NSPainel to wake up and call a specific card?? 

Exemplo: 
```
if input1.press= Nspainel Wakeup
{
- type: cardAlarm
  title: Alarm
 entity: alarm_control_panel.home_alarm

}
```
```
---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_C35E50/RESULT"
    panelSendTopic: "cmnd/tasmota_C35E50/CustomSend"
    model: us-l
    sleepTimeout: 15
    sleepBrightness: 0
    locale: "pt_PT"
    screensaver:
      entities:
        - entity: weather.tdm_house
        - entity: sensor.weather_forecast_daily
          type: 1
        - entity: sensor.weather_forecast_daily
          type: 2
        - entity: sensor.weather_forecast_daily
          type: 3
        - entity: sensor.weather_forecast_daily
          type: 4
      doubleTapToUnlock: True
    cards:

      - type: cardGrid
        title: Cozinha
        entities:
          - entity: sensor.tasmota_analog_temperature1
            name: Temperatura
          - entity: cover.estore_cozinha
            name: Estore
          - entity: light.teto_cozinha
            name: Luz Teto
      - type: cardGrid
        title: Divisões
        entities:
          - entity: navigate.sala
            icon: mdi:sofa
          - entity: navigate.q1
            icon: mdi:hanger
          - entity: navigate.garagem
            icon: mdi:garage
          - entity: navigate.q2
            icon: mdi:bed
          - entity: navigate.qp
            icon: mdi:bed
          - entity: navigate.grass
            icon: mdi:grass

      - type: cardAlarm
        title: Alarm
        entity: alarm_control_panel.home_alarm
    hiddenCards:
      - type: cardThermo
        title: HeatPump
        entity: climate.caldeiraemaquecimento
        key: caldeira

      - type: cardMedia
        entity: media_player.aiplus2k
        entities:
          - entity: cover.estore_qp
          - entity: cover.estore_qp
          - entity: cover.estore_qp
        key: tv_qp
        entities:
          - entity: delete
          - entity: delete
          - entity: delete
          - entity: delete
          - entity: delete

      - type: cardEntities
        entities:
          - entity: sensor.iaq_sala_temperature
            name: Temperatura
          - entity: switch.sala_centro_0
            name: Luz Centro
        title: Sala
        key: sala
      - type: cardEntities
        entities:
          - entity: sensor.th01_q1_temperature
            name: Temperatura
          - entity: cover.estore_q1
            name: Estore
        title: Quarto 1
        key: q1
      - type: cardEntities
        entities:           
          - entity: service.switch.toggle
            status: binary_sensor.status_portao
            name: Portao
            data:
              entity_id: switch.portao_garagem
          - entity: navigate.caldeira
            status: climate.caldeiraemaquecimento
            name: Caldiera
            icon: 'ha:{{ state_attr("climate.caldeiraemaquecimento","current_temperature")}}'
        title: Garagem
        key: garagem
      - type: cardEntities
        entities:
          - entity: sensor.th01_q2_temperature
            name: Temperatura
          - entity: cover.estore_frente_q2
            name: Estore Frente
          - entity: cover.estore_lateral_q2
            name: Estore Lateral
          - entity: light.rgb_q2
            name: Presenca
            icon: mdi:floor-lamp-outline
        title: Quarto 2
        key: q2
      - type: cardEntities
        entities:
          - entity: switch.controlo_rega_relvado
            name: Regar Relvado
            icon: mdi:grass
          - entity: switch.controlo_rega_quintal
            name: Regar Quintal
        title: Jardim
        key: grass
      - type: cardEntities
        entities:
          - entity: sensor.th01_qp_temperature
            name: Temperatura
          - entity: cover.estore_qp
            name: Estore Lateral
          - entity: navigate.tv_qp
            status: media_player.aiplus2k
            name: TV
            icon: mdi:television-classic
        title: Quarto Pais
        key: qp


```

**Comment by joBr99** [comment]
sure, you just need to send the message the panel would send for navigating to a card to the recive topic of the backend to "simulate" the touch actions to navigate that page

**Comment by tv4you2016** [comment]
Where can I consult this message?

**Comment by tv4you2016** [comment]
GO  AppDaemon -> log -> copy MQTT callback

```
action: mqtt.publish
data:
  evaluate_payload: false
  qos: 0
  retain: false
  topic: tele/tasmota_C35E50/RESULT
  payload: "{\"CustomRecv\":\"event,buttonPress2,navigate.uuid.CqJV8ILUnw,button\"}"
```
