### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by VendisF** [joBr99/nspanel-lovelace-ui#1313]
### PROBLEM DESCRIPTION
Thermostat, type: cardThermo  title: HeatPump

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
    screensaver:
      theme:
        time: [0, 255,255]
        date: [255, 255, 255]
      type: screensaver
      doubleTapToUnlock: True 
      entities:   
        - entity: sensor.tasmota_analog_temperature1   # NASTAVIT teplotní sensor NSPanelu 
          color: '{{iif(states("switch.tasmota_nspanel_15")=="on", "[0,255,0]", "[255,165,0]")}}'
          type: 0
        - entity: weather.forecast_home
          name: Venku
          font: medium
          icon: mdi:home-thermometer-outline

      statusIcon2: 
        entity: switch.tasmota_nspanel_15 
        icon:
                "on": mdi:heat-wave
                "off": mdi:heat-wave

    cards:
      - type: cardThermo
        title: Teplota místnosti
        entity: climate.smart_thermostat_udirna  # NASTAVIT 
      - type: cardThermo



```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
![Image](https://github.com/user-attachments/assets/cb4ab505-c4a1-496f-a116-ab61818ff66f)

### ADDITIONAL CONTEXT
Why does the icon change color when I press the "FLAME" or "ON/OFF" icon on the "Thermostat" page a second time? Sometimes it happens that I want to turn off the thermostat, I press the "flame" and it changes color. I take that as off. Thank you for your response. VendisF

### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

![Image](https://github.com/user-attachments/assets/13a26348-6ae7-4595-bcab-fa85fa0e8087)
