### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kptkip** [joBr99/nspanel-lovelace-ui#1318]
### PROBLEM DESCRIPTION
I try to define dynamic colors in the screen saver via:

```
    screensaver:
      entities:
        - entity: sensor.deye_sunsynk_sol_ark_3_phase_grid_power
          icon: mdi:home-lightning-bolt-outline
          color: '{{iif(states("sensor.deye_sunsynk_sol_ark_3_phase_grid_power") >= "0", iif(states("sensor.deye_sunsynk_sol_ark_3_phase_grid_power") <= "0", "[240, 55, 7]", "[10,255,20]"), "[128,128,128]")}}'
```
The problem is, that the syntax seems not correct. the display shows no values in entities at all (beside of the time an date). When I ommit color-line it works perfectly.

As shown below it seems to be a typing problem. How can I convert the values to make math functions witht the state values?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
see above

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
TypeError: unsupported operand type(s) for >>: 'str' and 'int'

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
