### ISSUE TITLE
[HELP] Value text near Screensaver icons

### ISSUE THREAD

**Issue by kptkip** [joBr99/nspanel-lovelace-ui#1319]
### PROBLEM DESCRIPTION
I try to migrate my panel - formerly driven by iobroker - to HA. In the screensaver I was able to print values near the screensaver icon 1 & 2

<img width="997" alt="Image" src="https://github.com/user-attachments/assets/bbdf2bf7-c421-4c7f-a582-63a42c3e707b" />

In IoBroker it is defined by:
```
mrIcon2ScreensaverEntity: { ScreensaverEntity: 'deconz.0.Sensors.5.open', 
                                ScreensaverEntityIconOn: 'heat-wave',
                                ScreensaverEntityIconOff: null, 
                                ScreensaverEntityValue: 'deconz.0.Sensors.65.temperature',
                                ScreensaverEntityValueDecimalPlace : 1,
                                ScreensaverEntityValueUnit: '°', 
                                ScreensaverEntityOnColor: MSRed, 
                                ScreensaverEntityOffColor: Yellow },
```

so I assumed to use this kind of code in my apps.yaml:
```
    screensaver:
      statusIcon1:
          entity: sensor.deye_sunsynk_sol_ark_3_phase_pv_power
          icon: mdi:solar-power-variant
          color: [255, 189, 17]
          value: sensor.deye_sunsynk_sol_ark_3_phase_pv_power
          value_unit: 'W'
```
But it doesn't show the values at the icon in screensaver mode.

Is it generally not possible to do this with HA - or is there a mistake in my code?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
