### ISSUE TITLE
[BUG] Scripts not launching

### ISSUE THREAD

**Issue by Roxxor91** [joBr99/nspanel-lovelace-ui#1345]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Since the AppDaemon update launching scripts doesnt work anymore.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
  apps.yaml here:
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/NSPanelErdgeschoss/RESULT"
    panelSendTopic: "cmnd/NSPanelErdgeschoss/CustomSend"
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "6:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "de_DE"
    screensaver:
      doubleTapToUnlock: False
      entities:
      - entity: weather.XXXX
      - entity: sensor.weather_forecast_daily
        type: 0
      - entity: sensor.weather_forecast_daily
        type: 1
      - entity: sensor.weather_forecast_daily
        type: 2
      - entity: sensor.weather_forecast_daily
        type: 3
      - entity: sensor.5_in_1_wetterstation_temperature_wetterstation
        icon: mdi:thermometer
    cards:
      - type: cardGrid
        entities:
          - entity: script.tschuss
            name: "Tschüss!"
            icon: mdi:hand-wave-outline
          - entity: navigate.cover_eg
            name: "Rollos"
            icon: mdi:window-shutter
          - entity: navigate.waermeschutz
            name: "Wärmeschutz"
            icon: mdi:sun-thermometer
          - entity: navigate.wifi_qr
            name: "WiFi QR"
            icon: mdi:qrcode-scan
          - entity: navigate.haushalt
            name: "Haushalt"
            icon: mdi:vacuum
          - entity: navigate.sonos
            name: "Ambiente"
            icon: mdi:saxophone
        title: "Hauptmenü"
    hiddenCards:
      - type: cardGrid
        title: Raffstores & Rollos
        key: cover_eg
        entities:
          - entity: script.alle_rollos_offnen
            name: "Alle Rollos"
            icon: mdi:arrow-up-bold
          - entity: script.eg_rollos_offnen
            name: "EG Rollos"
            icon: mdi:arrow-up-bold
          - entity: script.og_rollos_offnen
            name: "OG Rollos"
            icon: mdi:arrow-up-bold
          - entity: script.alle_rollos_schliesen
            name: "Alle Rollos"
            icon: mdi:arrow-down-bold
          - entity: script.eg_rollos_schliesen
            name: "EG Rollos"
            icon: mdi:arrow-down-bold
          - entity: script.og_rollos_schliesen
            name: "OG Rollos"
            icon: mdi:arrow-down-bold
      - type: cardGrid
        title: "Wärmeschutz"
        key: waermeschutz
        entities:
          - entity: script.sonnenschutz_sud_auslosen
            name: "Süden dimmen"
            icon: mdi:umbrella-beach-outline
          - entity: script.sonnenschutz_west_auslosen
            name: "Westen dimmen"
            icon: mdi:umbrella-beach-outline

```
- [x] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
2025-06-04 16:47:50.074488 ERROR nspanel-1: =====  LuiMqttListener.mqtt_event_callback for nspanel-1  =================
2025-06-04 16:47:50.075037 ERROR nspanel-1: EventCallbackFail: Scheduled callback failed for app 'nspanel-1'
2025-06-04 16:47:50.075417 ERROR nspanel-1:   args: ('MQTT_MESSAGE', {'topic': 'tele/NSPanelErdgeschoss/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,script.sonnenschutz_west_auslosen,button"}'}, {'topic': 'tele/NSPanelErdgeschoss/RESULT', '__thread_id': 'thread-1'})
2025-06-04 16:47:50.076683 ERROR nspanel-1:   ServiceException: domain 'script' exists in namespace 'default', but does not contain service 'turn_on'. Services that exist in script: r2d2_zum_mulleimer
2025-06-04 16:47:50.082806 ERROR nspanel-1:   apps/nspanel-lovelace-ui/luibackend/controller.py line 318 in button_press
2025-06-04 16:47:50.083304 ERROR nspanel-1:   apps/nspanel-lovelace-ui/luibackend/mqtt.py line 75 in customrecv_event_callback
2025-06-04 16:47:50.083741 ERROR nspanel-1:   apps/nspanel-lovelace-ui/luibackend/mqtt.py line 34 in mqtt_event_callback
2025-06-04 16:47:50.084117 ERROR nspanel-1: ===========================================================================


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Try to launch a script.

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
Script is executed.

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU
