### ISSUE TITLE
[BUG] Service call requested response data but did not match any entities

### ISSUE THREAD

**Issue by GiZMoSK1221** [joBr99/nspanel-lovelace-ui#1350]
### PROBLEM DESCRIPTION
There are many warnings in Appdaemon log 
2025-06-15 15:02:55.328675 WARNING HASS: Error with websocket result: home_assistant_error: Service call requested response data but did not match any entities

I suppose it has to do with latest release and allowing to use weather entity again.
According to https://github.com/home-assistant/core/issues/120459 you seem to call weather.get_forecasts on sensor entity. When I remove 
        - entity: sensor.weather_forecast_hourly
          type: 2
the error disappears.

However, NSPanel shows correct values, only the message in log is annoying. 

I cannot use my weather entity, because it provides hourly data, not dayly.
The error is then home_assistant_error: Weather entity 'weather.domov_aladin' does not support 'daily' forecast
the command for retrieving  data is "hourly". Maybe you could add it as parameter
      - service: weather.get_forecasts
        data:
          type: hourly

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
        entities:
        - entity: sensor.zw_temp_outdoor_air_temperature
          icon: mdi:home-thermometer-outline
        - entity: sensor.wattsonic_battery_soc
        - entity: sensor.wattsonic_pv_input_total_power
          icon: mdi:solar-panel
        - entity: sensor.wattsonic_inverter_running_status_text
        - entity: sensor.weather_forecast_hourly
        - entity: sensor.weather_forecast_hourly
          type: 2
        - entity: sensor.weather_forecast_hourly
          type: 4
        - entity: sensor.weather_forecast_hourly
          type: 6
        - entity: sensor.weather_forecast_hourly
          type: 8
        - entity: sensor.weather_forecast_hourly
          type: 10
        - entity: binary_sensor.zw_door_open
  

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
2025-06-15 15:02:55.328675 WARNING HASS: Error with websocket result: home_assistant_error: Service call requested response data but did not match any entities



```

### TO REPRODUCE
_Steps to reproduce the behavior:_
add sensor entity instead of weather entity

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

If i'm right with the cause problem, solution is to call get_forecast only for weather entity

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
