### ISSUE TITLE
[Help] How to set up the 5 StatusIcon in screensaver2 (Homeassistant)

### ISSUE THREAD

**Issue by kls1003** [joBr99/nspanel-lovelace-ui#1359]
### PROBLEM DESCRIPTION

I don't even see one of the 5 icons (under time and date) in screensaver2. In the documentation for the setup under Homeassistant (apps.yaml) I can't find any information about the configuration.

[X] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:

<img width="708" alt="Image" src="https://github.com/user-attachments/assets/d0b7fc1e-e9e2-4fb5-81af-ad58d0d6a1e4" />

- [ ] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:


```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:
---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "MeineTasmotas/nspanel_1/tele/RESULT"
    panelSendTopic: "MeineTasmotas/nspanel_1/cmnd/CustomSend"
    model: eu
    locale: "de_DE"
    sleepTimeout: 60
# ==============================================================================
    screensaver:
      enabled: true
      type: screensaver2
      # testing ICONS ....
      id1: # <--- what to configure here ?
        entity: switch.myButton
        icon: mdi:window-closed 
        icon_on: mdi:window-open 
        icon_off: mdi:window-closed 
        text_on: "On"
        text_off: "Off"
        color_on: red 
        color_off: green 
      # end of test    
  


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:


```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_

**Comment by joBr99** [comment]
It's just a long list - you can skip entities on the screen by using the delete entity.
```
        entities:
          - entity: iText.1
            icon: txt:1
          - entity: delete
          - entity: iText.2
            icon: txt:2
          - entity: delete
          - entity: iText.3
            icon: txt:3
          - entity: delete
          - entity: iText.4
            icon: txt:4
```
