### ISSUE TITLE
Documentation outdated? Some Problems

### ISSUE THREAD

**Issue by KlausHans** [joBr99/nspanel-lovelace-ui#136]
Hello,

really nice project, thank you so much for sharing.

I have troubles to get the screensaver override to work. I've added:
```
    screensaver:
      entity: weather.home
      weatherOverrideForecast4:
        entity: sensor.momentanleistung
```
to my config, according to the config example. It does not work, the weather items are unchanged. But it seems, that the example config ist outdated in general on some places. For example there is `sleepTimeout` and `sleepBrightness`, but the correct items are `timeoutScreensaver` and `brightnessScreensaver`. Was this changed with an update?

What do i have to do to get the weather override to work? I want to show a sensor value here.

Thanks again.
