### ISSUE TITLE
[Feature Request] Display (room) temperature in screensaver

### ISSUE THREAD

**Issue by dartheide** [joBr99/nspanel-lovelace-ui#155]
I want to display te room temperature in the screensaver.  In that way you can see it without touching the panel.

In HA The NSpanel shows sensor.nspanel_analog_temperature1.

**Comment by joBr99** [comment]
You can override the last item on your screensaver:

```
    screensaver:
      entity: weather.openweathermap
      weatherOverrideForecast4:
        entity: sensor.nspanel_analog_temperature1
```
and also override the name if you want to have a different one than in HA
```
    screensaver:
      entity: weather.openweathermap
      weatherOverrideForecast4:
        entity: sensor.nspanel_analog_temperature1
        name: test
        
```
