### ISSUE TITLE
[Feature Request] Allow presence/occupancy sensors as sleepTracking entities

### ISSUE THREAD

**Issue by luisleonardo** [joBr99/nspanel-lovelace-ui#158]
Please allow the use of presence/occupancy sensors to control the lcd brightness with sleepTracking.

These sensors normally have an "on/off" state instead of "home/not_home".

Until solved, I am using a template sensor (example below, as it may help others):

```
sensor:
  - platform: template
    sensors:
      nspanel_presence:
        value_template: "{{ 'home' if is_state('binary_sensor.living_room_presence_occupancy','on') else 'not_home' }}"
```
