### ISSUE TITLE
[Feature Request] Extend maximum allowed hvac_modes

### ISSUE THREAD

**Issue by kroon040** [joBr99/nspanel-lovelace-ui#180]
Hi,

I got an daikin airco and I missing the icon for on/off and auto (heat_cool), I only have 4 on the display.

When looking in de devtools I seen that off is in single quote, maybe that is the issue?
![climate1](https://user-images.githubusercontent.com/40452265/167270832-e8e3d0e1-ac7e-4573-b32a-eef8805d28d9.png)

```
hvac_modes:
  - fan_only
  - dry
  - cool
  - heat
  - heat_cool
  - 'off'
min_temp: 7
max_temp: 35
target_temp_step: 1
fan_modes:
  - Auto
  - Silence
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
preset_modes:
  - none
  - away
  - eco
  - boost
swing_modes:
  - 'Off'
  - Vertical
  - Horizontal
  - 3D
current_temperature: 21
temperature: 19
fan_mode: '3'
hvac_action: 'off'
preset_mode: none
swing_mode: 3D
friendly_name: airco slaapkamer
supported_features: 57
```

Screenshot from Home assistant with 6 buttons

![climate3](https://user-images.githubusercontent.com/40452265/167270970-0e06344e-5241-4fee-aacc-88faa5cd9771.png)

**Comment by joBr99** [comment]
no, the number of buttons is currently limited to 4/5 icons, I will address this during redesign of the thermostat page

how do I get this kind of climate card in the homeassistant dashboard?

**Comment by kroon040** [comment]
That is the lovelace simple-thermostat

https://github.com/nervetattoo/simple-thermostat

Config I use 
```

type: custom:simple-thermostat
entity: climate.airco_slaapkamer
step_size: '1'
hide: null
temperature: true
sensors:
  - entity: sensor.airco_slaapkamer_inside_temperature
  - entity: sensor.airco_slaapkamer_outside_temperature
control:
  hvac:
    'off':
      name: false
    heat:
      name: false
    cool:
      name: false
    dry:
      name: false
    fan_only:
      name: false
    heat_cool:
      name: false`
```
`
