### ISSUE TITLE
[Feature Request] configure climate for Fahrenheit 

### ISSUE THREAD

**Issue by e2m32** [joBr99/nspanel-lovelace-ui#189]
Temperature value correctly pulled from HA in Fahrenheit, but the unit displays as "C." I did not see a way to configure it to Fahrenheit. 
![climateC](https://user-images.githubusercontent.com/10486510/168449546-6d9aac5c-f456-48fa-b85d-5ba316a8e63a.jpg)
"

**Comment by joBr99** [comment]
yes, you are right this is not possible with the current release, I will add this as a feature request for the next release

**Comment by joBr99** [comment]
with the current development version this should be working:

```yaml
      - type: cardThermo
        entity: climate.example_item
        temperatureUnit: fahrenheit
 ```
 
 https://github.com/joBr99/nspanel-lovelace-ui#how-to-upgrade-from-a-release-to-the-current-development-version
