### ISSUE TITLE
[Feature Request] Change default card to alarm panel when alarm is armed

### ISSUE THREAD

**Issue by Jonhug82** [joBr99/nspanel-lovelace-ui#193]
Is it possible to change the default card to show the Alarm control panel when the alarm is armed. This will make it easier to disable the alarm on entry.

**Comment by joBr99** [comment]
yes, good idea

**Comment by joBr99** [comment]
Hey, check out the current development version.

The config option `defaultCard` on the screensaver is now evaluated as Home Assistant template, allowing you to do things like this:

```
      defaultCard: '{{ "navigate.armed_card" if is_state("alarm_control_panel.alarmo", "armed") else "navigate.disarmed_card" }}'
```

https://github.com/joBr99/nspanel-lovelace-ui#waiting-for-content---this-is-taking-longer-than-usual-on-the-screen

**Comment by joBr99** [comment]
honestly I've never tested if this acually works, but it should try this:

```
screensaver:
  entity: weather.home
  theme:
    AutoWeather: auto
    time: [255, 255, 0]
  defaultCard: '{{ "navigate.cardAlarm_alarm" if is_state("alarm_control_panel.alarmo", "armed_away") else "navigate.cardGrid_default" }}'
cards:
  - type: cardAlarm
    entity: alarm_control_panel.alarmo
	key: alarm
  - type: cardGrid
    key: default
```

**Comment by woody166** [comment]
Unfortunately that didn't work, eneded up freezing the display on the screensaver page.  commenting out the line was able to free it back up.  AppDaemon log below:

AttributeError: 'NoneType' object has no attribute 'replace'
2022-05-24 16:16:28.727147 WARNING nspanel-1: ------------------------------------------------------------
2022-05-24 16:16:28.752183 INFO nspanel-1: MQTT callback for: {'topic': 'tele/hallwaynsp/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,screensaver,bExit,17"}'}
2022-05-24 16:16:28.759723 INFO nspanel-1: Received Message from Screen: event,buttonPress2,screensaver,bExit,17
2022-05-24 16:16:28.771113 INFO nspanel-1: Button Press Event; entity_id: screensaver; button_type: bExit; value: 17 
2022-05-24 16:16:28.811152 WARNING HASS: Error calling Home Assistant service default/template/render
2022-05-24 16:16:28.812225 WARNING HASS: Code: 400, error: {"message": "Error rendering template: TemplateSyntaxError: expected token 'end of print statement', got 'string'"}
2022-05-24 16:16:28.818542 INFO nspanel-1: Searching for the following page as defaultPage: None
2022-05-24 16:16:28.819857 WARNING nspanel-1: ------------------------------------------------------------
2022-05-24 16:16:28.820898 WARNING nspanel-1: Unexpected error in worker for App nspanel-1:
2022-05-24 16:16:28.822213 WARNING nspanel-1: Worker Ags: {'id': 'fe338a4bf37c4ea48697f3c9cc42f6bc', 'name': 'nspanel-1', 'objectid': '3c9290f396784d02a57846fa180c8123', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method LuiMqttListener.mqtt_event_callback of <luibackend.mqttListener.LuiMqttListener object at 0x7f9cbca280>>, 'data': {'topic': 'tele/hallwaynsp/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,screensaver,bExit,17"}'}, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'topic': 'tele/hallwaynsp/RESULT', '__thread_id': 'thread-0'}}
2022-05-24 16:16:28.823209 WARNING nspanel-1: ------------------------------------------------------------
2022-05-24 16:16:28.824966 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 950, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqttListener.py", line 58, in mqtt_event_callback
    self._controller.button_press(entity_id, btype, value)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 143, in button_press
    dstCard = self._config.searchCard(defaultCard)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/config.py", line 166, in searchCard
    id = id.replace("navigate.", "")
AttributeError: 'NoneType' object has no attribute 'replace'
2022-05-24 16:16:28.825927 WARNING nspanel-1: ------------------------------------------------------------
2022-05-24 16:17:01.026934 INFO nspanel-1: Sending MQTT Message: time~16:17

**Comment by joBr99** [comment]
I just tried this on my panel and it works fine:

```yaml
    screensaver:
      entity: weather.k3ll3r
      doubleTapToUnlock: True
      alternativeLayout: True
      defaultCard: '{{ "navigate.cardAlarm_alarm" if is_state("alarm_control_panel.alarmo", "armed_home") else "navigate.cardEntities_rolladen" }}'
    cards:
      - type: cardEntities
        title: Rolladen
        entities:
          - entity: cover.rolladenfenster_cover_1
          - entity: cover.nspterrasse_cover_1
          - entity: cover.rolladenterasse_cover_1
        key: rolladen
      - type: cardAlarm
        entity: alarm_control_panel.alarmo
        key: alarm

```

can you try your template in the HA dev tools template tab?

![image](https://user-images.githubusercontent.com/29555657/170081032-86f9bb66-4edd-4c9e-af70-a5d1a6bd7b3b.png)
