### ISSUE TITLE
[Feature Request] Asian / CJK Version of the Firmware

### ISSUE THREAD

**Issue by tianzhuang55** [joBr99/nspanel-lovelace-ui#197]
Great job, and I followed all your instructions for the flash and setup. Currently the functions work fine. However when I set up the entity title to Chinese, it just shows blank on the nspanel. 

Is it possible to add Asian characters support, or have I missed something?

BTW, the Babel package is well installed, and works well when I change locale to French or Italian.

Thanks!

**Comment by joBr99** [comment]
Hey, 
the firmware includes nearly all characters except for Chinese, Japanese, and Korean, due to space limitations, so a seperate CJK would be required.

The maximum firmware size of the firmware is 16MB, the current firmware has 9,77 MB. 
Adding all characters from the used Font NotoSans would increase the firmware size to 19 MB.

I'm using the following Font: "NotoSans-Regular.ttf", which you can download from here:
https://fonts.google.com/download?family=Noto%20Sans

Fonts for nextion projects can be created with the Font Generator of the Editor:

![image](https://user-images.githubusercontent.com/29555657/169637279-4ecf7f11-46bb-42c3-80f8-abe0e8bcac41.png)

To add support for CJK you will need to heavily cut down the supported languages in the font generator, to get the size of the font down. Try to remove any charset you don't need like arabic or cyrillic chars, would try to keep Chinese, Japanese, and Korean and Latin Characters for English. 

The two fonts that need to be replaced in the project have the IDs 0 and 2, the other fonts are containing the MDI Icons (and the last one is the time on the screensaver)

![image](https://user-images.githubusercontent.com/29555657/169637764-0d0fa9f0-c2c6-46a5-afc8-5fe748fe55e4.png)

I don't know if you are getting the font size down enough for the firmware beeing smaller than 16 MB with this approach, maybe you have to exclude even more.

You might have a better insight into which char tables are needed, I've personally no clue what to do with non-latin chars.

I can easily add the translations for CJK languages to the localization.py file, don't worry about that.

**Comment by tianzhuang55** [comment]
Exactly too many CJK Characters, however is it possible to keep only regular used characters? Especially for smart home control, the words and characters are actually quite limited.  Take Chinese for example, maybe 100 characters would be enough to apply on the nspanel?

**Comment by joBr99** [comment]
Would require to remove them somehow from the NotoSans ttf font in the first place with nextion editor you can only select whole character sets. There are probably tools out there to modify ttf fonts.

**Comment by joBr99** [comment]
Tried to convert a stripped down font generated with pyftsubset, but sadly it looks like Nextion Editor pulls the missing chars from some other font ...

**Comment by tianzhuang55** [comment]
> Tried to convert a stripped down font generated with pyftsubset, but sadly it looks like Nextion Editor pulls the missing chars from some other font ...

Thanks all the same! Since I'm not a coder, so it's not easy for me to edit the HMI file. However your well written readme file helps a lot to finish all the steps from firmware flash to config.

Currently I use English in display and everything goes well. Hopefully someday could have a CJK version of HMI release.

Great project!

**Comment by joBr99** [comment]
> Take Chinese for example, maybe 100 characters would be enough to apply on the nspanel?

Can you add list of characters that you would need on the panel?

**Comment by tianzhuang55** [comment]
I sum up 95 Chinese characters which might be often used in smart home:
`卧房室客洗手间阳台厨灯壁镜前后左右东南西北中空调风扇橱柜控温湿度网关串夜落地阅读水泵一二三四五六七八九十百年月日周星期播放窗帘门开高低家在电暖气器摄像头扫人机组群冷热模式时分秒大小上下多少主`

and 30 of these 95 characters are different in traditional Chinese (used in Taiwan, Hongkong etc.). Will be great if all these 125 characters could be added:
`臥間陽廚燈鏡後東調風櫥櫃溫濕網關閱讀簾門開電氣攝頭掃機組熱時`

**Comment by tianzhuang55** [comment]
> > Take Chinese for example, maybe 100 characters would be enough to apply on the nspanel?
> 
> Can you add list of characters that you would need on the panel? Looks like I can build fonts in Nextion Editor from a list of characters, should be possible to generate a list for all of the supported languages and generate a nextion font from it. Doesn't have to be fancy, just a string with the chars like this:
> 
> `ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜßabcdefghijklmnopqrstuvwxyzäöü`

I sum up 95 Chinese characters which might be often used in smart home:
`卧房室客洗手间阳台厨灯壁镜前后左右东南西北中空调风扇橱柜控温湿度网关串夜落地阅读水泵一二三四五六七八九十百年月日周星期播放窗帘门开高低家在电暖气器摄像头扫人机组群冷热模式时分秒大小上下多少主`

and 30 of these 95 characters are different in traditional Chinese (used in Taiwan, Hongkong etc.). Will be great if all these 125 characters could be added:
`臥間陽廚燈鏡後東調風櫥櫃溫濕網關閱讀簾門開電氣攝頭掃機組熱時`

**Comment by tianzhuang55** [comment]
> > Take Chinese for example, maybe 100 characters would be enough to apply on the nspanel?
> 
> Can you add list of characters that you would need on the panel? Looks like I can build fonts in Nextion Editor from a list of characters, should be possible to generate a list for all of the supported languages and generate a nextion font from it. Doesn't have to be fancy, just a string with the chars like this:
> 
> `ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜßabcdefghijklmnopqrstuvwxyzäöü`

I sum up 100 Chinese characters which might be often used in smart home: 
`卧房室客厅洗手间阳台厨灯壁镜前后左右东南西北`中空调风扇橱柜控温湿度网关串夜落地阅读水泵一二三四五六七八九十百年月日周星期播放窗帘门开高低家在电暖气器摄像头扫人机组群冷热模式时分秒大小上下多少主书层制浴`

and 33 of these 95 characters are different in traditional Chinese (used in Taiwan, Hongkong etc.). Will be great if all these 125 characters could be added: 
`臥廳間陽廚燈鏡後東調風櫥櫃溫濕網關閱讀簾門開電氣攝頭掃機組熱時書層`

Tell me if you need to cut down or enlarge. Thanks so much!

**Comment by tianzhuang55** [comment]
> > Take Chinese for example, maybe 100 characters would be enough to apply on the nspanel?
> 
> Can you add list of characters that you would need on the panel? Looks like I can build fonts in Nextion Editor from a list of characters, should be possible to generate a list for all of the supported languages and generate a nextion font from it. Doesn't have to be fancy, just a string with the chars like this:
> 
> `ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜßabcdefghijklmnopqrstuvwxyzäöü`

I sum up 100 Chinese characters which might be often used in smart home: 
`卧房室客厅洗手间阳台厨灯壁镜前后左右东南西北中空调风扇橱柜控温湿度网关串夜落地阅读水泵一二三四五六七八九十百年月日周星期播放窗帘门开高低家在电暖气器摄像头扫人机组群冷热模式时分秒大小上下多少主书层制浴`

and 33 of these 100 characters are different in traditional Chinese (used in Taiwan, Hongkong etc.). Will be great if all these 133 characters could be added: 
`臥廳間陽廚燈鏡後東調風櫥櫃溫濕網關閱讀簾門開電氣攝頭掃機組熱時書層`

Tell me if you need to cut down or enlarge. Thanks so much!

**Comment by joBr99** [comment]
Hey, @tianzhuang55
I've generated the translations for "zh-Hans" and came up with the following addional chars missing in your list. Please let me know if this makes sense.

**Comment by tianzhuang55** [comment]
> zh-Hans

Hi joBr99, that's GREAT! They're all very essential chars.

And my hardware is EU version. 

Thanks!

**Comment by joBr99** [comment]
Try this firmware: `FlashNextion nspanel.pky.eu/chinese-test/nspanel.tft`

Also replace the content of you localization.py with this version (restart AppDeamon afterwards): https://raw.githubusercontent.com/joBr99/nspanel-lovelace-ui/chinese-test/apps/nspanel-lovelace-ui/luibackend/localization.py

This should allow you to configure `zh-hans_x` or `zh-hant_x` (babel currently needs to be removed if configured)

**Comment by tianzhuang55** [comment]
Hi JoBr99,

test done, and I put my config and display photos as following to check the results together:
（generally speaking, it's a good start. Some fonts are weird since serif, non-serif, bold fonts are mixed; thermocard and weekday translations don't work）

_firmware done
babel removed
appdaemon restarted_

```
---
nspanel:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_nspanel/RESULT"
    panelSendTopic: "cmnd/tasmota_nspanel/CustomSend"
    updateMode: "auto-notify"
    sleepTimeout: 20
    sleepBrightness:
      - time: "6:00:00"
        value: 12
      - time: "7:00:00"
        value: 18
      - time: "20:00:00"
        value: 10
      - time: "23:30:00"
        value: 1
    locale: "zh-hans_CN"
    dateFormatBabel: "EEE, yyyy/MM/dd"

    screensaver:
      entity: weather.maple_2
      theme:
        autoWeather: true
    cards:
      - type: cardGrid
        entities:
          - entity: navigate.cardThermo_livingroom
            name: 01/客厅控温
            icon: sofa-single-outline
          - entity: navigate.cardThermo_bedroom
            name: 02/卧室控温
            icon: bed-king-outline
          - entity: navigate.cardEntities_lights
            name: 灯光
            icon: ceiling-light-multiple-outline
          - entity: navigate.cardThermo_guestroom
            name: 03/客房控温
            icon: bed-single-outline
          - entity: navigate.cardThermo_washroom
            name: 04/洗手间控温
            icon: shower
        title: 家庭
      - type: cardMedia
        entity: media_player.ke_ting
        title: HOMEPOD
    hiddenCards:
      - type: cardThermo
        entity: climate.01_livingroom
        key: livingroom
        title: 01_客厅LIVINGROOM
      - type: cardThermo
        entity: climate.02_bedroom
        title: 02_卧室BEDROOM        
        key: bedroom
      - type: cardThermo
        entity: climate.03_guestroom
        key: guestroom
        title: 03_客房GUESTROOM  
      - type: cardThermo
        entity: climate.04_washroom
        key: washroom
        title: 04_洗手间WASHROOM
      - type: cardEntities
        entities:
          - entity: light.switch_dimmer_living
            name: 吊灯
            icon: ceiling-light
          - entity: switch.sonoff_1000e55670
            name: 阅读灯
            icon: track-light          
          - entity: switch.sonoff_kitchen
            name: 厨房壁灯
            icon: coach-lamp
          - entity: switch.cp1_18fe3472da4c
            name: 橱柜灯
            icon: wall-sconce-flat
        key: lights
        title: 灯光
```
![IMG_2306](https://user-images.githubusercontent.com/60805058/170988214-c5ffda24-f28a-4e24-a2a3-d7d519a82cd0.jpeg)
![IMG_2307](https://user-images.githubusercontent.com/60805058/170988228-f085389a-b005-434a-bd06-45ea05a06457.jpeg)
![IMG_2308](https://user-images.githubusercontent.com/60805058/170988232-fb1a16bf-9cf2-4380-8f43-a23daa4d4be8.jpeg)
![IMG_2309](https://user-images.githubusercontent.com/60805058/170988236-1f197f3c-30c0-4def-b891-d8557f2d2fc6.jpeg)
![IMG_2310](https://user-images.githubusercontent.com/60805058/170988239-ea9e1047-92b4-4802-b3c9-1bd47cf0b994.jpeg)
