### ISSUE TITLE
[Feature Request] allow navigate entity to have a status

### ISSUE THREAD

**Issue by Llntrvr** [joBr99/nspanel-lovelace-ui#228]
would be cool if you could define a status for a navigate entity so that the overall navigate entity is "active"

something like so
```
        entities:
          - entity: navigate.cardGrid_sparebedroom
             status: switch.sparebedroom
```

**Comment by joBr99** [comment]
this should be working now:

```
          - entity: navigate.cardThermo_test2
            status: light.schreibtischlampe
```

also for alarm page: @LucaBors

```
      - type: cardAlarm
        entity: alarm_control_panel.alarmo
        alarmControl:
          entity: light.schreibtischlampe
          status: light.schreibtischlampe
```
