### ISSUE TITLE
[Feature Request] Display colored icons when active on screensaver pssible?

### ISSUE THREAD

**Issue by kroon040** [joBr99/nspanel-lovelace-ui#233]
Hi,

I would like to have 2 icons on the right upper corner and when they are active they are colored.

I have an Heating when it's active it color red.
I have an Hot Water icon when it's active it should color red.

Default it colors grey on the screensaver. Is something like this possible in the upper right of the screensaver, near the time

I would love to use these binary state icons

![binary](https://user-images.githubusercontent.com/40452265/170762352-ec847177-8992-45b1-9a3a-3f7437c489ae.png)

**Comment by joBr99** [comment]
sound's also like an good solution for #187 and #221

**Comment by kroon040** [comment]
For these it is also a good option, to have 2 icons for that in the upper right corner. I hope it will fit near the time.

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/170777870-623ae27b-6b18-4444-81f5-04b42a2c84a3.png)

okay top right corner doesn't work :(

it collides with the text of time depending on the configuration and the icons will dissappear after a minute because on redrawing of the time

I guess the only position where this page could fit addional icons would be this:

![image](https://user-images.githubusercontent.com/29555657/170779254-55f4141f-bb52-43b0-a1bf-007436281c27.png)

**Comment by kroon040** [comment]
That's also a good place. For the physical button states it is also nice that there is one left and one right.

**Comment by joBr99** [comment]
![1653680843007754809806494229639](https://user-images.githubusercontent.com/29555657/170780137-0828860d-6ac5-4b6e-88cb-9d6339f7c778.jpg)

👍 update to the current dev version and try yourself (which firmware are you using? currently it's only in the EU version)

**Comment by kroon040** [comment]
I have the EU. I  need als to update the firmware of the panel?

**Comment by joBr99** [comment]
yes, `FlashNextion http://nspanel.pky.eu/lui.tft` in tasmota console and you also need to update the appdaemon app

https://github.com/joBr99/nspanel-lovelace-ui#how-to-upgrade-from-a-release-to-the-current-development-version

**Comment by kroon040** [comment]
Hi,

Some issues: 

Binary sensor doesn't work. Also is it with binary sensor than possible to overwrite the icon?

I have also alternativelayout , weatheroverride, and than it doesn't work
```

    screensaver:
        entity: weather.weerstation
        statusIcon1:
          entity: switch.buitenlamp
        statusIcon2:
           entity: binary_sensor.boiler_heating_active
        alternativeLayout: true
        weatherOverrideForecast3:
         entity: sensor.thermostat_hc1_current_room_temperature
         name: " "
         icon: home-thermometer-outline
```

**Comment by joBr99** [comment]
yes, it should be possible to override the icon

```
        statusIcon2:
           entity: binary_sensor.boiler_heating_active
           icon: lightbulb
```

I've just tried a binary_sensor and it showed up, what exactly isn't working?

**Comment by kroon040** [comment]
It works now see photo. Is it possible to only show the icon when it's on (active)?
![nspanel](https://user-images.githubusercontent.com/40452265/170790143-4f5b1356-be75-48cd-a5e9-b952fe45e445.jpeg)

**Comment by illuzn** [comment]
A couple of issues for me (us portrait).

1. I've lost the first forecast icon again. I assume this is because you copied and pasted from EU where enabling alternativeLayout also disables the first forecast icon.

2. The status icons do not abide the background color set and instead default to HA Grey (this occurs whether statusIcons are configured or not).

**Comment by joBr99** [comment]
@illuzn should be fixed

**Comment by joBr99** [comment]
@kroon040

I've extended the icon overwrite feature, you can now configure an overrwrite per state
````yaml
        icon:
          "on": "text:"
          "off": mdi:lightbulb
```
