### ISSUE TITLE
[Feature Request] alarm card: verbose failed to arm 

### ISSUE THREAD

**Issue by LucaBors** [joBr99/nspanel-lovelace-ui#242]
A really cool thing with alarmo is that if a door o windows is open the alarm fail to arm and show in the ha card what's wrong (attached an example). 
![image](https://user-images.githubusercontent.com/73178440/170935231-e7316d03-d877-4232-993f-d096c3c347a0.png)

Can this feature can be supported also in alarm card on nspanel?

I'm in US landscape.

Thank you :)

**Comment by joBr99** [comment]
however, this is currently only avalible in the EU version

**Comment by joBr99** [comment]
added changes to dev versions of us-l and us-p

**Comment by LucaBors** [comment]
Wow that's really cool! :) Is the procedure same as the eu version? so after upgrade hacs than FlashNextion http://nspanel.pky.eu/lui-us-l.tft ?
thank you!

**Comment by joBr99** [comment]
Yes, update to main in hacs, restart appdameon and update to the dev firmware, your url is correct

**Comment by LucaBors** [comment]
Updated, seems like something is not going or at least not as i expected :)
The yellow (!) only appear if i try to alarm panel and does not execute because of an object open (an this is ok). The problem is that it's static and does not disappear if i close door or windows, only if i try to re-arm. Is it how it should be expeted to work?
Thank you again! :)

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/171211402-cdecbe22-2506-4c87-9020-db5e3a54bb1d.png)

looks like the open_sensors value does only update if you are trying to rearm, i guess this is a question for alarmo

**Comment by LucaBors** [comment]
Yes, i think so. I'll open a case on alarmo repo. I'll let you know!

**Comment by LucaBors** [comment]
This is the replay of alarmo developer:
_"The open_sensors property provides the reason why arming failed (or alarm was triggered).
The property will not update if the sensor status changes afterwards, since this has nothing to do with the reason of the failure.

For getting the current sensor state (rather than its state while triggering or arming) you can check the HA entity directly, there is no need to use an Alarmo property for this."_

At this point is it possible to link the button with yellow (!) to a page than show only open sensors? Also the yellow button only appear if at least one sensor is open.

Thank you :)

**Comment by joBr99** [comment]
the open sensors property only contains the open sensors at the time where arming fails, 
so checking the sensor status after the arming fails doesn't make sense, because the information is already correct
subscribing to changes of sensor in the open_sensors is also not optimal, because it won't cover windows opened after trying to arm and not part of the open_sensors property

How does your card in HA handle this?


>Also the yellow button only appear if at least one sensor is open.

The yellow button won't show if open_sensors is none

**Comment by LucaBors** [comment]
You are right but would be great to separate the check of open sensor from alarmo and use them from HA (that change status every time  status change). At this point a conditional card linked to the yellow ! can be the right choise; not only when system fail to arm but from the beginning.
something like that:
- go in alarmcard
- if windows/doors (that we can define from a conditional card) are open the yellow ! is already there asking for attention.
- at this point clicking on it'll open the conditional card with information (in real time) of what's open.
- once all windows/doors are closed (and conditional card is empty/status of object is "closed" for all), yellow ! disappear from alarmcard.

**Comment by joBr99** [comment]
first part of this implemented in #258

**Comment by LucaBors** [comment]
Perfect!
I've created an "open sensors" card with all my object and work perfect and in real time! :)
Now we only miss a link from (!) to this card (that i'll make hidden) and available only if some sensor in open.

thank you :)

**Comment by joBr99** [comment]
```
      - type: cardAlarm
        entity: alarm_control_panel.alarmo
        alarmControl:
          entity: navigate.cardGrid_test
```

to show the button only if a sensor is open, #228 needs to be implemented

**Comment by LucaBors** [comment]
Maybe i'm missing something but it does nothing. When i press on (!) nothing appears. 

this is a part of my config
```
      - type: cardGrid
          entities:
           - entity: binary_sensor.portafinestra_cucina_contact
             name: Cucina
             state: "off"
        title: Chiudere
        key: opensensors
    hiddenCards:
      - type: cardAlarm
        entity: alarm_control_panel.casa
        key: alarm
        alarmControl:
          entity: navigate.cardGrid_opensensors
```
