### ISSUE TITLE
[Feature Request] Dynamic Brightness Adjustment

### ISSUE THREAD

**Issue by tianzhuang55** [joBr99/nspanel-lovelace-ui#243]
**Describe the solution you'd like**
Dynamic brightness according to environment luminance.

**Additional context**
I have a luminance to get the lux on the livingroom. And I wonder if the NSPANEL could adjust the brightness according to that?
I have make a template in Homeassistant, and could return an int value accordingly.

`{{ ((states('sensor.xiaomi_gateway_illuminance') | int / 100 - 4) * 2 + 2) | int}}`

However when I put it in the nspanel app config, it get stuck.

**Panel / Firmware Version**
EU / v2.9.3

**Comment by joBr99** [comment]
Hey, this config isn't an HA template, because it requires callbacks on changes of the value, afaik AppDaemon only has a function to render templates and not a function to register callbacks on a changed template.

You can configure an input_number and change the input number externally with the automation tool of your choise.

```
input_number:
  brightness_nspanel:
    initial: 20
    min: 0
    max: 100
```

**Comment by tianzhuang55** [comment]
Hey, 

I created a template sensor in HA configuration.yaml, and use it as the brightness value in nspanel config. It works fine just with seconds of delay.

```
  - platform: template
    sensors:
      nspanel_brightness:
        friendly_name: "NS-BRIGHT"
        value_template: "{{ ((states('sensor.xiaomi_gateway_illuminance') | int / 100 - 4) * 2 + 2) | int}}"
        unit_of_measurement: u
```

`    sleepBrightness: sensor.nspanel_brightness
