### ISSUE TITLE
[inquiry] How do I add multiple NSPanels using this method?

### ISSUE THREAD

**Issue by Astogems** [joBr99/nspanel-lovelace-ui#246]
My goal is to have 2 different NSPanels that have different dashboards for 2 different rooms. What is the procedure to do this?

**Comment by joBr99** [comment]
Just dublicate your config in apps.yaml and change nspanel-1 to nspanel-2 or whatever you want

**Comment by diginfo** [comment]
I use the last 4 digits of the device mac address ie. nspanel-04f8

**Comment by joBr99** [comment]
Yeah I'm using the location of the device like "nspanel-kitchen"

**Comment by joBr99** [comment]
```
---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_your_mqtt_topic/RESULT"
    panelSendTopic: "cmnd/tasmota_your_mqtt_topic/CustomSend"
    updateMode: "auto-notify"

nspanel-2:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_your_mqtt_topic2/RESULT"
    panelSendTopic: "cmnd/tasmota_your_mqtt_topic2/CustomSend"
    updateMode: "auto-notify"
```
