### ISSUE TITLE
Navigation Home

### ISSUE THREAD

**Issue by diginfo** [joBr99/nspanel-lovelace-ui#249]
Sorry for keeping you busy but I am creating and hitting a couple of things that would be useful.

I would like to add a home button to my cardGrid and link it to the screensaver home page:

```
    cards:
      - type: cardGrid
        title: Main Menu
        entities:
          - entity: navigate.screensaver
            icon: home

          - entity: navigate.cardGrid_u_lights
            icon: lightbulb-group

          - entity: navigate.cardGrid_heating
            icon: temperature-celsius

```

**Comment by joBr99** [comment]
this was added in version 2.4, should be working like this

```
  config:
    screensaver:
      type: screensaver
      entity: weather.k3ll3r
      key: screensaver
      title: Screensaver
    cards:
      - type: cardEntities
        title: Test
        entities:
          - entity: navigate.screensaver_screensaver
```

#55
