### ISSUE TITLE
[Feature Request] Pass data_template to script / calling service directly

### ISSUE THREAD

**Issue by Llntrvr** [joBr99/nspanel-lovelace-ui#253]
I have multi of these NSpanels and it would be nice to be able to pass to the script what panel is being used to fire the event

          - entity: script.show_nspanel_action
            data_template:
              panel: kitchen

**Comment by illuzn** [comment]
You should be able to do this using the builtin script functionality of homeassistant.

Please see particularly [fields](https://www.home-assistant.io/integrations/script/#fields).

Set up a master script which performs your actions based upon the field e.g.

````yaml
alias: "Toggle a light based upon a field input"
fields:
  area:
    name: "Trigger Area"
    description: "Variable input which sets which light to toggle"
    example: "Kitchen"
sequence:
  - service: light.toggle
    target:
      entity_id: {{ "light." ~ field1 }}
````
Obviously, you would set up whatever logic you want in that master script.

Then set up a child script to call that master script.

````yaml
alias: "Call master script from Living Room"
sequence:
  - service: script.master_script
    data:
      area: "living_room"
````

Then you nspanel calls this child script
e.g. `entity: script.master_script_kitchen` or `entity: script.master_script_living_room`

If this is going to be implemented I would suggest that cards can accept either entities or service calls i.e.

````yaml
cards:
  - type: cardEntities
    entities:
      - entity: light.kitchen
      - service: shell_command.do_something_not_natively_supported_by_HA
        data:
          flags: "service data goes here"
````
I think this can be done without too much changes to the core code (which can't be said for the above suggestion).

**Comment by joBr99** [comment]
>I think this can be done without too much changes to the core code (which can't be said for the above suggestion).

Implementation wise, parameters need to get encoded into the entity name that is transmitted to the panel. The entity names on the panel are limited to 80 chars, due to memory limitations on the panel.

This could be generated by automatically translated from the backend if addiontal data is supplied:

`script.show_nspanel_action{panel="kitchen"}`

To work around the 80 char limit it would be possible to add a translation layer to the backend which is creating a hash of the entity names and transating them back and forth between the panel and HA, but this requires a lot of changes.

**Comment by Llntrvr** [comment]
yeah no i dont care of the 80 chars limit, I can work with that

**Comment by wvalko** [comment]
I wrote a static script this evening for an NSpanel task, that I wouldn't have had to create if I was able to provide a data template.   I could find immediate use being able to pass template values if that would become possible :)

**Comment by joBr99** [comment]
Current development version allows to configure services. This should allow to call anything you want with any data.

```
            - entity: service.light.turn_on
              name: test123
              data:
                entity_id: light.schreibtischlampe
                color_name: "red"
```

This should also work with ` - entity: service.service.xxx`, adding data directly to entities isn't (yet) supported.
