### ISSUE TITLE
[Feature Request] change icon color

### ISSUE THREAD

**Issue by tbretz65** [joBr99/nspanel-lovelace-ui#254]
is it possible to change the color of an icon.

example:
mdi:trash_can ->yellow;blue;gray or brown
like this:
![grafik](https://user-images.githubusercontent.com/74619971/171271375-5917a52c-2a3e-4900-81ff-152e00ffa1db.png)

Thank You

**Comment by joBr99** [comment]
implemented in current development version

![image](https://user-images.githubusercontent.com/29555657/172167967-e1385f4b-0666-4a67-ba33-bc68c5be3972.png)

```
      - type: cardEntities
        title: Sensor Test 1
        entities:
          - entity: sensor.outside_humidity
            color: [255, 0, 0]
```
