### ISSUE TITLE
[Feature Request] Improve cardGrid information density

### ISSUE THREAD

**Issue by ivdimitro** [joBr99/nspanel-lovelace-ui#263]
**Describe the solution you'd like**
In a grid card navigate entities are only icon shortcut. Alternatively the sensors entities display meaningful information in the grid but no actions are taken "on click". 
The request is to improve the information density of the grid card. I see two options to achieve this: 
1. Add "action" property for the sensor entities. When the icon is clicked it should redirect to a pre-define page
2. Add option to overwrite the representation of "navigate" entities. Introduce a new field "representation" which can be either an icon or should be possible to give HA entity from which the state will be read. 

Example configuration: 
```
- type: cardGrid
        entities:
          - entity: sensor.air_temperature
            name: kitchen
            action: navigate.cardThermo_kitchenTRV   ### example for option 1

          - entity: navigate.cardThermo_kitchenTRV
            name: test
            representation: sensor.air_temperature     ### example for option 2
```

**Additional context**
I think option 1 will be easier to implement as I can see the sensor is already clickable not there is no action assigned to it. 
My use case is to show the temperatures from the different rooms on a grid card and on click to go the thermostat for the particular room. With the current implementation I will have to have 2 cards - one with the temperatures and second one for the controls. This introduces unnecessary extra page.   

**Panel / Firmware Version**
Please add the Panel/Firmware Version you are using (EU)

**Comment by joBr99** [comment]
This is already halfway implemented with status on navigate items. Needs some more lines to display the  value for sensors on card grid

https://github.com/joBr99/nspanel-lovelace-ui/blob/a22cf00774f997e6d36fc03bd3fe2c9ecbe90fef/apps/nspanel-lovelace-ui/luibackend/pages.py#L166

**Comment by ivdimitro** [comment]
Great. Waiting to test the feature.

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/172165071-bfc21425-2053-4fde-9b59-f89c75f0b5ae.png)

```
    cards:
      - type: cardGrid
        title: Test Light/Switch
        entities:
          - entity: navigate.cardEntities_sw1
            status: sensor.today_energy
```
