### ISSUE TITLE
[Feature Request] cover card buttons

### ISSUE THREAD

**Issue by jrspowers** [joBr99/nspanel-lovelace-ui#264]
hello is it possible to add 2 button to the cover card for self-set function such as position that I often use the settings are like this see below & in the photo I have indicated the place where the buttons could come I think?

```yaml
service: cover.set_cover_position
data:
  position: 15
target:
  entity_id: cover.jarne_low_speed
```

![image](https://user-images.githubusercontent.com/60328474/172149132-76429191-0bb8-42b8-9a28-12c8e5905a2f.jpeg)

Panel / Firmware Version
Please add the Panel/Firmware Version you are using (EU)

**Comment by jrspowers** [comment]
that's a shame and how can I do it, do you have any tips maybe via script but it's not so handy would be useful if it could come in the map itself?

**Comment by illuzn** [comment]
```yaml
alias: Blinds to Position 1
sequence:
  - service: cover.set_cover_position
    data:
      position: 30
    target:
      entity_id: cover.left_blind_window_covering
mode: single
````

In apps.yaml
````yaml
      - type: cardGrid
        entities:
        - entity: script.blinds_to_position_1
          icon: blinds-open
          name: Daytime
````
