### ISSUE TITLE
[BUG] QRCode Card entity cannot contain dot

### ISSUE THREAD

**Issue by newhinton** [joBr99/nspanel-lovelace-ui#270]
**Describe the bug**

```
      - type: cardQR
        title: my.cool.ssid
        qrCode: "WIFI:S:my.cool.ssid;T:WPA2;P:secret;;"
        entities:
          - entity: iText.Name.my.cool.ssid
            icon: mdi:wifi
          - entity: iText.Password.secret
            icon: mdi:key
```
Using the above card results in the ssid beeing displayed as 'my'. I assume it has to do with the iText also using dots, but this is not documented. (I hope this can get added to the upcoming wiki i read about in a different issue)
The title works as expected.

A workaround is to use this character: ·
It is a more centered dot, so there is a visible difference to the normal dot.

**Comment by joBr99** [comment]
changed the syntax for using iText in cardQR (untested)

```
      - type: cardQR
        title: Guest Wifi
        qrCode: "WIFI:S:test_ssid;T:WPA;P:test_pw;;"
        entities:
          - entity: iText.test_ssid
            name: Name
            icon: mdi:wifi
          - entity: iText.test_pw
            name: Password
            icon: mdi:key
```

instead of iText you can also use an input_text from HA there (or even a switch)
