### ISSUE TITLE
[BUG] Climate Card Formatting issues

### ISSUE THREAD

**Issue by arunsudhakar** [joBr99/nspanel-lovelace-ui#271]
**Describe the bug**
I'm getting some random numeric values in the climate card . It looks like the formatting info from the MQTT message is not being handled correctly

**To Reproduce**
Set up a climate card using the cardThermo type

```
hello_world:
  module: hello
  class: HelloWorld

nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel/RESULT"
    panelSendTopic: "cmnd/nspanel/CustomSend"
    updateMode: "auto-notify"
    sleepTimeout: 20
    #sleepBrightness: 10
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "en_US" # used for translations in translations.py and for localized date if babel python package is installed
    screensaver:
      entity: weather.openweathermap
    cards:
      - type: cardThermo
        entity: climate.livingroomac
      - type: cardThermo
        entity: climate.diningroomac
      - type: cardMedia
        entity: media_player.playstation_4

```

**Screenshots**
![Screenshot_2022-06-10 00 28 40_yrB2gA](https://user-images.githubusercontent.com/18276374/172898527-7a457262-91ab-4651-9835-18fee61363bb.png)

**AppDaemon Logs**

```
2022-06-10 00:14:33.193581 INFO nspanel-1: Sending MQTT Message: pageType~cardThermo
2022-06-10 00:14:33.222710 INFO nspanel-1: Sending MQTT Message: entityUpd~Aircon 1~1|1~climate.livingroomac~250~230~Cooling~160~310~10~~~~~~~~~~~~~~~~~~~~~���~64512~0~heat_cool~���~11487~1~cool~���~60897~0~dry~���~64512~0~heat~���~35921~0~fan_only~���~35921~0~off
2022-06-10 00:14:53.265052 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,sleepReached,cardThermo"}'}
```

**Additional context**
I updated the NSPanel firmware and autoexec.be to the latest version by running these commands today

```
FlashNextion http://nspanel.pky.eu/lui-release.tft
UpdateDriverVersion https://raw.githubusercontent.com/joBr99/nspanel-lovelace-ui/main/tasmota/autoexec.be
```
