### ISSUE TITLE
[Feature Request]  - Display an entity with JSON format attributes

### ISSUE THREAD

**Issue by diginfo** [joBr99/nspanel-lovelace-ui#272]
I have a sensor, that is managed thru an appdaemon script, the result is an entity with JSON format attributes i.e.:

```
next: {
"RECYCLING": "XXXXXX"
"REFUSE": "XXXXXX"
"GARDEN": "XXXXXX"
}
```

I can pull the data into the developer tools templates no problem with:

```
{{ state_attr("sensor.bindata","next")["RECYCLING"] }}
```

But how do I pull it into a card entity ?

```
      - type: cardEntities
        title: Refuse Collection
        key: refuse
        entities:
          - entity: sensor.bindata
            state: '{{ state_attr("sensor.bindata","next")["RECYCLING"] }}'
            icon: recycle
            name: Recycling
```
