### ISSUE TITLE
[Feature Request] Screen Lock

### ISSUE THREAD

**Issue by cmeissl** [joBr99/nspanel-lovelace-ui#275]
**Describe the solution you'd like**
During cleaning the screen some accidental touch inputs can happend. A screen lock could prevent them. This could be exposed as a switch that can then be added to a card and automatically turned off after some time in an automation. 

**Panel / Firmware Version**
2.9.3 (EU)

**Comment by ivdimitro** [comment]
Currently there is [doubleTapToUnlock](https://docs.nspanel.pky.eu/config-screensaver/) option for the screensaver.

**Comment by joBr99** [comment]
Configure an [input_boolean](https://www.home-assistant.io/integrations/input_boolean/) and use the default card option of the screensaver for this.

```
    screensaver:
      key: screensaver
      defaultCard: '{{ "navigate.locked" if is_state("input_boolean.test", "off") else "navigate.unlocked" }}'
```

in combination with a card that doesn't contain UI controls:

```
      - type: cardGrid
        key: locked
        navItem1:
          entity: delete
        navItem2:
          entity: delete
        title: Locked
```

or just navigate to the screensaver itself:

```
      defaultCard: '{{ "navigate.first_card" if is_state("switch.ac", "off") else "navigate.screensaver" }}'
```

(There's only the drawback that it won't unlock to the last used card and to the configured one instead.)
