### ISSUE TITLE
screen dark after exiting screensaver

### ISSUE THREAD

**Issue by Linzer05** [joBr99/nspanel-lovelace-ui#278]
after the update on 06/12/2022
at start only screensave page is visible, 
when I touch touchscreen everything goes black for sleepTimeout time, 
then screensave  page comes back.
```
nspanel-2:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel_eu/RESULT"
    panelSendTopic: "cmnd/nspanel_eu/CustomSend"
    model: "eu"
    updateMode: "auto-notify"
    sleepTimeout: 20
    sleepBrightness:
      - time: "5:30:00"
        value: 1
      - time: "08:00:00"
        value: 10
      - time: "22:00:00"
        value: 0
    locale: "de_DE" # used for translations in translations.py and for localized date if babel python package is installed
    
    screensaver:
        statusIcon1:
          entity: binary_sensor.rain_sensor_water_leak
          name: Leckage
          icon: weather-rainy
        statusIcon2:
          entity: switch.nspanel_eu_r1
          name: Thermoventil
          icon: valve-open
        entity: weather.openweathermap
        weatherOverrideForecast4:
          entity: sensor.senseair2_co2
          name: CO2
          icon: air-filter
        
        alternativeLayout: false
        theme: 
         autoWeather: true
    cards:
      - type: cardGrid
        title: Sensors
        entities:
          - entity: sensor.senseair2_co2
            name: CO2
            icon: air-filter
          - entity: sensor.klima_outside_temperature
            name: Außen
          - entity: sensor.klima_schlafzimmer_temperature
            name: Schlafzimmer
          - entity: sensor.klima_schlafzimmer_humidity
            name: Feuchtigkeit
            icon: water-percent
```

**Comment by joBr99** [comment]
Hey did you restart AppDaemon after updateing?

**Comment by redford-jones** [comment]
I too have this issue, I have restarted appdaemon a number of times.

it seems that the issue may occur after the first screensaver timeout, once you try to go back in the screen goes black but if I click in the area where I know there is an entity icon then the action is still performed behind the black screen. Suggests to me the issue lies in the screen timeout and brightness.

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/173252341-4fc36fba-07c9-4701-8e10-12a83d772877.png)

Sounds like it has something to with the new feature to configure screenBrightness. Please append the appdaemon log after startup of appdaemon

**Comment by Linzer05** [comment]
> Hey, did you restart AppDaemon after updateing the app in HACS?

I restarted Home Assistant 3 or 4 times becouse of other reasons.
how can i restart only app daemon?

just before timeout for screensave expires, i can see entites screen, maybe 1s long

**Comment by Linzer05** [comment]
upp, sorry i found where to restart :)
I'll test tomorrow then

**Comment by Linzer05** [comment]
oh yee it worked thanks!
the topic is done

**Comment by redford-jones** [comment]
> oh yee it worked thanks!
> the topic is done

I still see this issue after several restarts of AppDaemon. 
I have not yet had a chance to post up a log yet, I’ll do that later today.

**Comment by redford-jones** [comment]
OK. I found my issue. You were right @joBr99 it is related to the new screen dim mode command, but it was me that had caused the issue.

Before you introduced the entity tracking for screen dimming I had built a simple automation that dimmed the screen based on a door sensor. When the door was closed it issued this MQTT command:
```
service: mqtt.publish
data:
  payload: dimmode~0
  topic: cmnd/nspanel_office/CustomSend
```
and when opened issued this:
```
service: mqtt.publish
data:
  payload: dimmode~10
  topic: cmnd/nspanel_office/CustomSend
```
I have changed these to the new commands and the issue has now gone.
