### ISSUE TITLE
[BUG] timeAdditionalTemplate and dataAdditionalTemplate are not working

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#281]
**Describe the bug**
i tested and both timeAdditionalTemplate and dataAdditionalTemplate are not working, i followed what you guide in the overview config page to put a timeAdditionalTemplate either in config portion and screensaver portion and none of them works, i notice you typed Additonal instead of Additional so i am not sure whether you typed it in purpose or a typo. 
pls have a look here : 
https://docs.nspanel.pky.eu/config-overview/

**Comment by jrspowers** [comment]
hello @joBr99 timeAdditionalTemplate  does not work with my posts eu version update versions 3.0.4 the dateAdditionalTemplate does work how come?

**Comment by joBr99** [comment]
please share your config

**Comment by jrspowers** [comment]
```yaml
nspanel:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_your_mqtt_topic/RESULT"
    panelSendTopic: "cmnd/tasmota_your_mqtt_topic/CustomSend"
    timeAdditionalTemplate: " {{ state_attr('calendar.jarneroussard_gmail_com','message') }} "
    dateAdditionalTemplate: " {{ state_attr('calendar.jarneroussard_gmail_com','message') }} "
```
