### ISSUE TITLE
[Feature Request] icon color state entitie

### ISSUE THREAD

**Issue by jrspowers** [joBr99/nspanel-lovelace-ui#295]
### FEATURE DESCRIPTION
hello is it possible to add this function if the state of entity on= color red of icon & off = color blue of icon is it possible to make this so that we can give our own colors ?

### ADDITIONAL CONTEXT
```yaml
entity: binary_sensor.deur_sensor_jarne
icon:
  "on": mdi:door-open
  "off": mdi:door-closed-lock
 coloricon: 
  "on": [0, 0, 255]
  "off": [255, 0, 0]
```

### PANEL / FIRMWARE VERION
Please add the Panel/Firmware Version you are using (EU)
