### ISSUE TITLE
[Feature Request] - Card Contrast

### ISSUE THREAD

**Issue by diginfo** [joBr99/nspanel-lovelace-ui#302]
### FEATURE DESCRIPTION
I have no idea if this is a bug or a feature request :-)

As you can see in the 2 attached images, the home screen is nice and bright, but the other navigated screens appear to be 'washed-out' and not as sharp.

Why is it that all screens except for the main home / screensaver screen and less bright than the main screen ?

This might be something that I have misunderstood or mis-configured ?!

### ADDITIONAL CONTEXT
None

### PANEL / FIRMWARE VERION
EU
![IMG_4608 Small](https://user-images.githubusercontent.com/6010010/174943589-d5c35ba1-8d24-4946-9867-1ad74320f1a3.jpeg)
![IMG_4607 Small](https://user-images.githubusercontent.com/6010010/174943598-61657d0a-4eac-4a35-820b-d5ce87288b79.jpeg)

**Comment by illuzn** [comment]
What are your configured `screenBrightness` and `sleepBrightness` settings from apps.yaml?

**Comment by diginfo** [comment]
Hi, thanks for helping.

Well screenBrightness is 100 and sleepBrightness change depending on the time of day, but I think I might know what the problem is.

Unless I am mistaken, you can set the background colour for the screensaver which I have done:

```
    screensaver:
      entity: weather.openweathermap
      key: home
      defaultCard: navigate.cardGrid_menu
      theme: 
        autoWeather: true
        background: [25,25,112]
        time: [255,255,100]
```
 but you cant set it for all of the other cards / screens, so my screensaver home page is dark blue, but all other pages are the default 'black' i.e. all background colours off ??

Is it possible to set the background colour of cards / other pages except the screensaver page ?
