### ISSUE TITLE
[Feature Request]  color change on screensaver

### ISSUE THREAD

**Issue by copilador** [joBr99/nspanel-lovelace-ui#305]
### FEATURE DESCRIPTION
It is possible to send (mqtt?) a new color to the background of screensaver mode. Thanks

### ADDITIONAL CONTEXT
my configuration in apps.yaml
    screensaver:    
      entity: weather.openweathermap
      defaultCard: navigate.cardGrid_covers
      weatherOverrideForecast4:
        entity: sensor.netatmo_home_indoor_temperature
        name: Home
      theme: 
        autoWeather: true
        background: [25,25,112] -->color change?
        time: [255,255,100] 

### PANEL / FIRMWARE VERION

Panel/Firmware Version (EU) v3.1.1

**Comment by copilador** [comment]
My wish is to be able to change in color of background on screensaver according to the state of a sensor (solar import/export), similary to changing the brightness by mqtt (for example 10% brightness -> cmnd/nspanel_XXXXXX/CustomSend payload: dimmode~10)

**Comment by illuzn** [comment]
That's going to require a pretty significant rewrite for a very niche feature.

Have you considered using `statusIcon1` and `statusIcon2`? You can configure these to any sensor you wish and use a dict in the icon to change the icon based upon state e.g.:
```yaml
nspanel-1:
  config:
    screensaver:
      statusIcon1:
        entity: sensor.solar_import_export
        icon:
          "export": "mdi:solar-power"
          "import": "mdi:transmission-tower"
```
This should produce a solar panel when exporting and a transmission tower when importing.
