### ISSUE TITLE
[Feature Request]  Managing multiple NSPanels efficent

### ISSUE THREAD

**Issue by markuserlacher** [joBr99/nspanel-lovelace-ui#327]
### FEATURE DESCRIPTION
I looking for a way to manage the apps.yaml very efficent without duplicates at all.

I currently plan to implement multiple nspanels in different rooms all over the house (total over 10 at the end)

When ever possible i would like to maintaine one single configuration over all nspanels and just have different defaultpages on each of the panels, thats mean in the yaml it part of the panel (module,class,config,screensaver) will be specific for each panel but the cards
and hiddenCards i would like to share across all nspanels in the yaml.

There a small diagram about my idea:

![image](https://user-images.githubusercontent.com/38162885/176273782-867f45dd-a357-409d-ae6a-de0a313594e5.png)

Is this possible or is there a other better way? 

I am a big fan of your solution and a big thank you for all the work you do.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
US-L

**Comment by joBr99** [comment]
you can move the hidden cards to a seperate file and then use !include to reference it.

`theme: !include /config/appdaemon/apps/screensaver-theme.yaml`

https://github.com/joBr99/nspanel-lovelace-ui/tree/main/appdaemon/screensaver-theme-include

https://www.home-assistant.io/docs/configuration/splitting_configuration/

**Comment by illuzn** [comment]
Also this section from AppDaemon docs: https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html#include-yaml-files

This is untested so it's unclear if it would work but:

```yaml
nspanel-livingroom: !include /config/appdaemon/apps/master.yaml
    cards:
    [individual card config goes here]
nspanel-kitchen: !include /config/appdaemon/apps/master.yaml
  cards:
    [individual card config goes here]
```

master.yaml would have:
```yaml
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
  [etc]
```

That means only your card config is different per panel. But now that I think about it `defaultCard` is a key under screensaver so I'm not sure this could work.

You might want to include the following in `appdaemon.yaml` if you do this:
```yaml
  missing_app_warnings: 0
  invalid_yaml_warnings: 0
```
This supresses some warnings about invalid yaml.  

This all depends on how the upstream !include directive works in AppDaemon and I'm not sure how it works.

**Comment by joBr99** [comment]
also untested, but sharing hidden cards should look like this:

# apps.yaml
```
nspanel-kueche:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_nspkueche/RESULT"
    panelSendTopic: "cmnd/tasmota_nspkueche/CustomSend"
    screensaver:
      entity: weather.k3ll3r
    cards:
      - type: cardEntities
        title: Kueche
        entities:
          - entity: light.kueche_lights
      - type: cardMedia
        entity: media_player.spotify_jojojo27
      - type: cardThermo
        entity: climate.kuche_boden
	hiddenCards: !include /config/appdaemon/apps/hiddenCards.yaml
	
nspanel-terrasse:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_NsPanelTerrasse/RESULT"
    panelSendTopic: "cmnd/tasmota_NsPanelTerrasse/CustomSend"
    screensaver:
      entity: weather.k3ll3r
    cards:
      - type: cardEntities
        title: Rolladen
        key: rolladen
        entities:
          - entity: cover.rolladenfenster_cover_1
          - entity: cover.nspterrasse_cover_1
          - entity: cover.rolladenterasse_cover_1
          - entity: fan.ceiling_fan
	hiddenCards: !include /config/appdaemon/apps/hiddenCards.yaml
```

# hiddenCards.yaml
```
- type: cardGrid
  title: Exmaple Hidden
  key: test
  entities:
    - entity: light.kueche_lights
    - entity: light.kueche_lights
    - entity: light.kueche_lights
- type: cardThermo
  entity: climate.kuche_boden
  key: test2
```
