### ISSUE TITLE
[BUG] Sensor values don't update on cardGrid

### ISSUE THREAD

**Issue by oastBloke** [joBr99/nspanel-lovelace-ui#356]
### PROBLEM DESCRIPTION

Thanks for the hardwork, this has drawn me in to Home Assistant, just for the panel support.

When a sensor is updated in HASS the corresponding sensor is not updated on cardGrid if the page is open (unlike a light status, for example)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml:
```
      - type: cardGrid
        entities:
          - entity: input_button.incr_temp
            icon: thermometer-chevron-up
            name: ""
          - entity: sensor.garden_room_setpoint
            name: ""
          - entity: input_button.decr_temp
            icon: thermometer-chevron-down
            name: ""
        title: Thermostat


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
Update a sensor from HASS while it is displayed on NSPanel

### EXPECTED BEHAVIOUR

The sensor value updates in line with HASS

### PANEL / FIRMWARE VERION

EU
