### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by ZeniaBol** [joBr99/nspanel-lovelace-ui#359]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:
![Screenshot 2022-07-18 165135](https://user-images.githubusercontent.com/75325337/179616078-bf7a131a-118e-46ce-a6b6-5d348fa22678.png)
![Screenshot 2022-07-18 165135](https://user-images.githubusercontent.com/75325337/179616162-c3f74628-bb8e-43ac-8d79-d1fdd18e9411.png)
![Screenshot 2022-07-18 165359](https://user-images.githubusercontent.com/75325337/179616163-ef452d9b-56ba-4f44-a63a-363a8239526a.png)
![Screenshot 2022-07-18 165503](https://user-images.githubusercontent.com/75325337/179616164-64112306-cb66-44dc-bab0-b62ad51d4a6e.png)

- [ ] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:
---
#secrets: /config/secrets.yaml
appdaemon:
  latitude: 39.083378820783466
  longitude: -77.2285046901373
  elevation: 125
  time_zone: America/New_York
  plugins:
    HASS:
      type: hass
     # ha_url: 192.168.1.35:8123
     # token: J8kvOzsByV2kGlBBdPUvvv3LD7xrdy...
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: 192.168.1.35
      client_port: 1883
      client_user: "Zenia1"
      client_password: "Zenia1 password"
      client_topics: NONE
http:
  url://192.168.1.35:5050
  #url: http://127.0.0.1:5050
#admin:
#api:
#hadashboard:


```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:
---
NSPanel:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel/RESULT"
    panelSendTopic: "cmnd/nspanel/CustomSend"
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "en_US"
    screensaver:
      entity: weather.k3ll3r
    cards:
      - type: cardEntities
        entities:
          - entity: switch.example_item
          - entity: light.example_item
        title: Example 1
      - type: cardGrid
        entities:
          - entity: switch.example_item
          - entity: light.example_item
        title: Example 2

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:
For some reason my logs for all add-ons is emty, even after restart

```
I use a DuckDNS for my HA. My MQTT broker can see my ZigbeetoMqtt devices without any problem. Thank you for your help in advanced

**Comment by ZeniaBol** [comment]
2022-07-18 17:10:37.624030 INFO AppDaemon: Previous message repeated 1 times
2022-07-18 17:10:37.625801 INFO AppDaemon: AppDaemon Exited
[17:10:37] INFO: AppDaemon stoped, restarting...
[17:10:38] INFO: Starting AppDaemon...
2022-07-18 17:10:47.412446 INFO AppDaemon: AppDaemon Version 4.2.1 starting
2022-07-18 17:10:47.413556 INFO AppDaemon: Python version is 3.10.4
2022-07-18 17:10:47.414197 INFO AppDaemon: Configuration read from:
/config/appdaemon/appdaemon.yaml
2022-07-18 17:10:47.414966 INFO AppDaemon: Added log: AppDaemon
2022-07-18 17:10:47.415791 INFO AppDaemon: Added log: Error
2022-07-18 17:10:47.416451 INFO AppDaemon: Added log: Access
2022-07-18 17:10:47.417565 INFO AppDaemon: Added log: Diag
2022-07-18 17:10:47.782573 INFO AppDaemon: Loading Plugin HASS using
class HassPlugin from module hassplugin
2022-07-18 17:10:48.196330 INFO HASS: HASS Plugin Initializing
2022-07-18 17:10:48.196993 INFO HASS: HASS Plugin initialization complete
2022-07-18 17:10:48.198013 INFO AppDaemon: Loading Plugin MQTT using
class MqttPlugin from module mqttplugin
2022-07-18 17:10:48.451892 INFO MQTT: MQTT Plugin Initializing
2022-07-18 17:10:48.452566 INFO MQTT: Using 'appdaemon/status' as Will Topic
2022-07-18 17:10:48.453115 INFO MQTT: Using 'appdaemon/status' as Birth Topic
2022-07-18 17:10:48.454780 INFO AppDaemon: Initializing HTTP
2022-07-18 17:10:48.455937 WARNING AppDaemon:
------------------------------------------------------------
2022-07-18 17:10:48.456665 WARNING AppDaemon: Unexpected error during run()
2022-07-18 17:10:48.457362 WARNING AppDaemon:
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/__main__.py", line
141, in run
    self.http_object = adhttp.HTTP(
  File "/usr/lib/python3.10/site-packages/appdaemon/http.py", line
138, in __init__
    self._process_http(http)
  File "/usr/lib/python3.10/site-packages/appdaemon/http.py", line
352, in _process_http
    self._process_arg("url", http)
  File "/usr/lib/python3.10/site-packages/appdaemon/http.py", line
390, in _process_arg
    setattr(self, arg, kwargs[arg])
TypeError: string indices must be integers
2022-07-18 17:10:48.463236 INFO AppDaemon: Previous message repeated 1 times
2022-07-18 17:10:48.464196 INFO AppDaemon: AppDaemon Exited
[17:10:48] INFO: AppDaemon stoped, restarting...
[17:10:48] INFO: Starting AppDaemon...
2022-07-18 17:10:58.126267 INFO AppDaemon: AppDaemon Version 4.2.1 starting
2022-07-18 17:10:58.126954 INFO AppDaemon: Python version is 3.10.4
2022-07-18 17:10:58.127504 INFO AppDaemon: Configuration read from:
/config/appdaemon/appdaemon.yaml
2022-07-18 17:10:58.128113 INFO AppDaemon: Added log: AppDaemon
2022-07-18 17:10:58.128794 INFO AppDaemon: Added log: Error
2022-07-18 17:10:58.129321 INFO AppDaemon: Added log: Access
2022-07-18 17:10:58.129820 INFO AppDaemon: Added log: Diag
2022-07-18 17:10:58.488702 INFO AppDaemon: Loading Plugin HASS using
class HassPlugin from module hassplugin
2022-07-18 17:10:58.899012 INFO HASS: HASS Plugin Initializing
2022-07-18 17:10:58.899772 INFO HASS: HASS Plugin initialization complete
2022-07-18 17:10:58.900670 INFO AppDaemon: Loading Plugin MQTT using
class MqttPlugin from module mqttplugin
2022-07-18 17:10:59.151376 INFO MQTT: MQTT Plugin Initializing
2022-07-18 17:10:59.152128 INFO MQTT: Using 'appdaemon/status' as Will Topic
2022-07-18 17:10:59.152708 INFO MQTT: Using 'appdaemon/status' as Birth Topic
2022-07-18 17:10:59.154250 INFO AppDaemon: Initializing HTTP
2022-07-18 17:10:59.155301 WARNING AppDaemon:
------------------------------------------------------------
2022-07-18 17:10:59.156202 WARNING AppDaemon: Unexpected error during run()
2022-07-18 17:10:59.156900 WARNING AppDaemon:
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/__main__.py", line
141, in run
    self.http_object = adhttp.HTTP(
  File "/usr/lib/python3.10/site-packages/appdaemon/http.py", line
138, in __init__
    self._process_http(http)
  File "/usr/lib/python3.10/site-packages/appdaemon/http.py", line
352, in _process_http
    self._process_arg("url", http)
  File "/usr/lib/python3.10/site-packages/appdaemon/http.py", line
390, in _process_arg
    setattr(self, arg, kwargs[arg])
TypeError: string indices must be integers
2022-07-18 17:10:59.162303 INFO AppDaemon: Previous message repeated 1 times
2022-07-18 17:10:59.163144 INFO AppDaemon: AppDaemon Exited
[17:10:59] INFO: AppDaemon stoped, restarting...
[17:10:59] INFO: Starting AppDaemon...
2022-07-18 17:11:08.838688 INFO AppDaemon: AppDaemon Version 4.2.1 starting
2022-07-18 17:11:08.839355 INFO AppDaemon: Python version is 3.10.4
2022-07-18 17:11:08.840411 INFO AppDaemon: Configuration read from:
/config/appdaemon/appdaemon.yaml
2022-07-18 17:11:08.840974 INFO AppDaemon: Added log: AppDaemon
2022-07-18 17:11:08.841517 INFO AppDaemon: Added log: Error
2022-07-18 17:11:08.842052 INFO AppDaemon: Added log: Access
2022-07-18 17:11:08.842562 INFO AppDaemon: Added log: Diag
2022-07-18 17:11:09.203182 INFO AppDaemon: Loading Plugin HASS using
class HassPlugin from module hassplugin
2022-07-18 17:11:09.622157 INFO HASS: HASS Plugin Initializing
2022-07-18 17:11:09.623216 INFO HASS: HASS Plugin initialization complete
2022-07-18 17:11:09.624196 INFO AppDaemon: Loading Plugin MQTT using
class MqttPlugin from module mqttplugin
2022-07-18 17:11:09.864785 INFO MQTT: MQTT Plugin Initializing
2022-07-18 17:11:09.865508 INFO MQTT: Using 'appdaemon/status' as Will Topic
2022-07-18 17:11:09.866195 INFO MQTT: Using 'appdaemon/status' as Birth Topic
2022-07-18 17:11:09.868256 INFO AppDaemon: Initializing HTTP
2022-07-18 17:11:09.869494 WARNING AppDaemon:
------------------------------------------------------------
2022-07-18 17:11:09.870398 WARNING AppDaemon: Unexpected error during run()
2022-07-18 17:11:09.871248 WARNING AppDaemon:
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/__main__.py", line
141, in run
    self.http_object = adhttp.HTTP(
  File "/usr/lib/python3.10/site-packages/appdaemon/http.py", line
138, in __init__
    self._process_http(http)
  File "/usr/lib/python3.10/site-packages/appdaemon/http.py", line
352, in _process_http
    self._process_arg("url", http)
  File "/usr/lib/python3.10/site-packages/appdaemon/http.py", line
390, in _process_arg
    setattr(self, arg, kwargs[arg])
TypeError: string indices must be integers
2022-07-18 17:11:09.877231 INFO AppDaemon: Previous message repeated 1 times
2022-07-18 17:11:09.877996 INFO AppDaemon: AppDaemon Exited
[17:11:10] INFO: AppDaemon stoped, restarting...
[17:11:10] INFO: Starting AppDaemon...

**Comment by ZeniaBol** [comment]
![image](https://user-images.githubusercontent.com/75325337/179618589-eceedc29-4e26-449f-b8a6-dac55fa93c0c.png)

**Comment by joBr99** [comment]
>http:
  url://192.168.1.35:5050
  #url: http://127.0.0.1:5050
  
Start with removeing this syntax error in url line from appdaemon.yaml, you can use this one:
  
```
---
secrets: /config/secrets.yaml
appdaemon:
  latitude: 39.083
  longitude: -77.228
  elevation: 125
  time_zone: America/New_York
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: 192.168.1.35
      client_port: 1883
      client_user: "Zenia1"
      client_password: "Zenia1 password"
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
  
```
