### ISSUE TITLE
[Feature Request] - PowerCard

### ISSUE THREAD

**Issue by cybertza** [joBr99/nspanel-lovelace-ui#371]
### FEATURE DESCRIPTION
Powercard,  Similar to Tesla power card https://community.home-assistant.io/t/custom-solar-power-card-the-tesla-style-almost/220705
just perhaps without the moving lines, 
perhaps the ability to rotate screensavers on preset timer. 

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by magnusoverli** [comment]
The power card is a great idea! Maybe even more useful is a more generic energy card? Visualizing energy consumption for different rooms/devices?

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/189524300-ddc73c0d-5a37-4284-91e2-65727f67916d.png)
![image](https://user-images.githubusercontent.com/29555657/189524318-8100d8e6-377b-4d53-88d3-2f862106c092.png)

Far, far away from being usable, but it could look like this.

**Comment by magnusoverli** [comment]
That looks really cool! 👌🏻
I guess it depends on the use case of the card. This is good for visualisation of energy flows. Maybe there is room for another energy related card that takes consumption more into account? I was thinking a card that takes a few devices, gives them an icon, puts the current energy consumption (total and per device) in text and a graph that compares the most energy hungry devices? 

I know this might be a lot to ask! 🥰

**Comment by joBr99** [comment]
I don't think that I completly got what you mean, however a graph won't be possible on nspanel.

**Comment by joBr99** [comment]
cardPower is doing something in current dev version
```
    cards:
      - type: cardPower
        title: PowerTest
        entities:
          - entity: sensor.sml2mqtt_elw_total_energy
          - entity: sensor.sml2mqtt_mt631_total_energy
          - entity: sensor.aussenbeleuchtungeingang_energy_today
          - entity: sensor.sml2mqtt_elw_total_energy
          - entity: sensor.sml2mqtt_mt631_total_energy
          - entity: sensor.aussenbeleuchtungeingang_energy_today
```

**Comment by magnusoverli** [comment]
Is `dev` not the same as `main`?

**Comment by joBr99** [comment]
yes development is main

**Comment by joBr99** [comment]
Did you update to the latest firmware aswell?

EU VERSION: FlashNextion http://nspanel.pky.eu/lui.tft

https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version

**Comment by magnusoverli** [comment]
No, I did not realise there was a dev version of the tft also… 🤦🏼‍♂️

**Comment by joBr99** [comment]
Documenation still missing, but it should should be more or less implemented now.

![image](https://user-images.githubusercontent.com/29555657/194730691-ab219bf5-6291-44aa-b05e-d9b8b591ca5e.png)

**Comment by magnusoverli** [comment]
This looks very interesting! 👌🏻 Care to share the card config for the example?

**Comment by joBr99** [comment]
you need the newest appdaemon app & dev firmware

```
    cards:
      - type: cardPower
        title: PowerTest
        entities:
          - entity: sensor.sml2mqtt_elw_total_energy
            speed: -1
          - entity: sensor.sml2mqtt_mt631_total_energy
          - entity: sensor.aussenbeleuchtungeingang_energy_today
          - entity: sensor.sml2mqtt_elw_total_energy
          - entity: sensor.sml2mqtt_mt631_total_energy
          - entity: sensor.aussenbeleuchtungeingang_energy_today
          - entity: sensor.aussenbeleuchtungeingang_energy_today
```

**Comment by pbvdven** [comment]
This looks very nice. still tying it but how dit you appley the color because like this isn't working for me?

`      - type: cardPower
        title: PowerTest
        entities:
          - entity: sensor.envoy_122136057607_current_power_consumption
            icon: home-lightning-bolt-outline
            color: [255,255,51]
            speed: -1
          - entity: sensor.envoy_122136057607_current_power_production
            icon: solar-power
            color: [255,255,51]
          - entity: sensor.envoy_122136057607_today_s_energy_production
          - entity: sensor.watermeter_active_water_usage
          - entity: sensor.watermeter_total_water_usage
          - entity: sensor.envoy_122136057607_today_s_energy_consumption
          - entity: sensor.homebase_gas_consumption
        key: powertest`

**Comment by joBr99** [comment]
update to lastest dev and try again, this should fix it (untested)

https://github.com/joBr99/nspanel-lovelace-ui/commit/81e008b37db2297c97d4956fe07e5b5cd893308c

**Comment by magnusoverli** [comment]
Just did a quick test, and it works great.
Missing being able to put names on the entities though. Not all devices have good options for icons to let user sknow what enity it is...

**Comment by joBr99** [comment]
@magnusoverli I wasn't able to fit in two lines per entity.

**Comment by joBr99** [comment]
> I also really like it. i have made an entire energy menu last night with current view, day view, month view. I'm only missing the unit of measurement because power is in kwh and water and gas are m3 and i would like a month view in €. But the problem i have is home assistant shows the value with unit of measurement but the NS panel only shows value without the unit of measurement or am i forgetting something?
> 
> ![image](https://user-images.githubusercontent.com/39600990/194875940-a3d5e1aa-0814-4c37-be61-82a76e3663c1.png)
> 
> ![IMG_1987](https://user-images.githubusercontent.com/39600990/194877798-77c036e4-b03c-45f9-829b-a922dae30ef6.jpg)

I will have a look at the units, also the different background colors. Do you have a defaultBackgroundColor configured?

**Comment by pbvdven** [comment]
That would be great 👍 yes default background would be nice if it could be the same color.

**Comment by pbvdven** [comment]
And maybe its just me but i would like the option to use this screen as screensaver on some of my panels. maybe with the time and current temp there where now the titel is.

**Comment by magnusoverli** [comment]
My "cirles" are all moving the same speed and in sync... A bug?

> And maybe its just me but i would like the option to use this screen as screensaver on some of my panels. maybe with the time and current temp there where now the titel is.

I have also thought about this... A small time display in the corner or something makes it perfect!

**Comment by pbvdven** [comment]
> My "cirles" are all moving the same speed and in sync... A bug?
> 
> > And maybe its just me but i would like the option to use this screen as screensaver on some of my panels. maybe with the time and current temp there where now the titel is.
> 
> I have also thought about this... A small time display in the corner or something makes it perfect!

You can change the moving with speed option -1 moves it from right to left. If the same speed the dots are insync

**Comment by magnusoverli** [comment]
But the speed should be based on the amount of power for the entity, no?

**Comment by magnusoverli** [comment]
Well, I think that unless the movement of the circles actually contributes with meaningful info, I feel like the display real estate could be better used. For example for units of measurement or entity names…?

Having the circles speed of movement as a fraction of the total power would be a really good addition to this card!

**Comment by MattiaFontanaErrepinet** [comment]
Hi,i have tried this new card but i show only home icon i have added few sensor but nothing
`      - type: cardPower
        title: PowerTest
        entities:
          - entity: sensor.tapparella_cottura_power
            icon: home-lightning-bolt-outline
            color: [255, 255, 51]
            speed: -1
          - entity: sensor.tapparella_cucina_power
            icon: solar-power
            color: [255,255,51]`

**Comment by MattiaFontanaErrepinet** [comment]
I have tried to use this card but not working i see only central icon (home)

`      - type: cardPower
        title: PowerTest
        entities:
          - entity: sensor.tapparella_cottura_power
            icon: home-lightning-bolt-outline
            color: [255, 255, 51]
            speed: -1
          - entity: sensor.tapparella_cucina_power
            icon: solar-power
            color: [255,255,51]
`

**Comment by cybertza** [comment]
Update to the latest dev ver on appDReinstall drop down on top right, in hacsSelect “main”Wait till its color changes.Click install.Try ignore the one warning that tells you there Is a new version daily 🤣RegardsJaco GoussardOn 19 Oct 2022, at 08:16, MattiaFontanaErrepinet ***@***.***> wrote:﻿
I have tried to use this card but not working i see only central icon (home)
     - type: cardPower title: PowerTest entities: - entity: sensor.tapparella_cottura_power icon: home-lightning-bolt-outline color: [255, 255, 51] speed: -1 - entity: sensor.tapparella_cucina_power icon: solar-power color: [255,255,51]

**Comment by joBr99** [comment]
This is only working in the eu version and not yet included in us-l

**Comment by cybertza** [comment]
Would have fixed that allready, but i didnt clone the repo.

**Comment by irqnet** [comment]
Is there a specific order need where I have to place the sensors in the configuration?

**Comment by MattiaFontanaErrepinet** [comment]
> is on the US-P and works, Its just the dot slides left to right, and not up and down, but the lines are up and down, but it works

Now i try with US-P firmware

**Comment by cybertza** [comment]
make sure you running dev version for both
<img width="269" alt="image" src="https://user-images.githubusercontent.com/20600538/196728620-663cb04c-4117-4d92-9dfd-8af8a8a0a38f.png">
<img width="764" alt="image" src="https://user-images.githubusercontent.com/20600538/196729059-c8bf75d2-3c36-4b17-8a64-a7f8c451df49.png">
<img width="194" alt="image" src="https://user-images.githubusercontent.com/20600538/196729238-387be3e1-5e4e-472d-a534-0dddeeec86c3.png">
```

      - type: cardPower
        title: PowerTest
        entities:
          - entity: sensor.grid_ct_power
            icon: home-lightning-bolt-outline
            color: [255,255,51]
            speed: -1
          - entity: sensor.solar_power_total
            icon: solar-power
            color: [255,255,51]
          - entity: sensor.battery_power
            icon: battery
            color: [0,255,0]
          - entity: sensor.load_power
            icon: power
          - entity: sensor.grid_ct_power
          - entity: sensor.grid_ct_power
          - entity: sensor.grid_ct_power
        key: powertest

```

**Comment by cybertza** [comment]
<img width="187" alt="image" src="https://user-images.githubusercontent.com/20600538/196736144-c6faca82-1b38-4254-91b7-be544394a61d.png">

**Comment by joBr99** [comment]
fixed the bug with the wrong background color on ha-gray and also the bug with the horizontal dots on US-P

**Comment by joBr99** [comment]
@MattiaFontanaErrepinet

you can try the newest US-L firmware

**Comment by joBr99** [comment]
There's now an addional value above the home icon.

And the speed value is now evaluated as HA Template allowing to base it on calculations.

https://docs.nspanel.pky.eu/card-power/

![image](https://user-images.githubusercontent.com/29555657/212476554-1820a299-592c-4663-9653-1bdb34aaabd4.png)

**Comment by blubbel42** [comment]
Thx for this, the second information in the center is great!
As you were asking for working examples for speed-config: I'm using this:

```
            speed: >-
                {% if states('sensor.battery_feed')| float > 1500  %}
                  3
                {% elif 1500 > states('sensor.battery_feed')| float > 500 %}
                  2
                {% elif 500 > states('sensor.battery_feed')| float > 0 %}
                  1
                {% elif -500 < states('sensor.battery_feed')| float < 0 %}
                  -1
                {% elif -1500 < states('sensor.battery_feed')| float < -500 %}
                  -2
                {% elif states('sensor.battery_feed')| float < -1500 %}
                  -3
                {% else %}
                  0
                {% endif %}
```
It is a bit crude, but working really fine and for any of the sensors used.
Greetings, Blubbel

**Comment by joBr99** [comment]
This is a good starting point :)

I was thinking about something to which set's different energy entities into relation, but maybe I just thought to complicated :)

**Comment by blubbel42** [comment]
I'm just not that good with templates. But I figured it is better than randomness ans smarter people will follow with better ideas.  What's not good about my example is that it is using fixed values. Perhaps one could use text_inputs for energyflows "small" "medium" "big". Then the templates would not have to be updatet just because you got bigger solar panels and therefore more potential solar influx

**Comment by magnusoverli** [comment]
I have another approach to calculating the speed. Maybe someone gets inspired... ;-)
```
{% set entity_power = states('sensor.hvac_sensor_active_power') |float | round(3)%}
{% set total_power = states('sensor.ams_power_active') | float | round(3) %}
{% set entity_usage = (entity_power / total_power * 3) | float | round(3) %}
{{ (entity_usage | round(1)) * -1 }}
```
This calculates the power of a device as a fraction of the total power draw in my house, and converts it to a scale of -3 to 0.
If you prefer the dot moving towards the centre of the card (scale of 0 to 3), just drop the invert on the last line:
```
{{ entity_usage | round(1) }}
```

**Comment by magnusoverli** [comment]
For future use....
The speed setting will at some point be changed to accept levels from -100 to 100.
An updated template:
```
              {% set entity_power = states('sensor.appliance_water_heater_power') |float | round(3)%}
              {% set total_power = states('sensor.ams_power_active') | float | round(3) %}
              {% set entity_usage = (entity_power / total_power * 100) | float %}
              {{ (entity_usage | round()) * -1 }}
```

**Comment by TheGroundZero** [comment]
Some comments on the [documentation](https://docs.nspanel.pky.eu/card-power/).

It would be useful to have this info about the location of the entities available in the docs:
![Power Card element locations](https://user-images.githubusercontent.com/29555657/189524300-ddc73c0d-5a37-4284-91e2-65727f67916d.png)

The example config in the docs also doesn't appear to match the screenshots? I count 7 entities and only 5 elements.
Using the same entity repeatedly also doesn't help in figuring out the locations of each entity.
```yaml
    cards:
      - type: cardPower
        title: Power Test
        entities:
          - entity: sensor.today_energy
          - entity: delete
          - entity: sensor.today_energy
            speed: 30
          - entity: sensor.today_energy
            speed: -10
          - entity: sensor.today_energy
            speed: -20
          - entity: sensor.today_energy
            speed: -30
          - entity: sensor.today_energy
            speed: 10
          - entity: sensor.today_energy
            speed: 10
```
![Docs example](https://user-images.githubusercontent.com/2406013/215738485-866ef215-58de-4ee2-be36-784d9fe81631.png)


Finally, there's no info on the `delete` entity in the example docs?

**Comment by joBr99** [comment]
you are right; the example should match the picture, adjusted the example

**Comment by joBr99** [comment]
well, @illuzn provided that part of the documentation in #730

However isn't that the same thing?

**Comment by illuzn** [comment]
Here's my example config... it pretty much uses every single available option. Feel free to include this in as an example in the docs if you would find that helpful.

````yaml
- type: cardPower
  title: Home Power
  navItem1:
    entity: navigate.default
    icon: mdi:arrow-up-bold
    color: [255, 255, 255]
  navItem2:
    entity: navigate.DailyPower
    icon: mdi:currency-usd
    color: [255, 255, 50]
  entities:
    - entity: sensor.house_consumption
      icon: mdi:home-lightning-bolt
    - entity: sensor.battery_state_of_charge
    - entity: sensor.pv_power
      icon: mdi:solar-panel
      color: [255, 255, 50]
      speed: >-
        {% set entity_power = states('sensor.pv_power') |float | round(3)%}
        {% set total_power = (states('sensor.pv_power') | float | round(3) + states('sensor.battery_power_consumption') | float | round(3) + states('sensor.meter_power_import') | float | round(3)) %}
        {% set entity_usage = (entity_power / total_power * 100) | float %}
        {{ (entity_usage | round()) * -1 }}
    - entity: sensor.meter_power_import
      icon: mdi:transmission-tower-import
      color: [255, 50, 50]
      speed: >-
        {% set entity_power = states('sensor.meter_power_import') |float | round(3)%}
        {% set total_power = (states('sensor.pv_power') | float | round(3) + states('sensor.battery_power_consumption') | float | round(3) + states('sensor.meter_power_import') | float | round(3)) %}
        {% set entity_usage = (entity_power / total_power * 100) | float %}
        {{ (entity_usage | round()) * -1 }}
    - entity: sensor.meter_power_export
      icon: mdi:transmission-tower-export
      color: [50, 50, 255]
      speed: >-
        {% set entity_power = states('sensor.meter_power_export') |float | round(3)%}
        {% set total_power = (states('sensor.pv_power') | float | round(3) + states('sensor.battery_power_consumption') | float | round(3) + states('sensor.meter_power_import') | float | round(3)) %}
        {% set entity_usage = (entity_power / total_power * 100) | float %}
        {{ (entity_usage | round()) }}
    - entity: sensor.battery_power_charge
      icon: mdi:battery-charging
      color: [255, 255, 50]
      speed: >-
        {% set entity_power = states('sensor.battery_power_charge') |float | round(3)%}
        {% set total_power = (states('sensor.pv_power') | float | round(3) + states('sensor.battery_power_consumption') | float | round(3) + states('sensor.meter_power_import') | float | round(3)) %}
        {% set entity_usage = (entity_power / total_power * 100) | float %}
        {{ (entity_usage | round()) * -1 }}
    - entity: sensor.battery_power_consumption
      icon: mdi:battery-arrow-down
      color: [255, 50, 50]
      speed: >-
        {% set entity_power = states('sensor.battery_power_consumption') |float | round(3)%}
        {% set total_power = (states('sensor.pv_power') | float | round(3) + states('sensor.battery_power_consumption') | float | round(3) + states('sensor.meter_power_import') | float | round(3)) %}
        {% set entity_usage = (entity_power / total_power * 100) | float %}
        {{ (entity_usage | round()) }}
````
and the hidden page:
````yaml
hiddenCards:
- type: cardPower
  title: Daily Power
  entities:
    - entity: sensor.todays_home_energy_consumption
      icon: mdi:home-lightning-bolt
    - entity: sensor.battery_state_of_charge
    - entity: sensor.todays_pv_generated
      icon: mdi:solar-panel
      color: [255, 255, 50]
      speed: >-
        {% set entity_power = states('sensor.todays_pv_generated') |float | round(3)%}
        {% set total_power = (states('sensor.todays_pv_generated') | float | round(3) + states('sensor.todays_battery_consumption') | float | round(3) + states('sensor.todays_energy_import') | float | round(3)) %}
        {% set entity_usage = (entity_power / total_power * 100) | float %}
        {{ (entity_usage | round()) * -1 }}
    - entity: sensor.todays_energy_import
      icon: mdi:transmission-tower-import
      color: [255, 50, 50]
      speed: >-
        {% set entity_power = states('sensor.todays_energy_import') |float | round(3)%}
        {% set total_power = (states('sensor.todays_pv_generated') | float | round(3) + states('sensor.todays_battery_consumption') | float | round(3) + states('sensor.todays_energy_import') | float | round(3)) %}
        {% set entity_usage = (entity_power / total_power * 100) | float %}
        {{ (entity_usage | round()) * -1 }}
    - entity: sensor.todays_energy_export
      icon: mdi:transmission-tower-export
      color: [50, 50, 255]
      speed: >-
        {% set entity_power = states('sensor.todays_energy_export') |float | round(3)%}
        {% set total_power = (states('sensor.todays_pv_generated') | float | round(3) + states('sensor.todays_battery_consumption') | float | round(3) + states('sensor.todays_energy_import') | float | round(3)) %}
        {% set entity_usage = (entity_power / total_power * 100) | float %}
        {{ (entity_usage | round()) }}
    - entity: sensor.todays_battery_charge
      icon: mdi:battery-charging
      color: [255, 255, 50]
      speed: >-
        {% set entity_power = states('sensor.battery_energy_charge') |float | round(3)%}
        {% set total_power = (states('sensor.todays_pv_generated') | float | round(3) + states('sensor.todays_battery_consumption') | float | round(3) + states('sensor.todays_energy_import') | float | round(3)) %}
        {% set entity_usage = (entity_power / total_power * 100) | float %}
        {{ (entity_usage | round()) * -1 }}
    - entity: sensor.todays_battery_consumption
      icon: mdi:battery-arrow-down
      color: [255, 50, 50]
      speed: >-
        {% set entity_power = states('sensor.battery_energy_consumption') |float | round(3)%}
        {% set total_power = (states('sensor.todays_pv_generated') | float | round(3) + states('sensor.todays_battery_consumption') | float | round(3) + states('sensor.todays_energy_import') | float | round(3)) %}
        {% set entity_usage = (entity_power / total_power * 100) | float %}
        {{ (entity_usage | round()) }}
  key: DailyPower
````
For the speeds it makes sense to have the total as either the total energy/ power consumed or total energy/ power produced then each speed derived from that.
