### ISSUE TITLE
[BUG] StatusIcon1 & StatusIcon2 not working

### ISSUE THREAD

**Issue by sn00zerman** [joBr99/nspanel-lovelace-ui#376]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Color-values for on/off for StatusIcon1 & 2 not working.

When I define the on/off values for the color, I only get the the date time and date on screen, in white,
weather-values are not shown, also the statusIcon 1 & 2 are not shown.
Furthermore, other cards do work fine.
Whenever I put the on/off icon colors, in comment, everything works fine.
on/off state for the icons itself works fine (they switch, when I push the buttons)
When using simple color: (without on/off state), that works also fine.
The entities them self are correct, I can use them as button-cards within HA, and hear the relais clicking.
(and when pressing the actual buttons, the state is picked up correctly in HA)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml:
```
  apps.yaml here:

---
nspanel-01:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  #------------------------------------------------------------
  #--- General config + first page (time/date/weather       ---
  #------------------------------------------------------------
  config:
    panelRecvTopic: "tele/tasmota_mqtt_01/RESULT"
    panelSendTopic: "cmnd/tasmota_mqtt_01/CustomSend"
    sleepTimeout: 15
    sleepBrightness: 5
    screenBrightness: 25
    screensaver:
      entity: weather.huis
      doubleTapToUnlock: True
      theme:
        autoWeather: false
        time: [128,128,255]
        background: [0,0,0]
        date: [255,255,0]
      statusIcon1: 
        entity: light.nspanel_01
        icon: 
            "on": mdi:thermometer
            "off": mdi:lightbulb
        color:
            "on": [255,0,0]
            "off": [0,255,0]
      statusIcon2: 
        entity: light.nspanel_01_2
        icon: mdi:heart
        color:
            "on": [255,0,0]
            "off": [0,255,0]

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
No errors in the log

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
I expect the icons to change color, with the "on" / "off" definitions,
as it does with the icons itself with the "on" / "off" definitions.

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU, latest firmware
