### ISSUE TITLE
[Feature Request] weatherOverrideForecast color

### ISSUE THREAD

**Issue by jrspowers** [joBr99/nspanel-lovelace-ui#382]
### FEATURE DESCRIPTION
would it be possible to make the weather Override Forecast color change through the state like this see example that would be really nice if this would work ?

### ADDITIONAL CONTEXT
```yaml
weatherOverrideForecast2:
entity: sensor.tomorrow_io_slaapkamer_tree_pollen_index
name: BomenP
icon: mdi:tree
color: 
    "unavailable": [255,0,0]
    "none": [128, 128, 128]
    "very_low": [0, 128, 0]
    "low": [241, 196, 15]
    "medium": [243, 156, 18]
    "high": [231, 76, 60]
    "very_high": [199, 0, 8]
```

### PANEL / FIRMWARE VERION
Please add the Panel/Firmware Version you are using (EU)
