### ISSUE TITLE
[BUG] RTL Languages not showing as expected

### ISSUE THREAD

**Issue by AviFix** [joBr99/nspanel-lovelace-ui#389]
### PROBLEM DESCRIPTION
When setting the local to a right to left languages such as Hebrew or Arabic, the text is shown from left to right

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml:
```
  apps.yaml here:
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/xxxx/RESULT"
    panelSendTopic: "cmnd/xxxx/CustomSend"
    sleepTimeout: 10
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "he_IL"
    screensaver:
      entity: weather.k3ll3r
    cards:
      - type: cardEntities
        entities:
          - entity: light.aaa
          - entity: light.bbb
        title: Front yard
      - type: cardGrid
        entities:
          - entity: switch.example_item
          - entity: light.example_item
        title: Example 2

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
set local to "he_IL"

### EXPECTED BEHAVIOUR
text will appear from right to left

### SCREENSHOTS
![telegram-cloud-photo-size-4-6017107955037615892-y](https://user-images.githubusercontent.com/3835504/183293532-ed56e055-5dcc-43a3-a54c-b580b96fbf69.jpg)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
EU Tasmota 12.0.2 by Theo Arends
