### ISSUE TITLE
[Help] Play local mp3 files in mediaCard

### ISSUE THREAD

**Issue by AviFix** [joBr99/nspanel-lovelace-ui#390]
### PROBLEM DESCRIPTION

My main use of media, is the local media
I was able to configure the mediaCard to play music from a specific source, but I'm trying to find a way to be able to browse through the local media folders and select a specific mp3 file to play.

Is there any way to do so?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:

- [ ] Provide your appdaemon.yaml: 
```

```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:

nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/xxxx/RESULT"
    panelSendTopic: "cmnd/xxxx/CustomSend"
    sleepTimeout: 10
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "he_IL"
    screensaver:
      entity: weather.k3ll3r
    cards:
      - type: cardMedia
        entity: media_player.ytube_music_player   

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```


```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_
