### ISSUE TITLE
[Feature Request] Alarm Control as cardEntities or cardGrid

### ISSUE THREAD

**Issue by WhistleMaster** [joBr99/nspanel-lovelace-ui#398]
Hi ! 

Thanks for the great work on that project, it's working really well !

### FEATURE DESCRIPTION
It would be a nice feature to be able to display an alarm control in a cardEntities or a cardGrid view, and clicking on it would display the cardAlarm as a popup. More or less as displaying a cover entity and when clicking on it, you have the position and so on.

### ADDITIONAL CONTEXT
N/A

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
there is already a feature request for an alarm clock #378

**Comment by WhistleMaster** [comment]
I think there is a misunderstanding, I talking about a security alarm, not an alarm clock 😅

**Comment by WhistleMaster** [comment]
What I would like to achieve is, as an example:

![card-entities](https://user-images.githubusercontent.com/1544568/184469345-cb691032-d5c8-4a33-bad1-2db2e34f79da.png)

```
    cards:
      - type: cardEntities
        title: Test Entities Card
        entities:
          - entity: light.bed_light
          - entity: switch.decorative_lights
          - entity: cover.hall_window
          - entity: alarm_control_panel.alarmo
```

or:

![card-grid](https://user-images.githubusercontent.com/1544568/184469346-cc92fed8-d04c-417f-bd7b-d0faabfef815.png)

```
    cards:
      - type: cardGrid
        title: Test Grid Card
        entities:
          - entity: alarm_control_panel.alarmo
          - entity: switch.decorative_lights
          - entity: sensor.outside_temperature
            name: Outside Temp
          - entity: sensor.carbon_monoxide
          - entity: light.entrance_color_white_lights
            name: Entrance
          - entity: light.office_rgbw_lights
            name: Office RGBW
            icon: mdi:office-building
```

And clicking on the entity would popup the cardAlarm:
![card-alarm](https://user-images.githubusercontent.com/1544568/184469369-fced6ae3-93fc-41ee-b1c8-18f0e15aac85.png)
