### ISSUE TITLE
[Feature Request] Assign cards to hardware buttons

### ISSUE THREAD

**Issue by Grrzzz** [joBr99/nspanel-lovelace-ui#409]
### FEATURE DESCRIPTION
Please add an option to assign cards to hardware buttons 1 & 2. The iobroker implementation supports this, and it would be great to have this feature for home assistant as well to quickly open up "your facorite shortcuts". 

You are almost there, just 2 things to left to do:
1. extend configuration, see below
2. Add new custom events to react to (-> https://docs.nspanel.pky.eu/phys-btn)

### ADDITIONAL CONTEXT
compare functionality of entity: navigate.cardXXX_XXX
make that:
```
nspanel:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:  
    button1: navigate.cardEntities_button1Page
    button2: navigate.cardEntities_button2Page
   ....

```
### PANEL / FIRMWARE VERION
doesn't matter
