### ISSUE TITLE
[BUG] Time-based brightness and sleepTracking

### ISSUE THREAD

**Issue by smarttv193** [joBr99/nspanel-lovelace-ui#425]
### PROBLEM DESCRIPTION
Hi, I have configured time-based brightness and sleepTracking using configuration below.
However, the screen brightness is not set to 10 when person.test changed state from 'not_home' to 'home' after 7:00am

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml:
```
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:59:00"
        value: 0
    sleepTracking: person.test


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
Please refer to brightness and different person.test state result from 6:30am to 7:10am in table below. 

time      | person.test state | screen brightness
6:30am | not_home           | 0
7:05am | not_home           | 0
7:10am | home                  | 0

### EXPECTED BEHAVIOUR
Screen brightness should be 10 when person.test is 'home' at 7:10am

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
Panel EU
