### ISSUE TITLE
[Feature Request] Ability for icon to take state from secondary entity

### ISSUE THREAD

**Issue by magnusoverli** [joBr99/nspanel-lovelace-ui#427]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
Visualizing the current state (on/off) for any entity is great for these displays, but some entities don't have a state. For example the helper buttons in HA. They are stateless.
It would be nice if an icon can take the state of another entity.
### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
Doing that in the config of the panel sounds like this isn't solving the problem in the first place and using a workaround instead. Wound't be a solution better that also works in the HomeAssistant's UI?

Take this as an example that I have in my homeassistant configuration.yaml

There are two scripts that are executed based on the state, the state is determined though a template based on the energy usage.

```
switch:
  - platform: template
    switches:
      beamer_setup:
        friendly_name: "Beamer Setup"
        value_template: "{{ (int(states('sensor.beamer_steckdose_energy_power_1')) > 3) }}"
        turn_on:
          service: script.beamer_setup_an
        turn_off:
          service: script.beamer_setup_aus
```
