### ISSUE TITLE
[Feature Request] Home button on hidden cards

### ISSUE THREAD

**Issue by ujvarigergo1** [joBr99/nspanel-lovelace-ui#438]
### FEATURE DESCRIPTION
_I have many hidden cards organised to a menu (eg.: Home -> Media players -> Spotify , or Home -> Switches -> Lights -> Wall light). It works great but it requires a lot of tap to navigate between pages. It would be easier if there would be a home button on the top right corner of a hidden card which would navigate back to the default or an optional page._

### ADDITIONAL CONTEXT
_._

### PANEL / FIRMWARE VERION
_EU, v3.3.1_

**Comment by joBr99** [comment]
implemented in current development version


just add `    homeButton: True` to your config
```
  config:
    panelRecvTopic: "tele/tasmota_nspdebugtest/RESULT"
    panelSendTopic: "cmnd/tasmota_nspdebugtest/CustomSend"
    homeButton: True
```
the button will take you to the top level card you started on

![image](https://user-images.githubusercontent.com/29555657/206728148-fe71fc9b-b6b1-4256-bb3b-f67a2fffa961.png)

**Comment by Censored3** [comment]
Looking good! Thanks!!

**Comment by esdcmc** [comment]
no longer works on rel. 3.8.1

**Comment by joBr99** [comment]
With 3.8 you can overwrite the navigation buttons with any entity:

```
    cards:
      - type: cardGrid
        title: Home
        key: home
        entities:
          - entity: light.bad

    hiddenCards:
      - type: cardGrid
        title: Wohnzimmer
        navItem2:
          entity: navigate.home
          icon: mdi:home
        entities:
          - entity: light.kitchen
```
