### ISSUE TITLE
[BUG] Climate component translation (pl-PL)

### ISSUE THREAD

**Issue by sledziu1** [joBr99/nspanel-lovelace-ui#443]
### PROBLEM DESCRIPTION
Climate control uses too descriptive/too long text for Mode in Polish language which is wrongly displayed (overlap buttons).

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml:
```
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel/RESULT"
    panelSendTopic: "cmnd/nspanel/CustomSend"
    locale: "pl_PL"
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 8
      - time: "23:00:00"
        value: 0
    screensaver:
      entity: weather.dom
      theme:
        autoWeather: true
    cards:
      - type: cardThermo
        title: Klimatyzacja
        entity: climate.1ec15ead
```
- [x] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log during your issue/bug occurs:
```
N/A
```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Set pl-PL language and open Climate control

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
"Tryb" instead of "Tryb pracy"

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._
![image](https://user-images.githubusercontent.com/59708143/188680077-32b30d5c-1ac1-4bfb-b8b6-3c34a7bca26f.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
N/A

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU
