### ISSUE TITLE
[Feature Request] display icon for sensors on cardGrid in case icon overrides are specified

### ISSUE THREAD

**Issue by diginfo** [joBr99/nspanel-lovelace-ui#447]
### FEATURE DESCRIPTION
Enhancement - User Defined Icon States

### ADDITIONAL CONTEXT
It would be nice to be able to set your own icon states instead of just on and off, and have more than 2

```
          - entity: sensor.pac_wiser_living_heating
            name: Status
            icon:
              "Boost": timer-plus
              "Off": radiator-off
              "Time": calendar-clock
```

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
on and off is just the example in the docs it works with any states

**Comment by diginfo** [comment]
I just tried the example above, and it does not appear to work ?

**Comment by joBr99** [comment]
take a look at the state of your sensor in HA developers tools, it it really "Boost" or "Time" with capital letters

**Comment by diginfo** [comment]
Initially the sensor template has indents in the if - else expression and this adds whitespaces to the state keyword.

so I fixed them with:

```
        {%- if states("climate.wiser_living_room") == 'auto' -%}
          Timed
        {%- elif state_attr('climate.wiser_living_room', 'is_boosted') == true -%}
          Boost
        {%- else -%}
          Off
        {% endif %}
```
But despite it showing the correct keyword it is still displaying the text rather than the icons.

```
          - entity: sensor.pac_wiser_living_heating
            name: Status
            icon:
              "Boost": timer-plus
              "Off": radiator-off
              "Timed": calendar-clock
```
