### ISSUE TITLE
[Feature Request] - override state on service call btn

### ISSUE THREAD

**Issue by diginfo** [joBr99/nspanel-lovelace-ui#452]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
When I press a sensor, I see the following output in the APPDAEMON log, so I know the interface has detected the press.

Would it be possible to allow this press to call a service, as for me this would be extremely useful.

This means I can press the sensor icon which is displaying a sensor value, and call a service which which would then modify the source of the sensor value.

```
2022-09-10 05:40:49.856489 INFO nspanel-4c18: MQTT callback for: {'topic': 'tele/nspanel-4c18/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,sensor.pac_wiser_living_temp_set,button"}'}
2022-09-10 05:40:49.857771 INFO nspanel-4c18: Received Message from Screen: event,buttonPress2,sensor.pac_wiser_living_temp_set,button
2022-09-10 05:40:49.858522 INFO nspanel-4c18: Button Press Event; entity_id: sensor.pac_wiser_living_temp_set; button_type: button; value: None 
```

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
```
          - entity: service.light.turn_on
            data:
              entity_id: light.schreibtischlampe
              color_name: "green"
            status: sensor.server_energy_power
            name: test
```

**Comment by diginfo** [comment]
Thanks, so this needs the dev version to work ?

**Comment by joBr99** [comment]
yep

**Comment by diginfo** [comment]
Excellent, tested and working - thank you 👍

**Comment by diginfo** [comment]
Ahh, my mistake / oversight, is it also possible to call climate as well as service:

```
          - entity: climate.set_temperature
            data:
              temperature: 25
            target:
              entity_id: climate.wiser_living_room
            status: sensor.pac_wiser_living_temp_set
            name: Room Temp

```

**Comment by joBr99** [comment]
yeah why not? you can call all services

**Comment by diginfo** [comment]
ok, cos the above produces "Not Found check".
maybe I will have to create a script and call the script to call the climate

**Comment by joBr99** [comment]
well it has to be

 - entity: service.climate.set_temperature

**Comment by diginfo** [comment]
yes, just spotted that, thanks

**Comment by cornholio1234** [comment]
First: Thanks for your awesome work! Works pretty great.
I just tried to call a service like shown here but unfortunately I got this response:

2022-11-12 20:08:29.318867 INFO nspanel-1: Button Press Event; entity_id: uuid.39919c76d9ce43e2a7493dec09eccee8; button_type: button; value: None 
2022-11-12 20:08:29.336146 WARNING HASS: Error calling Home Assistant service default/light/turn_on
2022-11-12 20:08:29.336504 WARNING HASS: Code: 400, error: 400: Bad Request

Config looks just like this:

          - entity: service.light.turn_on
            data: {}
            target:
              entity_id: light.029_dim_luftraum_2_9

Can you give me a hint what I am doing wrong? Just updated HACS to main and flashed the newest TTST...
I am using a US model, maybe thats the reason?

**Comment by joBr99** [comment]
try this config:

```
      - entity: service.light.turn_on
        data:
          entity_id: light.schreibtischlampe
```

**Comment by cornholio1234** [comment]
Hi, 

now I get following responst:
2022-11-12 20:19:59.615532 INFO nspanel-1: Received Message from Screen: event,buttonPress2,uuid.6277324f0e2d47e0a3b432433a48235b,button
2022-11-12 20:19:59.624012 INFO nspanel-1: Button Press Event; entity_id: uuid.6277324f0e2d47e0a3b432433a48235b; button_type: button; value: None 
But light is not turning on :-).

Nevertheless, this is just my test balloon for following task:
          - entity: service.media_player.play_media
            data:
              media_content_id: spotify:playlist:37i9dQZF1E8OWvvO0TIRXM
              media_content_type: spotify://playlist
            target:
              entity_id: media_player.spotify_de
            name: Test

any hope to get this running for making a playlist selection page?

**Comment by joBr99** [comment]
```
          - entity: service.media_player.play_media
            data:
              media_content_id: spotify:playlist:37i9dQZF1E8OWvvO0TIRXM
              media_content_type: spotify://playlist
              entity_id: media_player.spotify_mes_de
```

**Comment by cornholio1234** [comment]
Hi Jo,

thanks a lot. Works like a charm!
Is this the right place to ask how to use the "mediacontrol" config key for the Media Card?
Id like to put a logic on it opening the page with the playlists just created above.

Have a great day!

**Comment by joBr99** [comment]
you need to configure it to `navigate.cardMedia_key`

https://docs.nspanel.pky.eu/subpages/?h=navigate

**Comment by cornholio1234** [comment]
I love it! 

Just for some humble wanderer who might come across:
```
cards:
  - type: cardMedia
          entity: media_player.spotify_mes_de
          mediaControl: navigate.cardEntities_Playlists
        - type: cardEntities 
          title: Playlists
          key: Playlists
          entities:
            - entity: service.media_player.play_media
              data:
                media_content_id: spotify:playlist:37i9dQZF1E8OWvvO0TIRXM
                media_content_type: spotify://playlist
                entity_id: media_player.spotify_mes_de
            name: Playlist Wellerman
```
