### ISSUE TITLE
[Feature Request] Text row for Hardwarebuttons

### ISSUE THREAD

**Issue by fugazzy** [joBr99/nspanel-lovelace-ui#455]
### FEATURE DESCRIPTION
A row for descriptive text for the Funktion available on the two hardwarebuttons

### ADDITIONAL CONTEXT
Maybe also adaptive to different situations with different funktions on the buttons. 

### PANEL / FIRMWARE VERION
All versions

**Comment by joBr99** [comment]
There is no space for an additional text line.

You can configure statusIcon1 and 2 on the screensaver with speaking icons.

````
  config:
    screensaver:
        entity: weather.k3ll3r
        statusIcon1:
          entity: switch.example_item
        statusIcon2:
           entity: binary_sensor.example_item
````

https://docs.nspanel.pky.eu/config-screensaver/?h=statusicon#possible-configuration-values-for-screensaver-theme-config

https://htmlpreview.github.io/?https://github.com/joBr99/nspanel-lovelace-ui/blob/main/HMI/icon-cheatsheet.html
