### ISSUE TITLE
[BUG]  Screensaver notification area distortion.

### ISSUE THREAD

**Issue by pro1212123** [joBr99/nspanel-lovelace-ui#482]
### PROBLEM DESCRIPTION
_if weatherOverrideForecast updates while notification is displayed, icons and values go over notification making a mess_

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:


panel-gost:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    model: us-l
    panelRecvTopic: "tele/panel-gost/RESULT"
    panelSendTopic: "cmnd/panel-gost/CustomSend"
    updateMode: "manual"
    sleepTimeout: 600
    sleepBrightness:
      - time: "6:00:00"
        value: 2
      - time: "7:00:00"
        value: 4
      - time: "8:00:00"
        value: 6
      - time: "9:00:00"
        value: 8
      - time: "10:00:00"
        value: 10
      - time: "11:00:00"
        value: 12
      - time: "12:00:00"
        value: 14
      - time: "13:00:00"
        value: 16
      - time: "14:00:00"
        value: 18
      - time: "15:00:00"
        value: 20
      - time: "16:00:00"
        value: 18
      - time: "17:00:00"
        value: 16
      - time: "18:00:00"
        value: 14
      - time: "19:00:00"
        value: 12
      - time: "20:00:00"
        value: 10
      - time: "21:00:00"
        value: 8
      - time: "22:00:00"
        value: 6
      - time: "23:00:00"
        value: 4
      - time: "0:00:00"
        value: 2
      - time: "1:00:00"
        value: 0
    locale: "ru_RU"
    sleepTracking: person.denis
    sleepOverride:
      entity: light.gost_panel_brightness
      brightness: 50
    timeFormat: "%H:%M"
    dateFormatBabel: "EEE, d MMMM"
    dateAdditionalTemplate: ", {{ states('sensor.fedorovskoye_forecast_cloud_coverage') }}%"
    timeAdditionalTemplate: "{{ states('sensor.24hr_kwh') }}кВтч, {{ states('sensor.24hr_rub') }}руб."
    screensaver:
      entity: weather.fedorovskoye
      statusIcon1:
        entity: light.gr_gostinnaya_1_2_3_1d_2d_3d
        icon: mdi:home-lightbulb
        color: 
            "off": [128, 128, 128]
            "unavailable": [128, 128, 128]
            "on": [255, 255, 25]
      statusIcon2:
        entity: light.gr_nar_all
        icon: mdi:leaf
        color: 
            "off": [128, 128, 128]
            "on": [25, 255, 25]
      defaultBackgroundColor: black
      theme: 
        #background: [255, 255, 255]
        #time: [127, 153, 0]
        #timeAMPM: [127, 153, 0]
        #date: [127, 153, 0]
        #tMainIcon: [127, 153, 0]
        #tMainText: [127, 153, 0]
        #tForecast1: [127, 153, 0]
        #tForecast2: [127, 153, 0]
        #tForecast3: [127, 153, 0]
        #tForecast4: [127, 153, 0]
        #tF1Icon: [127, 153, 0]
        #tF2Icon: [127, 153, 0]
        #tF3Icon: [127, 153, 0]
        #tF4Icon: [127, 153, 0]
        #tForecast1Val: [127, 153, 0]
        #tForecast2Val: [127, 153, 0]
        #tForecast3Val: [127, 153, 0]
        #tForecast4Val: [127, 153, 0]
        #bar: [127, 153, 0]
        #tMRIcon: [127, 153, 0]
        #tMR: [127, 153, 0]
        #tTimeAdd: [106, 128, 0]
        autoWeather: true
      weatherOverrideForecast1:
        entity: sensor.fedorovskoye_wind_speed
        name: " "
        icon: weather-windy
      weatherOverrideForecast2:
        entity: sensor.panel_entry_temp
        name: " "
        icon: thermometer
      weatherOverrideForecast3:
        entity: sensor.house_power_consumption
        name: " "
        icon: mdi:transmission-tower-export
      weatherOverrideForecast4:
        entity: switch.gas_boiler
        name: " "
        icon:
            "on": mdi:fire-circle
            "off": mdi:fire-off
        color: 
            "off": [128, 128, 128]
            "on": [255, 255, 25]
        
        
        
    cards:
      - type: cardGrid
        title: ""
        entities:
          - entity: navigate.cardGrid_lights
            name: "Освещение"
            status: light.gr_1et_2et
            icon:
                "on": mdi:home-lightbulb
                "off": mdi:home-lightbulb-outline
            color: 
                "off": [128, 128, 128]
                "on": [255, 255, 25]
          - entity: navigate.cardMedia_media
            name: "Мультимедиа"
            status: media_player.clementine_remote
            icon:
                "playing": mdi:motion-play
                "paused": mdi:motion-pause
            color: 
                "paused": [128, 128, 128]
                "playing": [255, 255, 25]
          - entity: navigate.cardThermo_climate
            name: "Климат"
            status: switch.gas_boiler
            icon:
                "on": mdi:home-thermometer
                "off": mdi:home-thermometer-outline
            color: 
                "off": [128, 128, 128]
                "on": [255, 255, 25]
          - entity: navigate.cardGrid_sec
            name: "Охрана"
            status: alarm_control_panel.schaste
            icon:
                "disarmed": mdi:home-lock
                "armed_home": mdi:shield-home
                "armed_away": mdi:shield-lock-outline
                "arming": mdi:home-lock
            color: 
                "disarmed": [128, 128, 128]
                "armed_home": [255, 255, 25]
                "armed_away": [255, 25, 25]
                "arming": [255, 25, 25]
          - entity: navigate.cardGrid_it
            name: "Сеть"
            icon: mdi:home-automation
          - entity: navigate.cardGrid_users
            name: "Пользователи"
            icon: mdi:home-account
    hiddenCards:
      - type: cardGrid
        title: Освещение
        entities:

          - entity: navigate.cardGrid_kitc
            name: "Кухня"
            icon: mdi:view-dashboard-variant-outline
            
          - entity: light.gr_gostinnaya_1_2_3_1d_2d_3d
            name: "Гостинная"
            icon:
                "on": mdi:lightbulb-group
                "off": mdi:lightbulb-group-outline
                
          - entity: navigate.cardEntities_lights_dimmers
            name: "Яркость"
            status: light.gr_gostinnaia_dimm
            icon: mdi:lightbulb-night-outline
            
          - entity: light.gostinnaya1_1
            name: ""
            icon:
                "on": lightbulb-variant
                "off": lightbulb-variant-outline
                "unavailable": lightbulb-off-outline
            color:
                "on": [255, 255, 0]
                "off": [100, 100, 255]
                "unavailable": [75, 75, 75]
          - entity: light.gostinnaya2_1
            name: ""
            icon:
                "on": lightbulb-variant
                "off": lightbulb-variant-outline
                "unavailable": lightbulb-off-outline
            color:
                "on": [255, 255, 0]
                "off": [100, 100, 255]
                "unavailable": [75, 75, 75]
          - entity: light.gostinnaya3_1
            name: ""
            icon:
                "on": lightbulb-variant
                "off": lightbulb-variant-outline
                "unavailable": lightbulb-off-outline
            color:
                "on": [255, 255, 0]
                "off": [100, 100, 255]
                "unavailable": [75, 75, 75]
        key: lights
      - type: cardEntities
        title: Яркость
        entities:
          - entity: light.gr_gostinnaia_dimm
            name: ""
            color_mode: brightness
          - entity: light.gostinnaya1_2_dimmer
            name: ""
            color_mode: brightness
          - entity: light.gostinnaya2_2_dimmer
            name: ""
            color_mode: brightness
          - entity: light.gostinnaya3_2_dimmer
            name: ""
            color_mode: brightness
        key: lights_dimmers
      - type: cardGrid
        title: Контроль освещения
        entities:
          - entity: delete
          - entity: delete
          - entity: delete
          - entity: light.koridor_1
            icon:
                "on": mdi:numeric-1-circle-outline
                "off": mdi:numeric-1-circle-outline
          - entity: light.koridor_1
            icon:
                "on": mdi:numeric-2-circle-outline
                "off": mdi:numeric-2-circle-outline
          - entity: light.koridor_2
            icon:
                "on": mdi:numeric-3-circle-outline
                "off": mdi:numeric-3-circle-outline
        key: flights
      - type: cardEntities
        title: Передняя камера
        entities:
          - entity: button.onvif_front_01_reboot
            name: "Перезагрузка камеры"
            icon: mdi:restart
          - entity: switch.front_detect
            name: "Обнаружение обьектов"
            icon:
                "on": mdi:motion-sensor-on
                "off": mdi:motion-sensor-off
          - entity: switch.front_recordings
            name: "Записывать видео"
            icon:
                "on": mdi:pause-circle
                "off": mdi:record-rec
          - entity: switch.front_snapshots
            name: "Сохранять фото обьектов"
            icon:
                "on": mdi:camera
                "off": mdi:camera-off
        key: fcam
      - type: cardEntities
        title: Задняя камера
        entities:
          - entity: button.onvif_rear_01_reboot
            name: "Перезагрузка камеры"
            icon: mdi:restart
          - entity: switch.rear_detect
            name: "Обнаружение обьектов"
            icon:
                "on": mdi:motion-sensor-on
                "off": mdi:motion-sensor-off
          - entity: switch.rear_recordings
            name: "Записывать видео"
            icon:
                "on": mdi:pause-circle
                "off": mdi:record-rec
          - entity: switch.rear_snapshots
            name: "Сохранять фото обьектов"
            icon:
                "on": mdi:camera
                "off": mdi:camera-off
        key: rcam
      - type: cardGrid
        title: Пользователи
        entities:
          - entity: input_text.d_lokatsiia
            icon: mdi:face-man
          - entity: sensor.ksa_lx9_detected_activity
            name: " "
            icon:
                "in_vehicle": mdi:camera
                "on_foot": mdi:run
                "on_bicycle": scooter-electric
                "still": mdi:sleep
                "unknown": mdi:account-question
                "walking": mdi:walk
          - entity: sensor.ksa_lx9_battery_level
            name: "% Батарея"
          - entity: input_text.n_lokatsiia
            icon: mdi:face-woman
          - entity: sensor.fig_lx1_detected_activity
            name: " "
            icon:
                "in_vehicle": mdi:camera
                "on_foot": mdi:run
                "on_bicycle": scooter-electric
                "still": mdi:sleep
                "unknown": mdi:account-question
                "walking": mdi:walk
          - entity: sensor.fig_lx1_battery_level
            name: "% Батарея"

        key: users
      - type: cardMedia
        title: Медиа
        entity: media_player.clementine_remote
        key: media
      - type: cardThermo
        entity: climate.tioplyi_pol
        title: Отопление
        key: climate
      - type: cardEntities
        title: Яркость
        entities:
          - entity: delete
          - entity: delete
          - entity: delete
          - entity: delete
        key: dimmers
      - type: cardGrid
        title: Кухня
        entities:
          - entity: delete
          - entity: delete
          - entity: delete
          - entity: delete
          - entity: delete
          - entity: delete
        key: kitc
      - type: cardGrid
        title: Видеонаблюдение
        entities:
          - entity: sensor.v01_server_cpu_used
            name: "% CPU"
          - entity: sensor.v01_server_ram_used_percent
            name: "% RAM"
          - entity: sensor.v01_server_used_percent
            name: "% SSD"
          - entity: sensor.v01_server_acpitz_1_temperature
            name: "Температура"
          - entity: navigate.cardEntities_fcam
            name: "Парковка"
            icon: mdi:car-multiple
          - entity: navigate.cardEntities_rcam
            name: "Двор"
            icon: mdi:flower-tulip
        key: cctv
      - type: cardGrid
        title: Обьекты
        entities:
          - entity: binary_sensor.street_person_motion
            name: "Улица"
            icon:
                "on": mdi:human
                "off": mdi:road-variant
          - entity: binary_sensor.parking_person_motion
            name: "Парковка"
            icon:
                "on": mdi:human
                "off": mdi:car-outline
          - entity: binary_sensor.yard_person_motion
            name: "Двор"
            icon:
                "on": mdi:human
                "off": mdi:flower-outline
          - entity: binary_sensor.street_car_motion
            name: " "
            icon:
                "on": mdi:car
                "off": mdi:road-variant
          - entity: binary_sensor.parking_car_motion
            name: " "
            icon:
                "on": mdi:car
                "off": mdi:car-outline
          - entity: binary_sensor.yard_cat_motion
            name: " "
            icon:
                "on": mdi:cat
                "off": mdi:flower-outline
        key: objects
      - type: cardGrid
        title: Охранная система
        entities:
          - entity: delete
          - entity: navigate.cardGrid_flights
            name: "Освещение"
            status: light.ves_svet
            icon: mdi:home-lightbulb
          - entity: navigate.cardGrid_cctv
            name: "Окна и двери"
            icon: mdi:window-closed-variant
          - entity: navigate.cardAlarm_alarm
            name: "Режим охраны"
            icon: mdi:shield-home
          - entity: navigate.cardGrid_objects
            name: "Обьекты"
            icon: mdi:cctv
          - entity: navigate.cardGrid_cctv
            name: "Настройки"
            icon: mdi:file-video-outline
        key: sec
      - type: cardGrid
        title: Сеть и файлы
        entities:
          - entity: delete
          - entity: delete
          - entity: delete
          - entity: delete
          - entity: switch.r1_port_wlan_guest
            name: "Точка доступа"
            icon: mdi:signal-5g
          - entity: navigate.cardQR_wifi
            name: "Гостевая сеть"
            icon: mdi:wifi
        key: it
      - type: cardQR
        title: Гостевая сеть
        qrCode: "WIFI:S:PR3;T:WPA;P:{{states('input_text.guest_pw')}};;"
        entities:
          - entity: switch.r1_port_wlan_guest
            name: PR3
            icon: mdi:wifi
          - entity: input_text.guest_pw
            name: Ключ
            icon: mdi:key
        key: wifi
      - type: cardAlarm
        title: Охранная система
        entity: alarm_control_panel.schaste
        key: alarm
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:

2022-09-26 13:01:22.048152 INFO panel-gost: Sending MQTT Message: color~0~65535~65535~65535~31728~65535~65535~65535~65535~65535~65535~65535~65535~31727~65535~65535~65535~65535~65535~65535~65535~65535
2022-09-26 13:01:26.336874 INFO panel-gost: Started rendering of page None with type screensaver
2022-09-26 13:01:26.371866 INFO panel-gost: Forecast 1 is overriden with {'entity': 'sensor.fedorovskoye_wind_speed', 'name': ' ', 'icon': 'weather-windy'}
2022-09-26 13:01:26.391647 INFO panel-gost: Forecast 2 is overriden with {'entity': 'sensor.panel_entry_temp', 'name': ' ', 'icon': 'thermometer'}
2022-09-26 13:01:26.411122 INFO panel-gost: Forecast 3 is overriden with {'entity': 'sensor.house_power_consumption', 'name': ' ', 'icon': 'mdi:transmission-tower-export'}
2022-09-26 13:01:26.431687 INFO panel-gost: Forecast 4 is overriden with {'entity': 'switch.gas_boiler', 'name': ' ', 'icon': {'on': 'mdi:fire-circle', 'off': 'mdi:fire-off'}, 'color': {'off': [128, 128, 128], 'on': [255, 255, 25]}}
2022-09-26 13:01:26.468837 INFO panel-gost: Sending MQTT Message: weatherUpdate~���~10.6��C~ ~���~1.8 m/s~ ~���~26.0  ~ ~���~253 W~ ~���~off ~~~���~31727~���~31727
2022-09-26 13:01:26.486169 INFO panel-gost: Sending MQTT Message: color~0~65535~65535~65535~31728~65535~65535~65535~65535~65535~65535~65535~65535~31727~65535~65535~65535~65535~65535~65535~65535~65535
2022-09-26 13:01:39.640734 INFO panel-gost: Started rendering of page None with type screensaver
2022-09-26 13:01:39.670059 INFO panel-gost: Forecast 1 is overriden with {'entity': 'sensor.fedorovskoye_wind_speed', 'name': ' ', 'icon': 'weather-windy'}
2022-09-26 13:01:39.689896 INFO panel-gost: Forecast 2 is overriden with {'entity': 'sensor.panel_entry_temp', 'name': ' ', 'icon': 'thermometer'}
2022-09-26 13:01:39.708517 INFO panel-gost: Forecast 3 is overriden with {'entity': 'sensor.house_power_consumption', 'name': ' ', 'icon': 'mdi:transmission-tower-export'}
2022-09-26 13:01:39.728190 INFO panel-gost: Forecast 4 is overriden with {'entity': 'switch.gas_boiler', 'name': ' ', 'icon': {'on': 'mdi:fire-circle', 'off': 'mdi:fire-off'}, 'color': {'off': [128, 128, 128], 'on': [255, 255, 25]}}
2022-09-26 13:01:39.768007 INFO panel-gost: Sending MQTT Message: weatherUpdate~���~10.6��C~ ~���~1.8 m/s~ ~���~26.0  ~ ~���~255 W~ ~���~off ~~~���~31727~���~31727
2022-09-26 13:01:39.785086 INFO panel-gost: Sending MQTT Message: color~0~65535~65535~65535~31728~65535~65535~65535~65535~65535~65535~65535~65535~31727~65535~65535~65535~65535~65535~65535~65535~65535

### TO REPRODUCE
_set fast updating sensor as weatherOverrideForecast (current energy consumption in my case) and send notification to nspanel_

### EXPECTED BEHAVIOUR
_values of weatherOverrideForecast shouldn't be updated until notification is cleared_

### SCREENSHOTS
notification displayed
<a href="https://ibb.co/7gst1tZ"><img src="https://i.ibb.co/1sFGmGP/photo-2022-09-26-13-06-32-3.jpg" alt="photo-2022-09-26-13-06-32-3" border="0" /></a>

weatherOverrideForecast4 updates
<a href="https://ibb.co/rbyQZw8"><img src="https://i.ibb.co/vszcJjy/photo-2022-09-26-13-06-32-2.jpg" alt="photo-2022-09-26-13-06-32-2" border="0" /></a>

after notification is cleared
<a href="https://ibb.co/jJZ2Hnr"><img src="https://i.ibb.co/HhpsX5H/photo-2022-09-26-13-06-32.jpg" alt="photo-2022-09-26-13-06-32" border="0" /></a>

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_US-L_
