### ISSUE TITLE
[Feature Request] Conditional card or entity

### ISSUE THREAD

**Issue by koffienl** [joBr99/nspanel-lovelace-ui#483]
### FEATURE DESCRIPTION
Make the appearance of a entity (or card) based on the state of an entity

### ADDITIONAL CONTEXT
Would be nice to make some entities optional wether a entity is on or off. 
If this would be to much of a hassle, you could do it with an entire card?

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
Hey, 
take a look at state and state_not config values of entities.

https://docs.nspanel.pky.eu/entities/#possible-configuration-values-for-entities-key

**Comment by koffienl** [comment]
I tried what you suggested, but that is only working for the state of the current entitie.
What I was suggesting is showing the value of a certain sensor based on the state of a other entitie.

**Comment by joBr99** [comment]
I think I'm not getting what you mean.

**Comment by koffienl** [comment]
Let's say I have a switch. When the switch is on I want to see the state of a few sensors. When the switch is off I want to hide these sensors.
Just like https://www.home-assistant.io/dashboards/conditional/

**Comment by joBr99** [comment]
no, something like this is currently not possible

you can only build a page with all open windows or something like that

**Comment by Markus1995** [comment]
> no, something like this is currently not possible
> 
> you can only build a page with all open windows or something like that

Hi,

because you wrote that an page with all open windows is possible.
How can i do that?

Or is it possible to show all open windows in the popup?
Thank for your great work

👍

**Comment by joBr99** [comment]
vstate: "on"` will only display the entity if the state is "on"

```
      - type: cardGrid
        title: Fensterkontakte
        entities:
          - entity: binary_sensor.sensor_bad_contact
            state: "on"
          - entity: binary_sensor.sensor_fenster_links_contact
            state: "on"
          - entity: binary_sensor.sensor_fenster_rechts_contact
            state: "on"
          - entity: binary_sensor.sensor_fenster_terrasse_contact
            state: "on"
          - entity: binary_sensor.0x00158d000451d931_contact
            state: "on"
          - entity: binary_sensor.0x00158d0004314218_contact
            state: "on"
```

**Comment by Markus1995** [comment]
> vstate: "on"` will only display the entity if the state is "on"
> 
> ```
>       - type: cardGrid
>         title: Fensterkontakte
>         entities:
>           - entity: binary_sensor.sensor_bad_contact
>             state: "on"
>           - entity: binary_sensor.sensor_fenster_links_contact
>             state: "on"
>           - entity: binary_sensor.sensor_fenster_rechts_contact
>             state: "on"
>           - entity: binary_sensor.sensor_fenster_terrasse_contact
>             state: "on"
>           - entity: binary_sensor.0x00158d000451d931_contact
>             state: "on"
>           - entity: binary_sensor.0x00158d0004314218_contact
>             state: "on"
> ```

Thank you.

💯

**Comment by joBr99** [comment]
With #652 you should be able to something like this:

```yaml
    - entity: binary_sensor.nuki_zuhause_door_open
      state_template: '{{is_state("switch.bad", "on")}}'
```

there are no callbacks in for state templates in appdaemon, if you want your page to rerender on changes of switch.bad it must be mentioned in the card this could be done like this

```yaml
    - entity: switch.bad
      status: binary_sensor.nuki_zuhause_door_open
      state_template: '{{is_state("switch.bad", "on")}}'
```

alternatively it's also enough to specify it as an entity of the card and it doesn't have to visible it could be the 5th or 7th entity
