### ISSUE TITLE
[Feature Request] Option to remove modes from cardThermo

### ISSUE THREAD

**Issue by nelim** [joBr99/nspanel-lovelace-ui#484]
### FEATURE DESCRIPTION
Can you add option on cardThermo to list of supported config keys to hide modes/presets?

### ADDITIONAL CONTEXT
Idea is to control ONLY temperature, without switching mode/presets from Auto/Heat/Cold and etc which can be clicked by accident
something like this:
```
    cards:
      - type: cardThermo
        title: HeatPump
        entity: climate.heatpump
        compact: true (optional: true, type: string, default: false)
```
Thanks in advance for great work.

### PANEL / FIRMWARE VERION
EU
