### ISSUE TITLE
[Feature Request] Add option for cardThermo

### ISSUE THREAD

**Issue by lewiatanx** [joBr99/nspanel-lovelace-ui#486]
### FEATURE DESCRIPTION
Can you add an option on cardThermo to run an additional one or two configurable switch items, eg schedule next to flame action and on / off?

### ADDITIONAL CONTEXT
For example, a schedule entity (switch) will enable or disable the corresponding heating schedule defined in HA.
Other thermostat related options can also be run, such as scripts written in HA.

### PANEL / FIRMWARE VERION
Panel EU

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/192876259-636d48c9-243e-44aa-8430-98fc88b4e01f.png)

What kind of schedule do you have? Climate entities can have a auto mode that shows up like the fire or off buttonon the panel. The generic thermostat component in HA doesn't support auto/schedules. This might be helpful to climate devices with more advanced features than the generic one. 
https://github.com/jcwillox/hass-template-climate

**Comment by lewiatanx** [comment]
I use a DIY thermostat and know the limitations of Generic Thermostat in HA.  I use the scheduler-card to set the gas stove heating work schedule and I could use an additional button (switch entity in HA) in the cardThermo nspanel which I could turn on or off the heating automation without switching to another card in the nspanel, which would be convenient to use.

**Comment by koffienl** [comment]
I think the request is similar to mine: https://github.com/joBr99/nspanel-lovelace-ui/issues/484#issuecomment-1260477539
Remove the default options and overrule with a entity free of choice.

**Comment by lewiatanx** [comment]
Yes, in general, it would be enough to be able to add any HA entity of your choice in order to include it and show the state of the entity on thermoCard

**Comment by joBr99** [comment]
The standard way in homeassistant to combine multiple enties are templates. Unfortunally there is no build-in template for climate devices.

This integration adds climate templates: https://github.com/jcwillox/hass-template-climate

With a template you can extend your existing thermostat with addional hvac modes like "auto" and you can do whatever you want to do in this mode with scripting (in this example turning on and off the lamp on my desk)

```
  - platform: climate_template
    name: template_climate_test
    modes:
      - "auto"
      - "heat"
      - "off"
    min_temp: 18
    max_temp: 24
    current_temperature_template: "{{ state_attr('climate.bad_boden', 'current_temperature') }}"
    set_temperature:
      - service: climate.set_temperature
        data:
          entity_id: climate.bad_boden
          temperature: "{{ temperature }}"
    set_hvac_mode:
      - if:
          - condition: template
            value_template: "{{ hvac_mode == 'auto' }}"
        then:
          - service: light.turn_on
            target:
              entity_id: light.schreibtischlampe
        else:
          - service: light.turn_off
            target:
              entity_id: light.schreibtischlampe
          - service: climate.set_hvac_mode
            data:
              entity_id: climate.bad_boden
              hvac_mode: "{{ hvac_mode }}"
```
