### ISSUE TITLE
[Feature Request] Vacuum Card

### ISSUE THREAD

**Issue by LucaBors** [joBr99/nspanel-lovelace-ui#508]
### FEATURE DESCRIPTION
A card for vacuum robots
### ADDITIONAL CONTEXT
I’d like to have a card to manage my robot (start, stop, room choice, go back to base)
### PANEL / FIRMWARE VERION
Us-L

**Comment by joBr99** [comment]
You can create a card with buttons (that are calling services from HA) for your robot with cardEntities/cardGrid. Displaying a map isn't possible on nextion.

**Comment by joBr99** [comment]
You can create a cardGird with different rooms and service calls. An Vacuum will allow you to start/stop it.

```
      - type: cardGrid
        title: Szenen
        entities:
          - entity: service.light.turn_on
            data:
              entity_id: light.schreibtischlampe
              color_name: "green"

          - entity: vacuum.valetudo_robi
            icon: "mdi:food"         
```
