### ISSUE TITLE
[Bug] Light Detail Page

### ISSUE THREAD

**Issue by fschwarz86** [joBr99/nspanel-lovelace-ui#51]
Hi there,

first of all: Thanks a ton for this amazing work, exactly what I've been looking for since I ordered my NSPanel!

I'm facing the following issue: When tapping on a RGB lamp, all I'm getting is an empty page with just an on/off toggle, no RGB selector and/or color temperature slider. I'm using a cardEntities page for the lights and not all of them are RGB lights:

```
- type: cardEntities
  heading: Licht
  items:
    - light.esstischlampe # switch only
    - light.fernsehlampe # RGB enabled
    - light.sofa # RGB enabled
    - light.vitrine # switch only
```

What am I missing?

Cheers,
Florian
