### ISSUE TITLE
[BUG] cardThermo shows the 2-temperature format

### ISSUE THREAD

**Issue by illuzn** [joBr99/nspanel-lovelace-ui#512]
### PROBLEM DESCRIPTION
The cardThermo pages shows the 2-temperature format instead of a single temperature input. As far as I'm aware, my climate device doesn't support the high low settings only a single target temperature.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
hiddenCards:
      - type: cardThermo
        entity: climate.air_conditioning_control
        name: Air Conditioning
        title: Air Conditioning
        key: AirConditioning
```
- [x] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
Not Applicable
```

Developer Tools States:
```
hvac_modes:
  - 'off'
  - heat
  - cool
min_temp: 7
max_temp: 35
current_temperature: 18.2
temperature: null
current_humidity: 61
hvac_action: idle
friendly_name: Air Conditioning Control
supported_features: 1
```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Per above. 

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
Only 1 temperature control should be shown. This works correctly for another hiddencard with a climate device that has `supported_features: 17`

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
US-P
