### ISSUE TITLE
[Feature Request] Change Page via MQTT

### ISSUE THREAD

**Issue by nevermind2001** [joBr99/nspanel-lovelace-ui#513]
### FEATURE DESCRIPTION
It would be great if you can send a command to the panel via MQTT to trigger a page-change to a specific page.

**Comment by Armilar** [comment]
Need a few days for internal testing. I will report back on this

**Comment by randybb** [comment]
yes you can, you have to use "key" to select the right page https://docs.nspanel.pky.eu/card-entities/

my esphome with https://github.com/sairon/esphome-nspanel-lovelace-ui is doing it - when I press a button on nspanel, then it jumps to the right page:
```yaml
      - mqtt.publish_json:
          topic: $panel_recv_topic
          payload: |-
            root["CustomRecv"] = "event,buttonPress1,navigate.cardGrid_light,button";
```
