### ISSUE TITLE
[BUG] Time display does not take account TZ offset

### ISSUE THREAD

**Issue by SupraJames** [joBr99/nspanel-lovelace-ui#530]
### PROBLEM DESCRIPTION
I am using Tasmota on the NSPanel and AppDaemon to drive it. It works great, however the clock on the screensaver is one hour behind. Tasmota's clock is synced to NTP and the TZ is set to Europe/London (+01:00) and the time command on Tasmota returns the correct time.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel/RESULT"
    panelSendTopic: "cmnd/nspanel/CustomSend"
    sleepTimeout: 30
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "en_GB"
    screensaver:
      entity: weather.home
      statusIcon1:
          entity: switch.office
      theme:
        autoWeather: true
    cards:
      - type: cardEntities
        entities:
          - entity: switch.office
          - entity: light.dogs_light
        title: Office
      - type: cardGrid
        entities:
          - entity: switch.office
          - entity: light.dogs_light
        title: Grid Example
      - type: cardQR
        title: Guest Wifi
        qrCode: "WIFI:S:test_ssid;T:WPA;P:test_pw;;"
        entities:
          - entity: iText.test_ssid
            name: Name
            icon: mdi:wifi
          - entity: iText.test_pw
            name: Password
            icon: mdi:key
      - type: cardThermo
        title: Heating
        entity: climate.thermostat
```

### TO REPRODUCE
On Tasmota, sync time using NTP, and then set a timezone

### EXPECTED BEHAVIOUR
The display on the screensaver should show the local time

### PANEL / FIRMWARE VERION
EU Panel. Don't know how to get FW version, but it's Tasmota 12.2 and the lui-release.tft as of today.
