### ISSUE TITLE
[Help] Issue with card navigation

### ISSUE THREAD

**Issue by SupraJames** [joBr99/nspanel-lovelace-ui#531]
### PROBLEM DESCRIPTION
First, sorry if this is the wrong place for this. Is there somewhere else where we should post for general help?

I am trying to configure sub page navigation, so that tapping on an entity will navigate to a particular card. I can't get this to work, and it's possible I am misunderstanding something in the documentation.

Specifically, I have a cardGrid where one of the entities is a sensor showing the temperature of a room. I want to be able to tap on the temperature, and go directly do the cardThermo. Please see my apps.yaml. The entity I am tapping on is sensor.kitchen_temperature.

Note that the sensor information is displaying fine, and the cardThermo is also working fine.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel/RESULT"
    panelSendTopic: "cmnd/nspanel/CustomSend"
    sleepTimeout: 30
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "en_GB"
    screensaver:
      entity: weather.home
      statusIcon1:
          entity: light.all_office_lights
      theme:
        autoWeather: true
    cards:
      - type: cardGrid
        entities:
          - entity: switch.dehumidifier
          - entity: light.all_office_lights
          - entity: sensor.live_power
            name: Watts
          - entity: sensor.kitchen_temperature
            name: Indoor Temp
            navigate: cardThermo.myHeater
        title: Mission Control
      - type: cardThermo
        title: Heating
        entity: climate.thermostat
        key: myHeater

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
2022-10-22 19:17:52.321644 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,sensor.kitchen_temperature,button"}'}
2022-10-22 19:17:52.324093 INFO nspanel-1: Received Message from Screen: event,buttonPress2,sensor.kitchen_temperature,button
2022-10-22 19:17:52.326429 INFO nspanel-1: Button Press Event; entity_id: sensor.kitchen_temperature; button_type: button; value: None

```

### EXPECTED BEHAVIOUR
I would like that tapping on the entity would show the configured cardThermo
