### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by spn91** [joBr99/nspanel-lovelace-ui#548]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

hiddenCards cannot be used with `navigate`. The card where it should be shown, always shows `Page not found`. As soon as the entity (which should be used by navigate) is added to cards, it is working as intended.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
  apps.yaml here:
---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel/RESULT"
    panelSendTopic: "cmnd/nspanel/CustomSend"
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "de_DE"
    screensaver:
      entity: weather.home
    cards:
      - type: cardGrid
        title: Automations
        entities:
          - entity: script.living_room_blinds_open
            name: Jalousien Wohnbereich öffnen
            icon: mdi:blinds-horizontal
      - type: cardEntities
        entities:
          - entity: navigate.cardGrid_testKey
    hiddencards:
      - type: cardGrid
        title: Exmaple Grid
        entities:
          - entity: script.living_room_blinds_open
        key: testKey
      - type: cardThermo
        title: Office
        entity: climate.office
        key: office
      - type: cardThermo
        title: Wohnbereich
        entity: climate.living_room
      - type: cardThermo
        title: Schlafzimmer
        entity: climate.living_room
      - type: cardThermo
        title: Badezimmer
        entity: climate.living_room
      - type: cardThermo
        title: WC
        entity: climate.living_room


```
- [x] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
2022-10-29 22:48:17.352699 INFO nspanel-1: Received Message from Screen: event,buttonPress2,cardGrid,bNext
2022-10-29 22:48:17.355127 INFO nspanel-1: Button Press Event; entity_id: cardGrid; button_type: bNext; value: None 
2022-10-29 22:48:17.357744 INFO nspanel-1: Started rendering of page 2 with type cardEntities
2022-10-29 22:48:17.361175 INFO nspanel-1: Sending MQTT Message: pageType~cardEntities
2022-10-29 22:48:17.372940 INFO nspanel-1: Sending MQTT Message: entityUpd~unknown~1|1~text~navigate.cardGrid_testKey~���~17299~page not found~

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Follow steps on this page of the documentation -> https://docs.nspanel.pky.eu/subpages/

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
navigate can be used with hiddenCards as stated in the documentation

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

using nspanel with esphome and homeassistant
### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU
