### ISSUE TITLE
[BUG] Documentation refers to combining climate entities with navigate but not explaining

### ISSUE THREAD

**Issue by danielszilagyi** [joBr99/nspanel-lovelace-ui#554]
### PROBLEM DESCRIPTION
This is a documentation question, I read this on the Entities and Grid card page for climate entities: "status only, may be used in combination with navigate"
I understood this as it would be somehow possible to put a climate entity on an entities card, and able to touch it too see a respective climate card for the device. I could not solve this however, only with a climate entity and a navigate entity below it.
If I misunderstood the documentation then sorry.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
      - type: cardEntities
        title: Hálószoba további
        entities:
          - entity: climate.haloszoba
            name: Radiátor
          - entity: navigate.cardThermo_haloszoba_trv
            name: Radiátor állítás
          - entity: climate.haloszoba_klima
            name: Klíma
          - entity: navigate.cardThermo_haloszoba_klima
            name: Klíma állítás

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
N/A

### EXPECTED BEHAVIOUR
I understood this as it would be somehow possible to put a climate entity on an entities card, and able to touch it too see a respective climate card for the device. I could not solve this however, only with a climate entity and a navigate entity below it.

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
Tasmota Driver Version: 4 Panel Version: 43 EU
