### ISSUE TITLE
[Feature Request] Kiosk Mode (Replacing ScreenSaver)

### ISSUE THREAD

**Issue by kub3let** [joBr99/nspanel-lovelace-ui#563]
### FEATURE DESCRIPTION
I think it would be awesome if there was a kiosk mode

e.g. cycle trough cards on repeat

should replace the screen saver if enabled

### ADDITIONAL CONTEXT
Example config file

```
---
nspanel1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    # new type screensaverMode ["clock", "kiosk"], default: clock
    screensaverMode: "kiosk"
    # new type kioskInterval, default: 10
    kioskInterval: 10
    cards:
    # new type kioskCards
    # will be shown in order for kioskInterval each
    # repeat on last card
    kioskCards:
      entities:
        - entity: navigate.cardEntities_sensors
        - entity: navigate.cardEntities_devices
    # hidden cards already exist, just examples
    hiddenCards:
      - type: cardEntities
        title: Geräte
        key: devices
        entities:
          - entity: light.wled_2
            name: Licht2
          - entity: light.wled
            name: Licht1
      - type: cardEntities
        title: Sensoren
        key: sensors
        entities:
          - entity: sensor.atc5b3c9a_temperature
            name: Temperatur
          - entity: sensor.atc5b3c9a_humidity
            name: Luftfeuchtigkeit
```

### PANEL / FIRMWARE VERION

Latest EU
