### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by TheGroundZero** [joBr99/nspanel-lovelace-ui#573]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

- [x] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide a screenshot of your tasmota mqtt configuration:

![image](https://user-images.githubusercontent.com/2406013/201810973-fa8208b9-2dfa-40db-9b09-be5e2291c6fc.png)

- [x] Provide your appdaemon.yaml: 
```yaml
---
secrets: /conf/secrets.yaml
appdaemon:
  latitude: ##.##########
  longitude: ##.##########
  elevation: 30
  time_zone: !env_var TZ
  plugins:
    HASS:
      type: hass
      ha_url: !secret ha_url
      token: !secret ha_token
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: !secret mqtt_host
      client_port: 1883
      client_user: !secret mqtt_user
      client_password: !secret mqtt_pass
      client_topics: NONE
http:
  url: http://192.168.70.195:5050
admin:
api:
hadashboard:
```

- [x] Provide your apps.yaml:
```yaml
---
hello_world:
  module: hello
  class: HelloWorld

nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_nspanel_bureau/RESULT"
    panelSendTopic: "cmnd/tasmota_nspanel_bureau/CustomSend"
    model: eu
```
- [x] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
appdaemon  | fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
appdaemon  | fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
appdaemon  | OK: 921 MiB in 69 packages
appdaemon  | Requirement already satisfied: Babel in /usr/local/lib/python3.9/site-packages (from -r /conf/requirements.txt (line 1)) (2.11.0)
appdaemon  | Requirement already satisfied: pytz>=2015.7 in /usr/local/lib/python3.9/site-packages (from Babel->-r /conf/requirements.txt (line 1)) (2021.3)
appdaemon  | WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
appdaemon  | WARNING: You are using pip version 21.2.4; however, version 22.3.1 is available.
appdaemon  | You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
appdaemon  | 2022-11-15 03:25:03.769953 INFO AppDaemon: AppDaemon Version 4.2.1 starting
appdaemon  | 2022-11-15 03:25:03.770115 INFO AppDaemon: Python version is 3.9.9
appdaemon  | 2022-11-15 03:25:03.770251 INFO AppDaemon: Configuration read from: /conf/appdaemon.yaml
appdaemon  | 2022-11-15 03:25:03.770396 INFO AppDaemon: Added log: AppDaemon
appdaemon  | 2022-11-15 03:25:03.770515 INFO AppDaemon: Added log: Error
appdaemon  | 2022-11-15 03:25:03.770623 INFO AppDaemon: Added log: Access
appdaemon  | 2022-11-15 03:25:03.770724 INFO AppDaemon: Added log: Diag
appdaemon  | 2022-11-15 03:25:03.783672 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
appdaemon  | 2022-11-15 03:25:03.796080 INFO HASS: HASS Plugin Initializing
appdaemon  | 2022-11-15 03:25:03.796265 INFO HASS: HASS Plugin initialization complete
appdaemon  | 2022-11-15 03:25:03.796514 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
appdaemon  | 2022-11-15 03:25:03.801221 INFO MQTT: MQTT Plugin Initializing
appdaemon  | 2022-11-15 03:25:03.801392 INFO MQTT: Using 'appdaemon/status' as Will Topic
appdaemon  | 2022-11-15 03:25:03.801508 INFO MQTT: Using 'appdaemon/status' as Birth Topic
appdaemon  | 2022-11-15 03:25:03.801932 INFO AppDaemon: Initializing HTTP
appdaemon  | 2022-11-15 03:25:03.802190 INFO AppDaemon: Using 'ws' for event stream
appdaemon  | 2022-11-15 03:25:03.804626 INFO AppDaemon: Starting API
appdaemon  | 2022-11-15 03:25:03.806814 INFO AppDaemon: Starting Admin Interface
appdaemon  | 2022-11-15 03:25:03.807083 INFO AppDaemon: Starting Dashboards
appdaemon  | 2022-11-15 03:25:03.821665 INFO HASS: Connected to Home Assistant 2022.11.2
appdaemon  | 2022-11-15 03:25:03.825750 INFO MQTT: Connected to Broker at URL 192.168.20.38:1883
appdaemon  | 2022-11-15 03:25:03.827945 INFO AppDaemon: Got initial state from namespace mqtt
appdaemon  | 2022-11-15 03:25:03.831264 INFO MQTT: MQTT Plugin initialization complete
appdaemon  | 2022-11-15 03:25:03.832303 INFO AppDaemon: App 'hello_world' added
appdaemon  | 2022-11-15 03:25:03.833039 INFO AppDaemon: App 'nspanel-1' added
appdaemon  | 2022-11-15 03:25:03.833588 INFO AppDaemon: Found 2 total apps
appdaemon  | 2022-11-15 03:25:03.833850 INFO AppDaemon: Starting Apps with 2 workers and 2 pins
appdaemon  | 2022-11-15 03:25:03.834472 INFO AppDaemon: Running on port 5050
appdaemon  | 2022-11-15 03:25:03.877420 INFO HASS: Evaluating startup conditions
appdaemon  | 2022-11-15 03:25:03.889044 INFO HASS: Startup condition met: hass state=RUNNING
appdaemon  | 2022-11-15 03:25:03.889269 INFO HASS: All startup conditions met
appdaemon  | 2022-11-15 03:25:03.914222 INFO AppDaemon: Got initial state from namespace default
appdaemon  | 2022-11-15 03:25:04.153395 INFO AppDaemon: New client Admin Client connected
appdaemon  | 2022-11-15 03:25:05.072347 INFO AppDaemon: New client Admin Client connected
appdaemon  | 2022-11-15 03:25:05.841348 INFO AppDaemon: Scheduler running in realtime
appdaemon  | 2022-11-15 03:25:05.850656 INFO AppDaemon: Adding /conf/apps to module import path
appdaemon  | 2022-11-15 03:25:05.851989 INFO AppDaemon: Loading App Module: /conf/apps/hello.py
appdaemon  | 2022-11-15 03:25:05.855145 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
appdaemon  | 2022-11-15 03:25:05.868740 INFO AppDaemon: New client Admin Client connected
appdaemon  | 2022-11-15 03:25:05.919857 INFO hello_world: Hello from AppDaemon
appdaemon  | 2022-11-15 03:25:05.920610 INFO hello_world: You are now ready to run Apps!
appdaemon  | 2022-11-15 03:25:05.921646 INFO AppDaemon: App initialization complete
```

### ADDITIONAL INFORMATION

Running Home Assistant Container

docker-compose,yaml

```yaml
version: '3.0'

services:
  appdaemon:
    container_name: appdaemon
    image: "acockburn/appdaemon:latest"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - HA_URL=!secret ha_url
      - TOKEN=!secret ha_token
      - DASH_URL=http://192.168.70.195:5050
    volumes:
      - /opt/appdaemon/config:/conf
      - /etc/localtime:/etc/localtime:ro
    networks:
      not-lan:
        ipv4_address: "192.168.70.195"

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ}
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - /var/run/docker.sock:/var/run/docker.sock
    devices:
      - /dev/serial/by-id/usb-Arduino__www.arduino.cc__0042_55139313335351610270-if00:/dev/ttyACM0
    privileged: true
    depends_on:
      - mariadb
      - influxdb
      - mosquitto
```
