### ISSUE TITLE
[BUG] Cover Card - Tilting does not work

### ISSUE THREAD

**Issue by flop90** [joBr99/nspanel-lovelace-ui#591]
### PROBLEM DESCRIPTION
Via the cover card it is possible to move blinds up/down, also the tilt position can be defined. 

But no matter which tilt position is selected, the adjustment is not transferred to Home Assistant and executed. 

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_nspanel/RESULT"
    panelSendTopic: "cmnd/tasmota_nspanel/CustomSend"
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "5:00:00"
        value: 10
      - time: "02:00:00"
        value: 0
    locale: "de_DE"
    screensaver:
      entity: weather.forecast_home
      theme:
            autoWeather: true
    cards:
      - type: cardGrid
        title: Home
        entities:
        - entity: navigate.cardGrid_Licht
          icon: mdi:lightbulb
        - entity: navigate.cardGrid_Klima
          icon: mdi:home-thermometer 
        - entity: navigate.cardEntities_Raffstoren
          icon: mdi:blinds-horizontal
        - entity: navigate.cardGrid_Medien
          icon: mdi:movie
        - entity: navigate.cardGrid_car
          icon: mdi:car
    hiddenCards:
      - type: cardGrid
        title: Licht
        entities:
          - entity: light.wohnen
            name: Wohnzimmer
            icon: mdi:sofa-outline
          - entity: light.essen
            name: Esszimmer
            icon: mdi:table-chair
          - entity: light.kuche
            name: Küche
            icon: mdi:countertop-outline
          - entity: light.bad
            name: Badezimmer
            icon: mdi:toilet
          - entity: light.schlafen
            name: Schlafzimmer
            icon: bed-double-outline
        key: Licht
      - type: cardGrid
        title: Heizung
        entities:
          - entity: navigate.cardEntities_Klima_Uebersicht
            name: Übersicht
            icon: mdi:home-thermometer 
          - entity: navigate.cardThermo_Klima_Wohnzimmer
            name: Wohnzimmer
            icon: mdi:sofa-outline
          - entity: navigate.cardThermo_Klima_Esszimmer
            name: Esszimmer
            icon: mdi:table-chair
          - entity: navigate.cardThermo_Klima_Badezimmer
            name: Bad
            icon: mdi:toilet
          - entity: navigate.cardThermo_Klima_Schlafzimmer
            name: Schlafzimmer
            icon: mdi:bed-double-outline
        key: Klima
      - type: cardEntities
        title: Raffstoren
        entities:
          - entity: cover.wohnzimmer_raffstoren
            name: Wohnzimmer
          - entity: cover.raffstore_esszimmer
            name: Esszimmer
          - entity: cover.raffstore_kuche
            name: Küche
          - entity: cover.raffstore_schlafzimmer
            name: Schlafzimmer
        key: Raffstoren
      - type: cardEntities
        title: Übersicht
        entities:
          - entity: sensor.wohnzimmer_temperature
            name: Wohnzimmer
          - entity: sensor.esszimmer_temperature
            name: Esszimmer
          - entity: sensor.bad_temperature
            name: Bad
          - entity: sensor.schlafzimmer_temperature
            name: Schlafzimmer
        key: Klima_Uebersicht
      - type: cardThermo
        title: Wohnzimmer
        entity: climate.wohnzimmer
        key: Klima_Wohnzimmer
      - type: cardThermo
        title: Esszimmer
        entity: climate.esszimmer
        key: Klima_Esszimmer
      - type: cardThermo
        title: Badezimmer
        entity: climate.bad
        key: Klima_Badezimmer
      - type: cardThermo
        title: Schlafzimmer
        entity: climate.schlafzimmer
        key: Klima_Schlafzimmer
      - type: cardMedia
        entity: media_player.couch
        key: Sonos_Couch
      - type: cardMedia
        entity: media_player.badezimmer
        key: Sonos_Badezimmer
      - type: cardMedia
        entity: media_player.kuche
        key: Sonos_Kueche
      - type: cardGrid
        title: Medien
        entities:
          - entity: navigate.cardGrid_Sonos
            name: Sonos
            icon: mdi:music
          - entity: navigate.cardGrid_Heimkino
            name: Heimkino
            icon: mdi:movie-open
        key: Medien
      - type: cardGrid
        title: Sonos
        entities:
          - entity: navigate.cardMedia_Sonos_Couch
            name: Couch
            icon: mdi:sofa-outline
          - entity: navigate.cardMedia_Sonos_Badezimmer
            name: Bad
            icon: mdi:toilet
          - entity: navigate.cardMedia_Sonos_Kueche
            name: Küche
            icon: mdi:countertop-outline
        key: Sonos
      - type: cardGrid
        title: Heimkino
        entities:
          - entity: switch.harmony_hub_apple_tv_sehen
            name: Apple TV 
            icon: mdi:movie-open-outline
          - entity: switch.harmony_hub_fernsehen
            name: Fernsehen
            icon: mdi:television
        key: Heimkino
      - type: cardGrid
        title: Autos
        entities:
          - entity: navigate.cardEntities_battery
            name: Akku
            icon: mdi:battery
          - entity: navigate.cardEntities_odometer
            name: Kilometerstände
            icon: mdi:counter
          - entity: navigate.cardThermo_AC_Klimaanlage
            name: A/C F.R.I.D.A.Y.
            icon: mdi:air-conditioner
        key: car
      - type: cardEntities
        title: Akku
        entities:
          - entity: sensor.f_r_i_d_a_y_battery
            name: F.R.I.D.A.Y.
          - entity: sensor.j_a_r_v_i_s_battery
            name: J.A.R.V.I.S.
          - entity: sensor.k_i_t_t_battery
            name: K.I.T.T. 
        key: battery
      - type: cardEntities
        title: Kilometerstände
        entities:
          - entity: sensor.f_r_i_d_a_y_odometer
            name: F.R.I.D.A.Y.
          - entity: sensor.j_a_r_v_i_s_odometer
            name: J.A.R.V.I.S.
          - entity: sensor.k_i_t_t_odometer
            name: K.I.T.T. 
        key: odometer
      - type: cardThermo
        title: F.R.I.D.A.Y.
        entity: climate.f_r_i_d_a_y_hvac_climate_system
        key: AC_Klimaanlage

        


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
022-11-23 13:54:26.627981 INFO nspanel-1: Started rendering of page None with type cardEntities
2022-11-23 13:54:26.697348 INFO nspanel-1: Sending MQTT Message: entityUpd~Raffstoren~2|0~shutter~cover.wohnzimmer_raffstoren~���~17299~Wohnzimmer~���|���|���|enable|enable|enable~shutter~cover.raffstore_esszimmer~���~17299~Esszimmer~���|���|���|disable|enable|enable~shutter~cover.raffstore_kuche~���~17299~K��che~���|���|���|disable|enable|enable~shutter~cover.raffstore_schlafzimmer~���~17299~Schlafzimmer~���|���|���|disable|enable|enable
2022-11-23 13:54:26.739777 INFO nspanel-1: Sending MQTT Message: entityUpdateDetail~cover.wohnzimmer_raffstoren~81~Position: 81~Position~���~���~���~���~enable~enable~enable~Kippstellung~���~���~���~disable~enable~enable~100

```

### TO REPRODUCE
Select any tilt position on the NSPanel

### EXPECTED BEHAVIOUR
Kippstellung sollte analog zum Dashboard in Home Assistant ausgeführt werden.

### PANEL / FIRMWARE VERION
EU Version 
Panelversion 3.5.0
