### ISSUE TITLE
[Feature Request] cardMedia Improvements

### ISSUE THREAD

**Issue by Censored3** [joBr99/nspanel-lovelace-ui#608]
### FEATURE DESCRIPTION
I might have looked over this feature - in this case, please point me to how :-)

I would like to be able to show a detail page as an action (i.e., navigate.pageOpenDetail.PopupInSel.input_select.my_select_list).

Or what might be even more elegant: have a cardDetail card type (e.g. taking exactly one entity and automatically rendering the correct detail page, or heck, just defining the detail type statically), have it as a hidden page and refer to it like any other page navigation.

### ADDITIONAL CONTEXT
An example use case: I have a input_select on my media player with pre-defined "presets" (filled in the real controller app), acting as a radio station selection list. I'd like to jump to this list from the cardMedia media control without having to show a page showing this input_select and then tapping this input_select to show the list of options.

It would come in handy for several other uses like light scene selection.

### PANEL / FIRMWARE VERION
NSPanel EU, v3.6.0

**Comment by joBr99** [comment]
Would see this as a feature request for the following things:

- rework speaker selection on cardMedia and use new insel popups instead of next btn

- Add custom button(s) for navigation, including input_select entities

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/205990706-2c6835ae-ab38-4a51-99ad-d24842b676dc.png)
```
      - type: cardMedia
        key: m2
        title: Kitchen
        entity: media_player.kitchen
        entities:
          - entity: light.bed_light
          - entity: light.ceiling_lights
          - entity: light.entrance_color_white_lights
          - entity: light.kitchen_lights
          - entity: light.living_room_rgbww_lights
```

- removed speaker selection
- added 5 buttons similar to cardGrid

TODO:
- add way to open up insel card with speakers
- transmit type to mediaBtn
- implement popups on media button

**Comment by joBr99** [comment]
showing an input_select on clicking the music icon should now work like this:

```
      - type: cardMedia
        key: m2
        title: Kitchen
        entity: input_select.test123
        status: media_player.kitchen
        entities:
          - entity: light.bed_light
          - entity: light.ceiling_lights
          - entity: light.entrance_color_white_lights
          - entity: light.kitchen_lights
          - entity: media_player.kitchen
```
