### ISSUE TITLE
sleepOverride with multiple entities

### ISSUE THREAD

**Issue by soyxan** [joBr99/nspanel-lovelace-ui#611]
Is it possible to assign multiple entities (lights) to sleepOverride functionality? I have several lights in my room, and I want to consider all of them.
I was thinking about something like this, but it is not working:
```
    sleepOverride:
      entities:
        - entity: light.light1
        - entity: light.light2
        - entity: light.light3
      brightness: 20
```
Thanks!
