### ISSUE TITLE
[BUG]  Cardgrid - two temperature sensors disappeared

### ISSUE THREAD

**Issue by bartlomiejborzucki** [joBr99/nspanel-lovelace-ui#613]
### PROBLEM DESCRIPTION
Hi, 
I want to add 6 temperature sensors to the card grid. 
This is my configuration:
```
 - type: cardGrid
        title: Temperatura
        entities:
          - entity: sensor.livingroom_air_quality_sensor_main_air_quality_sensor_temperature
            name: Salon
          - entity: sensor.bathroom_big_temperature_humidity_sensor_door_temperature
            name: Łazienka
          - entity: sensor.margaret_temperature_humidity_sensor_main_temperature_humidity_sensor_temperature
            name: Pokój Małgosi
          - entity: sensor.max_temperature_humidity_sensor_main_temperature_humidity_sensor_temperature
            name: Pokój Maksa
          - entity: sensor.miley_temperature_humidity_and_pressure_sensor_main_temperature_humidity_and_pressure_sensor_temperature
            name: Milenka
          - entity: sensor.guest_room_temperature_humidity_sensor_main_temperature_humidity_sensor_temperature
            name: Pokoj goscinny 
```

But  my panel shows only first 4 temperature sensors (two sensors are hidden, I don't know why)

When I create a new card grid with 2 hidden sensors (from the first card grid), these sensors work.

Where is my mistake and how to create a panel with 6 temperature sensors?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
```
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_C82E14/RESULT"
    panelSendTopic: "cmnd/tasmota_C82E14/CustomSend"
    locale: "pl_PL"
    sleepTimeout: 20
    screensaver:
      entity: weather.dom
    cards:
      - type: cardEntities
        title: Rolety
        entities:
          - entity: cover.roleta_okno_26
          - entity: cover.roleta_okno_ppz_37
            name: Pokój gościnny okno
          - entity: cover.roleta_sypialnia_35
            name: Sypialnia
          - entity: cover.roleta_taras_38
      - type: cardEntities
        title: Rolety
        entities:
          - entity: cover.shellyswitch25_3494546a19be
          - entity: cover.shellyswitch25_4c7525336857
          - entity: cover.shellyswitch25_4c752534758a
          - entity: cover.roleta_pokoj_goscin_33
            name: Pokój gościnny loggia
      - type: cardGrid
        title: Temperatura
        entities:
          - entity: sensor.livingroom_air_quality_sensor_main_air_quality_sensor_temperature
            name: Salon
          - entity: sensor.bathroom_big_temperature_humidity_sensor_door_temperature
            name: Łazienka
          - entity: sensor.margaret_temperature_humidity_sensor_main_temperature_humidity_sensor_temperature
            name: Pokój Małgosi
          - entity: sensor.max_temperature_humidity_sensor_main_temperature_humidity_sensor_temperature
            name: Pokój Maksa
          - entity: sensor.miley_temperature_humidity_and_pressure_sensor_main_temperature_humidity_and_pressure_sensor_temperature
            name: Milenka
          - entity: sensor.guest_room_temperature_humidity_sensor_main_temperature_humidity_sensor_temperature
            name: Pokoj goscinny
      - type: cardGrid
        title: Temperatura 2 //works
        entities:
          - entity: sensor.miley_temperature_humidity_and_pressure_sensor_main_temperature_humidity_and_pressure_sensor_temperature
            name: Milenka
          - entity: sensor.guest_room_temperature_humidity_sensor_main_temperature_humidity_sensor_temperature
            name: Pokoj goscinny

```
```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
UI panel card grid should display 6 temperature sensors

### SCREENSHOTS
![image](https://user-images.githubusercontent.com/2742766/206849138-89778eb6-0eba-4c54-a70d-948944a9dcf9.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU 
locale:PL_pl 
Version: 3.5 and  3.6

**Comment by joBr99** [comment]
Hey, 
the command that is sent to the panel is limited to 500 chars on cardGrid.
I guess you are reaching this limit of the cardGrid Page, because you have really long entity names, can you rename them?

**Comment by bartlomiejborzucki** [comment]
It's working. I changed my config and I can see all temperature sensors.
Thanks!!

Is it possible to increase the limit? 
```
   - type: cardGrid
        title: Temperatura
        entities:
          - entity: sensor.livingroom_air_quality_sensor_temperature
            name: Salon
          - entity: sensor.bathroom_big_temperature_humidity_sensor_door_temperature
            name: Łazienka
          - entity: sensor.margaret_temp_rh_sensor_temperature
            name: Małgosia
          - entity: sensor.max_temp_rh_sensor_temperature
            name: Maks
          - entity: sensor.miley_temp_rh_and_p_sensor_temperature
            name: Milenka
          - entity: sensor.guest_room_temp_rh_sensor_temperature
            name: Pokoj goscinny
```
