### ISSUE TITLE
[Feature Request] Increase status icons size in screensaver

### ISSUE THREAD

**Issue by soyxan** [joBr99/nspanel-lovelace-ui#618]
### FEATURE DESCRIPTION
Increase the size of the status icons on the upper right and left corners of the screensaver screen

### ADDITIONAL CONTEXT
The space available in the screensaver should allow to increase the size of both icons.
Also to be checked why sometimes the clock canvas covers partially the status icons (z-index issue?)

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
https://github.com/joBr99/nspanel-lovelace-ui/commit/f8c1c19dae100d896c2c668ed268459c4d049987

Implemented an option to increase the font size.

```
    screensaver:
      entity: weather.k3ll3r
      doubleTapToUnlock: True
      alternativeLayout: False
      statusIcon1:
        entity: sensor.temp_wohn_humidity
        icon: 'ha:{{int(states("sensor.temp_wohn_humidity"))}}%'
        altFont: True
      statusIcon2:
        entity: climate.wohnzimmer_boden
        altFont: True
```

https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version

**Comment by soyxan** [comment]
Thanks a lot for the update but I am not able to get the bigger icons on my panel.

I was already using the dev version (main), so I redownloaded again from HACS and flashed Nextion again:

![image](https://user-images.githubusercontent.com/8955206/207841654-e5f89289-ddf1-44ca-a482-343e2f4ce5e7.png)

And this is my apps.yaml config:

```
    screensaver:
      entity: weather.madriguera
      statusIcon1:
        entity: climate.termostato_dormitorio
        icon: 'ha:{{state_attr("climate.termostato_dormitorio","current_temperature")}}°'
        color: [255,255, 255]
        altFont: True
      statusIcon2:
        entity: switch.nspanel_dormitorio_switch1
        icon: mdi:fire
        altFont: True
```

Am I missing anything?
