### ISSUE TITLE
popupLight not updating the entity's state on change

### ISSUE THREAD

**Issue by Ulrar** [joBr99/nspanel-lovelace-ui#619]
Hi,

I'm using ESPHome, but hopefully that's not the issue.
I've set one of the physical buttons to toggle my ceiling lights through home assistant, and I'd like it to at the same time open up the lights control card to control brightness and whatnot if needed.

```
  - platform: gpio
    name: $device_name Right Button
    pin:
      number: GPIO27
      inverted: true
    id: right_button
    on_press:
      then:
        - if:
            condition:
              lambda: 'return !id(living_room_lights).state;'
            then:
              - lambda: 'id($device_id).send_custom_command("pageType~popupLight~Main Lights~light.living_room_lights");'
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.living_room_lights
```

This checks if the lights were off, and if so opens up a popupLight on the ceiling light's entity. Then regardless of the status it toggles the light through home assistant.
I also had it the other way (toggle first, then open the popup) but essentially in both cases the behavior is a bit inconsistent, since the state may or may not have been updated in time for the popup to display it correctly. So basically sometimes the lights will turn on and the popup will show them off. I've also noticed that if the popup is opened and the light state changes, the popup does not update, which I suppose is the same issue.
This only works well and reliably if I toggle the light, delay a couple of seconds then open the popup, but even then if I press the button again to turn them off the popup will show an incorrect state.

Is there a way to make the popup update with the light's state in real-ish time ? Can I do something to tell the AppDaemon to stream updates for that one entity when the popup is open ?

Thanks for the project, I'm very appreciative not to have to fiddle with the Nextion editor myself ! I'm very impressed with what this can do.

**Comment by joBr99** [comment]
The AppDaemon Backend will stream updates for entities that are on the page currently open.
You could send a navigate command to AppDaemon of a cardGrid/cardEntities containing `light.living_room_lights`.

This popup pagetype command is implemented for this specific use case that I'm using in my kitchen and not used by the appdaemon backend in any way.

However I do not really need state updates for the light.
I'm just sending `pageType~popupLight~Main Lights~light.living_room_lights` to the CustomSend Topic after the state of my light has changed.

![image](https://user-images.githubusercontent.com/29555657/207726899-f28bcfe0-7f19-43c8-bc80-6b15b191d329.png)

If you have a use case for state updates, we will find a solution, but opening the page after the state has changed with an automation in homeassistant or nodered should be sufficent.

**Comment by Ulrar** [comment]
I suspected as much, that makes sense.
I've tried having it navigate to the main grid card I have before opening the popup, but it makes it behave kind of weird.

So now I created an automation in HA to re-open the popup every time the light state changes, which works great.
Only issue is HA has no way to know if the popup is already opened or not so it has to do it regardless of state, so I end up with the popup opening when the light turns off as well, but that's not that big of a deal.

Thanks for the suggestion !

**Comment by Ulrar** [comment]
Actually after some more use, that's not great either. It works well for on/off, but other changes aren't very usable.

Sliding the brightness on the display for example updates the entity multiple time, so the automation triggers multiple times and the popup redraws a bunch in close succession, making it kind of blink. It also shows the wrong state on some of the draws making it even more obvious.

Is that also happening with your automation, or am I doing something wrong ?
```
alias: Lights - Living Room - Open NSPanel Lights Popup
description: ""
trigger:
  - platform: state
    entity_id:
      - light.living_room_lights
condition: []
action:
  - service: mqtt.publish
    data:
      topic: cmnd/nspanel-livingroom-1/CustomSend
      payload: pageType~popupLight~Main Lights~light.living_room_lights
mode: single
```

**Comment by joBr99** [comment]
Hey, 
I'm just opening the the popup on the state change from off to on, which happens after pressing the physical button of the light switch.

So the automation would look like this:

```
alias: Lights - Living Room - Open NSPanel Lights Popup
description: ""
trigger:
  - platform: state
    entity_id:
      - light.living_room_lights
    from: "off"
    to: "on"
condition: []
action:
  - service: mqtt.publish
    data:
      topic: cmnd/nspanel-livingroom-1/CustomSend
      payload: pageType~popupLight~Main Lights~light.living_room_lights
mode: single
```

For all other state changes, I don't need to open up the page, because if they are changing I've already something in my hands to change it, but if there is a use case which requires other state changes I can look into it.

**Comment by joBr99** [comment]
I played a bit with it and replaced my nodered thing with an HA automation.

```
alias: Kueche - Open NSPanel Lights Popup
description: ""
trigger:
  - platform: state
    entity_id:
      - light.kueche_lights
    from: "off"
    to: "on"
condition: []
action:
  - service: mqtt.publish
    data:
      topic: tele/tasmota_nspkueche/RESULT
      payload: "{\"CustomRecv\":\"event,buttonPress2,screensaver,bExit,2\"}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 80
  - service: mqtt.publish
    data:
      topic: cmnd/tasmota_nspkueche/CustomSend
      payload: pageType~popupLight~Kueche~light.kueche_lights
mode: single
```

This way it is exiting the screensaver first, which should lead into state updates (If the entity of your detail page is on the card, which is the case for me because I'm exiting the screensaver always to the same card, but you could also do this with a navigate)

**Comment by Ulrar** [comment]
So I've played a bit with that myself and indeed it looks like that works, although I had to add a navigate after the Screensaver exit since I do have other cards that may have been opened.
It blinks a bit but this seems to work fairly well : 

```yaml
alias: Lights - Living Room - Open NSPanel Lights Popup
description: ""
trigger:
  - platform: state
    entity_id:
      - light.living_room_lights
    from: "off"
    to: "on"
condition: []
action:
  - service: mqtt.publish
    data:
      topic: tele/nspanel-livingroom-1/RESULT
      payload: "{\"CustomRecv\":\"event,buttonPress2,screensaver,bExit,2\"}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 80
  - service: mqtt.publish
    data:
      topic: tele/nspanel-livingroom-1/RESULT
      payload: "{\"CustomRecv\":\"event,buttonPress2,navigate.main,button\"}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 80
  - service: mqtt.publish
    data:
      topic: cmnd/nspanel-livingroom-1/CustomSend
      payload: pageType~popupLight~Main Lights~light.living_room_lights
mode: single
```

I'll keep using that for a few days to see but looks good !
Thanks !

**Comment by joBr99** [comment]
this should also work; you don't need to send the screensaver exit before navigate

```
alias: Lights - Living Room - Open NSPanel Lights Popup
description: ""
trigger:
  - platform: state
    entity_id:
      - light.living_room_lights
    from: "off"
    to: "on"
condition: []
action:
  - service: mqtt.publish
    data:
      topic: tele/nspanel-livingroom-1/RESULT
      payload: "{\"CustomRecv\":\"event,buttonPress2,navigate.main,button\"}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 80
  - service: mqtt.publish
    data:
      topic: cmnd/nspanel-livingroom-1/CustomSend
      payload: pageType~popupLight~Main Lights~light.living_room_lights
mode: single
```

**Comment by Ulrar** [comment]
Well actually no, I've tried it and if I don't exit the Screensaver first it doesn't seem to work.
But that's alright, exiting it first works well.
Thanks

**Comment by joBr99** [comment]
The issue is that your navigate command isn't going to work.

`navigate.main` isn't valid, the format is `navigate_cardType_key`

See this example:

```
      - type: cardGrid
        key: testKey
        title: Exmaple Grid
        entities:
          - entity: light.test_item

```

```
navigate.cardGrid_testKey

```
