### ISSUE TITLE
[BUG] Cover icon reversed

### ISSUE THREAD

**Issue by Ulrar** [joBr99/nspanel-lovelace-ui#621]
### PROBLEM DESCRIPTION
Hi, minor detail but I've noticed the cover icons are reversed, they show open when the curtains are closed and closed when they're open.
I'm using Switchbot curtains using the official integration, the icon and state on the HA side is valid.

Sometimes switchbots push against each other so they may not be at 0 or 100 exactly, but the entity state does reflect "open" or "closed" correctly in HA. I'm not sure if this is basing the icons on the position or the state, that may be what's going on but I'm not sure.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Provide your apps.yaml (or your config):
```
---
nspanel-livingroom-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel-livingroom-1/RESULT"
    panelSendTopic: "cmnd/nspanel-livingroom-1/CustomSend"
    model: eu
    screensaver:
      entity: weather.home
      weatherUnit: celsius
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "en_GB"
    cards:
      - type: cardGrid
        key: main
        title: Living Room
        entities:
          - entity: switch.sideboard_lamp
            name: Sideboard Lamp
            icon: mdi:lamp
          - entity: light.living_room_lights
            name: Main Lights
            icon: mdi:ceiling-light-multiple
          - entity: cover.curtain_5ea5
            name: Main Door
          - entity: cover.curtain_2df2
            name: Bay Window
          - entity: navigate.cardGrid_sensorCard
            name: Sensors
            icon: mdi:access-point
          - entity: navigate.cardAlarm_alarmCard
            name: Alarm
    hiddenCards:
      - type: cardGrid
        title: Sensors
        key: sensorCard
        entities:
          - entity: sensor.awair_element_17698_temperature
            name: Temperature
          - entity: sensor.awair_element_17698_humidity
            name: Humidity
          - entity: sensor.awair_element_17698_carbon_dioxide
            name: Co2
          - entity: sensor.awair_element_17698_volatile_organic_compounds
            name: VoC
          - entity: sensor.awair_element_17698_pm2_5
            name: PM 2.5
          - entity: sensor.hot_water_tank_charge
            name: Hot Water
      - type: cardAlarm
        title: Alarm
        key: alarmCard
        entity: alarm_control_panel.home
```

### EXPECTED BEHAVIOUR
For the entity in the grid to show the open icon when open, and closed icon when closed.

### PANEL / FIRMWARE VERION
Panel is EU version, flashed a few days ago so it should be the latest version
