### ISSUE TITLE
[BUG] StatusIcons with state-bound icons break the screensaver, colors don't work in dev

### ISSUE THREAD

**Issue by blubbel42** [joBr99/nspanel-lovelace-ui#622]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
When configuring StatusIcons in the newest dev (e2e91ad) which use colors for different states the colorchange will not work, when using different icons for different states all status and weathericons dissapear. Everything else works fine 

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Provide your apps.yaml (or your config):
```
    screensaver:
      entity: weather.wettervorhersage
      theme:
        autoWeather: true
      alternativeLayout: true
      defaultCard: navigate.cardGrid_nestnavigation
      statusIcon1:
        entity: binary_sensor.inselbetrieb
        color:
          "on": [255, 255, 0]
          "off": [255, 0, 155]
        icon: mdi:transmission-tower-off
          "on": mdi:transmission-tower-off
          "off": mdi:transmission-tower-import

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Configure a binary_sensor Status icon with two different icons for "on" and "off" state, then weathericons and statusicons dissapear.
If you just use different colors the icons will be shown with the color for off, but not change with statechanges of the used sensor.

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
Icons should change with state changes as before.

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU, Tasmota 12.1.1, newest Nextion firmware
