### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by Vogete** [joBr99/nspanel-lovelace-ui#648]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

- [X] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Provide a screenshot of your tasmota mqtt configuration:
![image](https://user-images.githubusercontent.com/16021671/209942019-684f37af-a2e1-4951-8666-1957398152a5.png)

- [X] Provide your appdaemon.yaml: 
```yaml
appdaemon:
  latitude: 0
  longitude: 0
  elevation: 30
  time_zone: Europe/Berlin
  plugins:
    HASS:
      type: hass
      ha_url: "http://192.168.2.210:8123"
      token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhYjQ5M2QyZDgxMzc0ZmE5ODAwZjQ3YWNhOTUwMzVkMCIsImlhdCI6MTY3MjMwMjE3MywiZ>
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: 192.168.2.210
      client_port: 1883
      client_user: ""
      client_password: ""
      client_topics: NONE
http:
  url: "http://192.168.2.210:5050"
admin:
api:
hadashboard:
```

- [X] Provide your apps.yaml:
```yaml
hello_world:
  module: hello
  class: HelloWorld

nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_0CB430/RESULT"
    panelSendTopic: "cmnd/tasmota_0CB430/CustomSend"
    model: eu
```
- [X] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:

```log
Attaching to appdaemon
appdaemon  | fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/aarch64/APKINDEX.tar.gz
appdaemon  | fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/aarch64/APKINDEX.tar.gz
appdaemon  | OK: 894 MiB in 69 packages
appdaemon  | 2022-12-29 11:49:08.175475 INFO AppDaemon: AppDaemon Version 4.2.1 starting
appdaemon  | 2022-12-29 11:49:08.176220 INFO AppDaemon: Python version is 3.9.9
appdaemon  | 2022-12-29 11:49:08.176951 INFO AppDaemon: Configuration read from: /conf/appdaemon.yaml
appdaemon  | 2022-12-29 11:49:08.177770 INFO AppDaemon: Added log: AppDaemon
appdaemon  | 2022-12-29 11:49:08.178685 INFO AppDaemon: Added log: Error
appdaemon  | 2022-12-29 11:49:08.179482 INFO AppDaemon: Added log: Access
appdaemon  | 2022-12-29 11:49:08.180218 INFO AppDaemon: Added log: Diag
appdaemon  | 2022-12-29 11:49:08.215607 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
appdaemon  | 2022-12-29 11:49:08.249329 INFO HASS: HASS Plugin Initializing
appdaemon  | 2022-12-29 11:49:08.250155 INFO HASS: HASS Plugin initialization complete
appdaemon  | 2022-12-29 11:49:08.251043 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
appdaemon  | 2022-12-29 11:49:08.263379 INFO MQTT: MQTT Plugin Initializing
appdaemon  | 2022-12-29 11:49:08.264118 INFO MQTT: Using 'appdaemon/status' as Will Topic
appdaemon  | 2022-12-29 11:49:08.264877 INFO MQTT: Using 'appdaemon/status' as Birth Topic
appdaemon  | 2022-12-29 11:49:08.266275 INFO AppDaemon: Initializing HTTP
appdaemon  | 2022-12-29 11:49:08.267439 INFO AppDaemon: Using 'ws' for event stream
appdaemon  | 2022-12-29 11:49:08.273977 INFO AppDaemon: Starting API
appdaemon  | 2022-12-29 11:49:08.279931 INFO AppDaemon: Starting Admin Interface
appdaemon  | 2022-12-29 11:49:08.281049 INFO AppDaemon: Starting Dashboards
appdaemon  | 2022-12-29 11:49:08.301840 INFO HASS: Connected to Home Assistant 2022.12.7
appdaemon  | 2022-12-29 11:49:08.323489 INFO MQTT: Connected to Broker at URL 192.168.2.210:1883
appdaemon  | 2022-12-29 11:49:08.327449 INFO AppDaemon: App 'hello_world' added
appdaemon  | 2022-12-29 11:49:08.335641 INFO AppDaemon: App 'nspanel-1' added
appdaemon  | 2022-12-29 11:49:08.337920 INFO AppDaemon: Found 2 total apps
appdaemon  | 2022-12-29 11:49:08.339420 INFO AppDaemon: Starting Apps with 2 workers and 2 pins
appdaemon  | 2022-12-29 11:49:08.342424 INFO AppDaemon: Running on port 5050
appdaemon  | 2022-12-29 11:49:08.344563 INFO AppDaemon: Got initial state from namespace mqtt
appdaemon  | 2022-12-29 11:49:08.345818 INFO MQTT: MQTT Plugin initialization complete
appdaemon  | 2022-12-29 11:49:08.417345 INFO HASS: Evaluating startup conditions
appdaemon  | 2022-12-29 11:49:08.425359 INFO HASS: Startup condition met: hass state=RUNNING
appdaemon  | 2022-12-29 11:49:08.426151 INFO HASS: All startup conditions met
appdaemon  | 2022-12-29 11:49:08.457254 INFO AppDaemon: Got initial state from namespace default
appdaemon  | 2022-12-29 11:49:08.511344 INFO AppDaemon: New client Admin Client connected
appdaemon  | 2022-12-29 11:49:09.183102 INFO AppDaemon: New client Admin Client connected
appdaemon  | 2022-12-29 11:49:10.358666 INFO AppDaemon: Scheduler running in realtime
appdaemon  | 2022-12-29 11:49:10.404917 INFO AppDaemon: Adding /conf/apps to module import path
appdaemon  | 2022-12-29 11:49:10.409218 INFO AppDaemon: Loading App Module: /conf/apps/hello.py
appdaemon  | 2022-12-29 11:49:10.417671 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
appdaemon  | 2022-12-29 11:49:10.549364 INFO hello_world: Hello from AppDaemon
appdaemon  | 2022-12-29 11:49:10.551491 INFO hello_world: You are now ready to run Apps!
appdaemon  | 2022-12-29 11:49:10.554158 INFO AppDaemon: App initialization complete
appdaemon  | 2022-12-29 11:49:21.011970 INFO AppDaemon: Client disconnection from Admin Client
appdaemon  | 2022-12-29 11:49:21.183482 INFO AppDaemon: New client Admin Client connected
appdaemon  | 2022-12-29 11:49:47.238417 INFO AppDaemon: Client disconnection from Admin Client
appdaemon  | 2022-12-29 11:49:47.401717 INFO AppDaemon: New client Admin Client connected
appdaemon  | 2022-12-29 11:49:47.971867 INFO AppDaemon: Client disconnection from Admin Client
appdaemon  | 2022-12-29 11:49:48.109814 INFO AppDaemon: New client Admin Client connected
```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_

Home Assistant can already control the 2 buttons (and display their state) on the NSPanel. Mosquitto is using anonymous login, but it seems that NSPanel is publishing updates of the temp sensor and the 2 relays correctly to MQTT, which HA then fetches and displays correctly.
All indication shows that MQTT is connected and working on AppDaemon, NSPanel Tasmota, and HomeAssistant.

Containers running:
```
acockburn/appdaemon:4.2.1
ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2022.12.7
eclipse-mosquitto:2.0.15
```

![image](https://user-images.githubusercontent.com/16021671/209943018-525f98e7-dd04-44b3-a067-0f72b87b3f70.png)

**Comment by joBr99** [comment]
hey, can you add the log from tasmota console?

**Comment by joBr99** [comment]
foget the tasmota log; I think the app in appdaemon is not running at all; can you post the volume mounts you are using for homeassistant and appdaemon?

**Comment by joBr99** [comment]
The Backend is downloaded by HACS inside of the homeassistant container; to enable appdaemon to access this downloaded application your appdaemon volume mount needs to be inside of the homeassistant one.

See this Example:

```
version: "3.5"
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    network_mode: host
    volumes:
      - ./docker-data/homeassistant/:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
    privileged: true
    restart: unless-stopped

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    environment:
      - HA_URL=http://your-homeassistant-url:8123
      - TOKEN="xxxxxx"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker-data/homeassistant/appdaemon:/conf
    depends_on:
      - homeassistant
    restart: unless-stopped
```
