### ISSUE TITLE
[BUG] Alarm Card not displaying title

### ISSUE THREAD

**Issue by duanemck** [joBr99/nspanel-lovelace-ui#658]
### PROBLEM DESCRIPTION
When I add an Alarm card, I set the `title` field but it is not rendered on the card on the panel

### REQUESTED INFORMATION
- [x] Provide your apps.yaml (or your config):
```
- type: cardAlarm
  title: "House Alarm"
  entity: alarm_control_panel.house
  supportedModes: ['arm_away', 'arm_home']
```
- [x] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:

2022-12-31 22:17:21.642155 INFO nspanel-1: Started rendering of page 2 with type cardAlarm
2022-12-31 22:17:21.653710 INFO nspanel-1: Sending MQTT Message: pageType~cardAlarm
2022-12-31 22:17:21.767632 INFO nspanel-1: Sending MQTT Message: entityUpd~alarm_control_panel.house~1|1~Arm away~arm_away~Arm home~arm_home~~~~~���~3334~disable~disable~

```

### TO REPRODUCE
1. Add an Alarm Card
2. Set the `title` property
3. Save the file and wait for NSPanel to reload
4. Navigate to the Alarm Card

### EXPECTED BEHAVIOUR
The title is displayed at the top of the card, but it's not

### SCREENSHOTS
![WhatsApp Image 2022-12-31 at 23 20 10](https://user-images.githubusercontent.com/429394/210155806-e14bd4f9-8f2a-467a-9c22-e767c4e3bc1d.jpg)

### PANEL / FIRMWARE VERION
v3.7.3
US-P

**Comment by joBr99** [comment]
There's no title on cardAlarm, because the code for the numpad is displaied there.

![image](https://user-images.githubusercontent.com/29555657/210156272-2daa512e-5fd1-4922-9c12-9720601fa665.png)

**Comment by joBr99** [comment]
If you want a card with just the alarm panel status and some buttons to arm/disarm and no numpad, I would recommend you building one with cardGird
```
    cards:
      - type: cardGrid
        title: Test Grid Card
        entities:
          - entity: alarm_control_panel.xxx
          - entity: service.alarm_control_panel.alarm_arm_home
            name: "Arm Home"
            data:
              entity_id: alarm_control_panel.xxx
```
