### ISSUE TITLE
[BUG] Key is not optional anymore for multiple cardenteties on root level

### ISSUE THREAD

**Issue by DEVIDTR** [joBr99/nspanel-lovelace-ui#669]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
With 3.8.0 the navigation by key does not work when multiple cards with the same type have been configured and there is no key configured in apps.yaml.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
  apps.yaml here:

Case1: Only Solar will be available

    cards:
      - type: cardEntities
        title: Solar
        entities:
          - entity: sensor.abc
      - type: cardEntities
        title: Solar2
        entities:
          - entity: sensor.abc

Fix in yaml:

    cards:
      - type: cardEntities
        key: 1
        title: Solar
        entities:
          - entity: sensor.abc
      - type: cardEntities
        key: 2
        title: Solar2
        entities:
          - entity: sensor.abc


```
- [x] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:

No errors :-) Or fix the code in config.py:

class Card(object):
    def __init__(self, card_input_config, hidden=False):
        self.uuid = f"uuid.{uuid()}"
        self.uuid_prev = None
        self.uuid_next = None
        self.hidden = hidden
        self.raw_config = card_input_config
        self.cardType = card_input_config.get("type", "unknown")
        self.title =  card_input_config.get("title", "unknown")
-->># self.key = card_input_config.get("key", "unknown")
-->> self.key = card_input_config.get("key", self.uuid)

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

See apps.yaml

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU, 3.8.0
