### ISSUE TITLE
[BUG] presetModes on cardThermo missing

### ISSUE THREAD

**Issue by nelim** [joBr99/nspanel-lovelace-ui#670]
### PROBLEM DESCRIPTION
After latest update, preset modes (three dots) on cardThermo missing on all cards

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
    hiddenCards:
      - type: cardAlarm
        title: Аларма
        entity: alarm_control_panel.alarmo
        key: myAlarm
      - type: cardThermo
        title: Детска
        entity: climate.detska
        key: Detska
      - type: cardThermo
        title: Камина
        entity: climate.stove
        key: Stove


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._
![image](https://user-images.githubusercontent.com/3601587/211018991-126d7c02-8aee-46b6-8fe0-ccc1d34433fd.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
EU/3.8.1
