### ISSUE TITLE
[BUG] 6th Entity not rendered correctly on US-P

### ISSUE THREAD

**Issue by zunaidhoorjook** [joBr99/nspanel-lovelace-ui#671]
### PROBLEM DESCRIPTION
Text at the bottom of the screen when switching between sub pages

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:

---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    #Must correspond to the topic in tasmota
    panelRecvTopic: "tele/tasmota_nspanel/RESULT"
    panelSendTopic: "cmnd/tasmota_nspanel/CustomSend"
    
    #Displays the home button on hidden cards
    homeButton: True
    
    #Set the display to potrait
    model: "us-p"
    weather: weather.home
    defaultBackgroundColor: "ha-dark"
    sleepTimeout: 20
    
    #Adjust the brightness based on the time of day
    sleepBrightness:
      - time: "4:45:00"
        value: 4
      - time: "sunset"
        value: 5
      - time: "22:30:00"
        value: 0
    dateFormatBabel: "long"
    
    #Screensaver values
    screensaver:
      theme:
        #time: [255, 255, 255]
        timeAMPM: [220, 0, 255]
        date: [0, 119, 255]
        bar: [255, 255, 255]
        autoWeather: true
        sunny: [253, 237, 6]
        #background: [183, 174, 174]
      #Displays an icon next to the line on the screensaver screen
      statusIcon1:
        entity: switch.shellygaragedooronesensor
        icon:
          "on": mdi:garage-alert
          "off": mdi:garage-lock
      entity: weather.openweathermap
      weatherOverrideForecast:
        entity: sensor.openweathermap_condition
        name: name
      alternativeLayout: True
    
    #Cards section
    cards:
      - type: cardGrid
        title: MyPanel
        entities:
          - entity: navigate.lightskey
            icon: mdi:lightbulb-group
          - entity: script.bedtime_2
            icon: mdi:sleep
            name: Bed Time
          - entity: navigate.loadsheddingKey
            icon: mdi:flash-alert
          - entity: navigate.garagekey
            icon: mdi:garage
        key: mainScreen
    
    #Hidden cards
    hiddenCards:
      #Loadshedding Card
      - type: cardEntities
        title: Loadshedding
        entities:
#          - entity: sensor.currentstage
#            name: "Stage"
#          - entity: sensor.currentstagestarttime
#            name: "Start"
#          - entity: sensor.currentstageendtime
#            name: "End"
          - entity: sensor.nextstage
            name: "Stage"
          - entity: sensor.nextstagestarttime
            name: "Start Time"
          - entity: sensor.nextstageendtime
            name: "End Time"
        key: loadsheddingKey
        
        #Lights Card
      - type: cardGrid
        title: Lights
        entities:
          - entity: switch.boxlight
            icon: mdi:jabber
          - entity: switch.lighthouselamp
            icon: mdi:jabber
          - entity: switch.tasmota
            icon: mdi:jabber
          - entity: switch.sonoffdoublevolume_outside
            icon: mdi:jabber
            name: "Outside"
          - entity: switch.patiorecess
            icon: mdi:jabber
            name: "Patio Recess"
        key: lightskey
        
        #Garage door cards
      - type: cardGrid
        title: Garage
        entities:
          - entity: script.garagedoor
            icon: mdi:gesture-tap
            name: Garage Door
          - entity: switch.shellygaragedooronesensor
            name: Garage Status
            icon:
              "on": mdi:garage-open
              "off": mdi:garage
          - entity: switch.tasmota_2
            name: Garage Power 
            icon: mdi:garage-lock
        key: garagekey
        


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
Create a subpage. Place an icon on the 'main page' that loads the sub page. As the subpage loads the last line of the subpage shows the text 'tEntity5' with a slide along side it. The  'tEntity5' with a slide along side it then disappears and the screen subpage displays correctly.

### EXPECTED BEHAVIOUR
The subpage should not display the 'tEntity5' with a slide along side it. 

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._
![NSPanelBugReport](https://user-images.githubusercontent.com/99598788/211019210-64e1d382-d179-4f62-ad80-23ecf7696cf4.jpg)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
US-P
Lovelace UI V.3.8.1
