### ISSUE TITLE
[Feature Request] Switch between weather entities and others based on HA Templates

### ISSUE THREAD

**Issue by ebendl** [joBr99/nspanel-lovelace-ui#680]
### FEATURE DESCRIPTION
Have the ability to switch between showing the weather entities and others (e.g. forecast override), based on HA templates (or some other condition/config. 

### ADDITIONAL CONTEXT
I love the weather layout and so does my family - especially with the AutoWeather colors. I also use the additional two entities to show certain important aspects at all times, and also use the Additional Time and Date lines. 

There are some instances where I want to show something else as well - but only when it is "critical". E.g. I have a home PV system and I live in an area with frequent power outages. While the grid is available, all is well, but when the grid is not available, I am reliant on the PV and battery system for my power needs, and at that point I would want to override Weather entity 4 for example with another entity (showing home Power consumption for example). 

If this is already possible, I'd love to know how! Not sure if I can create a new template sensor that decides itself (e.g. have forecast information usually, unless some condition is true, then changes the icon and information. And then I just always use the say weatherOverrideForecast4: with this new sensor?

### PANEL / FIRMWARE VERION
US-P, 3.7.3

**Comment by joBr99** [comment]
in the latest development version you can configure the screensaver like this:

```
    screensaver:
      #entity: weather.openweathermap
      entities:
        - entity: weather.demo_weather_north
        - entity: weather.demo_weather_north
          type: 0
        - entity: weather.demo_weather_north
          type: 1
        - entity: weather.demo_weather_north
          type: 2
        - entity: weather.demo_weather_north
          type: 3
```

It should be possible to use it in combination with state_template, hide or show an entity.
https://docs.nspanel.pky.eu/entities/#calling-service-directly-as-button


I ported the changes to the screensaver to the US-P version, however this is untested.
https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version
