### ISSUE TITLE
[BUG] Dynamic color overwrites using homeassistant templates not working in cardGrid

### ISSUE THREAD

**Issue by Mozzzy** [joBr99/nspanel-lovelace-ui#681]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

I have entities on a cardGrid triggering scenes via an automation. To show which scene was last triggered I made binary sensors that I use for color overrides of icons.
The template works fine on an entity in a hidden cardGrid card, but does not work on an entity within a regular cardGrid.
Setting just a color on the other hand works just fine.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
    cards:
      - type: cardThermo
        title: Woonkamer
        entity: climate.woonkamer_2
      - type: cardGrid
        title: Lampen woonkamer
        entities:
          - entity: service.automation.trigger
            data:
              entity_id: automation.nspanel_hue_knop_1
            name: AAN
            icon: mdi:lightbulb-on
            color: '{{iif(states("binary_sensor.nspanel_hue1")=="on", "[255,255,0]", "[0,0,255]")}}'

    hiddenCards:
      - type: cardGrid
        title: Kamers
        key: Kamers
        entities:
          - entity: navigate.cardThermo_Badkamer
            icon: mdi:radiator-disabled
            color: '{{iif(states("binary_sensor.nspanel_hue1")=="on", "[255,255,0]", "[0,0,255]")}}'

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

I am running version 3.8.3

**Comment by joBr99** [comment]
Can you try to add your binary sensor as an additional sensor on your card?

```
- entity: binary_sensor.nspanel_hue1
```

There are no callbacks for templates in Appdaemon, so you need to have it as an entity on the card to get it updated. However the config isn't limited to 6 entities, so you can add it as a 7th entity and it won't be shown on the panel.

**Comment by Mozzzy** [comment]
Adding
`- entity: binary_sensor.nspanel_hue1`
shown the binaty sensor correctly and th eicon and color changes with its state.
However, the color of:
`          - entity: service.automation.trigger
            data:
              entity_id: automation.nspanel_hue_knop_1
            name: AAN
            icon: mdi:lightbulb-on
            color: '{{iif(states("binary_sensor.nspanel_hue1")=="on", "[255,255,0]", "[0,0,255]")}}'`
is not changing along with it.

**Comment by joBr99** [comment]
okay checked the code, service indeed doesn't support overwriting the color this way:

Try to do this, should be a bit simpler:
```
          - entity: service.automation.trigger
            data:
              entity_id: automation.nspanel_hue_knop_1
            name: AAN
            icon: mdi:lightbulb-on
            status: binary_sensor.nspanel_hue1
```
