### ISSUE TITLE
[BUG] No Cyrillic font support on the screensaver date

### ISSUE THREAD

**Issue by diahellfire** [joBr99/nspanel-lovelace-ui#686]
### PROBLEM DESCRIPTION
No Cyrillic font support on the screensaver.
Font used in screensaver ID 1 (date) does not contain Cyrillic, this checked in Nextion Editor. Because of this, there is no date display.
(babel is loaded!)

### REQUESTED INFORMATION

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/esphome_nspanel/RESULT"
    panelSendTopic: "cmnd/esphome_nspanel/CustomSend"
    model: us-p
    dateFormat: "%d %B %Y %A"
    homeButton: true
    sleepTimeout: 10
    sleepBrightness:
      - time: "7:00:00"
        value: 20
      - time: "23:00:00"
        value: 5
    locale: "ru_RU"
    cards:
      - type: cardThermo
        title: Gas Boiler
        entity: climate.hall_e1_ha_thermostat
      - type: cardQR
        title: Guest Wifi Network
        qrCode: "WIFI:S:Quantum;T:WPA;P:123456789;"
        entities:
          - entity: iText.Quantum
            name: Name
            icon: mdi:wifi
          - entity: iText.123456789
            name: Password
            icon: mdi:key
      - type: cardAlarm
        title: Security
        entity: alarm_control_panel.home_alarm
      - type: cardMedia
        entity: media_player.yandex_station
      - type: cardEntities
        title: 2 Floor
        entities:
          - entity: sensor.sonoff_e22_temperature
            icon: mdi:thermometer
          - entity: sensor.sonoff_e23_temperature
            icon: mdi:thermometer
          - entity: sensor.komnata_3_temperature
            icon: mdi:thermometer
          - entity: sensor.sonoff_e24_temperature
            icon: mdi:thermometer
            
    screensaver:
      statusIcon1:
        entity: sun.sun
      statusIcon2:
        entity: climate.hall_e1_ha_thermostat
        icon: 'ha:{{ state_attr("climate.hall_e1_ha_thermostat","current_temperature")}}'
      entity: weather.quantum_2
      theme:
        time: [255, 255, 255]
        date: [255, 175, 0]
        tMainIcon: [57, 169, 255]
        bar: [57, 169, 0]
        autoWeather: true
        clear-night: [150, 150, 100]
        cloudy: [75, 75, 75]
        exceptional: [255, 50, 50]
        fog: [150, 150, 150]
        hail: [200, 200, 200]
        lightning: [200, 200, 0]
        lightning-rainy: [200, 200, 150]
        partlycloudy: [150, 150, 150]
        pouring: [50, 50, 255]
        rainy: [100, 100, 255]
        snowy: [150, 150, 150]
        snowy-rainy: [150, 150, 255]
        sunny: [255, 255, 0]
        windy: [150, 150, 150]
        windy-variant: [255, 125, 125]

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
`Sending MQTT Message: date~08 ������������ 2023 ����������������������`

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
![photo1673251524](https://user-images.githubusercontent.com/8593409/211263571-84c8b84c-90f7-428c-9592-e605c8df06d1.jpeg)

### ADDITIONAL CONTEXT
ESPhome

### PANEL / FIRMWARE VERION
US-P 
[nspanel_US_P.tft](https://github.com/joBr99/nspanel-lovelace-ui/blob/main/HMI/US/portrait/nspanel_US_P.tft)
