### ISSUE TITLE
[BUG] Double tap to unlock screensaver with notify

### ISSUE THREAD

**Issue by koffienl** [joBr99/nspanel-lovelace-ui#706]
### PROBLEM DESCRIPTION
Not entirely sure whether this is a bug or a feature.
I have a empty screensaver, I don't use the weather card because I don't care about that info. The info I do care is send from HA as a notification. When I walk by the nspanel I see al the info at a glance.
Now the issue: when I want to use the panel I have to double tap (most of the time, not always!). It looks like I have to tap first to dismiss the notification resulting in a screen with higher brightness and a empty screensaver (only date/time because I have no weather entity). after tapping again the screensaver disappears and I see my main card.
Sometimes a single tap is enough to display the main card.
I have *not* enabled the ```doubleTapToUnlock``` feature (see my yaml).
IIRC the double tap was not needed a few version before, but not entirely sure.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel_woonkamer/RESULT"
    panelSendTopic: "cmnd/nspanel_woonkamer/CustomSend"
    sleepTimeout: 30
    sleepTracking: input_boolean.display_nspanel_woonkamer
    locale: "nl_NL"
    screensaver:
#      entity: weather.home
      defaultCard: cardGrid_home
    cards:
      - type: cardGrid
        title: Overview
        key: home
```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Send a notify to the NSPanel when the screensaver is active. Tap on the screen. Tap again to see the card.

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
In my opinion a double tap should not be nescesary. It is a screensaver, so me tapping on the screen should already dismiss the info.

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_
HA 2023.1.6
AppDeamon 0.11.0 
Tasmota 12.2.0 

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
NSPanel lovalelace UI v3.8.3 (EU version)

**Comment by joBr99** [comment]
This is indeed a feature, to dismiss notifications. 

```
if(tNotifyHead.txt!=""||tNotifyText.txt!="")
{
  if(dim!=0)
  {
    tNotifyHead.txt=""
    tNotifyText.txt=""
    vis tNotifyHead,0
    vis tNotifyText,0
  }
}
dim=dimValueNormal
vaTap.val+=1
```

What are you showing in your notifications? 
In the current development version you can do this:

![image](https://user-images.githubusercontent.com/29555657/213889249-77933223-0e79-48c0-a716-304867e7a166.png)

**Comment by koffienl** [comment]
I'm showing room and outside temperature. I like the new options in the dev, I'll try.
(although, personally for me I don't give a crap about weather forecast. That's the reason I don't use it)

**Comment by joBr99** [comment]
Config Example:
```
    screensaver:
      doubleTapToUnlock: True
      entities:
        - entity: weather.k3ll3r
        - entity: weather.k3ll3r
          type: 0
        - entity: weather.k3ll3r
          type: 1
        - entity: weather.k3ll3r
          type: 2
        - entity: weather.k3ll3r
          type: 3
        - entity: sensor.temp_wohn_temperature
          icon: mdi:home-thermometer-outline
```
