### ISSUE TITLE
Touching doesn't open cards.

### ISSUE THREAD

**Issue by Chreece** [joBr99/nspanel-lovelace-ui#71]
First of all thank you very much for your wonderful work, the ui is part from home assistant and I'm very impressed.

I had the panel flashed a while ago and only since today I could mount it on the wall with a 3d printed adapter (was too big for the box in my old german appartment), so today I flashed everything new.

Suddently touching the panel it doesn't open the cards.
If I reboot the first card pops up, everything works but I can't move to the next one (touching the arrows doesn't do anything).

In tasmota console everytime I touch the screen I got:
```
MQT: tele/nspanel/RESULT = {"CustomRecv":"event,buttonPress2,screensaver,bExit"}
```

Tried:
Flashing latest tasmota32.bin
Flashing latest lui.tft from your website (panel starts from 92% and tasmota console doesn't show any received bytes but only percentage done)
Flashing latest berry drive

My appdaemon.yaml:
```yaml
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel/RESULT"
    panelSendTopic: "cmnd/nspanel/CustomSend"
    updateMode: "auto-notify"
    timeoutScreensaver: 15
    brightnessScreensaver:
      - time: "9:00:00"
        value: 10
      - time: "21:00:00"
        value: 0
    locale: "de_DE"
    timeFormat: "%H:%M"
    dateFormatBabel: "EEEE dd/M/y"
    weatherEntity: weather.openweathermap
    pages:
      - type: cardEntities
        heading: Licht
        items:
          - light.gastzimmer_licht_1
          - light.gastzimmer_licht_2
          - light.gastzimmer_licht_3
          - delete
      - type: cardThermo
        heading: Heizung
        item: climate.gastezimmer_thermostat
      - type: cardMedia
        heading: Musik
        item: media_player.mopidy_http_server_on_esprimominipc_2_6680
```
