### ISSUE TITLE
Cover and Lock do not adhere to color changes

### ISSUE THREAD

**Issue by PhiKapJames** [joBr99/nspanel-lovelace-ui#711]
This started because I realized the garage door (cover) no longer changes colors when is up.  Trying a couple different things, I noticed lock and cover do not use the color setting, light does.  In the example below, only light.office works to change colors based on state.
```
  config:
    locale: "en_US"
    model: "us"
    cards:
      - type: cardGrid
        title: Main
        key: cardgrid-main
        entities:
          - entity: cover.garage_door
            name: Garage Door
            color:
              "on": [255,0,0]
              "off": [0,0,255]
          - entity: lock.front_door
            name: Front Door
            color:
              "on": [255,0,0]
              "off": [0,0,255]
          - entity: light.office
            name: Office Lights
            color:
              "on": [255,0,0]
              "off": [0,0,255]
```
NSPanel Lovelace UI: v3.8.3
Using ESPHome: v2022.12.6
