### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Dark-Sider** [joBr99/nspanel-lovelace-ui#714]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

I use NSPanel with lovelace-ui in several rooms to control my Sonso system. Basic operation seems fine, however I can't see an option to access the Sonos favorites to select different radio stations or playlists. I would suggest to add such functionality, as the HomeAssistant media-control already has this built in.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
See the example with configured entities in the documentation.

https://docs.nspanel.pky.eu/card-media/

You can add entities to the bottom row of the card.

This also works in combination with service calls, so you can also configure it to call the service that is starting a playlist or a radio station.

https://docs.nspanel.pky.eu/entities/#calling-service-directly-as-button

```
      - type: cardMedia
        title: Kitchen
        entity: media_player.kitchen
        entities:
          - entity: light.bed_light
          - entity: service.light.turn_on
             data:
              entity_id: light.schreibtischlampe
              color_name: "green"
```
