### ISSUE TITLE
[Help] sleepBrightness error config?

### ISSUE THREAD

**Issue by copilador** [joBr99/nspanel-lovelace-ui#715]
### PROBLEM DESCRIPTION
Local sunset does not match the one being run on sleepBrightness

### REQUESTED INFORMATION
    sleepBrightness:
      - time: "sunrise"
        value: 10
      - time: "sunset"
        value: 0

locale: "es_ES"

### ADDITIONAL INFORMATION
The sunset in my location is at 18:12, but the screen does not switch to sleepBrightness: value: 0, but much later.
Do I have an error in the configuration? thank you

**Comment by joBr99** [comment]
You can configure an offset to the time, something like this:

```
    sleepBrightness:
      - time: "sunrise"
        value: 10
      - time: "sunset - 1:00:00"
        value: 0
```

Also make sure that the latitude and longitude and timezone in your appdaemon.yaml is correct.

```
---
secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.12345
  longitude: 4.12345
  elevation: 2
  time_zone: Europe/Berlin
```
