### ISSUE TITLE
[BUG] Delete entity does not work with Power Card

### ISSUE THREAD

**Issue by beanian** [joBr99/nspanel-lovelace-ui#716]
### PROBLEM DESCRIPTION
using ` entity: delete` breaks the Power Card.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
     cards:
      - type: cardPower
        entities:
          - entity: sensor.myenergi_home_home_consumption
            icon: home-lightning-bolt
          - entity: delete
          - entity: sensor.myenergi_home_power_generation
            icon: mdi:solar-panel
            color: [124,252,0]
          - entity: sensor.myenergi_eddi_21523979_internal_load_ct1
            icon: mdi:bathtub
            speed: -1
          - entity: sensor.myenergi_zappi_10179165_internal_load_ct1
            icon: mdi:ev-station
            speed: -10
          - entity: sensor.myenergi_home_power_export
            icon: mdi:transmission-tower-export
        title: Solar

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Include - entity:delete in the list of entities for the Power Card
### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
I should see an empty space where the delete entity is.

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._
 Here is the Power card with the delete entity added:
![image](https://user-images.githubusercontent.com/930359/214811632-10eb91aa-f6b9-44c2-9953-5898af06bee0.png)

An here it is with just that entity removed:
![image](https://user-images.githubusercontent.com/930359/214811783-be54da34-e35e-4807-91b3-40ac49290302.png)

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU
