### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by mic267** [joBr99/nspanel-lovelace-ui#717]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:
- [ ] esp home:
```
substitutions:
  devicename: nspanel
  friendly_devicename: NSPanel
  panel_recv_topic: "tele/nspanel/RESULT"
  panel_send_topic: "cmnd/nspanel/CustomSend"

esphome:
  name: $devicename

esp32:
  board: esp32dev

wifi:
  networks:
    - ssid: xxxxxxxxxx
      password: xxxxxxxxx

# Logger. Disable the temperature sensor etc. to focus on the HMI development
logger:
  level: DEBUG
  logs:
    sensor: WARN
    resistance: WARN
    text_sensor: WARN
    ntc: WARN

ota:
  safe_mode: true

# API. Add api_pwd to your secrets.yaml.
api:
  services:
    - service: upload_tft
      variables:
        url: string
      then:
        - lambda: |-
            id(nspanel).upload_tft(url);
    # Service to play a rtttl tone
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda "return song_str;"
    # Service to send a command directly to the display. Useful for testing
    - service: send_command
      variables:
        cmd: string
      then:
        - lambda: "id(nspanel).send_custom_command(cmd.c_str());"
    # Service to pusblish to mqtt used for refreshin the panel
    - service: publish_to_recv_topic
      variables:
        cmd: string
      then:
        - mqtt.publish:
            topic: $panel_recv_topic
            payload: !lambda "return cmd;"
    # Service to send a command wake the screen
    - service: wake
      then:
        - lambda: 'id(nspanel).send_custom_command("wake");'
    # Service to send a command to show screensaver (some of the values are hardcoded)
    - service: show_screensaver
      then:
        - mqtt.publish:
            topic: $panel_recv_topic
            payload: '{"CustomRecv":"event,sleepReached,cardGrid"}'
    # Service to navigate to screen
    - service: navigate_to_page
      variables:
        page: string
      then:
        - mqtt.publish_json:
            topic: $panel_recv_topic
            payload: |-
              root["CustomRecv"] = "event,buttonPress2,navigate." + page + ",button";
    # Service to send a command disable screensaver
    - service: disable_screensaver
      then:
        - lambda: 'id(nspanel).send_custom_command("timeout~0");'
    # Service to send a command enabled screensaver
    - service: enable_screensaver
      then:
        - lambda: 'id(nspanel).send_custom_command("timeout~20");'
    # Service to send a command wake the screen
    - service: dim_0_to_100
      variables:
        intensity: string
      then:
        - lambda: 'id(nspanel).send_custom_command("dimmode~"+intensity+"~100");'
    # Service to send a command To show the screen of a specific like
    - service: show_entity
      variables:
        entity: string
        title: string
      then:
        - lambda: 'id(nspanel).send_custom_command("pageType~popupLight~" + title + "~" + entity);'
    # Service to send a command To show the screen of a specific like
    - service: notify_on_screensaver
      variables:
        line1: string
        line2: string
      then:
        - lambda: 'id(nspanel).send_custom_command("notify~" + line1 + "~" + line2);'
        - rtttl.play: "short:d=4,o=5,b=100:16e6"
    # Service to send a command To show the screen of a specific like
    # interaction of the buttons are on implemented yet
    - service: notify_fullscreen
      variables:
        title: string
        description: string
        button1: string
        button2: string
        time_secs: string
      then:
        # show notification screen
        - lambda: 'id(nspanel).send_custom_command("pageType~popupNotify");'
        # set values on notification screen
        # color defined as number created in binary and converted to decimal (rrrrggggbbbbaaaa)
        - lambda: 'id(nspanel).send_custom_command("entityUpdateDetail~id~"+ title + "~65535~" + button1 +"~3840~" + button2 + "~61440~" + description + "~65535~" + time_secs);'
        - rtttl.play: "scale_up:d=32,o=5,b=100:c,c#,d#,e,f#,g#,a#,b"

# Uart for the Nextion display
uart:
  tx_pin: 16
  rx_pin: 17
  baud_rate: 115200

# Functionality for the Nextion display
external_components:
  - source:
      type: git
      url: https://github.com/sairon/esphome-nspanel-lovelace-ui
      ref: dev
    components: [nspanel_lovelace]

mqtt:
  id: mqtt_client
  broker: 192.168.178.153
  username: xxxxxxxxx
  password: xxxxxxxxx

nspanel_lovelace:
  id: nspanel
  mqtt_recv_topic: $panel_recv_topic
  mqtt_send_topic: $panel_send_topic

sensor:
  # Internal temperature sensor, adc value
  - platform: adc
    id: ntc_source
    pin: 38
    update_interval: 10s
    attenuation: 11db

  # Internal temperature sensor, adc reading converted to resistance (calculation)
  - platform: resistance
    id: resistance_sensor
    sensor: ntc_source
    configuration: DOWNSTREAM
    resistor: 11.2kOhm

  # Internal temperature sensor, resistance to temperature (calculation)
  - platform: ntc
    id: temperature
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: $friendly_devicename Temperature

output:
  # Buzzer for playing tones
  - platform: ledc
    id: buzzer_out
    pin:
      number: 21

# Rtttl function for buzzer
rtttl:
  id: buzzer
  output: buzzer_out

switch:
  # Physical relay 1
  - platform: gpio
    name: $friendly_devicename Relay 1
    id: relay_1
    pin:
      number: 22
    on_turn_on:
      # show a light on the panel when we swich on the light
      # - lambda: 'id(nspanel).send_custom_command("pageType~popupLight~[TITLE TO SHOW ON SCREEN]~[ENTITY NAME]");'
      - lambda: 'id(nspanel).send_custom_command("pageType~popupLight~Light 1~light.bed_light");'
    on_turn_off:
      # send to screensaver when switch off the light
      - mqtt.publish:
          topic: $panel_recv_topic
          payload: '{"CustomRecv":"event,sleepReached,cardGrid"}'

  # Physical relay 2
  - platform: gpio
    name: $friendly_devicename Relay 2
    id: relay_2
    pin:
      number: 19
    on_turn_on:
      # show a light on the panel when we swich on the light
      - lambda: 'id(nspanel).send_custom_command("pageType~popupLight~Light 2~light.bed_light2");'
    on_turn_off:
      # send to screensaver when switch off the light
      - mqtt.publish:
          topic: $panel_recv_topic
          payload: '{"CustomRecv":"event,sleepReached,cardGrid"}'

  # Turn screen power on/off. Easy way to configure the screen power control, but this should not be used from HA, as all components must be re-initialized afterwards. For lights, names of lights etc. this practically means that the state must change once to happen.
  - platform: gpio
    name: Screen Power
    id: screen_power
    entity_category: config
    pin:
      number: 4
      inverted: true
    restore_mode: ALWAYS_ON

# Binary sensors
binary_sensor:
  # Left button below the display
  - platform: gpio
    name: $friendly_devicename Left Button
    pin:
      number: GPIO14
      inverted: true
    id: left_button
    on_press:
      then:
        - switch.toggle: relay_1

  # Right button below the display
  - platform: gpio
    name: $friendly_devicename Right Button
    pin:
      number: GPIO27
      inverted: true
    id: right_button
    on_press:
      then:
        - switch.toggle: relay_2
```
- [ ] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:

secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Amsterdam
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: 192.168.178.153
      client_port: 1883
      client_user: "xxxxxxxxx"
      client_password: "xxxxxxxx"
      client_topics: NONE

http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
```
- [ ] Provide your apps.yaml:
```
  apps.yaml here:
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panel_recv_topic: "tele/nspanel/RESULT"
    panel_send_topic: "cmnd/nspanel/CustomSend" 
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "de_DE"

    screensaver:
      entity: weather.openweathermap
      alternativeLayout: True      
      theme:
        autoWeather: true
    cards:
      - type: cardGrid
        title: Test Grid Card
        entities:
          - entity: switch.leselicht
          - entity: switch.kugellampe
          - entity: switch.schranklicht
            name: Licht Tv Board
            icon: mdi:light  
            


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:

[14:25:49] INFO: Starting AppDaemon...
2023-01-26 14:25:51.377307 INFO AppDaemon: AppDaemon Version 4.2.1 starting
2023-01-26 14:25:51.377498 INFO AppDaemon: Python version is 3.10.9
2023-01-26 14:25:51.377628 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2023-01-26 14:25:51.377768 INFO AppDaemon: Added log: AppDaemon
2023-01-26 14:25:51.377862 INFO AppDaemon: Added log: Error
2023-01-26 14:25:51.377948 INFO AppDaemon: Added log: Access
2023-01-26 14:25:51.378044 INFO AppDaemon: Added log: Diag
2023-01-26 14:25:51.478061 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2023-01-26 14:25:51.590350 INFO HASS: HASS Plugin Initializing
2023-01-26 14:25:51.590611 INFO HASS: HASS Plugin initialization complete
2023-01-26 14:25:51.590866 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
2023-01-26 14:25:51.634483 INFO MQTT: MQTT Plugin Initializing
2023-01-26 14:25:51.634677 INFO MQTT: Using 'appdaemon/status' as Will Topic
2023-01-26 14:25:51.634816 INFO MQTT: Using 'appdaemon/status' as Birth Topic
2023-01-26 14:25:51.635228 INFO AppDaemon: Initializing HTTP
2023-01-26 14:25:51.635536 INFO AppDaemon: Using 'ws' for event stream
2023-01-26 14:25:51.637911 INFO AppDaemon: Starting API
2023-01-26 14:25:51.639697 INFO AppDaemon: Starting Admin Interface
2023-01-26 14:25:51.639920 INFO AppDaemon: Starting Dashboards
2023-01-26 14:25:51.651905 INFO HASS: Connected to Home Assistant 2023.1.7
2023-01-26 14:25:51.663367 INFO AppDaemon: App 'nspanel-1' added
2023-01-26 14:25:51.665076 INFO AppDaemon: Found 1 total apps
2023-01-26 14:25:51.665734 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2023-01-26 14:25:51.667677 INFO AppDaemon: Running on port 5050
2023-01-26 14:25:51.672537 INFO MQTT: Connected to Broker at URL 192.168.178.153:1883
2023-01-26 14:25:51.675611 INFO AppDaemon: Got initial state from namespace mqtt
2023-01-26 14:25:51.675861 INFO MQTT: MQTT Plugin initialization complete
2023-01-26 14:25:51.707873 INFO HASS: Evaluating startup conditions
2023-01-26 14:25:51.716035 INFO HASS: Startup condition met: hass state=RUNNING
2023-01-26 14:25:51.716224 INFO HASS: All startup conditions met
2023-01-26 14:25:51.731478 INFO AppDaemon: Got initial state from namespace default
2023-01-26 14:25:53.675116 INFO AppDaemon: Scheduler running in realtime
2023-01-26 14:25:53.677155 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2023-01-26 14:25:53.678148 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/hello.py - ignoring
2023-01-26 14:25:53.678762 INFO AppDaemon: App initialization complete
```
### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_
AppDaemon
Current version: 0.11.0

**Comment by joBr99** [comment]
Hey, 
the nspanel-lovelace-backend application is not properly installed and not loading at all.

Which type of HomeAssistant Installation are you using?

https://docs.nspanel.pky.eu/prepare_ha/#installing-lovelace-appdaemon-backend-application

In case you are using HA Core in a docker container, see the `Instructions for users of HomeAssistant Core installed through docker containers.` Note.

https://docs.nspanel.pky.eu/prepare_ha/#installing-appdaemon

**Comment by mic267** [comment]
Ha läuft bei mir unter Promox in einer Virtuellen Maschine. Wo finde ich die Anleitung? Danke im Vorraus

**Comment by joBr99** [comment]
gut also HomeAssistant OS?

Hast du die App aus HACS installiert?

https://docs.nspanel.pky.eu/prepare_ha/#installing-lovelace-appdaemon-backend-application

Sind die Dateien bei dir hier vorhanden?

![image](https://user-images.githubusercontent.com/29555657/214898391-88ce9b98-9bd2-4315-ad9e-87660d9977be.png)

**Comment by joBr99** [comment]
dann deinstallier und installier es nochmal in HACS

**Comment by mic267** [comment]
ok mach ich

**Comment by mic267** [comment]
jetzt ist es unter apps drin. was muss ich jetzt noch tun?

**Comment by joBr99** [comment]
starte das appdaemon addon mal neu und poste den log nochmal

**Comment by mic267** [comment]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: AppDaemon
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.11.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (amd64 / qemux86-64)
 Home Assistant Core: 2023.1.7
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
Looking in links: https://wheels.home-assistant.io/musllinux/
Collecting babel
  Downloading Babel-2.11.0-py3-none-any.whl (9.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 11.3 MB/s eta 0:00:00
Requirement already satisfied: pytz>=2015.7 in /usr/lib/python3.10/site-packages (from babel) (2021.3)
Installing collected packages: babel
Successfully installed babel-2.11.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[18:16:33] INFO: Starting AppDaemon...
2023-01-26 18:16:35.483899 INFO AppDaemon: AppDaemon Version 4.2.1 starting
2023-01-26 18:16:35.484089 INFO AppDaemon: Python version is 3.10.9
2023-01-26 18:16:35.484210 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2023-01-26 18:16:35.484310 INFO AppDaemon: Added log: AppDaemon
2023-01-26 18:16:35.484427 INFO AppDaemon: Added log: Error
2023-01-26 18:16:35.484518 INFO AppDaemon: Added log: Access
2023-01-26 18:16:35.484595 INFO AppDaemon: Added log: Diag
2023-01-26 18:16:35.556069 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2023-01-26 18:16:35.658350 INFO HASS: HASS Plugin Initializing
2023-01-26 18:16:35.658519 INFO HASS: HASS Plugin initialization complete
2023-01-26 18:16:35.658713 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
2023-01-26 18:16:35.698287 INFO MQTT: MQTT Plugin Initializing
2023-01-26 18:16:35.698451 INFO MQTT: Using 'appdaemon/status' as Will Topic
2023-01-26 18:16:35.698558 INFO MQTT: Using 'appdaemon/status' as Birth Topic
2023-01-26 18:16:35.698891 INFO AppDaemon: Initializing HTTP
2023-01-26 18:16:35.699130 INFO AppDaemon: Using 'ws' for event stream
2023-01-26 18:16:35.701334 INFO AppDaemon: Starting API
2023-01-26 18:16:35.703134 INFO AppDaemon: Starting Admin Interface
2023-01-26 18:16:35.703355 INFO AppDaemon: Starting Dashboards
2023-01-26 18:16:35.714571 INFO HASS: Connected to Home Assistant 2023.1.7
2023-01-26 18:16:35.732709 INFO AppDaemon: App 'nspanel-1' added
2023-01-26 18:16:35.733216 INFO AppDaemon: Found 1 total apps
2023-01-26 18:16:35.733483 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2023-01-26 18:16:35.734207 INFO MQTT: Connected to Broker at URL 192.168.178.153:1883
2023-01-26 18:16:35.734758 INFO AppDaemon: Running on port 5050
2023-01-26 18:16:35.746106 INFO AppDaemon: Got initial state from namespace mqtt
2023-01-26 18:16:35.746336 INFO MQTT: MQTT Plugin initialization complete
2023-01-26 18:16:35.763746 INFO HASS: Evaluating startup conditions
2023-01-26 18:16:35.772704 INFO HASS: Startup condition met: hass state=RUNNING
2023-01-26 18:16:35.772892 INFO HASS: All startup conditions met
2023-01-26 18:16:35.788588 INFO AppDaemon: Got initial state from namespace default
2023-01-26 18:16:37.745353 INFO AppDaemon: Scheduler running in realtime
2023-01-26 18:16:37.748131 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2023-01-26 18:16:37.748427 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui to module import path
2023-01-26 18:16:37.748661 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend to module import path
2023-01-26 18:16:37.748893 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations to module import path
2023-01-26 18:16:37.749215 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/backend to module import path
2023-01-26 18:16:37.749484 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/frontend to module import path
2023-01-26 18:16:37.758159 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/hello.py - ignoring
2023-01-26 18:16:37.758981 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py
2023-01-26 18:16:37.859046 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/theme.py - ignoring
2023-01-26 18:16:37.859863 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/apis.py - ignoring
2023-01-26 18:16:37.860605 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py - ignoring
2023-01-26 18:16:37.861393 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py - ignoring
2023-01-26 18:16:37.862204 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py - ignoring
2023-01-26 18:16:37.862870 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/config.py - ignoring
2023-01-26 18:16:37.863600 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icons.py - ignoring
2023-01-26 18:16:37.864375 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/localization.py - ignoring
2023-01-26 18:16:37.865237 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icon_mapping.py - ignoring
2023-01-26 18:16:37.865979 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/helper.py - ignoring
2023-01-26 18:16:37.866654 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/updater.py - ignoring
2023-01-26 18:16:37.867216 INFO AppDaemon: Initializing app nspanel-1 using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui
2023-01-26 18:16:37.912376 INFO nspanel-1: Starting
2023-01-26 18:16:37.915490 INFO nspanel-1: Input config: {'panel_recv_topic': 'tele/nspanel/RESULT', 'panel_send_topic': 'cmnd/nspanel/CustomSend', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': [{'time': '7:00:00', 'value': 10}, {'time': '23:00:00', 'value': 0}], 'locale': 'de_DE', 'screensaver': {'entity': 'weather.openweathermap', 'alternativeLayout': True, 'theme': {'autoWeather': True}}, 'cards': [{'type': 'cardGrid', 'title': 'Test Grid Card', 'entities': [{'entity': 'switch.leselicht'}, {'entity': 'switch.kugellampe'}, {'entity': 'switch.schranklicht', 'name': 'Licht Tv Board', 'icon': 'mdi:light'}]}]}
2023-01-26 18:16:37.916254 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/tasmota_your_mqtt_topic/RESULT', 'panelSendTopic': 'cmnd/tasmota_your_mqtt_topic/CustomSend', 'updateMode': 'auto-notify', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': [{'time': '7:00:00', 'value': 10}, {'time': '23:00:00', 'value': 0}], 'screenBrightness': 100, 'defaultBackgroundColor': 'ha-dark', 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': None, 'locale': 'de_DE', 'timeFormat': '%H:%M', 'dateFormatBabel': 'full', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'homeButton': False, 'cards': [{'type': 'cardGrid', 'title': 'Test Grid Card', 'entities': [{'entity': 'switch.leselicht'}, {'entity': 'switch.kugellampe'}, {'entity': 'switch.schranklicht', 'name': 'Licht Tv Board', 'icon': 'mdi:light'}]}], 'screensaver': {'type': 'screensaver', 'entity': 'weather.openweathermap', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': False, 'alternativeLayout': True, 'defaultCard': None, 'key': 'screensaver', 'theme': {'autoWeather': True}}, 'hiddenCards': [], 'panel_recv_topic': 'tele/nspanel/RESULT', 'panel_send_topic': 'cmnd/nspanel/CustomSend'}
2023-01-26 18:16:37.920144 INFO nspanel-1: Sending MQTT Message: pageType~pageStartup
2023-01-26 18:16:37.928235 INFO nspanel-1: Registering callbacks for the following items: ['switch.leselicht', 'switch.kugellampe', 'switch.schranklicht', 'weather.openweathermap']
2023-01-26 18:16:37.935170 INFO nspanel-1: Started
2023-01-26 18:16:37.936175 INFO AppDaemon: App initialization complete

**Comment by joBr99** [comment]
mit deiner apps.yaml stimmt was nicht, recv/send muss so aussehen:

```yaml
nspanel-kueche:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel/RESULT"
    panelSendTopic: "cmnd/nspanel/CustomSend"
```
