### ISSUE TITLE
[Feature Request] Add support for single entity as a separated page

### ISSUE THREAD

**Issue by yfrans** [joBr99/nspanel-lovelace-ui#720]
### FEATURE DESCRIPTION
Add support for a single entity card as a separated page / sub-page

### ADDITIONAL CONTEXT
Similar to "cardThermo" or "cardMedia" which point to a single entity, add support to "cardEntity" which can point to a single entity from other types as well.
For example: show the properties of a light as a page and not by long-pressing the light entity.

### PANEL / FIRMWARE VERION
 US-L

**Comment by aussiebum71** [comment]
I didn't know about the long press taking you to the entity page. So I was doing as you are requesting by using the ESPHome function for the panel. For example.

          - entity: service.esphome.nspanel_livingroom_show_entity
            data:
              entity: light.ceiling_light
              title: Ceiling

**Comment by byraff613** [comment]
How would you do this on Home assistant?

**Comment by aussiebum71** [comment]
If you're using ESPHome in HomeAssistant for the NSPanel. You can add an api service. Then that service will show up in Services in HomeAssistant. 

```
api:
  services:
    # Service to send a command to show the screen of a specific like
    - service: show_entity
      variables:
        entity: string
        title: string
      then:
        - lambda: 'id(nspanel).send_custom_command("pageType~popupLight~" + title + "~" + entity);'
```

Full example NSPanel ESPHome code at https://github.com/sairon/esphome-nspanel-lovelace-ui/blob/dev/examples/advanced-config.yml
