### ISSUE TITLE
[Feature Request] Adding entity names to Power Card

### ISSUE THREAD

**Issue by magnusoverli** [joBr99/nspanel-lovelace-ui#722]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
Display an entity name with the entities on the Power Card. Icons alone are not enough to make the Power Card readable enough at a glance. This is especially true when there are identical devices in more than one room. Then there is no way to differentiate the different entities in the Power Card based on icons alone.
### ADDITIONAL CONTEXT
_Add any other context about the problem here._
Example of possible config:
```
      - type: cardPower
        title: ""
        key: power
        entities:
          - entity: sensor.ams_power_active
            icon: home-lightning-bolt-outline
            color: [255,255,251]
            name: Total
          - entity: delete
          - entity: sensor.hvac_sensor_active_power
            name: HVAC
            color: [255,255,251]
```
### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
