### ISSUE TITLE
[BUG] Notification does not disappear when it is manual sent to the screen saver page

### ISSUE THREAD

**Issue by dylanpedro** [joBr99/nspanel-lovelace-ui#728]
When a message is sent manually to the screensaver, it doesn't disappear after some time. The NSPanel is using ESPHome not tasmota

### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
What kind of Notification? There are two different types ... Also what's the message you've sent to the panel?

**Comment by dylanpedro** [comment]
I am using the following service to send a message:

esphome.nspanel1_notify_on_screensaver

When my doorbell detects a person it triggers an automation to send "Person Detected" as the message but I've noticed the message will not clear by itself automatically and will only clear if you navigate to a different page first manually

**Comment by randybb** [comment]
Just checking and I can confirm, that it stays on. Esphome is executing `id(nspanel_id).send_custom_command("notify~" + line1 + "~" + line2);` like it is documented [Send Message to the Screensaver](https://docs.nspanel.pky.eu/notifications/#notification-on-screensaver).

**Comment by randybb** [comment]
Taking it back :) We have discussed about this a long time ago, so I modified my service accordingly :)
```yaml
api:
  services:
    - service: notify
      variables:
        heading: string
        message: string
        song: string
      then:
        - lambda: 'id(nspanel_id).send_custom_command("notify~" + heading + "~" + message);'
        - rtttl.play:
            rtttl: !lambda 'return song;'
        - delay: 10s
        - lambda: 'id(nspanel_id).send_custom_command("notify~~");'
```
