### ISSUE TITLE
Unable to replicate screensavor config shown in 3.9.4 release notes

### ISSUE THREAD

**Issue by johntdyer** [joBr99/nspanel-lovelace-ui#735]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

In the release notes it shows two entities on the bottom left... 
![image](https://user-images.githubusercontent.com/58234/215872778-4ddbbc30-45c1-450b-b677-325ad3c25c97.png)

I cant however find any info in the docs showing how to add two sensors in this place... any help would be appreciated .. Thanks again !

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:

spanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_0DBF2C/RESULT"
    panelSendTopic: "cmnd/tasmota_0DBF2C/CustomSend"
    model: us-l
    sleepTimeout: 40
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "22:00:00"
        value: 0
    locale: "en_US"
    screensaver:
      theme:
        time: [65, 105, 225]
        date: [220, 255, 0]
        tMainText: [220, 255, 0]
      statusIcon1:
        entity: binary_sensor.sun_dark_enough
        altFont: True
        icon: mdi:alert
      show_forecast: true
      alternativeLayout: true
      autoWeather: true
      key: screensaver
      entity: weather.openweathermap
      weatherUnit:
        fahrenheit
```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
Using a 6th entity will automatically activate the alternative layout.
```
    screensaver:
      entities:
        - entity: weather.demo_weather_north
        - entity: weather.demo_weather_north
          type: 0
        - entity: weather.demo_weather_north
          type: 1
        - entity: sensor.energy_usage
        - entity: delete
        - entity: sensor.indoor_temp
          icon: mdi:home-thermometer-outline
 ```
 
 https://docs.nspanel.pky.eu/config-screensaver/#possible-configuration-values-for-screensaver-config
