### ISSUE TITLE
[Feature Request] Customize OTA Urls

### ISSUE THREAD

**Issue by joBr99** [joBr99/nspanel-lovelace-ui#736]
Is there a way to change that internal OTA URL, e.g. to the home assistant shared folder ?

I currently use
`FlashNextion http://homeassistant.local:8123/local/firmware/nspanel-us-p.tft`

_Originally posted by @phoenixtechnam in https://github.com/joBr99/nspanel-issue-graveyard/issues/62

**Comment by joBr99** [comment]
Added config options for the OTA URLs:

```yaml
  config:
    panelRecvTopic: "tele/tasmota_NsPanelTerrasse/RESULT"
    panelSendTopic: "cmnd/tasmota_NsPanelTerrasse/CustomSend"
    displayURL-US-L: "http://example.com/us-l.tft"
    displayURL-US-P: "http://example.com/us-l.tft"
    displayURL-EU: "http://example.com/us-l.tft"
    berryURL: "http://exampe.com/autoexec.be"
```
