### ISSUE TITLE
[Feature Request] More Info on Screensaver

### ISSUE THREAD

**Issue by SurfGargano** [joBr99/nspanel-lovelace-ui#739]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

Ich hätte ich gern noch ein paar mehr Infos auf dem Screensaver.
(z.B. Solar kW, evtl . ein Icon für die Frau, jetzt kannst Du die Waschmaschine anwerfen,
falls ich mal zu Tibber wechsele : Auch da die Infos)
Da ist dann ein Blick auf das Panel ohne Wechseln der Seiten hilfreich.
Die Uhrzeit ist ziemlich groß, da passt daneben noch ein paar Infos.
-> Uhrzeit kleiner und rechts daneben ein Grid (2 horizontal x 4 vertikal) mit 4 Icons und 4 Zahlen oder Text
-> Icons und Zahlen oder Text 'on-the-fly' änderbar.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by Harrie62** [comment]
The clock on the screensaver  takes a lot off space. 
It could be a bit smaller and move more to the right.
Than in the left top corner add the room temperature (from NS panel?).

**Comment by SurfGargano** [comment]
Nice, that was I am looking for.
Is the weather days info alternately with the current weather info , like the existing one ?

**Comment by joBr99** [comment]
It works with the exact same serial commands the other screensaver is working, so changes on Iobroker/homeassistent side are minimal to get the alternative version. However everything I'm saying is related to homeassistent :)

@Armilar just extend the weatherUpdate for (a lot) more entities

**Comment by joBr99** [comment]
adding in the config example used in the above screenshot

```yaml
  config:
    panelRecvTopic: "tele/tasmota_debug/RESULT"
    panelSendTopic: "cmnd/tasmota_debug/CustomSend"
    sleepTimeout: 20
    sleepBrightness: 40
    screenBrightness: 100
    dateFormat: "%A, %d.%m"
    screensaver:
      type: screensaver2
      entities:
        - entity: weather.demo_weather_north
        - entity: sensor.outside_temperature
        - entity: sensor.outside_temperature
        - entity: sensor.outside_temperature
        - entity: weather.demo_weather_north
          type: 1
        - entity: weather.demo_weather_north
          type: 2
        - entity: weather.demo_weather_north
          type: 3
        - entity: sensor.total_gas_m3
        - entity: sensor.carbon_dioxide
        - entity: sensor.today_energy
        - entity: light.bed_light
          icon: mdi:bed
        - entity: light.kitchen_lights
          icon: mdi:fridge-outline
        - entity: light.office_rgbw_lights
          icon: mdi:office-building
        - entity: switch.ac
          icon: mdi:home-thermometer
        - entity: fan.ceiling_fan
      doubleTapToUnlock: True
      statusIcon1:
        entity: switch.decorative_lights
      statusIcon2:
        entity: light.office_rgbw_lights
        icon: "txt:test12345"
```

added the page to the development version (EU) and also added the code needed in homeassistant to get it working
