### ISSUE TITLE
[Feature Request] Disable screensaver per card

### ISSUE THREAD

**Issue by EddyK69** [joBr99/nspanel-lovelace-ui#746]
### FEATURE DESCRIPTION
I would like to have an option to prevent that the screensaver kicks in, per card. If I have for example my powercard open with, I would like it be displayed permanently until I press the home button.

### ADDITIONAL CONTEXT
n/a

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
the screensaver is a normal card, you can add a key to it and use it with navigate

**Comment by EddyK69** [comment]
> the screensaver is a normal card, you can add a key to it and use it with navigate

I think this is an comment for #747 ?

**Comment by LucaBors** [comment]
Ciao,
since you are already working on this is it possible to also add it to alarmcard?
something like: if alarm is not in state disable (so all the other state) don't activate screensaver.

Luca :)

**Comment by joBr99** [comment]
I implemented something; however the python part is still missing and as you can see it is added to the next release.

**Comment by joBr99** [comment]
should be possible to set the timeout per card in current dev version:

```
      - type: cardGrid
        title: Wohnzimmer
        key: home-wohn
        sleepTimeout: 3
        entities:
          - entity: navigate.szenen
```

A sleepTimeout of 0 disables the timeout.
