### ISSUE TITLE
[Feature Request] sensor info on screensaver

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#75]
Hi 
is it possible to add some sensor info like room Temp, Air quality sensor onto the screensaver ? and it would be great if the switches status can appear on all the pages and screensaver like the original firmware ?

**Comment by joBr99** [comment]
With the current development version you can override the Weather Forecast on the screensaver:

````yaml
    weather: weather.k3ll3r
    weatherOverrideForecast1: sensor.vicare_outside_temperature
    weatherOverrideForecast2: sensor.vicare_outside_temperature
    pages:
````

**Comment by hatran0884** [comment]
I think it would be great if you have a space for the sensor info, i still want to keep the weather forecast there. Nevermind, you can do this later if you want

**Comment by joBr99** [comment]
the space on this page is limited, where should an additional sensor information go?

**Comment by Chreece** [comment]
I'm on with it... Some custom data on the screensaver would benefit any user :)
Maybe the clock is too big?

@joBr99 you are doing a great job, it's the most maintained project I follow, so many features and changes in a little time!
Passioned people like you move the DIY community further!
Keep up!!!

**Comment by joBr99** [comment]
```
    dateFormat: "%A, %d. %B %Y"
    weather: weather.k3ll3r
    weatherOverrideForecast2:
      sensor.temp_wohn_temperature:
        name: Innen
    pages:
```
![image](https://user-images.githubusercontent.com/29555657/160250640-0f500491-a473-4133-9b48-82f41fd0c9dd.png)

This is what's currently possible with the override feature.

I see the following challanges for additional data on this page

- time should be readable without standing close to the panel
- space on that page is limited
- it has to be implemented in a way that it doesn't look empty or uncented in case additonal sensors are unused

Moving the clock more to the center & placing additional stuff at the top is also not really satisfying and looks overloaded.
![image](https://user-images.githubusercontent.com/29555657/160251306-055bbbc6-13d8-4f6f-add8-a001bf70e724.png)
