### ISSUE TITLE
[Feature Request] adding a panel for departure timetable for train stops

### ISSUE THREAD

**Issue by rossi75** [joBr99/nspanel-lovelace-ui#759]
### FEATURE DESCRIPTION
showing a departure timetable for a station

### ADDITIONAL CONTEXT
Time table filtering is already done by a RestAPI within HomeAssistant. So the departure time table exists as many many entities, like line number, direction, optional delay, departure HH, departure MM.

So I want to bring those many entries/lines/departures on the display, only for viewing at this point, maybe additional a reload button or for navigating to the next slide with more departures. Anything similar to a flex table (HACS)

Should look similar like:
`         Duisburg-Rahm           `
`S1  Langenfeld HBF     +5 09:36`
`S2  Hamburg HBF           09:39`
`786 München-Hofbräu... +8 10:10`
`i: Aufzug defekt ! Verspätungen aufgrund von Schneefall im Sauerland`

If the strings are too long, cut them or maybe later an option to let them scroll through automatically or via touch :)

### PANEL / FIRMWARE VERION
EU-Version, V3.94

**Comment by joBr99** [comment]
you should be able to configure this with a cardEntities (execpt for the "Lauftext"?)

it is possible to override the name, value and also the icon and you can use ha templates within the overrides

```
        - entity: sensor.temp_bad_temperature
          value: '{{states("sensor.temp_bad_temperature") | round(1)}}°C'
          name: '{{states("sensor.temp_bad_temperature")}}°C'
          icon: 'ha:{{int(states("sensor.temp_bad_humidity")) }}'
```

(Examples dosn't make a lot of sense; I just copied some lines from my config together as an exmaple)

**Comment by rossi75** [comment]
works a bit for me, thanks. More formatting options would be great at this point.

**Comment by rossi75** [comment]
So here is the code. The entities "StopTableDepart0x" were extracted from a JSON request/response:
```
      - type: cardEntities
        title: Hellerhof S
        key: CardStation_1
        navItem1:
          entity: navigate.Home
          icon: mdi:home
        navItem2:
          entity: navigate.CardStation_2
          icon: mdi:arrow-right-bold
        entities:
          - entity: sensor.stoptabledepart01delay
            state: "0"                                                          # pünktlich
            color: "[0, 255, 0]"                                                # grün
            icon: 'ha: {{states("sensor.stoptabledepart01linename")}}'
            name: '{{states("sensor.stoptabledepart01dest")}}'
            value: '{{states("sensor.stoptabledepart01hhmm")}}'
          - entity: sensor.stoptabledepart01delay
            state_not: "0"                                                      #verspätet
            color: "[255, 255, 0]"                                              # gelb
            icon: 'ha: {{states("sensor.stoptabledepart01linename")}}'
            name: '{{states("sensor.stoptabledepart01dest")}}'
            value: '+{{states("sensor.stoptabledepart01delay")}}: {{states("sensor.stoptabledepart01hhmm")}}'
```

the entites for every row/departure. Maybe someone has an idea how to check for two conditions simultaneously? Due to the strike I figured out a third condition which I need to consider (-9999, 0, >0) for the state of *delay...


![DSC_3388](https://user-images.githubusercontent.com/91349581/217943604-9bbdab8d-90f2-4f13-9667-d82931cef92b.JPG)
