### ISSUE TITLE
[Feature Request] Extra screensaver card to navigate to

### ISSUE THREAD

**Issue by EddyK69** [joBr99/nspanel-lovelace-ui#769]
### FEATURE DESCRIPTION
I'd like to add an extra screensaver type card that I can navigate to (and which disables the default screensaver card). The default screensaver would just work like it is now (after timeout it will kick in) but when I navigate to the extra screensaver card with other or extra content, it will disable the default screensaver (#746)

### ADDITIONAL CONTEXT
I know the default screensaver is just a normal card with a key to navigate to, but is it possible to add multiple screensaver cards?

### PANEL / FIRMWARE VERION
EU, latest dev-version

**Comment by joBr99** [comment]
What's the difference to setting the the timeout to zero on that card?

**Comment by EddyK69** [comment]
> What's the difference to setting the the timeout to zero on that card?

None, no difference. The only I'd like to know how I can make an extra card in the style of a screensaver-card type 2? So with the time in the right upper corner and all the extra icons. I could set this timeout to 0 and use a navigate.screensaver2. But how do I make an extra screensaver card? What should the card-type be?
```
    cards:
      - type: ???
        key: screensaver2
        title: Alternative Screensaver
```

**Comment by joBr99** [comment]
type is `screensaver2` however this might have other drawbacks that not sure and you might have to use `defaultCard` in you configuration

**Comment by EddyK69** [comment]
It doesn't seem to work that good: the `defaultCard` isn't working as well as the entities. They seem to get fetched from the default screensaver entities.

```
    screensaver:
      key: screensaver-1
      defaultCard: navigate.main-1
      theme:
        time: [255, 255, 255]
      type: screensaver2
      entities:
        - entity: weather.lokale_buienradar
        - entity: sensor.room_temp_thermostat_awb
          icon: mdi:home-thermometer-outline
          color: [245, 166, 66]
        - entity: sun.sun
          icon: mdi:weather-sunset-up
          value: '{{state_attr("sun.sun", "next_rising")|as_timestamp|timestamp_custom("%H:%M")}}'
          color: [255, 255, 255]
        - entity: sun.sun
          icon: mdi:weather-sunset-down
          value: '{{state_attr("sun.sun", "next_setting")|as_timestamp|timestamp_custom("%H:%M")}}'
          color: [255, 255, 255]
#...
#...
#...
    hiddenCards:
      - type: screensaver
        title: TEST ScreenSaver
        key: test-saver
        defaultCard: navigate.main-3
        theme:
          time: [255, 255, 0]
        entities:
          - entity: weather.lokale_buienradar 
```

![IMG_8682 klein](https://user-images.githubusercontent.com/13943630/220920560-23524eb6-b888-4b09-a5f3-d29a768cdc61.jpeg)
