### ISSUE TITLE
[Feature Request] - Be able to swap entity short and long press and also overide with navigate to

### ISSUE THREAD

**Issue by aussiebum71** [joBr99/nspanel-lovelace-ui#770]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
**I would like to be able to change swap and change the action from a short or long press on the entity to something else.** 

**Example** 
The two physical buttons on the panel are associated with light entities. Pressing the button toggles the entity on or off dependong upon the configuration programmed.  I'm also able to display the properties page when using ESPhome shortly after pressing the panel button as per below 

```
# Home Assistant Automation
alias: When Bedroom Panel Right Button is Pressed
description: ""
trigger:
  - type: turned_on
    platform: device
    device_id: d904f7d932bf08102eec145a57c94b02
    entity_id: binary_sensor.bedroom_panel_right_button
    domain: binary_sensor
condition: []
action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.hue_bedroom
mode: single

# ESPHome config
# Right button below the display
  - platform: gpio
    name: $friendly_devicename Right Button
    pin:
      number: GPIO27
      inverted: true
    id: right_button
    on_press:
      then:
        - delay: 2s
        - lambda: 'id(nspanel).send_custom_command("pageType~popupLight~Hue Bedroom~light.hue_bedroom");'
```

On the touch panel I also have added the light entity to say a cardCrid. Tapping on the entity will toggle the light on or off with a short press. As the physical button is already programmed for this light entity to this, it would be good to be able to swap the short press and long press round. A short press would instead bring up the light entity page. And a long press toggles the light on or off.

Additionally it be would ideal to also overide the long or short press.  In this example **light.hue_bedroom** is actually a light group. So long pressing on the entity for instance would navigate to a hidden page that could show all the individual entities in the light group.

```
#Example with modified buttons enabled.

      - type: cardEntities
        title: Bedroom
        entities:
          - entity: light.hue_bedroom
              swap_buttons: true
              override_longpress: navigate.nbed 
           
      - type: cardEntities
        key: nbed
        title: Hue Bedroom
        entities:
          - entity: light.hue_bedroom
            name:All Hue Bedroom
          - entity: light.left_bedside_lamp
            name: Left Bedside
          - entity: light.right_bedside_lamp
            name: Right Bedside
          - entity: light.corner_lamp
            name: Corner Lamp
```

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
V3.9.4 Latest EU
