### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by Harrie62** [joBr99/nspanel-lovelace-ui#776]
<html>
<body>

Hello, probebly not a big issue but i bought a second NSpanel.
Flashed it with TASMOTA 12.4.0.1 and did all the next steps.
Until the part with appdeamon.
Is it possible to add a second nspanel?

Program Version | 12.4.0.1(tasmota)
-- | --
2023-02-18T13:34:02
2_0_6/4.4.3.20230129
0T00:05:25
32
14
Software reset CPU
Tasmota NSPanel

 
 

</body>
</html>

### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:

- [ ] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:


```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:


```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_

**Comment by joBr99** [comment]
as simple as adding a second section to apps.yaml:

```yaml
nspanel-kitchen:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_nspkueche/RESULT"
    panelSendTopic: "cmnd/tasmota_nspkueche/CustomSend"



nspanel-bathroom:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_nspbath/RESULT"
    panelSendTopic: "cmnd/tasmota_bath/CustomSend"



```
