### ISSUE TITLE
[BUG] Power Card Appears to have issues with US Portrait

### ISSUE THREAD

**Issue by Theron21** [joBr99/nspanel-lovelace-ui#781]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

The following produces a box that flashes with the icon and is then replaced by a blue "1" in the box.  This is with US Portrait.

```
      - type: cardPower
        title: Power Usage
        key: PowerUsage
        entities:
          - entity: sensor.home_energy_meter_gen5_electric_consumption_kwh
            icon: mdi:home
```
### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:

nspanel-2:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "<Supressed>"
    panelSendTopic: "<Supressed>"
    model: us-p
    timeFormat: "%I:%M   ?%p"
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 20
      - time: "23:59:00"
        value: 5
    locale: "en_US"
    homeButton: true
    screensaver:
      entity: weather.openweathermap
      weatherUnit: fahrenheit
      defaultCard: navigate.cardGrid_MainMenu
      statusIcon1:
        entity: alarm_control_panel.safe_alarm_panel
        name: Alarm
        icon: mdi:security
        altFont: True
      statusIcon2:
        entity: binary_sensor.entry_ways
        name: Windows & Doors
        icon: mdi:door-closed-lock
        altFont: True
    cards:
      - type: cardGrid
        title: Menu
        key: MainMenu
        entities:
        - entity: navigate.cardGrid_Switches1
          icon: mdi:lightbulb
          name: Lighting
        - entity: navigate.cardEntities_Environment
          icon: mdi:thermometer
        - entity: navigate.cardEntities_SecurityCard
          icon: mdi:lock
          name: Security
        - entity: navigate.cardGrid_MediaCard
          icon: mdi:remote
        - entity: input_button.button_arm_instant
          name: Home Instant
          icon: mdi:shield-home
        - entity: input_button.goodnight
          name: Night Shutdown
          icon: mdi:weather-night
    hiddenCards:
      - type: cardAlarm
        title:  Alarm
        key: Alarm1
        entity: alarm_control_panel.safe_alarm_panel
      - type: cardGrid
        title: Lighting
        key: Switches1
        entities:
          - entity: input_button.tv_lighting
            name: TV Lighting
            icon: mdi:television
          - entity: input_button.movie_lighting
            name: Movie Lighting
            icon: mdi:movie-check-outline
          - entity: input_button.cleaning_lighting
            name: Cleaning Lighting
            icon: mdi:broom
          - entity: input_button.day_lighting
            name: Day Lighting
            icon: mdi:sun-clock
          - entity: light.open_living_area_hue_lights
            name: Hue Lights
          - entity: navigate.cardEntities_HueScenes
            name: Hue Scenes
      - type: cardEntities
        title: Hue Scenes
        key: HueScenes
        entities:
          - entity: scene.open_living_area_hue_lights_color_burst
            name: Color Burst
          - entity: scene.open_living_area_golden_star
            name: Golden Star
      - type: cardEntities
        title: Environment
        key: Environment
        entities:
          - entity: navigate.cardPower_PowerUsage
            name: Power Usage
            icon: mdi:transmission-tower-export
          - entity: navigate.cardEntities_LivingAreaTempCard
            name: Temperature
            icon: mdi:thermometer
          - entity: switch.fireplace
            name: Fireplace
            icon: mdi:fireplace
          - entity: fan.fan
            name: Fan
            icon: mdi:fan
          - entity: navigate.cardThermo_1stThermostat
            name: Thermostat
            icon: mdi:thermometer
      - type: cardEntities
        title: ""
        key: SecurityCard
        entities:
          - entity: binary_sensor.front_door_alarm_sensor
            name: Front Door
            icon: mdi:door
          - entity: binary_sensor.back_door_alarm_sensor
            name: Back Door
            icon: mdi:door
          - entity: cover.z_wave_garage_door_controller
            name: Garage
          - entity: lock.front_door_lock
            name: Front Lock
          - entity: navigate.cardEntities_Windows1
            name: Windows
            icon: mdi:window-closed-variant
          - entity: navigate.cardAlarm_Alarm1
            name: Alarm
            icon: mdi:security
      - type: cardThermo
        title: Thermostat
        key: 1stThermostat
        entity: climate.lyric_t9_thermostat
        temperatureUnit: fahrenheit
      - type: cardMedia
        title: Apple TV
        key: AppleTVPlayer
        entity: media_player.loft
      - type: cardMedia
        title: Google Home
        key: GoogleHomePlayer
        entity: media_player.loft_google_home
      - type: cardGrid
        title: Media
        key: MediaCard
        entities:
          - entity: automation.loft_projector_on_2
            name: Projector On
            icon: mdi:projector
          - entity: automation.loft_projector_off
            name: Projector Off
            icon: mdi:projector-off
          - entity: navigate.cardMedia_AppleTVPlayer
            name: Apple TV
            icon: mdi:apple
          - entity: navigate.cardMedia_GoogleHomePlayer
            name: Google Home
            icon: mdi:music
      - type: cardEntities
        title: Windows
        key: Windows1
        entities:
          - entity: binary_sensor.master_rear
            name: Master Rear
            icon: mdi:window-closed-variant
          - entity: binary_sensor.master_side
            name: Master Side
            icon: mdi:window-closed-variant
          - entity: binary_sensor.kitchen_left
            name: Kitchen Left
            icon: mdi:window-closed-variant
          - entity: binary_sensor.kitchen_right
            name: Kitchen Right
            icon: mdi:window-closed-variant
          - entity: binary_sensor.office_left
            name: Office Left
            icon: mdi:window-closed-variant
          - entity: binary_sensor.office_right
            name: Office Right
            icon: mdi:window-closed-variant
      - type: cardPower
        title: Power Usage
        key: PowerUsage
        entities:
          - entity: sensor.home_energy_meter_gen5_electric_consumption_kwh
            icon: mdi:home
      - type: cardEntities
        title: Temperature
        key: LivingAreaTempCard
        entities:
          - entity: sensor.honeywell_livingroom_thermostat_current_temperature
            name: Living Room
          - entity: sensor.honeywell_kitchen_air_sensor_temperature
            name: Kitchen
          - entity: sensor.honeywell_office_air_sensor_temperature
            name: Office

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
2023-02-22 18:30:26.549057 INFO nspanel-2: Received Message from Screen: event,buttonPress2,navigate.cardPower_PowerUsage,button
2023-02-22 18:30:26.550277 INFO nspanel-2: Button Press Event; entity_id: navigate.cardPower_PowerUsage; button_type: button; value: None 
2023-02-22 18:30:26.552628 INFO nspanel-2: Sending MQTT Message: pageType~cardPower
2023-02-22 18:30:26.564387 INFO nspanel-2: Sending MQTT Message: entityUpd~Power Usage~x~navUp~���~65535~~~delete~~~~~~17299~���~1~59.16 kWh

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._
NS Panel Photo Showing Issue:
![image0 (1)](https://user-images.githubusercontent.com/87958904/220787848-aef67a1f-8148-4f70-b913-e859267fe732.jpeg)

What I see in Home Assistant
![2023-02-22 18_37_59-Energy – Home Assistant](https://user-images.githubusercontent.com/87958904/220788285-838ec462-57fc-4b21-aabb-519045c175d3.png)

The sensors for Aeotec Gen5 Zwave Energy Monitor
![2023-02-22 18_38_35-Settings – Home Assistant](https://user-images.githubusercontent.com/87958904/220788412-eb04ba58-6d95-4006-ae45-881b1a290592.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
3.9.4 (US-P)
