### ISSUE TITLE
Screensaver - separate sources icon/text for entity(0) + buzzer

### ISSUE THREAD

**Issue by YeeYek** [joBr99/nspanel-lovelace-ui#782]
### FEATURE DESCRIPTION
Hi
It would be nice if it was possible on screensaver to separate the location of the icon collection (cloudy - eg accuweather) from the temperature sensor (with airly) for entity(0).

In addition, is it possible to trigger a beeper for the screensaver when the status changes (depending on the state of the door opening sensor, the color of the font on the screensaver changes from white to red, I would like the beeper to be heard also when opening)? My code:
`      theme:
        time:                     '{{iif(states("binary_sensor.drzwi_tyl_contact")=="off", "[255,255,255]","[170,12,12]")}}'
`

### ADDITIONAL CONTEXT
Due to incorrect indications from weather providers (openweathermap, accuweather, etc.), I use the temperature readings from a nearby Airly sensor. Unfortunately, there I can download data about temperature, pollution, etc., but there is no information about cloud cover.
For this reason, on the screensaver, I have the outdoor temperature configured as entity (1), and cloud cover data as entity (0).

### PANEL / FIRMWARE VERION
Panel Version:	12.1.1(tasmota)/NS Panel 3.9.4 (EU)
![20230225_131157_2](https://user-images.githubusercontent.com/77362116/221361120-3dd54966-dfef-46e3-9c2d-80371af93bfb.jpg)
![20230225_131129_2](https://user-images.githubusercontent.com/77362116/221361126-c8a2ff3c-6349-4206-80fd-c894f0d4ae55.jpg)

**Comment by joBr99** [comment]
Try something like this:
```
    screensaver:
      entities:
        - entity: weather.k3ll3r
          value: sensor.outdoor_temp
        - entity: weather.k3ll3r
          type: 0
        - entity: weather.k3ll3r
          type: 1
        - entity: weather.k3ll3r
          type: 2
        - entity: weather.k3ll3r
          type: 3
```
