### ISSUE TITLE
[Feature Request] Min/max weather forecast temperatures in screensaver

### ISSUE THREAD

**Issue by soyxan** [joBr99/nspanel-lovelace-ui#791]
### FEATURE DESCRIPTION
At this moment the weather forecast in the screensaver shows only the maximum temperature. It would be nice to have the option to show min/max temperatures.

### ADDITIONAL CONTEXT
This is already implemented in ioBorker as per the following post:
https://github.com/joBr99/nspanel-lovelace-ui/issues/739#issuecomment-1423287124

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
This should be actually already possible by configuring an homeassistent template with 'value' on the entities.

**Comment by jrspowers** [comment]
@joBr99 what should the template look like.  ?  wall wouldn't know how?

**Comment by joBr99** [comment]
something like this should work:

```yaml
    screensaver:
      doubleTapToUnlock: True
      entities:
        - entity: weather.k3ll3r
        - entity: weather.k3ll3r
          type: 0
          value: "{{state_attr('weather.openweathermap', 'forecast')[0].templow}} {{state_attr('weather.openweathermap', 'forecast')[0].temperature}}"
        - entity: weather.k3ll3r
          type: 1
          value: "{{state_attr('weather.openweathermap', 'forecast')[1].templow}} {{state_attr('weather.openweathermap', 'forecast')[1].temperature}}"
```
