### ISSUE TITLE
[BUG] Physical Button does not turn on wired light connected to the relay

### ISSUE THREAD

**Issue by smartmatic** [joBr99/nspanel-lovelace-ui#792]
### PROBLEM DESCRIPTION
I've replaced a physical light Switch with the NSPanel. Everything works except the the light connected to relay. It does not turn on once i push the button

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel_flurog/RESULT"
    panelSendTopic: "cmnd/nspanel_flurog/CustomSend"
    model: eu
    homeButton: true
    sleepTimeout: 20
    sleepBrightness:
      - time: "6:00:00"
        value: 5
      - time: "23:00:00"
        value: 0
    screensaver:
      entity: weather.smart_live
    locale: "de_DE"
    cards:
      - type: cardEntities
        title: Rolladen
        entities:
          - entity: cover.bad
          - entity: cover.schlafzimmer
          - entity: cover.lilly
          - entity: cover.noah
          - entity: lock.weru
      - type: cardGrid
        title: Licht & Co.
        entities:
          - entity: light.bubu
          - entity: light.stern
          - entity: lock.weru
          - entity: sensor.lilly_thermal_comfort_absolute_humidity_2
            name: Lilly
          - entity: sensor.noah_thermal_comfort_absolute_humidity
            name: Noah
          - entity: sensor.schlafen_thermal_comfort_absolute_humidity_6
            name: Schlafen
      - type: cardMedia
        entity: media_player.bad_flex
      - type: cardPower
        title: Haus Verbrauch
        entities:
          - entity: sensor.stromverbrauch_in_watt
            icon: mdi:home
          - entity: delete
          - entity: sensor.vicare_solar_power_production_today
            name: Solar
            icon: mdi:solar-power
          - entity: delete
          - entity: sensor.vicare_heating_gas_consumption_today
            name: Gas
            icon: mdi:gas-burner
          - entity: delete
          - entity: sensor.watermeter_daily
            name: Wasser


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
Log does not provide useful infos when i push the buttons


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
After Push the physical button the light connected to the relay should turn on

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
EU Version
Tasmota 12.4.0.2
