### ISSUE TITLE
[BUG] Waiting for content...

### ISSUE THREAD

**Issue by magnusoverli** [joBr99/nspanel-lovelace-ui#800]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
One of two NSpanels are failing to start, with "Waiting for content" on the screen. 

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
nspanel-2:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel_2/RESULT"
    panelSendTopic: "cmnd/nspanel_2/CustomSend"
    locale: "NO"
    model: "eu"
    screenBrightness: 80
    defaultBackgroundColor: black
    sleepTimeout: 100
    sleepBrightness:
      - time: "sunrise - 02:00:00"
        value: 40
      - time: "sunrise - 01:00:00"
        value: 60
      - time: "sunrise"
        value: 70
      - time: "sunset - 02:00:00"
        value: 60
      - time: "sunset - 01:00:00"
        value: 40
      - time: "sunset"
        value: 20
      - time: "sunset + 02:00:00"
        value: 10
    screensaver:
      entities:
        - entity:
      defaultCard: grid
      theme:
        time: [255, 255, 255]
        date: [255, 255, 225]
        background: [0, 0, 0]
    cards:
      - type: cardEntities
        key: entities
        title: Lys
        entities:
          - entity: light.silicon_labs_ezsp_livingroom_zha_group_0x0002
            icon:
              "on": mdi:lightbulb-on
              "off": mdi:lightbulb-off
            color:
              "on": [227,208,34]
              "off": [135,135,135]
          - entity: light.silicon_labs_ezsp_kitchen_zha_group_0x0003
            icon:
              "on": mdi:lightbulb-on
              "off": mdi:lightbulb-off
            color:
              "on": [227,208,34]
              "off": [135,135,135]
          - entity: light.silicon_labs_ezsp_hall_zha_group_0x0006
            icon:
              "on": mdi:lightbulb-on
              "off": mdi:lightbulb-off
            color:
              "on": [227,208,34]
              "off": [135,135,135]
      - type: cardGrid
        title: ""
        key: grid
        entities:
          - entity: light.silicon_labs_ezsp_livingroom_zha_group_0x0006
            name: Stuelys
            #icon: mdi:lightbulb-on-outline
            color: [255, 255, 255]
          - entity: input_button.nspanel_button_movie_mode
            name: Film!
            icon: mdi:movie-open-star-outline
            color: [255, 255, 255]
          - entity: input_button.nspanel_button_moviemode_off
            name: Film ferdig
            icon: mdi:movie-off-outline
            color: [255, 255, 255]
          - entity: input_button.nspanel_good_night_button
            name: God natt
            icon: mdi:bed-outline
            color: [255, 255, 255]
          - entity: input_button.nspanel_all_off
            name: Alt av
            icon: mdi:home-clock-outline
            color: [255, 255, 255]
      - type: cardThermo
        title: Varmepumpe
        entity: climate.livingroom_hvac
        supportedModes:
          - 'off'
          - 'heat'
      - type: cardPower
        title: ""
        key: power
        entities:
          - entity: sensor.ams_power_active
            icon: home-lightning-bolt-outline
            color: [255,255,251]
            title: Total
          - entity: delete
          - entity: sensor.hvac_sensor_active_power
#            icon: "ha:{% if states('sensor.hvac_sensor_active_power') | int >= 40 %}{% elif states('sensor.hvac_sensor_active_power') | int <= 39 %}{%endif%}"
            icon: >-
              {% if states('sensor.hvac_sensor_active_power') | int >= 40 %}
                "ha:"
              {% elif states('sensor.hvac_sensor_active_power') | int <= 39 %}
                "ha:"
              {%endif%}
            name: HVAC
            color:
              "on": [227,208,34]
              "off": [135,135,135]
            speed: >-
              {% set entity_power = states('sensor.hvac_sensor_active_power') |float | round(3)%}
              {% set total_power = states('sensor.ams_power_active') | float | round(3) %}
              {% set entity_usage = (entity_power / total_power) * 100 | float | round(3) %}
              {{ (entity_usage | round()) * -1 }}
          - entity: sensor.appliance_water_heater_power
            icon: mdi:water-boiler
            name: Boiler
            color:
              "on": [227,208,34]
              "off": [135,135,135]
            speed: >-
              {% set entity_power = states('sensor.appliance_water_heater_power') |float | round(3)%}
              {% set total_power = states('sensor.ams_power_active') | float | round(3) %}
              {% set entity_usage = (entity_power / total_power * 100) | float %}
              {{ (entity_usage | round()) * -1 }}
          - entity: sensor.bathroom_floor_heating_electric_consumption_w
            icon: mdi:heating-coil
            name: Bathroom
            color:
              "on": [227,208,34]
              "off": [135,135,135]
            speed: >-
              {% set entity_power = states('sensor.bathroom_floor_heating_electric_consumption_w') |float | round(3)%}
              {% set total_power = states('sensor.ams_power_active') | float | round(3) %}
              {% set entity_usage = (entity_power / total_power * 100) | float %}
              {{ (entity_usage | round()) * -1 }}
          - entity: sensor.garage_car_charger_power
            icon: mdi:car-electric-outline
            name: EV
            color:
              "on": [227,208,34]
              "off": [135,135,135]
          - entity: delete
          - entity: sensor.kids_bedroom_floor_heating_electric_consumption_w
            icon: mdi:heating-coil
            name: Kids Room
            color:
              "on": [227,208,34]
              "off": [135,135,135]
            speed: >-
              {% set entity_power = states('sensor.kids_bedroom_floor_heating_electric_consumption_w') |float | round(3)%}
              {% set total_power = states('sensor.ams_power_active') | float | round(3) %}
              {% set entity_usage = (entity_power / total_power * 100) | float %}
              {{ (entity_usage | round()) * -1 }}
      - type: cardMedia
        title: "Sonos Kjøkken"
        entity: media_player.sonos
      - type: cardMedia
        title: "Sonos Roam"
        entity: media_player.sonos_roam
      - type: cardQR
        title: Guest Wifi
        qrCode: ## redacted



```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
2023-03-06 09:31:44.073349 INFO nspanel-2: Sending MQTT Message: pageType~pageStartup
2023-03-06 09:31:44.082349 WARNING nspanel-2: ------------------------------------------------------------
2023-03-06 09:31:44.082462 WARNING nspanel-2: Unexpected error running initialize() for nspanel-2
2023-03-06 09:31:44.082578 WARNING nspanel-2: ------------------------------------------------------------
2023-03-06 09:31:44.083195 WARNING nspanel-2: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 27, in initialize
    controller = LuiController(cfg, mqttsend.send_mqtt_msg)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 27, in __init__
    self.register_callbacks()
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 148, in register_callbacks
    items = [x for x in items if not x.startswith(prefixes)]
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 148, in <listcomp>
    items = [x for x in items if not x.startswith(prefixes)]
AttributeError: 'NoneType' object has no attribute 'startswith'

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
ESPhome config:
```
substitutions:
  node_name: livingroom-nspanel
  friendly_devicename: Livingroom NSpanel
  panel_recv_topic: "tele/nspanel_2/RESULT"
  panel_send_topic: "cmnd/nspanel_2/CustomSend"

external_components:
  - source:
      type: git
      url: https://github.com/sairon/esphome-nspanel-lovelace-ui
      ref: release/v0.2.x
    components: [nspanel_lovelace]

nspanel_lovelace:
  id: nspanel
  mqtt_recv_topic: $panel_recv_topic
  mqtt_send_topic: $panel_send_topic

esphome:
  name: $node_name
  comment: $friendly_devicename

esp32:
  board: esp32dev
  framework:
    type: arduino

uart:
  tx_pin: 16
  rx_pin: 17
  baud_rate: 115200

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.5.181

mqtt:
  id: mqtt_client
  broker: !secret mqtt_ip
  username: !secret mqtt_username
  password: !secret mqtt_password
```

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU
