### ISSUE TITLE
[Feature Request] Do not ignore trailing blank spaces in a value template

### ISSUE THREAD

**Issue by soyxan** [joBr99/nspanel-lovelace-ui#808]
### FEATURE DESCRIPTION
I am trying to center the temperature values on the screensaver by adding trailing blank spaces but they are ignored.

### ADDITIONAL CONTEXT
Example:
```
    screensaver:
      entities:
        - entity: weather.madriguera
          value: '{{states("sensor.ewelink_th01_a6451925_temperature")}}°   '
```

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
