### ISSUE TITLE
[Help] Physical Buttons

### ISSUE THREAD

**Issue by boroloko** [joBr99/nspanel-lovelace-ui#822]
### PROBLEM DESCRIPTION

I would like to use the physical buttons to control two dimmable bulbs. I want the panel to show the corresponding light entity when I press the button, in addition to switching on and off, so that I can adjust the brightness and so on.
Would it be possible to create a rule in Tasmota for this?

### ADDITIONAL INFORMATION

Thaks for your great job!

**Comment by joBr99** [comment]
just configure status icons on the screensaver to show the state

```
    screensaver:
        entity: weather.k3ll3r
        statusIcon1:
          entity: switch.example_item
        statusIcon2:
           entity: binary_sensor.example_item
```

https://docs.nspanel.pky.eu/config-screensaver/

**Comment by joBr99** [comment]
so you want to open the detail page on pressing the button?

**Comment by boroloko** [comment]
yes! sorry if I didn't explain myself well

**Comment by joBr99** [comment]
seomthing like this should work

```
Rule2 on Button1#state do Publish tele/%topic%/RESULT {"CustomRecv":"event,pageOpenDetail,popupLight,light.yourlight"} endon on Button2#state do Publish tele/%topic%/RESULT {"CustomRecv":"event,pageOpenDetail,popupLight,light.yourlight2"} endon

Rule2 1
```

**Comment by boroloko** [comment]
Perfect! This is just that I've been looking for!
Thanks a lots!

**Comment by boroloko** [comment]
Hi, I have been testing and, for me, this solution does'nt work. The rule is created and executed correctly, as I see in the tasmota console log, but the screen does'nt show the requested detail pages.
I have tried changing "light.xxx" to "uuid.xxx", so that the message received is the same as when touching the panel. No success.
I have also tried pressing the physical button when showing the screensaver and without it, and from the grid card where I have those lights. No success.
Sorry for the delayed feedback. Any other ideas?
Thanks

**Comment by joBr99** [comment]
you are right, isn't going to work this way

try this:

`Rule2 on Button1#state do CustomSend pageType~popupLight~Kueche~light.kueche_lights endon on Button2#state do Publish CustomSend pageType~popupLight~Kueche~light.kueche_lights endon`

**Comment by boroloko** [comment]
Yes, I've changed "light.xxx" for "uuid.xxx" and deleted "Publish" in second part and it works. Thanks!

**Comment by joBr99** [comment]
do not use the uuid's they will change on each reboot of appdaemon

**Comment by boroloko** [comment]
Ok. I'll try with the entities.
It's posible to open the detail pages only when turning on the lights? I'll need to compile tasmota for have conditional rules, right?
Thanks for your time

**Comment by joBr99** [comment]
You can just send the command to the customsend topic from homeassistent itself.

**Comment by boroloko** [comment]
Sorry but my programming skill is only a little better than just copy&paste.
I must to use the mqtt publish service for this, right?
Can you paste a example topic and payload, please?

**Comment by joBr99** [comment]
```
  - service: mqtt.publish
    data:
      topic: cmnd/tasmota_NsPanelTerrasse/CustomSend
      payload: pageType~popupLight~Kueche~light.kueche_lights
```
