### ISSUE TITLE
[Feature Request] overview page / navigation

### ISSUE THREAD

**Issue by antibill51** [joBr99/nspanel-lovelace-ui#83]
First of all thank you, I just sent you a little something to buy you some coffees ;)

Would it be possible to define the icons or the type of entity and deduce the corresponding icon on the "cardGrid" card?

The "cardGrid" are really useful to navigate with many pages. 
Would it be possible to modify the function of the arrows?
Ideally, I will see a cardGrid welcome screen, redirecting to other cardGrids with a possibility of returning to the previous cardGrid, without waiting for standby, or without adding an item for that?
I would see an optional configuration in the sytle:
```
- type: xxx
  heading: xxx
  items:
    -xxx
    -xxx
    -xxx
    -xxx
  parent_page: navigate.xxx.yyy
  next_page:navigate.xxx.yyy
```

Last thing, would it be possible to add a scroll for the value of certain sensors? For example for text sensors?

Thanks.

**Comment by joBr99** [comment]
thank you :)

you should be able to do something like this, you can override the icon aswell asthe name

```yaml
        items:
          - light.wled
          - light.schreibtischlampe
          - switch.deckenbeleuchtung_hinten:
              icon: lightbulb
              name: Lampe
```

The navigation feature isn't finished, but a change on the navigation buttons is planned.

Scolling text is possible with nextion, but afaik it always scolls no matter of the text length so unlikely that this is possible.

**Comment by antibill51** [comment]
It doesn't seem to work with navigate items.
Is it possible to force the first page (or another) after exiting the screensaver?

**Comment by joBr99** [comment]
override on navigate should now also work (on current dev/main)

**Comment by antibill51** [comment]
This is perfect for navigating item customization.

Looking at the code, I found the following icons:
```
home: 
	shield-home

power:
	flash
	power
	solar-power
	battery-charging-medium
	battery-medium

light:
	lightbulb
	palette

window / door / cover:
	door-open
	door-closed
	window-open
	window-closed

temperature:
	thermometer
	water-percent

thermostat:
	fire
	fan

media:
	music
	pause
	play

weather:
	weather-night
	weather-cloudy
	weather-fog
	weather-hail
	weather-lightning
	weather-lightning-rainy
	weather-partly-cloudy
	weather-pouring
	weather-rainy
	weather-snowy
	weather-snowy-rainy
	weather-sunny
	weather-windy
	weather-windy-variant
	snowflake

other:
	gesture-tap-button
	alert-circle-outline
	check-circle-outline
	close-circle-outline
	calendar-sync
```
It might be useful to have a file with the complete list of icons, and their pictures

**Comment by joBr99** [comment]
Like this one?
https://github.com/joBr99/nspanel-lovelace-ui/blob/main/HMI/icons.md

**Comment by antibill51** [comment]
Indeed, I had not looked in the right place... It's perfect!

**Comment by antibill51** [comment]
I've made a little automation to force my first page on screensaver exit. Not perfect, but it work... 

```
alias: Accueil NsPanel
description: ''
trigger:
  - platform: mqtt
    topic: tele/NsPanel_7DEE08/RESULT
    payload: '{"CustomRecv":"event,buttonPress2,screensaver,bExit,1"}'
    encoding: utf-8
condition: []
action:
  - service: mqtt.publish
    data:
      topic: tele/NsPanel_7DEE08/RESULT
      payload: '{"CustomRecv":"event,buttonPress2,navigate.cardGrid_Accueil,button"}'
mode: single

```

**Comment by joBr99** [comment]
yes this is the way to go until it's possible to configure this :)

**Comment by joBr99** [comment]
with the current release the current_page does no longer change to subpages, so this is also solved

also the config format has changed:

```yaml
    cards:
      - type: cardEntities
        title: Example Entities
        entities:
          - entity: light.kueche_lights
          - entity: navigate.cardGrid_testKey
    hiddenCards:
      - type: cardGrid
        title: Exmaple Hidden Grid
        entities:
          - entity: light.kueche_lights
        key: testKey

```

**Comment by antibill51** [comment]
Hi. That's a very good news! 

I hidde all cards except my first menu, 
Working fine for : cardEntities; cardGrid but only for one go back.
Example : cardGrid" first level menu" -> cardGrid "sub level menu" -> cardEntities
I can go back to "sub level menu" from cardEntities, but no to "first level menu". 

cardThermo; cardMedia; cardAlarm doesn't work, display left/right arrows, and not up arrow. 

No new function to set a default card after screensaver rather than going back to the last card displayed? 


It's nice to see how fast this project is progressing.

**Comment by joBr99** [comment]
update to 2.5.0 and try again, I fixed the navigation on cardThermo; cardMedia; cardAlarm and added multi level subpages

nothing new for default card

**Comment by joBr99** [comment]
@antibill51 done

```yaml
    screensaver:
      type: screensaver
      entity: weather.k3ll3r
      doubleTapToUnlock: True
      key: screensaver
      title: Screensaver
      defaultCard: cardEntities_rolladen
    cards:
      - type: cardEntities
        title: Rolladen
        entities:
          - entity: cover.rolladenfenster_cover_1
          - entity: cover.nspterrasse_cover_1
          - entity: cover.rolladenterasse_cover_1
          - entity: navigate.cardGrid_test
        key: rolladen
```
