### ISSUE TITLE
[BUG] aemet weather showing wrong day names

### ISSUE THREAD

**Issue by lluisd** [joBr99/nspanel-lovelace-ui#840]
### PROBLEM DESCRIPTION
I use the AEMET weather plugin, but in screensaver it shows wrong day names, they are sliced +1 day. Temperatures are the correct ones, the problem is only for the day names sliced by 1 day.

### REQUESTED INFORMATION

AEMET weather object
```
{
    "temperature": 19.2,
    "temperature_unit": "°C",
    "humidity": 38,
    "pressure_unit": "hPa",
    "wind_bearing": 45,
    "wind_speed": 26,
    "wind_speed_unit": "km/h",
    "visibility_unit": "km",
    "precipitation_unit": "mm",
    "forecast": [
        {
            "condition": "partlycloudy",
            "precipitation_probability": 25,
            "datetime": "2023-04-02T22:00:00+00:00",
            "wind_bearing": 45,
            "temperature": 20,
            "templow": 8,
            "wind_speed": 20
        },
        {
            "condition": "partlycloudy",
            "precipitation_probability": 20,
            "datetime": "2023-04-03T22:00:00+00:00",
            "wind_bearing": 90,
            "temperature": 16,
            "templow": 5,
            "wind_speed": 20
        },
        {
            "condition": "partlycloudy",
            "precipitation_probability": 15,
            "datetime": "2023-04-04T22:00:00+00:00",
            "wind_bearing": 180,
            "temperature": 20,
            "templow": 5,
            "wind_speed": 5
        },
        {
            "condition": "partlycloudy",
            "precipitation_probability": 5,
            "datetime": "2023-04-05T22:00:00+00:00",
            "wind_bearing": 90,
            "temperature": 20,
            "templow": 6,
            "wind_speed": 5
        },
        {
            "condition": "cloudy",
            "precipitation_probability": 35,
            "datetime": "2023-04-06T22:00:00+00:00",
            "wind_bearing": 90,
            "temperature": 16,
            "templow": 7,
            "wind_speed": 10
        },
        {
            "condition": "partlycloudy",
            "precipitation_probability": 45,
            "datetime": "2023-04-07T22:00:00+00:00",
            "wind_bearing": null,
            "temperature": 17,
            "templow": 6
        }
    ],
    "attribution": "Powered by AEMET OpenData",
    "friendly_name": "AEMET daily"
} 
```

- [ ] Provide your apps.yaml (or your config):
```
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel_topic/RESULT"
    panelSendTopic: "cmnd/nspanel_topic/CustomSend"
    model: eu
    sleepTimeout: 20
    screenBrightness: 30
    sleepBrightness:
      - time: "7:00:00"
        value: 5
      - time: "23:00:00"
        value: 0
    locale: "en_US"
    screensaver:
      type: screensaver
      key: screensaver
      entities:
        - entity: weather.aemet_daily
        - entity: weather.aemet_daily
          type: 0
        - entity: weather.aemet_daily
          type: 1
        - entity: weather.aemet_daily
          type: 2
        - entity: delete
        - entity: sensor.aemet_wind_speed
          icon: mdi:weather-windy
      defaultCard: temp
      doubleTapToUnlock: True

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
2023-04-02 16:57:18.914218 INFO nspanel-1: Sending MQTT Message: weatherUpdate~~~���~25375~AEMET daily~19.2��C~~~���~38066~Mon~20.0��C~~~���~38066~Tue~16.0��C~~~���~38066~Wed~20.0��C~delete~~~~~~~~���~17299~AEMET Wind speed~26 km/h
```

### TO REPRODUCE
Use the integration AEMET. Monday is day 2023-04-03 and the temperature is 16 from the AEMET object but in the logs of appdaemon is 20.0, which is the one from Sunday (current day) 

### EXPECTED BEHAVIOUR
expecting correct name

### SCREENSHOTS
wrong in nspanel
![image](https://user-images.githubusercontent.com/7629843/229361218-d1a50541-be00-4ea6-a741-5d716ed1122d.png)

correct in HA
![image](https://user-images.githubusercontent.com/7629843/229361377-07514f02-871d-47df-9725-7ee5d9c02720.png)

### PANEL / FIRMWARE VERION
EU master
