### ISSUE TITLE
System Error DATA! on display unable to flash tft.

### ISSUE THREAD

**Issue by lockeandev** [joBr99/nspanel-lovelace-ui#862]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Not sure this is a bug but I don't know where else to go for some help. I've got 4 NSPanels all flashed and working correctly but on the 4th one the jumpe cables suplying the 5v while flashing the tft file came lose and the flash was interrupted. Now I just see "System Data ERROR!" on the screen and trying "FlashNextion http://nspanel.pky.eu/lui-us-l-release.tft" in the console seems to do nothing. I've tried to flash the TFT file from the Nextion Editor locally but have not had any success. everything on the Tasmota GUI seems to working fine and I have access to the console, but I jest see the attached screenshot when trying to flash, and the screen is lit with "System Data ERROR!" displayed

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:

---
Master_NSPanel:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/MasterBed_NSPanel/RESULT"
    panelSendTopic: "cmnd/MasterBed_NSPanel/CustomSend"
    model: us-p
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 50
      - time: "23:00:00"
        value: 0
    locale: "en_US"
    screensaver:
      entity: weather.downstairs
    cards:
      - type: cardEntities
        entities:
          - entity: light.master_light
          - entity: fan.master_fan
          - entity: light.bedroom_lamps
            name: Lamps
          - entity: switch.master_bedroom_blinds
            name: Master         Blinds
          - entity: switch.clints_blinds
            name: Clint's           Blinds
          - entity: switch.jessicas_blinds
            name: Jess's             Blinds
        title: Master Bedroom 1

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._
<img width="628" alt="image" src="https://user-images.githubusercontent.com/11232490/232341046-d7ddb1cb-1e3c-44d6-89de-0b99076db293.png">

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
