### ISSUE TITLE
[Help] Character not shown on display

### ISSUE THREAD

**Issue by Semetra22** [joBr99/nspanel-lovelace-ui#863]
### PROBLEM DESCRIPTION

I have followed the suggestion from #607 and display the temperature via a HA template.  
In my case, however, the ° symbol is not shown on the display. 

My configuration looks like this:

```
entities:
  - entity: sensor.temperatur_luftfeuchtigkeit_schlafzimmer_temperature
    icon: 'ha:{{ state_attr("sensor.temperatur_luftfeuchtigkeit_schlafzimmer_temperature","temperature")|round}} °C'
    name: Schlafzimmer
  - entity: sensor.temperatur_luftfeuchtigkeit_badezimmer_temperature
    icon: 'ha:{{ state_attr("sensor.temperatur_luftfeuchtigkeit_badezimmer_temperature","temperature")|round}} °C'
    name: Badezimmer


```
But the display shows this: 

<a href="https://ibb.co/mS1n8Bk"><img src="https://i.ibb.co/Wsqrt3Z/Whats-App-Image-2023-04-17-at-01-04-58.jpg"  border="0" height="350"></a>

**Comment by joBr99** [comment]
Try to use the icon Char instead. You can get the Icon Char by clicking U on the icon.
https://docs.nspanel.pky.eu/icon-cheatsheet.html

For the °C Icon replace °C with 

**Comment by joBr99** [comment]
```
entities:
  - entity: sensor.temperatur_luftfeuchtigkeit_schlafzimmer_temperature
    icon: 'ha:{{ state_attr("sensor.temperatur_luftfeuchtigkeit_schlafzimmer_temperature","temperature")|round}} '
    name: Schlafzimmer
  - entity: sensor.temperatur_luftfeuchtigkeit_badezimmer_temperature
    icon: 'ha:{{ state_attr("sensor.temperatur_luftfeuchtigkeit_badezimmer_temperature","temperature")|round}} '
    name: Badezimmer
```
