### ISSUE TITLE
[BUG] Icon not rendering since AppDaemon v0.12.1

### ISSUE THREAD

**Issue by EddyK69** [joBr99/nspanel-lovelace-ui#867]
### PROBLEM DESCRIPTION
Since the update of AppDaemon v0.11.0 to v0.12.1 the statusIcon1 on the screensaver-card is not rendering anymore.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
      statusIcon1:
        entity: sun.sun
        icon:
          "above_horizon": '[xxx]ha:{{state_attr("sun.sun", "next_setting")|as_timestamp|timestamp_custom("%H:%M")}}'
          "below_horizon": '[xxx]ha:{{state_attr("sun.sun", "next_rising")|as_timestamp|timestamp_custom("%H:%M")}}'
        color: [255, 255, 255]

*) the [xxx] has the U-code from the cheat-sheet of icon weather-sunset-down and weather-sunset-up
```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
Update to AppDaemon v0.12.1

### EXPECTED BEHAVIOUR
The rendering should work like it was in v0.11.0

### SCREENSHOTS
**AppDeamon v0.11.0**
![IMG_9122 klein](https://user-images.githubusercontent.com/13943630/233017121-b0a985e8-f1b2-499d-9a91-21d4b32a5d7a.jpeg)

**AppDeamon v0.12.1**
![IMG_9121 klein](https://user-images.githubusercontent.com/13943630/233017145-2c0cded2-088f-4468-8c21-269f82babab3.jpeg)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
EU v4.0.5
