### ISSUE TITLE
multiple devices using same config

### ISSUE THREAD

**Issue by Lux-WorldPC** [joBr99/nspanel-lovelace-ui#870]
### FEATURE DESCRIPTION
I would like to have multiple EU NSPanels using exact same config from apps.yaml
don't know how to do

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
You can move parts of your config to a seperate file, I did this with my hiddenCards, but you can do this with other parts of the config like with your cards aswell.

apps.yaml
```
nspanel-kueche:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_nspkueche/RESULT"
    panelSendTopic: "cmnd/tasmota_nspkueche/CustomSend"
    screensaver:
      entity: weather.k3ll3r
    cards:
      - type: cardGrid
        title: Kueche
        entities:
          - entity: light.kueche_lights
            icon: mdi:ceiling-light-multiple
          - entity: delete
          - entity: navigate.cardMedia_spotify
            icon: mdi:spotify
          - entity: navigate.cardGrid_timer
          - entity: delete
          - entity: navigate.cardThermo_kueche
            status: climate.kuche_boden
            icon: mdi:thermometer
    hiddenCards: !include /config/appdaemon/apps/hiddenCards.yaml

nspanel-terrasse:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_NsPanelTerrasse/RESULT"
    panelSendTopic: "cmnd/tasmota_NsPanelTerrasse/CustomSend"
    screensaver:
      entity: weather.k3ll3r
    cards:
      - type: cardGrid
        title: Terrasse
        entities:
          - entity: navigate.cardEntities_rolladen
            icon: mdi:window-shutter
          - entity: delete
          - entity: navigate.cardMedia_spotify
            icon: mdi:spotify
          - entity: light.beleuchtung_terrasse
            name: Terassenbeleuchtung
          - entity: delete
          - entity: navigate.cardAlarm_alarm
            status: alarm_control_panel.alarmo
    hiddenCards: !include /config/appdaemon/apps/hiddenCards.yaml
.
.
.
```

hiddenCards.yaml:

```
- type: cardMedia
  entity: media_player.spotify
  title: Spotify
  key: spotify

- type: cardThermo
  entity: climate.kuche_boden
  key: kueche
  title: Fußboden
.
.
.
```
