### ISSUE TITLE
[BUG] Climate/Thermo Card not showing presets, showing error_tnf

### ISSUE THREAD

**Issue by ecov773** [joBr99/nspanel-lovelace-ui#874]
### PROBLEM DESCRIPTION
On the Climate/Thermo Card, the presets are shown as error_tnf instead of their real name

### REQUESTED INFORMATION
- [X] Provide your apps.yaml (or your config):
```
---
nspanel-pasillo-p1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "nspanel/RESULT"
    panelSendTopic: "nspanel/CustomSend"
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "en_US"
    screensaver:
      type: screensaver2
      doubleTapToUnlock: True
      entities:
        - entity: binary_sensor.garden_person_occupancy
          icon: mdi:shovel
    cards:
      - type: cardGrid
        title: Bedroom
        entities:
          - entity: navigate.bedroom_heater
            name: Heater
            icon: mdi:fire

    hiddenCards:
      - type: cardThermo
        key: bedroom_heater
        title: Bedroom Heater
        entity: climate.bedroom
        supportedModes: ["heat"]


```
- [X] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
2023-04-24 07:41:15.841484 INFO nspanel: Sending MQTT Message: entityUpdateDetail~climate.bedroom~���~64512~Preset~preset_modes~error_tnf~error_tnf?error_tnf?None?error_tnf~


```

### TO REPRODUCE
Add the card Thermo with a climate that contains presets.

### EXPECTED BEHAVIOUR
Presets are shown, with the real name

### SCREENSHOTS
![image](https://user-images.githubusercontent.com/55066827/233908798-99f114ad-e5fa-4e2a-b43e-7dabe36912e4.png)
<img width="346" alt="image" src="https://user-images.githubusercontent.com/55066827/233909349-f962b8f1-6f3f-4c32-b13c-809b28422bf2.png">

### ADDITIONAL CONTEXT
This project is amazing, thanks a lot guys!

### PANEL / FIRMWARE VERION
EU firmware version
