### ISSUE TITLE
Cant find how to install Babel

### ISSUE THREAD

**Issue by pbranly** [joBr99/nspanel-lovelace-ui#887]
I must be noob necause I dont find any menu for installing Babel;
I have the HACS add-on installed but cant find how to use it

![2023-05-07_20-17](https://user-images.githubusercontent.com/22018509/236695432-38c41361-6008-496b-bdfa-c0d808e0a717.png)

Thank you by advance
Phil

**Comment by joBr99** [comment]
https://appdaemon.readthedocs.io/en/latest/DOCKER_TUTORIAL.html#runtime-dependencies

For plain docker installations check appdaemon configuration, babel is a python package that needs to be present in the appdaemon container.

**Comment by joBr99** [comment]
for the app to work, the crucial part is that the appdaemon container is able to access the files downloaded by hacs

see the folder relationship between the appdaemon container and homeassistant

```
version: "3.5"
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    network_mode: host
    volumes:
      - ./docker-data/homeassistant/:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
    privileged: true
    restart: unless-stopped

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:4.2.3
    environment:
      - HA_URL=http://your-homeassistant-url:8123
      - TOKEN="xxxxxx"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker-data/homeassistant/appdaemon:/conf
    depends_on:
      - homeassistant
    restart: unless-stopped
```
