### ISSUE TITLE
Wiki with example configs.

### ISSUE THREAD

**Issue by byniow** [joBr99/nspanel-lovelace-ui#893]
Hi, where i can see configs with graphical results? On wiki page we see well looking screens, but what config is used - cannot find. I try find a named grid view for screensaver2 (pair name <-> position on screen).

**Comment by joBr99** [comment]
homeassistant or iobroker?

**Comment by byniow** [comment]
HomeAssistant.

**Comment by joBr99** [comment]
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/b90d8f63-3357-4eaa-a3d4-05170a4e794c)


```
      entities:
        - entity: weather.openweathermap
        - entity: weather.openweathermap
          type: 1
        - entity: weather.openweathermap
          type: 2
        - entity: weather.openweathermap
          type: 3
        - entity: sensor.outside_temperature
        - entity: iText.1
          name: 1n
        - entity: iText.2
          name: 2n
        - entity: iText.3
          name: 3n
        - entity: iText.4
          name: 4n
        - entity: iText.5
          name: 5n
        - entity: iText.6
          icon: text:6
        - entity: iText.7
          icon: text:7
        - entity: iText.8
          icon: text:8
        - entity: iText.9
          icon: text:9
        - entity: iText.10
          icon: text:10
```

To spare an icon out you need to use 

```
        - entity: delete
```
