### ISSUE TITLE
[Help]  A thermostat built into the NSPanel and a voltage-free relay

### ISSUE THREAD

**Issue by YeeYek** [joBr99/nspanel-lovelace-ui#903]
### PROBLEM DESCRIPTION

Hi
I would like to control a gas boiler using a thermostat built into the NSPanel and a voltage-free relay (https://delis.pl/OXT-Mini-Modul-Przekaznik-Beznapieciowy-ZigBee-TUYA-p18947).
Unfortunately, I don't know how to go about it. My attempts were unsuccessful.
I will be grateful for help in writing code that will allow me to control the set temperature manually using a thermostat, as well as automatically with a schedule (I suspect that I will have to use an extension like in this issue [#486]([url](https://github.com/joBr99/nspanel-lovelace-ui/issues/486))).

### REQUESTED INFORMATION
The entities of this switch shown in the screenshot.

### ADDITIONAL INFORMATION

AppDaemon 0.13.0 
Lovelace UI 4.1.4

![Kociol](https://github.com/joBr99/nspanel-lovelace-ui/assets/77362116/09103147-0973-43c3-ad63-652d3842f455)

**Comment by joBr99** [comment]
sounds like you want to create a generic thermostat in your home assistant with the switch and a temperature sensor

https://www.home-assistant.io/integrations/generic_thermostat/

**Comment by joBr99** [comment]
This is the configuration I'm using with the temp sensor from the nspanel and the relay of the panel.

```
climate:
  - platform: generic_thermostat
    name: "Bad Boden"
    heater: switch.nspbad1
    target_sensor: sensor.nspbad_analog_temperature1
    min_temp: 15
    max_temp: 25
    ac_mode: false
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      seconds: 1000
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat"
    away_temp: 19
    precision: 0.5
```
