### ISSUE TITLE
Call Service

### ISSUE THREAD

**Issue by robgru** [joBr99/nspanel-lovelace-ui#913]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Hello everyone,
I would like to call a service to steer shutters to a predefined position via a helper in Home Assistant. Unfortunately, this results in an error message. If I enter "{{ states('input_number.sonnenschutz_hoehe') }}" in Home Assistant for the service at position, the roller shutters are moved to the stored position. For example, if I put only 20 in apps.yaml, the service will run. I've also tried "ha:{{ states('input_number.sonnenschutz_hoehe') }}".
I hope someone can help with this.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:

### Rolladen
      - type: cardGrid
        title: Rollladen
        navItem2:
          entity: navigate.screensaver
          icon: mdi:home
        entities:
          - entity: service.cover.set_cover_position
            data:
              entity_id: cover.alle_dachrollladen
              position: "{{ states('input_number.sonnenschutz_hoehe') }}"
            name: Sonnenschutz
            color: [255,255,0]
            icon: mdi:sun-thermometer
          - entity: cover.alle_dachrollladen
            name: alle Dachrollladen
          - entity: cover.kueche_overkiz
            name: Küche
          - entity: cover.esszimmer_overkiz
            name: Esszimmer
          - entity: cover.hm_wohnung_kleines_fenster
            name: kleines Fenster
          - entity: cover.hm_wohnung_doppelfenster
            name: Doppelfenster
        key: rollladen
```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
2023-05-30 22:08:23.257327 WARNING HASS: Error calling Home Assistant service default/cover/set_cover_position
2023-05-30 22:08:23.258367 WARNING HASS: Code: 400, error: 400: Bad Request

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
Firmware: 2023.5.5 (May 29 2023, 11:12:36) EU Model
