### ISSUE TITLE
[BUG] Tapping 7th/8th icon in Grid Card page will run 6th entity

### ISSUE THREAD

**Issue by smarttv193** [joBr99/nspanel-lovelace-ui#915]
Restarted

### PROBLEM DESCRIPTION
I have 8 entities in cardGrid(Home Assistant).
However, tapping 7th/8th icon in Grid Card page will run 6th entity. Based on my configuration, tapping 7th(Test2) or 8th(Test3) icon will run 6th entity(Test1)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
    cards:
      - type: cardGrid
        title: Living Room
        key: living
        entities:
          - entity: switch.living_room_light_left
            name: Light 1
            icon: mdi:ceiling-light-multiple
          - entity: switch.living_room_light_right
            name: Light 2
            icon: mdi:ceiling-light-multiple
          - entity: switch.car_porch_light_center
            name: Car Porch
            icon: mdi:ceiling-light-multiple
          - entity: switch.living_room_fan_left
            name: Fan
            icon: mdi:ceiling-fan
          - entity: input_boolean.living_room_ac
            name: Air Cond
            icon: mdi:air-conditioner
          - entity: input_boolean.test1
            name: Test1
          - entity: input_boolean.test2
            name: Test2
          - entity: input_boolean.test3
            name: Test3


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
Based on my configuration, tapping 7th(Test2) or 8th(Test3) icon will run 6th entity(Test1).

### EXPECTED BEHAVIOUR
Tapping 7th icon will run 7th entity(Test2)
Tapping 8th icon will run 8th entity(Test3)

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
EU
