### ISSUE TITLE
[BUG] 'NoneType' object has no attribute 'uuid'

### ISSUE THREAD

**Issue by lluisd** [joBr99/nspanel-lovelace-ui#918]
### PROBLEM DESCRIPTION
I updated to the last version and copy the new ui for the appdaemon (also updated to the last version of appdaemon) and now I get an error on startup.

### REQUESTED INFORMATION
- [ ] Provide your apps.yaml (or your config):
```
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel_topic/RESULT"
    panelSendTopic: "cmnd/nspanel_topic/CustomSend"
    model: eu
    sleepTimeout: 20
    screenBrightness: 30
    sleepBrightness:
      - time: "7:00:00"
        value: 5
      - time: "23:00:00"
        value: 0
    locale: "es_ES"
    screensaver:
      type: screensaver2
      key: screensaver
      entities:
        - entity: weather.aemet_daily
        - entity: sensor.aemet_temperature_feeling
          icon: mdi:sun-thermometer
        - entity: sensor.aemet_wind_speed
          icon: mdi:weather-windy
        - entity: sensor.aemet_humidity
          icon: mdi:water-percent
        - entity: weather.accuweather
          type: 0
        - entity: weather.accuweather
          type: 1
        - entity: weather.accuweather
          type: 2
        - entity: weather.accuweather
          type: 3
        - entity: sensor.temp_sensor_living_room_temperature
          name: casa
          color: [255, 128, 0]
        - entity: sensor.temperature_humidity_sensor_1971_humidity
          icon: mdi:water-percent
          color: [15, 82, 186]
          name: cama
        - entity: switch.pc
          icon: mdi:desktop-classic
        - entity: switch.3d_printer
          icon: mdi:printer-3d-nozzle
        - entity: switch.camara
          icon: mdi:cctv
        - entity: sensor.persons_at_home
          state_template: '{{ is_state("sensor.persons_at_home")|int < 1 }}'
          icon: 'ha-i:{{iif(states("sensor.persons_at_home")|int == 1, "mdi:human-male", "mdi:human-male-female")}}'
        - entity: navigate.rollers_batteries
          icon: 'ha-i:{{iif(states("sensor.blind_left_battery")|int < 40 or states("sensor.blind_center_battery")|int < 40, "mdi:battery-alert", "mdi:battery")}}'
          color: '{{iif(states("sensor.blind_left_battery")|int < 40 or states("sensor.blind_center_battery")|int < 40, "[244,67,54]", "[76,175,80]")}}'
      defaultCard: temp
      doubleTapToUnlock: True
    cards:
      - type: cardGrid
        title: Temperaturas
        key: temp
        statusIcon1:
          entity: sensor.blind_left_battery
        statusIcon2:
          entity: sensor.blind_center_battery
        entities:
          - entity: sensor.temp_sensor_living_room_temperature
            name: Comedor
            color: [255, 128, 0]
          - entity: sensor.temp_sensor_outside_temperature
            name: Fuera
            color: [255, 128, 0]
          - entity: navigate.other_temps
            icon: mdi:plus-thick
            color: [255,255,255]
            name: Más
          - entity: sensor.temp_sensor_living_room_humidity
            name: Comedor
            color: [15, 82, 186]
          - entity: sensor.temp_sensor_outside_humidity
            name: Fuera
            color: [15, 82, 186]
          - entity: navigate.screensaver
            icon: mdi:weather-cloudy
            name: Tiempo
      - type: cardGrid
        title: Interruptores
        key: switches
        entities:
          - entity: switch.pc
            name: PC
            icon: mdi:desktop-classic
          - entity: switch.3d_printer
            name: 3D Printer
            icon: mdi:printer-3d-nozzle
          - entity: switch.camara
            name: Camara
            icon: mdi:cctv
          - entity: cover.rollers
            name: Estores
            icon: mdi:blinds-horizontal
          - entity: navigate.rollers_batteries
            icon: 'ha-i:{{iif(states("sensor.blind_left_battery")|int < 40 or states("sensor.blind_center_battery")|int < 40, "mdi:battery-alert", "mdi:battery")}}'
            color: '{{iif(states("sensor.blind_left_battery")|int < 40 or states("sensor.blind_center_battery")|int < 40, "[244,67,54]", "[76,175,80]")}}'
          - entity: sensor.persons_at_home
            state_template: '{{ is_state("sensor.persons_at_home")|int < 1 }}'
            icon: 'ha-i:{{iif(states("sensor.persons_at_home")|int == 1, "mdi:human-male", "mdi:human-male-female")}}'
      - type: cardGrid
        title: Consumos
        key: consumption
        entities:
          - entity: navigate.power
            name: Potencia Actual
            icon: mdi:lightning-bolt  
          - entity: navigate.energy_daily
            name: Consumo Dia
            icon: mdi:calendar-today
          - entity: navigate.energy_monthly
            name: Consumo Mes
            icon: mdi:calendar-month
    hiddenCards:
      - type: cardPower
        title: Energia Dia
        key: energy_daily
        navItem1:
          entity: navigate.consumption
          icon: mdi:arrow-up-bold
          color: [255,255,255]
        navItem2:
          entity: navigate.energy_monthly
          icon: mdi:calendar-month
        entities:
          - entity: sensor.sockets_total_energy_daily
            icon: mdi:power-socket-eu
            name: total
          - entity: iText.Total
          - entity: sensor.socket_router_energy_daily
            icon: mdi:router-wireless
            name: router + cam
            color: '{{iif(states("switch.socket_router_switch_local")=="on", "[255,255,0]", "[15, 82, 186]")}}'
          - entity: sensor.socket_tv_energy_daily
            icon: mdi:television
            name: TV
            color: '{{iif(states("switch.socket_tv_switch_local")=="on", "[255,255,0]", "[15, 82, 186]")}}'
          - entity: sensor.socket_washer_energy_daily
            icon: mdi:washing-machine
            name: Rentadora
            color: '{{iif(states("switch.socket_washer_switch_local")=="on", "[255,255,0]", "[15, 82, 186]")}}'
          - entity: sensor.socket_pc_energy_daily
            icon: mdi:desktop-classic
            color: '{{iif(states("switch.socket_pc_switch_local")=="on", "[255,255,0]", "[15, 82, 186]")}}'
            name: PC
          - entity: sensor.socket_nas_energy_daily
            icon: mdi:nas
            name: NAS
            color: '{{iif(states("switch.socket_nas_switch_local")=="on", "[255,255,0]", "[15, 82, 186]")}}'
          - entity: sensor.socket_printer_energy_daily
            icon: mdi:printer-3d-nozzle
            name: 3D printer
            color: '{{iif(states("switch.socket_printer_switch_local")=="on", "[255,255,0]", "[15, 82, 186]")}}'
      - type: cardPower
        title: Energia Mes
        key: energy_monthly
        navItem1:
          entity: navigate.consumption
          icon: mdi:arrow-up-bold
          color: [255,255,255]
        navItem2:
          entity: navigate.power
          icon: mdi:lightning-bolt
        entities:
          - entity: sensor.sockets_total_power
            value: '{{ "{:.0f}".format(state_attr("sensor.edata_as0f","month_kWh")| float) }}k {{ states("sensor.edata_as0f")[0:5] }}'
            icon: mdi:home-lightning-bolt
          - entity: sensor.sockets_total_energy_monthly
          - entity: sensor.socket_router_energy_monthly
            icon: mdi:router-wireless
            name: router + cam
            color: '{{iif(states("switch.socket_router_switch_local")=="on", "[255,255,0]", "[15, 82, 186]")}}'
          - entity: sensor.socket_tv_energy_monthly
            icon: mdi:television
            name: TV
            color: '{{iif(states("switch.socket_tv_switch_local")=="on", "[255,255,0]", "[15, 82, 186]")}}'
          - entity:  sensor.socket_washer_energy_monthly
            icon: mdi:washing-machine
            name: Rentadora
            color: '{{iif(states("switch.socket_washer_switch_local")=="on", "[255,255,0]", "[15, 82, 186]")}}'
          - entity: sensor.socket_pc_energy_monthly
            icon: mdi:desktop-classic
            color: [255, 255, 0]
            name: PC
            color: '{{iif(states("switch.socket_pc_switch_local")=="on", "[255,255,0]", "[15, 82, 186]")}}'
          - entity: sensor.socket_nas_energy_monthly
            icon: mdi:nas
            name: NAS
            color: '{{iif(states("switch.socket_nas_switch_local")=="on", "[255,255,0]", "[15, 82, 186]")}}'
          - entity: sensor.socket_printer_energy_monthly
            icon: mdi:printer-3d-nozzle
            name: 3D printer
            color: '{{iif(states("switch.socket_printer_switch_local")=="on", "[255,255,0]", "[15, 82, 186]")}}'
      - type: cardPower
        title: Potencia Actual
        key: power
        navItem1:
          entity: navigate.consumption
          icon: mdi:arrow-up-bold
          color: [255,255,255]
        navItem2:
          entity: navigate.energy_daily
          icon: mdi:calendar-today
        entities:
          - entity: sensor.sockets_total_power
            icon: mdi:power-socket-eu
            name: total
          - entity: delete
          - entity: sensor.socket_router_power_local
            icon: mdi:router-wireless
            name: router + cam
            color: '{{iif(states("switch.socket_router_switch_local")=="on", "[255,255,0]", "[15, 82, 186]")}}'
          - entity: sensor.socket_tv_power_local
            icon: mdi:television
            name: TV
            color: '{{iif(states("switch.socket_tv_switch_local")=="on", "[255,255,0]", "[15, 82, 186]")}}'
          - entity:  sensor.socket_washer_power_local
            icon: mdi:washing-machine
            name: Rentadora
            color: '{{iif(states("switch.socket_washer_switch_local")=="on", "[255,255,0]", "[15, 82, 186]")}}'
          - entity: sensor.socket_pc_power_local
            icon: mdi:desktop-classic
            color: [255, 255, 0]
            name: PC
            color: '{{iif(states("switch.socket_pc_switch_local")=="on", "[255,255,0]", "[15, 82, 186]")}}'
          - entity: sensor.socket_nas_power_local
            icon: mdi:nas
            name: NAS
            color: '{{iif(states("switch.socket_nas_switch_local")=="on", "[255,255,0]", "[15, 82, 186]")}}'
          - entity: sensor.socket_printer_power_local
            icon: mdi:printer-3d-nozzle
            name: 3D printer
            color: '{{iif(states("switch.socket_printer_switch_local")=="on", "[255,255,0]", "[15, 82, 186]")}}'
      - type: cardGrid
        title: Otras Temperaturas
        entities:
          - entity: sensor.temperature_humidity_sensor_1971_temperature
            name: Dormitorio
            color: [255, 128, 0]
          - entity: sensor.temp_sensor_study_temperature
            name: Estudio
            color: [255, 128, 0]
          - entity: sensor.temp_sensor_bathroom_temperature
            name: Baño
            color: [255, 128, 0]
          - entity: sensor.temperature_humidity_sensor_1971_humidity
            name: Dormitorio 
            color: [15, 82, 186]
          - entity: sensor.temp_sensor_study_humidity
            name: Estudio
            color: [15, 82, 186]
          - entity: sensor.temp_sensor_bathroom_humidity
            name: Baño
            color: [15, 82, 186]
        key: other_temps
      - type: cardEntities
        title: Baterias estores
        entities:
          - entity: sensor.blind_left_battery
            name: Estor izquierdo
          - entity: sensor.blind_center_battery
            name: Estor central
        key: rollers_batteries

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
2023-06-03 22:23:32.928309 INFO nspanel-1: Sending MQTT Message: pageType~pageStartup
2023-06-03 22:23:32.936519 WARNING nspanel-1: ------------------------------------------------------------
2023-06-03 22:23:32.936745 WARNING nspanel-1: Unexpected error running initialize() for nspanel-1
2023-06-03 22:23:32.936904 WARNING nspanel-1: ------------------------------------------------------------
2023-06-03 22:23:32.939788 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/local/lib/python3.10/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/conf/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 27, in initialize
    controller = LuiController(cfg, mqttsend.send_mqtt_msg)
  File "/conf/apps/nspanel-lovelace-ui/luibackend/controller.py", line 27, in __init__
    self.register_callbacks()
  File "/conf/apps/nspanel-lovelace-ui/luibackend/controller.py", line 146, in register_callbacks
    items = self._config.get_all_entity_names()
  File "/conf/apps/nspanel-lovelace-ui/luibackend/config.py", line 227, in get_all_entity_names
    entities.extend(card.get_entity_names())
  File "/conf/apps/nspanel-lovelace-ui/luibackend/config.py", line 81, in get_entity_names
    entityIds.setdefault(self.entity.uuid, []).append(val.get("entity"))
AttributeError: 'NoneType' object has no attribute 'uuid'
2023-06-03 22:23:32.939998 WARNING nspanel-1: ------------------------------------------------------------
```

### TO REPRODUCE
use my yaml

### EXPECTED BEHAVIOUR
no errors and working as before

### PANEL / FIRMWARE VERION
nspanel  EU
