### ISSUE TITLE
[BUG] Commit 35af3a7 causes state_attr not working anymore

### ISSUE THREAD

**Issue by EddyK69** [joBr99/nspanel-lovelace-ui#926]
### PROBLEM DESCRIPTION
Since commit 35af3a7 (#925) the state_attr is not rendered anymore.  

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
    screensaver:
      key: screensaver-1
      defaultCard: navigate.main-1
      theme:
        time: [255, 255, 255]
      type: screensaver2
      entities:
        - entity: weather.lokale_buienradar
        - entity: sensor.room_temp_thermostat_awb
          icon: mdi:home-thermometer-outline
          color: [245, 166, 66]
        - entity: sun.sun
          icon: mdi:weather-sunset-up
          value: '{{state_attr("sun.sun", "next_rising")|as_timestamp|timestamp_custom("%H:%M")}}'
          color: [255, 255, 255]
        - entity: sun.sun
          icon: mdi:weather-sunset-down
          value: '{{state_attr("sun.sun", "next_setting")|as_timestamp|timestamp_custom("%H:%M")}}'
          color: [255, 255, 255]


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### EXPECTED BEHAVIOUR
I'd expect to see the sun rising/setting as it used to work prior the mentioned commit.

### SCREENSHOTS
After commit:
![IMG_9630 normaal](https://github.com/joBr99/nspanel-lovelace-ui/assets/13943630/38eb28d3-c865-4f13-bfd0-54928de49a53)

Before commit:
![IMG_9631 normaal](https://github.com/joBr99/nspanel-lovelace-ui/assets/13943630/3f6a86f3-a64b-4f1f-ab0c-3d769e6d8758)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
EU, latest dev-version
