### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Hooshee** [joBr99/nspanel-lovelace-ui#932]
### PROBLEM DESCRIPTION
The screensaver entity icons are disappearing for a while after entering any page. Only the statusicons and the clock remains. It seems that after actication the screensaver two MQTT messages comes, one for the content, and after that immediately one for statusupdate. The latter clears the screen. Manually reposting the content message makes the panel showing information again (until next statusupdate).

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
---
nsbedroom:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_nspanel/RESULT"
    panelSendTopic: "cmnd/tasmota_nspanel/CustomSend"
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 1
    locale: "hu_HU"
    
    screensaver:
      type: screensaver2
      entities:
        - entity: weather.forecast_tancsics
        - entity: sensor.netatmo_halo_temperature
          icon: mdi:thermometer
        - entity: sensor.netatmo_halo_co2
          icon: mdi:molecule-co2
        - entity: sensor.netatmo_halo_humidity
          icon: mdi:water-percent
        - entity: weather.forecast_tancsics
          type: 1
        - entity: weather.forecast_tancsics
          type: 2
        - entity: weather.forecast_tancsics
          type: 3
        - entity: sensor.nappali_nappali_nappali_eso_szenzor_rain_today
          name: "Eső"
          icon: mdi:cloud-percent
        - entity: delete
        - entity: delete
        - entity: lock.danalock_v3_btzb_doorlock
          icon: mdi:lock
        - entity: cover.garage_door
        - entity: lock.lock
          icon: mdi:car
        - entity: alarm_control_panel.mqtt_alarm
          icon: mdi:shield-home
        - entity: cover.office_blinder
      statusIcon1:
        entity: light.halo_csillar
        icon: mdi:lightbulb

    cards:
      - type: cardGrid
        title: Hálószoba
        entities:
          - entity: navigate.bedroom_ac
            icon: mdi:air-conditioner
          - entity: navigate.bedroom_thermo
            icon: mdi:thermostat
          - entity: navigate.lockscovers
            icon: mdi:key
          - entity: navigate.energy
            icon: mdi:flash
          - entity: navigate.alarmpanel
            icon: mdi:shield-home
    hiddenCards:
      - type: cardThermo
        title: Háló klíma
        entity: climate.klima_dolgozo
        key: bedroom_ac
      - type: cardThermo
        title: Háló radiátor
        entity: climate.dolgozgato
        key: bedroom_thermo
      - type: cardEntities
        title: Zárak, redőnyök
        entities:
          - entity: lock.danalock_v3_btzb_doorlock
          - entity: cover.bedroom_blinder
          - entity: fan.nilan
        key: lockscovers
      - type: cardPower
        title: Power Test
        entities:
          - entity: sensor.p1_meter_5c2faf10184e_active_power
            icon: mdi:home
          - entity: delete
          - entity: sensor.p1_meter_5c2faf10184e_total_power_import
            icon: mdi:grid
            speed: -20
          - entity: delete
          - entity: sensor.p1_meter_5c2faf10184e_total_power_export
            icon: mdi:battery
            speed: 20
          - entity: delete
          - entity: sensor.tancsics_solar_energy_today
            icon: mdi:solar-panel
            color: [255, 255, 0]
            speed: 30
          - entity: sensor.today_energy
            speed: -40
            icon: mdi:help
        key: energy
      - type: cardAlarm
        title: Alarm Test 1
        entity: alarm_control_panel.partition_area_1
        key: alarmpanel

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
2023-07-14 10:29:25.747602 INFO nsbedroom: Button Press Event; entity_id: cardGrid; button_type: sleepReached; value: None 
2023-07-14 10:29:25.751443 INFO nsbedroom: Sending MQTT Message: pageType~screensaver2
2023-07-14 10:29:25.757017 INFO nsbedroom: Sending MQTT Message: timeout~20
2023-07-14 10:29:25.811260 INFO nsbedroom: Sending MQTT Message: weatherUpdate~~~���~65504~Forecast T��ncsics~23.4��C~~~���~17299~Netatmo h��l�� Temperature~24.2��C~~~���~17299~Netatmo h��l�� CO2~640 ppm~~~���~17299~Netatmo h��l�� Humidity~68 %~~~���~65504~Szo~32.2��C~~~���~65504~V~34.9��C~~~���~38066~H~35.1��C~~~���~17299~Es��~0 mm~delete~~~~~~delete~~~~~~~~���~65222~Danalock V3-BTZB Door lock~Bez��r~~~���~17299~Garage door~���|���|���|disable|enable|enable~~~���~17299~AMG lock~Kinyit~~~���~17299~MQTT Alarm~unknown~~~���~17299~Office blinder~���|���|���|enable|enable|enable
2023-07-14 10:29:25.817627 INFO nsbedroom: Sending MQTT Message: statusUpdate~���~17299~~~~

```

### TO REPRODUCE
Tap panel in screensaver mode, and then let it sleep back

### EXPECTED BEHAVIOUR
The whole screensaver content should reappear

### SCREENSHOTS
![20230714_103056](https://github.com/joBr99/nspanel-lovelace-ui/assets/76881082/ba0ad89b-b163-4211-819c-1520ba808140)
![20230714_103127](https://github.com/joBr99/nspanel-lovelace-ui/assets/76881082/9c46c71c-61e7-4dea-bfcb-e11912354d55)
![20230714_103056](https://github.com/joBr99/nspanel-lovelace-ui/assets/76881082/add5319f-cd1c-41cd-9285-434b6aaeca20)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
NSpanel EU
Tasmota
Program Version | 13.0.0(nspanel)

![20230714_103309](https://github.com/joBr99/nspanel-lovelace-ui/assets/76881082/c453833f-21c7-43eb-849e-d043c6409d6b)
![20230714_103127](https://github.com/joBr99/nspanel-lovelace-ui/assets/76881082/9c46c71c-61e7-4dea-bfcb-e11912354d55)

![20230714_103056](https://github.com/joBr99/nspanel-lovelace-ui/assets/76881082/add5319f-cd1c-41cd-9285-434b6aaeca20)
