### ISSUE TITLE
Toggle Switches turning off randomly[BUG] 

### ISSUE THREAD

**Issue by Rayeliint** [joBr99/nspanel-lovelace-ui#935]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
No idea what to do here but it seems every now and again one of the 2 buttons toggle off for no reason.
I have them on all the time as they feed other smart device lights.
Would this be a software issue or hardware issue?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
---
hello_world:
  module: hello
  class: HelloWorld
#sunsetlights:
#  module: sunset_lights
#  class: SunsetLights
#  entities:
#  - group.lounge_lights
#  - group.dining
#  - bedroom
spotify_mood_lights_sync:
  module: spotify_mood_lights_sync
  class: SpotifyMoodLightsSync
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
  media_player: media_player.outside_sonos
  light: light.outside_kitchen_dl1
  mode: search
  max_retries: 1
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/kitchen/RESULT"
    panelSendTopic: "cmnd/kitchen/CustomSend"
    model: us-l
    sleepTimeout: 20
    sleepBrightness:
      - time: "sunrise"
        value: 10
      - time: "22:00:00"
        value: 3
    locale: "en_US"
    timeFormat: "%-I:%M   ?%p"
    screensaver:
  #    type: screensaver2
      entities:
        - entity: weather.runaway_bay
        - entity: sensor.home_total_energy_today
        - entity: sensor.wind_state
        - entity: sensor.wind_speed
        - entity: light.guests
          icon: mdi:human-female-boy
      theme:
        autoWeather: true      
    cards:
      - type: cardEntities
        title: Kitchen
        key: Kitchen
        entities:
   #       - entity: switch.bench_lights
          - entity: switch.kitchen_light
      #- type: cardEntities
      #  title: Test Entities Card
       # entities:
         # - entity: sensor.wind_speed
        #  - entity: sensor.wind_state
         # - entity: scene.dining_scene
         #   name: Dining
         #   icon: mdi:lightbulb
         # - entity: scene.lounge_scene
         #   name: Lounge
         #   icon: mdi:lightbulb
         # - entity: group.balcony_downlights
         #   name: Balcony
         #   icon: mdi:lightbulb
         # - entity: group.outdoor_kitchen
         #   name: Bar
         #   icon: mdi:grill
       # title: Groups
nspanel-2:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/dining/RESULT"
    panelSendTopic: "cmnd/dining/CustomSend"
    model: us-l
    sleepTimeout: 20
  #  sleepBrightness:
   #   - time: "7:00:00"
   #     value: 30
   #   - time: "23:00:00"
   #     value: 5
    locale: "en_US"
    timeFormat: "%-I:%M   ?%p"
    screensaver:
      entity: weather.runaway_bay
      theme:
        autoWeather: true
    cards:
      - type: cardEntities
        title: Balcony Switches
        entities:
          - entity: cover.blind_lr
          - entity: sensor.wind_state
      - type: cardEntities
        title: Screen 2
        entities:
          - entity: sensor.wind_speed
        #  - entity: sensor.wind_state
        #  - entity: switch.kitchen_light
         #   name: Kitchen
          #  icon: mdi:lightbulb
       # title: Kitchen

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
