### ISSUE TITLE
[Feature Request] Enable state_template for internal entities

### ISSUE THREAD

**Issue by marek-vrana** [joBr99/nspanel-lovelace-ui#936]
### FEATURE DESCRIPTION
For styling purposes it will be great if delete entities and navigation entities will support state template.
Using cardEntities, I tried to put two options at the top, then have a spacer (delete) and last row to run an action based on selection on top (basically two different entities).
I found a workaround for delete entities which evaluates state template correctly 
```
- entity: input_text.void
  value: ""
  name: ""
  icon: "text:" 
  state_template: '{{ ... }}'
```
but I wasn't able to make it to work with navigation entities. Such feature could allow us to better organize visual options on nspanel and conditionally display entities based on user choices.

### ADDITIONAL CONTEXT
N/A

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
There are no callbacks for templates in appdaemon, so it's not possible to listen for events related to enties in the state_template.

However the template should still be evaluated for internal entities. In cases were you need callback from an additional entity on your page you can add it after your list of entities and it will be added to the callbacks (as 9th or 5th entity, depending on the page)

Please post an example for your use case, sound's like there is an easier way to do it, but maybe I also didn't fully get it.

**Comment by marek-vrana** [comment]
I tried to build a main screen for my vacuum cleaner using cardEntities. There are 4 possible rows to fill:

1. choose cleaning mode (input select)
2. choose segment mode - either room or zone (input select)
3. empty, but when it's cleaning it should show pause/resume button
4. based on selected option in pt. 2, it should either navigate to list of rooms or list of zones (using state_template)

It is impossible to add a conditional spacer (pt. 3) as is, but kind of workaround it with empty input_text (see above). Also having conditional navigation is not possible (pt. 4) at all:
```
- name: Room
  icon: *segment_room
  color: *green
  entity: navigate.rooms_1
  state_template: '{{ is_state("input_select.cleaning_segment", "Zone") }}'
- name: Zone
  icon: *segment_zone
  color: *green
  entity: navigate.zones_1
  state_template: '{{ is_state("input_select.cleaning_segment", "Room") }}'
```
I could not make it work, even though as you say - template is evaluated. My suspicion is that entities card is not taking into account the number of visible entities, but counts all of them in total, then cuts the rest. On cardGrid seems to be the same situation as despite I have only 4 checkboxes shown, it changes from layout 6 to layout 8 (I do have 8 of them in the background, but the rest is hidden = evaluated to not show).

So I ended up with a joined list of rooms and zones and with a constantly shown pause resume button. Not sure if there's any other or easier way currently.

**Comment by joBr99** [comment]
can you post the entire yaml of your card? (especially the one for the input_select's)

**Comment by marek-vrana** [comment]
I tried to assemble the card as close as possible to what I was talking about. Room and Zone entities are always shown, so state_template is not evaluated. 
I commented out input_text.void - state template works here and when this entity is shown (in fact it's just a spacer), it pushes last entity away from screen (only Room entity fits). When I switch it to a delete entity with a state_template, it is also not evaluated and shown always instead.

```
      - title: Vacuum test
        type: cardEntities
        key: main_screen
        entities:
          - name: Cleaning mode
            icon: *cleaning_icon
            color: *red
            entity: input_select.cleaning_profiles_nspanel

          - name: Segment
            entity: input_select.cleaning_segment
            icon:
              "Room": *segment_icon
              "Zone": *segment_zone

          # - entity: input_text.void
          #   value: ""
          #   name: ""
          #   icon: "text:"
          #   state_template: '{{ is_state("script.room_cleaning", "on") }}'

          - name: Room
            icon: *segment_room
            color: *green
            entity: navigate.rooms_1
            state_template: '{{ is_state("input_select.cleaning_segment", "Zone") }}'
          - name: Zone
            icon: *segment_zone
            color: *green
            entity: navigate.zones_1
            state_template: '{{ is_state("input_select.cleaning_segment", "Room") }}'
```

**Comment by joBr99** [comment]
okay found the issue, state templates are ignored if the entity doesn't have a state (and navigate entities do not have one as they are internal)

you can work around this with adding a status to the entity like this:

```
        entities:
          - entity: input_select.test_select
          - entity: navigate.h1
            state_template: '{{ is_state("input_select.test_select", "test1") }}'
            status: input_select.test_select
          - entity: navigate.h2
            state_template: '{{ is_state("input_select.test_select", "test2") }}'
            status: input_select.test_select
```
