### ISSUE TITLE
[BUG] Time on forecast is not shown timezone aware

### ISSUE THREAD

**Issue by mikosoft83** [joBr99/nspanel-lovelace-ui#955]
### PROBLEM DESCRIPTION
Time in weather forecast from weather entity doesn't take time zone into consideration

### REQUESTED INFORMATION

- [x] Provide your apps.yaml (or your config):
```
      entities:
        - entity: weather.home_hourly
        - entity: weather.home_hourly
          type: 0
          name: "HH:mm"
        - entity: weather.home_hourly
          type: 1
          name: "HH:mm"
        - entity: weather.home_hourly
          type: 2
          name: "HH:mm"


```
- [x] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
n/a


```

### TO REPRODUCE
As above

### EXPECTED BEHAVIOUR
Correctly adjusted time

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
datetime attribute for forecast uses this format: '2023-08-16T16:00:00+00:00' That means the time is adjusted to UTC (+00:00). For display it needs to be adjusted to local time zone (as set in appdaemon.yaml)

### PANEL / FIRMWARE VERION
EU, 4.1.4
