### ISSUE TITLE
[Feature Request] reuse cards/config among nspanels

### ISSUE THREAD

**Issue by nguyentrangia** [joBr99/nspanel-lovelace-ui#960]
### FEATURE DESCRIPTION
I have several nspanels in the house. Each nspanel have almost the same config and cards, that make apps.yaml file very very long. Would be great if the config or cards can be shared among nspanel in the apps.yaml file. I tried !include but doesn't work.

### ADDITIONAL CONTEXT
N/A

### PANEL / FIRMWARE VERION
N/A

**Comment by joBr99** [comment]
You can include files, with `!include:`. This is an example from my installation:

apps.yaml:
```
nspanel-bad:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspbad_0C8C00/RESULT"
    panelSendTopic: "cmnd/nspbad_0C8C00/CustomSend"
    screensaver:
      entities:
        - entity: weather.k3ll3r
    cards:
      - type: cardGrid
        title: Bad
        entities:
          - entity: navigate.szenen
            icon: palette
    hiddenCards: !include /config/appdaemon/apps/hiddenCards.yaml
```

hiddenCards.yaml:
```
- type: cardGrid
  title: Szenen
  key: szenen
  entities:
    - entity: scene.abend
      icon: "mdi:food"
```

It should also be possible to use this yaml syntax, but I've never tried:

https://joshdevlin.com/blog/yaml-repeating-sections/
