### ISSUE TITLE
[BUG] Fail to update to v4.2.0 Tasmota 12.3.1.4 

### ISSUE THREAD

**Issue by copilador** [joBr99/nspanel-lovelace-ui#963]
### PROBLEM DESCRIPTION
It is not possible to upgrade to the latest version v4.2.0 nspanel-v4.2.0.tft, with Tasmota 12.3.1.4

### REQUESTED INFORMATION
"AppDaemon, NSpanel and Home Assistant have been restarted, an attempt has been made to perform the upgrade automatically (1º update Home Assistant Hacs, 2º restart AppDaemon add-on, 3º from NsPanel screen select "Yes"), it has been tried manually (1º update Home Assistant Hacs, 2º restart AppDaemon add-on, 3º tasmota console-> FlashNextion command http://nspanel.pky.eu/lovelace-ui/github/nspanel-v4.2.0.tft), the result in both cases is the transition to the progress bar screen in Nspanel, but without any transfers

- [ ] Provide your apps.yaml (or your config):
```
 ---
#***************************Serial-lora**********************************************
serial_lora:
  module: serial_lora
  class: SerialApp
  port: /dev/ttyUSB0
  baudrate: 9600 
#***************************NSpanel**********************************************
nspanel-1:       # https://github.com/joBr99/nspanel-lovelace-ui
  module: nspanel-lovelace-ui 
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel_xxxxxx/RESULT"
    panelSendTopic: "cmnd/nspanel_xxxxxx/CustomSend"
    updateMode: "auto-notify"
    sleepTimeout: 45
    defaultBackgroundColor: "black"
    sleepBrightness:
      - time: "sunrise" 
        value: 10
      - time: "sunset" 
        value: 0
    sleepOverride: 
      entity: switch.luz_pasillo
      brightness: 30
    locale: "es_ES" 
    timeAdditionalTemplate: " {{ state_attr('calendar.calendario_hasio','message') }} "
    # salvapantallas
    screensaver:   
      entities:
        - entity: sensor.nspanel_htu21_temperature
          icon: mdi:thermometer
        - entity: weather.openweathermap
          type: 1
        - entity: weather.openweathermap
          type: 2
        #- entity: sensor.envoy_xxxxxxxxx_current_energy_production
        - entity: sensor.envoy_importing_exporting
          color: '{{iif(states("input_boolean.excedentes")=="on", "[0,255,0]", "[255,0,0]")}}'
        - entity: delete
        - entity: sensor.netatmo_casa_indoor_exterior_temperature
          icon: mdi:home-thermometer-outline
      defaultCard: navigate.cardThermo_calefaccion
      # icono arriba derecha
      statusIcon2: 
        entity: switch.tasmotanspanel
        name: Calefaccion
        altFont: True
        icon: fire
        color:
          "on": [255,0,0]
          "off": [0,0,255]
      # icono arriba izquierda
      statusIcon1: 
        entity: calendar.calendario_hasio
        name: Calendario
        altFont: True
        icon: 
          "on": bell-ring
          "off": bell-outline
        color:
          "on": [255,255,0]
          "off": [0,255,0]
      theme: 
        #background: [25,25,112] # 6350
        time: [255,255,100]  # 65484
        tTimeAdd: [0,255,0]
    #---------------------------------------------------------------------
    cards:
      - type: cardEntities
        entities:
          - entity: switch.luzcomedor
            name: Luz comedor
            icon: lightbulb
            color:
              "on": [255,0,0]
              "off": [0,0,255]
          - entity: light.lampara_comedor
            icon: floor-lamp
          - entity: switch.luzsofa_raswitch3
            name: Luz sofa
            icon: vanity-light
            color:
              "on": [255,0,0]
              "off": [0,0,255]
          - entity: switch.nextion_relay_2
            name: Luz TV
            icon: television-ambient-light
            color:
              "on": [255,0,0]
              "off": [0,0,255]
        title: Comedor luces
        key: lucescomedor
      - type: cardEntities
        entities:
          - entity: switch.nextion_relay_0
            name: Musica
            icon: power-socket-eu
            color:
              "on": [255,0,0]
              "off": [0,255,0]
          - entity: switch.nextion_relay_1
            name: Sonido TV
            icon: power-socket-eu
            color:
              "on": [255,0,0]
              "off": [0,255,0]
          - entity: switch.nextion_relay_2
            name: Radio
            icon: power-socket-eu
            color:
              "on": [255,0,0]
              "off": [0,255,0]
          - entity: cover.comedor1
            name: comedor
            icon: window-shutter
        title: Comedor
        key: comedor
      - type: cardEntities
        entities:
          - entity: sensor.netatmo_casa_indoor_exterior_temperature
          - entity: sensor.netatmo_casa_indoor_temperature
            name: Temperatura casa
          - entity: switch.entrada
            icon: door-closed-lock
            name: Entrada casa
          - entity: input_boolean.no_molestar
            icon: volume-mute
        title: Casa
        key: casa
      - type: cardEntities
        entities:
          - entity: cover.habitacion1
            name: persiana D
          - entity: cover.habitacion2
            name: persiana I
          - entity: light.luz_habitacion_2
          - entity: sensor.mi_air_purifier_3_3h_temperature
            name: Temperatura
        title: Habitación
        key: habitacion
      - type: cardGrid
        title: Persianas
        entities:
          - entity: cover.persianatasmota_cover_1
            name: Pasillo D
          - entity: cover.persianatasmota_cover_2
            name: Pasillo I
          - entity: cover.cuartillo1
            name: Cuartillo
          - entity: cover.persianaaseo_cover_1
          - entity: switch.abrir_persianas
            name: Abrir todas
            icon: window-shutter-open
          - entity: switch.cerrar_persianas
            name: Cerra todas
            icon: window-shutter
        key: persianas
      - type: cardThermo
        title: Calefaccion casa
        entity: climate.calefaccion_termostato
        key: calefaccion
      - type: cardThermo
        title: Aire Taller
        entity: climate.aire_taller
        key: acTaller
      - type: cardThermo
        title: Aire Comedor
        entity: climate.aire_comedor_2
        key: acComedor
      - type: cardThermo
        title: Aire Dormitorio
        entity: climate.aire_dormitorio_2
        key: acHabitacion
      - type: cardPower
        title: Energia
        entities:
          - entity: sensor.consumo_casa 
            speed: -40
            icon: home
          - entity: delete              
          - entity: sensor.envoy_importing_exporting 
            icon: transmission-tower
            color: [255,50,51]
          #agua
          - entity: sensor.consumo_agua 
            speed: -1
            icon: water
          - entity: delete
          # producion solar
          - entity: sensor.envoy_xxxxxxxxx_current_energy_production 
            icon: solar-panel
            color: [255,255,51]
            speed: 30
          #- entity: 
          #gas
          #- entity: 
        key: energia
    hiddenCards: 
      - type: cardGrid
        title: cambioLuces
        entities:
          - entity: light.lampara_comedor
          - entity: light.luz_habitacion_2
          - entity: binary_sensor.caldera
          - entity: switch.luz_pasillo
        key: cambioLuces
      - type: cardGrid
        title: cambiorele
        entity: switch.tasmotatermostato_nspanel
        key: cambiorele
      - type: cardThermo
        title: calefaccion
        entity: climate.calefaccion_termostato
        #entity: climate.cardThermo_calefaccion
        key: calefaccion


```
log. AppDaemon update (automated)
2023-08-22 15:01:32.422139 INFO nspanel-1: Sending MQTT Message: color~0~65516~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~2016
2023-08-22 15:01:32.430404 INFO nspanel-1: Sending MQTT Message: statusUpdate~���~2016~���~31~True~True
2023-08-22 15:01:34.280632 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel_xxxxxx/RESULT', 'wildcard': None, 'payload': '{"nlui_driver_version":"8"}'}
2023-08-22 15:01:34.283542 INFO nspanel-1: Update Pre-Check sucessful Tasmota Driver Version: 8 Panel Version: 51
2023-08-22 15:01:34.285788 INFO nspanel-1: Update of Display Firmware needed
2023-08-22 15:01:34.287692 INFO nspanel-1: Sending MQTT Message: pageType~popupNotify
2023-08-22 15:01:34.291318 INFO nspanel-1: Sending MQTT Message: entityUpdateDetail~updateDisplayNoYes~Display Update available!~65535~Dismiss~65535~Yes~65535~There's a firmware update available for the     
 Nextion screen of the NSPanel. Do you want tostart the update now?
 If the update fails check the installation
 manual and flash again over the Tasmota 
 console. Be patient, the update will take a while.~65535~0
2023-08-22 15:01:50.224661 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel_xxxxxx/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,updateDisplayNoYes,notifyAction,yes"}'}
2023-08-22 15:01:50.227901 INFO nspanel-1: Received Message from Screen: event,buttonPress2,updateDisplayNoYes,notifyAction,yes
2023-08-22 15:01:50.230838 INFO nspanel-1: Sending MQTT Message: http://nspanel.pky.eu/lovelace-ui/github/nspanel-v4.2.0.tft
2023-08-22 15:01:50.236549 INFO nspanel-1: Button Press Event; entity_id: updateDisplayNoYes; button_type: notifyAction; value: yes 
2023-08-22 15:01:55.683288 INFO nspanel-1: Sending MQTT Message: timeout~45
2023-08-22 15:01:55.742951 INFO nspanel-1: Sending MQTT Message: weatherUpdate~text~sensor.nspanel_htu21_temperature~���~17299~Not found check~ apps.yaml~~~���~38066~mi��~34.2��C~~~���~65504~jue~34.3��C~~~���~2016~Potencia red electrica~-708 W~delete~~~~~~~~���~17299~Temperatura externa~38.6��C
2023-08-22 15:01:55.749992 INFO nspanel-1: Sending MQTT Message: color~0~65516~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~65535~2016
```
Log. console Tasmota-> FlashNextion command http://nspanel.pky.eu/lovelace-ui/github/nspanel-v4.2.0.tft
00:00:51.418 MQT: stat/nspanel_xxxxxx/RESULT = {"FlashNextion":"Done"}
00:00:51.469 FLH: host: nspanel.pky.eu, port: 80, get: /lovelace-ui/github/nspanel-v4.2.0.tft
00:00:53.542 MQT: stat/nspanel_xxxxxx/RESULT = {"CustomSend":"Done"}
00:00:53.667 MQT: stat/nspanel_xxxxxx/RESULT = {"CustomSend":"Done"}
00:00:53.739 FLH: Send (High Speed) flash start
00:00:53.877 MQT: stat/nspanel_xxxxxx/RESULT = {"CustomSend":"Done"}
00:00:53.973 MQT: stat/nspanel_xxxxxx/RESULT = {"CustomSend":"Done"}
00:00:54.026 MQT: stat/nspanel_xxxxxx/RESULT = {"CustomSend":"Done"}
00:00:54.155 MQT: stat/nspanel_xxxxxx/RESULT = {"CustomSend":"Done"}
00:00:54.175 BRY: Exception> 'type_error' - unsupported operand type(s) for <: 'nil' and 'int'
00:00:54.240 MQT: stat/nspanel_xxxxxx/RESULT = {"CustomSend":"Done"}
00:00:54.297 MQT: stat/nspanel_xxxxxx/RESULT = {"CustomSend":"Done"}
00:00:57.420 MQT: stat/nspanel_xxxxxx/RESULT = {"CustomSend":"Done"}
00:01:11.924 MQT: tele/nspanel_xxxxxx/STATE = {"Time":"1970-01-01T00:01:11","Uptime":"0T00:01:12","UptimeSec":72,"Heap":137,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":999,"MqttCount":1,"Berry":{"HeapUsed":16,"Objects":243},"POWER":"OFF","Wifi":{"AP":1,"SSId":"wifi_domo","BSSId":"xx:xx:xx:xx:xx:xx","Channel":4,"Mode":"11n","RSSI":44,"Signal":-78,"LinkCount":1,"Downtime":"0T00:00:03"}}
00:01:11.975 MQT: tele/nspanel_xxxxxx/SENSOR = {"Time":"1970-01-01T00:01:11","ANALOG":{"Temperature1":32.2},"Thermostat0":{"ThermostatModeSet":0,"TempTargetSet":18.00,"CtrDutyCycleRead":0},"TempUnit":"C"}
00:01:19.805 MQT: stat/nspanel_xxxxxx/RESULT = {"POWER":"OFF"}
00:01:19.812 MQT: stat/nspanel_xxxxxx/POWER = OFF


```

### TO REPRODUCE
Flash latest release on NSPanel.

### EXPECTED BEHAVIOUR
loading of the nspanel-v4.2.0.tft file and completion of the update

### SCREENSHOTS
![cap](https://github.com/joBr99/nspanel-lovelace-ui/assets/36306437/39f97244-66b2-4506-a1ea-c1d821081c71)
![Captura desde 2023-08-22 15-09-46](https://github.com/joBr99/nspanel-lovelace-ui/assets/36306437/1abe015a-b7e3-40a6-b7ec-20e9fe3246b4)

### PANEL / FIRMWARE VERION
Tasmota 12.3.1.4, AppDaemon  0.13.4, Firmware Version EU
