### ISSUE TITLE
[Feature Request] Blinking entities

### ISSUE THREAD

**Issue by soyxan** [joBr99/nspanel-lovelace-ui#967]
### FEATURE DESCRIPTION
Add a new setting to the entities to display them blinking.

### ADDITIONAL CONTEXT
For instance, it could be added a `blink` parameter:
```
        entities:
          - entity: light.test_item
            name: NameOverride
            icon: mdi:lightbulb
            blink: "on"
```

It could be also nice to be able to use templates for the blink parameter.
If the parameters `state_template` or `state` are used, they should be considered as priority over the `blink `parameter.

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
N/A
