### ISSUE TITLE
[Help] Time is wrong on Screensaver page

### ISSUE THREAD

**Issue by ksihota** [joBr99/nspanel-lovelace-ui#988]
### PROBLEM DESCRIPTION

For the last few days the Screensaver page has been displaying the wrong time. It was slow by about 17 minutes and now it appears to be slow by about 45 minutes. This is the same on two different NSPanels. I have checked through every file I could think of and have hunted for similar issues on line but have not found anything, Everything else is working as expected including the weather, temperature sensors and switches.

There must be something really simple that I am missing. It's driving me nuts.
The time displayed in the Tasmota console is correct. The time displayed on the NSPanel is slow. How can that be? I can't find any way to change it. What have I done wrong? It was working properly before but I don't know when this changed so I can't figure out what might have been altered.

### REQUESTED INFORMATION
- [ ] Provide a screenshot of your tasmota mqtt configuration:
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29150649/1cc074c4-c2a9-4849-b385-f216f4c2593f)

- [ ] Provide your appdaemon.yaml: 
```
secrets: /config/secrets.yaml
appdaemon:
  latitude: 48.385300
  longitude: -123.578903
  elevation: 162
  time_zone: America/Vancouver
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: core-mosquitto.local.hass.io # This should work if you are using supervised HomeAssistant; if not use the IP Address instead.
      
#      client_host: 10.10.10.200
      client_port: 1883
      client_user: "mqtt"
      client_password: ""
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/NSPanel_1/RESULT"
    panelSendTopic: "cmnd/NSPanel_1/CustomSend"
    model: us-l
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 5
    locale: "en_CA"
    timeFormat: "%I:%M   ?%p"
    screensaver:
      entity: weather.1208
    cards:
      - type: cardGrid
        entities:
          - entity: sensor.deck_th01_temperature
            name: Outside
            icon: mdi:home-thermometer-outline
            color: [0,128,0]
          - entity: sensor.deck_th01_temperature
            name: Deck
            color: [0,128,0]
          - entity: sensor.backyard_th01_temperature
            name: Backyard
          - entity: sensor.livingroom_temperature
            name: Inside
            icon: mdi:home-thermometer-outline
            color: [128,0,0]
          - entity: sensor.livingroom_temperature
            name: Livingroom
            color: [128,0,0]  
          - entity: sensor.nspanel_1_analog_temperature
            name: Local
         title: Temps  
      - type: cardGrid
        entities:         
          - entity: switch.plug_5
            name: Kath's Light
            icon:
                "on": mdi:lightbulb
                "off": mdi:lightbulb
            color:
                "on": [255,255,0]
                "off": [0,0,255]            
          - entity: switch.plug_2
            name: Kim's Light
            icon:
                "on": mdi:lightbulb
                "off": mdi:lightbulb
            color:
                "on": [255,255,0]
                "off": [0,0,255]            
          - entity: switch.miniplug_1
            name: Lamp 1
            icon:
                "on": mdi:lightbulb
                "off": mdi:lightbulb
            color:
                "on": [255,255,0]
                "off": [0,0,255]            
          - entity: switch.miniplug_2
            name: Lamp 2
            icon:
                "on": mdi:lightbulb
                "off": mdi:lightbulb
            color:
                "on": [255,255,0]
                "off": [0,0,255]                        
        title: Livingroom Lights
      - type: cardGrid
        entities:
          - entity: light.dining_room_switch_light
            name: Dining room          
          - entity: light.kitchen_lights_light
            name: Kitchen          
        title: Other Lights
      - type: cardQR
        title: Wifi
        qrCode: "WIFI:S:Guest;T:WPA;P:#;;"
        entities:
          - entity: iText.Guest
            name: Name
            icon: mdi:wifi
          - entity: iText.#
            name: Password
            icon: mdi:key
nspanel-2:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/NSPanel_2/RESULT"
    panelSendTopic: "cmnd/NSPanel_2/CustomSend"
    model: us-l
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 5
    locale: "en_CA"
    timeFormat: "%I:%M   ?%p"
    screensaver:
        entity: weather.1208
    cards:
      - type: cardGrid
        entities:
          - entity: sensor.deck_th01_temperature
            name: Outside
            icon: mdi:home-thermometer-outline
            color: [0,128,0]
          - entity: sensor.deck_th01_temperature
            name: Deck
            color: [0,128,0]
          - entity: sensor.backyard_th01_temperature
            name: Backyard
          - entity: sensor.nspanel_2_analog_temperature
            name: Inside
            icon: mdi:home-thermometer-outline
            color: [128,0,0]
          - entity: sensor.livingroom_temperature
            name: Livingroom
            color: [128,0,0]  
          - entity: sensor.nspanel_2_analog_temperature
            name: Local
        title: Temps  
      - type: cardGrid
        entities:         
          - entity: switch.tasmota_p2
            name: Kath's Light
            icon:
                "on": mdi:lightbulb
                "off": mdi:lightbulb
            color:
                "on": [255,255,0]
                "off": [0,0,255]            
          - entity: switch.tasmota_p3
            name: Kim's Light
            icon:
                "on": mdi:lightbulb
                "off": mdi:lightbulb
            color:
                "on": [255,255,0]
                "off": [0,0,255]            
          - entity: switch.miniplug_1
            name: Lamp 1
            icon:
                "on": mdi:lightbulb
                "off": mdi:lightbulb
            color:
                "on": [255,255,0]
                "off": [0,0,255]            
          - entity: switch.miniplug_2
            name: Lamp 2
            icon:
                "on": mdi:lightbulb
                "off": mdi:lightbulb
            color:
                "on": [255,255,0]
                "off": [0,0,255]                        
        title: Livingroom Lights
      - type: cardGrid
        entities:
          - entity: light.dining_room_switch_light
            name: Dining room          
          - entity: light.kitchen_lights_light
            name: Kitchen          
        title: Other Lights
      - type: cardQR
        title: Wifi
        qrCode: "WIFI:S:Guest;T:WPA;P:#;;"
        entities:
          - entity: iText.Guest
            name: Name
            icon: mdi:wifi
          - entity: iText.#
            name: Password
            icon: mdi:key        

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: AppDaemon
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.13.5
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.9.3
 Home Assistant Supervisor: 2023.10.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting

```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_
